### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by MafiaUman**
change server but changed only server port.

### CODE REVIEW

**Comment by camelStyleUser** [comment]
this is too real #10017

**Comment by MafiaUman** [comment]
the router did it for me, it's my first time doing it.

**Comment by MafiaUman** [comment]
This is the first time I am doing this for my router, I have done everything I need to do

**Comment by MafiaUman** [comment]
I'm doing this for the first time, tell me what I need to change

**Comment by MafiaUman** [comment]
> це занадто реально #10017
роутер зробив це за мене, я вперше це роблю.

**Comment by MafiaUman** [comment]
> this is too real #10017

https://github.com/Anuken/Mindustry/pull/10018#issuecomment-2218224111

**Comment by MafiaUman** [comment]
> це занадто реально #10017

I'm doing this for the first time, tell me what I need to change

**Pull request closed without merging**
