### PR TITLE
Fix some Translation and missing Translation

### PR DESCRIPTION
**Pull request by Kiki012184**
Im real Indonesian but I was saw missing Translation and incorrect translation

### CODE REVIEW

**Review by DaGamerFiles — CHANGES_REQUESTED** [review]
Some of them are correct, while the others are confusing. Weapons name will not be translated, I've discussed this in the Mindustry Discord server. Don't shorten the generators name. Slag have been confirmed as 'terak' (KBBI: ampas leburan logam).

**Comment by grimsoul10** [comment]
This translation is so funny lmao

**Comment by DaGamerFiles** [comment]
Is this pr abandoned? @Kiki012184

**Comment by Anuken** [comment]
assuming the answer to the above question is yes

**Pull request closed without merging**
