### PR TITLE
Add Parallax Network to serverlist

### PR DESCRIPTION
**Pull request by Electron215**

### CODE REVIEW

**Comment by Anuken** [comment]
Almost certainly Omega related.

- Empty github account, likely an alt
- Formatting and gamemodes seem similar
- Maps are similar

I'm sure everyone involved in that will deny involvement here, so to avoid wasting everyone's time I'm just going to merge it, and remove it later if necessary.

**Comment by osp54** [comment]
I as the new Darkdustry owner did not give consent to use our mode (Forts) or maps to this person, please back remove the server from the global list
I also want to note that all our maps and modes are protected by a license and can not be used without our consent.

**Comment by Anuken** [comment]
@Electron215 Comments?

**Comment by Electron215** [comment]
Hello A nuke!

Thanks for merge, we are project in Thailand. Two months :)! Our gamemode very original, and we talk to map maker for map. we hope our server go well :)))))
(apology for bad english hope it understandable)

**Comment by hhhi17** [comment]
> Hello A nuke!
> 
> Thanks for merge, we are project in Thailand. Two months :)! Our gamemode very original, and we talk to map maker for map. we hope our server go well :))))) (apology for bad english hope it understandable)

This mode has been on Darkdustry for more than six months, and a large number of people can confirm this. Also, I do not know who you were talking to, since 70% of all maps are made by me.

**Comment by Anuken** [comment]
add some more chins, might make it more convincing

**Comment by TheDogOfChaos** [comment]
interesting

**Comment by osp54** [comment]
> add some more chins, might make it more convincing

what you mean

**Comment by Anuken** [comment]
Same host, same maps, same modes, troll replies - this is obviously Volas again so I'll remove it.

**Comment by OmniCorpTechAdmin** [comment]
@osp54 can you comment this?

ddos

Also for review @Anuken

**Comment by OmniCorpTechAdmin** [comment]
*Indulges licenses while doing dirty things themselves*

**Pull request merged**
