### PR TITLE
Add download links to readme

### PR DESCRIPTION
**Pull request by 1RedOne**
Lazy folks like me need links to do anything :p

### CODE REVIEW

**Comment by Anuken** [comment]
Looks like you need an account to download the Oracle JDK now - not a fan of that. I would try and redirect people to a different JDK, like OpenJDK/Azul/AdoptOpenJDK.

**Comment by 1RedOne** [comment]
I will link them to the releases page from the Oracle project instead, one
minute.

**Comment by 1RedOne** [comment]
Updated, I linked them to the JDk instead.

**Comment by Anuken** [comment]
That works.

**Pull request merged**
