### PR TITLE
Add server

### PR DESCRIPTION
**Pull request by kbeflo**
Temporarily without build permissions. Discord: https://discord.gg/ahhU6sy. Server located at South East Asia.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
no

**Comment by Arkanic** [comment]
> east asia
> ".eu"

**Comment by kbeflo** [comment]
Domain is from eu.org @Arkanic

**Comment by ActualWina** [comment]
As far as I know there are still no plans to put official servers in the game. you can promote your server on the discord server, but there is no need to add it to the game code

**Comment by kbeflo** [comment]
Thanks for letting me know @ActualWina

**Comment by Quezler** [comment]
@ActualWina @kbeflo https://github.com/Anuken/Mindustry/blob/master/SERVERLIST.md

**Comment by ActualWina** [comment]
i saw it yesterday, sorry for that

**Pull request closed without merging**
