### PR TITLE
how to translate viet (WIP)

### PR DESCRIPTION
**Pull request by Meltdown-Altair**
things are very much WIP, please accpet it so i can work on it later and for Percon to finish it with me to both get our own Translator role and help the Vietnamese community here
many thanks to to those like Percon to help me get into translating

### CODE REVIEW

**Comment by Meltdown-Altair** [comment]
welp wait for Percon to wake up and maybe help me abit
-roomba

**Comment by YellOw139** [comment]
1. bundle_vi? https://en.wikipedia.org/wiki/.vi This could get confusing.

2. This isn't finished, so it should be a draft.
image

3. There is no need for Anuke to accept it whatsoever until it's done. It won't help with anything.

4. You have another PR in progress. That one is a draft. Is this still valid? https://github.com/Anuken/Mindustry/pull/3073

5. Lost your PR? Find it in https://github.com/Anuken/Mindustry/pulls .

6. Wanna edit your old PR?
image

7. No need for two PRs. You can move the changes from this PR to that one or vice versa and close one of them.

8. Not trying to criticize. Just to help. If I provided too much info, ignore it. It's because asking too specific questions would've been slower in case more info was needed.

**Comment by Meltdown-Altair** [comment]
ah yes lost that one lol

**Comment by NgLamVN** [comment]
Outdated Translation, update or close.

**Pull request closed without merging**
