### PR TITLE
Fix units that can't be hit being hit by some things.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Fixes units that can't be hit still being detected, such as with:
- EnergyFieldAbility shocks
- SapBulletType linecasting
- FlakBulletType auto-bursting
- Probably other things

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
...this is a big deal, needs testing.

**Comment by MEEPofFaith** [comment]
javaw_oAoYIJYut7

Turn the chance up high enough and

**Comment by MEEPofFaith** [comment]
So far so good

https://user-images.githubusercontent.com/54301439/185721974-b7031074-8f37-4c29-aaba-ecb61b8ed5a4.mp4

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/185722603-70909a0f-a10e-4809-ac28-7ce2e724769b.mp4

(blu mentioned that rails hit blocks first, which I see in collideLine, so a separate test for that)

https://user-images.githubusercontent.com/54301439/185722614-aad1642d-2ced-4199-bd3e-9f7a927fdb1f.mp4

**Comment by MEEPofFaith** [comment]
Anyways, any specific cases of `checkTarget` that you know of that may occasionally need to target something that can't be targetted?

**Comment by MEEPofFaith** [comment]
hm now that I think about it maybe the checks should use `targetable` instead of `hittable`

**Comment by MEEPofFaith** [comment]
Why are `targettable` and `hittable` separate anyways?
When would you ever make a unit that can be targeted but not hit?

**Comment by MEEPofFaith** [comment]
Changes made:
- Reverted `checkTarget` back to normal.
- Added checks for `targetable` and `hittable` is various locations

**Comment by Anuken** [comment]
> Why are targettable and hittable separate anyways?
When would you ever make a unit that can be targeted but not hit?

It was more aimed towards making a unit that can be *hit*, but not targeted, like a harmless scout that isn't worth shooting, but can be hit by cross-fire. Useful? Probably not particularly, but still worth making distinct.

**Comment by MEEPofFaith** [comment]
I see

**Pull request merged**
