### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by GeoNew2011**
not my server, requester can't use github

### CODE REVIEW

**Comment by camelStyleUser** [comment]
killer yuo must learn json

**Comment by Anuken** [comment]
Missing comma.

**Comment by GeoNew2011** [comment]
I'm so dumb

**Comment by GeoNew2011** [comment]
> Missing comma.

anuke when approve

**Comment by Anuken** [comment]
image

**Comment by GeoNew2011** [comment]
lemehost turns off server every 30 minutes

**Pull request closed without merging**
