### PR TITLE
Resprite large launchpad in the same style as small

### PR DESCRIPTION
**Pull request by Quezler**
as teased upon in #4134 here are more visual changed for the unused large launchpad sprite which is here to stay until version 7, it changes the large launchpad's style to look more like the small launchpad, while keeping the pod sprite the same (and thus the launch hexagon and the lights), it does less than #4201 (which didn't make it in), but to be honest my respite looks a bit comical in comparison: (i'll just leave it up here for the users and anuke to judge, i just can't stand the current one 😗)

launch-pad
launch-pad-large

### CODE REVIEW

**Comment by Voz-Duh** [comment]
Anuke want to delete large launch pad

**Comment by nichrosia** [comment]
> Anuke want to delete large launch pad

This doesn't add it into the game, merely changes the sprite.

**Comment by Quezler** [comment]
> Anuke want to delete large launch pad, no?

once 7.0 rolls around yes, but for now a single sprite change won't kill anyone

**Comment by BlueWolf3682** [comment]
you literally just pasted the center of the small pad in the middle, please make it right

**Comment by Voz-Duh** [comment]
@Quezler 
image

**Comment by Quezler** [comment]
> you literally just pasted the center of the small pad in the middle, please make it right

it was far more work than that, do your homework

**Comment by Voz-Duh** [comment]
> > you literally just pasted the center of the small pad in the middle, please make it right
> 
> it was far more work than that, do your homework

You're very rude, I drawed this for 5 minute:
image

**Comment by joshuaptfan** [comment]
Though Mindustry's style usually calls for simplicity, this is too simple. Too much of the sprite is featureless and gray.

**Comment by Voz-Duh** [comment]
image
@Quezler, pls, use it :/

**Comment by Quezler** [comment]
> Also, the top left and bottom right bevels look strange.

those were already part of that sprite, didn't touch em

**Comment by Voz-Duh** [comment]
> > Also, the top left and bottom right bevels look strange.
> 
> those were already part of that sprite, didn't touch em

Part of **OLD** sprite

**Comment by BlueWolf3682** [comment]
> > you literally just pasted the center of the small pad in the middle, please make it right
> 
> it was far more work than that, do your homework

you changed the sides, how very interesting

**Comment by XEN0PHIL** [comment]
this is so bad
Quezler's is underdetailed
VozDuh's is overdetailed

**Pull request closed without merging**
