### PR TITLE
[Bundle][RU] actual L10n

### PR DESCRIPTION
**Pull request by Remint32**
This PR always has a relevant Russian translation and ready to merge at any time (if PR not in draft state)
Translations are tested before being sent to PR

### CODE REVIEW

**Comment by Anuken** [comment]
(will merge next release)

**Comment by Remint32** [comment]
Yes, I know

**Comment by Remint32** [comment]
it's just rolling: merged when merged

**Comment by Remint32** [comment]
TODO: L1240-L1261

**Pull request merged**
