### PR TITLE
Remove Darkdustry from the Global Server List

### PR DESCRIPTION
**Pull request by Darkness6030**
The time has come. It's been more than two years since we started Mindurka, which was later renamed to Darkdustry. It was an amazing time and an amazing experience to maintain the server, to create plugins and gamemodes, to discuss mindustry with all of you. But It's enough. The server is getting constantly DDoSed, the host dies all the time and I have no motivation to develop anything related to Mindustry.  Goodbye. And I hope, we'll meet again.

### CODE REVIEW

**Comment by phinner** [comment]
😔 You will be missed, mate.

**Comment by SITUVNgcd** [comment]
The best server i ever played. Goodbye! And hope we'll meet again.
F_ck those DDoS bot.

**Comment by ZetaMap** [comment]
hello, I saw your commit to remove darkdustry from the server list. Don't do it yet, Xpdustry is developing a new anti VPN service, with many providers (online and offline) with rotating lists. For the moment it is not very functional, but in a short time we will release a version especially for big servers. This version will not be very configurable, but it will allow you to have a reliable service while the plugin is fully completed.
So please wait a little while we send you the version. You can try to keep a server online if you want

A little teaser, for moment we have implemented all these services 
image

PS: sorry for the English, this is auto-translated

**Comment by phinner** [comment]
> hello, I saw your commit to remove darkdustry from the server list. Don't do it yet, Xpdustry is developing a new anti VPN service, with many providers (online and offline) with rotating lists. For the moment it is not very functional, but in a short time we will release a version especially for big servers. This version will not be very configurable, but it will allow you to have a reliable service while the plugin is fully completed. So please wait a little while we send you the version. You can try to keep a server online if you want
> 
> A little teaser, for moment we have implemented all these services image
> 
> PS: sorry for the English, this is auto-translated

The reasons goes beyond the DDOS zeta, the man is retiring for good :(

**Comment by ZetaMap** [comment]
=(

**Comment by osp54** [comment]
> The best server i ever played. Goodbye! And hope we'll meet again. F_ck those DDoS bot.

He didn't shut down the server because of ddos. He just has little time for the server (study, work) and he decided to transfer the owner's right to me, and then for some reason to make this pull....

**Comment by SpilLinux** [comment]
why not integrate a private client (wireguard) into mindustry, to secure connections between people and the host and prevent bots from coming without permission?

**Comment by TheRadioactiveBanana** [comment]
O7s. Largest mindustry server for ingame player count this was.

**Comment by osp54** [comment]
> why not integrate a private client (wireguard) into mindustry, to secure connections between people and the host and prevent bots from coming without permission?
> 
> instead of trying to find an anti vpn system, why not just privatize the network ?

genius

**Comment by ZetaMap** [comment]
> why not integrate a private client (wireguard) into mindustry, to secure connections between people and the host and prevent bots from coming without permission?
> 
> instead of trying to find an anti vpn system, why not just privatize the network ?

why not, but the first rule of a server: never trust the client. 
so whether we use something secure or not, there will always be abuses and flaws. Do not believe that if a client is secure, he is reliable. 
So in any case you will need an anti VPN service.

**Comment by TheRadioactiveBanana** [comment]
> > why not integrate a private client (wireguard) into mindustry, to secure connections between people and the host and prevent bots from coming without permission?
> > 
> > instead of trying to find an anti vpn system, why not just privatize the network ?
> 
> why not, but the first rule of a server: never trust the client. 
> so whether we use something secure or not, there will always be abuses and flaws. Do not believe that if a client is secure, he is reliable. 
> So in any case you will need an anti VPN service.

You know that nobody and i mean *absolutely nobody* will download and use a client like this specifically for darkdustry or whatever?

**Comment by SpilLinux** [comment]
if we include wireguard in mindustry, it will be impossible to create thousands of bots since the server will have to accept network communication each time, conclusion, the protection would be improved, not to mention the many other advantages of a virtual network : 
-masked identity
-very difficult hack
-if certain countries were to restrict internet access, people could still play ^^

**Comment by phinner** [comment]
> if we include wireguard in mindustry, it will be impossible to create thousands of bots since the server will have to accept network communication each time

And how would one go about implementing it ?

**Comment by SpilLinux** [comment]
i asked anuken to maybe add this inside mindustry v8

**Pull request merged**
