### PR TITLE
Large plastanium press. 

### PR DESCRIPTION
**Pull request by SnakkiZXZ**
What about adding a large plastanium press?
I have an idea and a sprite for it.
The more oil, the more efficiency.

P.S. I understand that this way you can add large copies of all the plants, but isn't that a good thing? 
Screenshot_20200421_105217_io anuke mindustry

of course if the idea doesn't like it you can delete this request

### CODE REVIEW

**Comment by SnakkiZXZ** [comment]
here are sprites as I understand you can download them right from here. 
большой пластановый пресс
большой пластановый пресс-top

**Comment by SnakkiZXZ** [comment]
sorry if a little screwed up

**Comment by Quezler** [comment]
looks like you've repurposed an old branch/pull, its one big mess, also: [here's a portal](https://github.com/Anuken/Mindustry-Suggestions) 😗

**Comment by SnakkiZXZ** [comment]
strange, I don't see there's a ban on big versions of factories

**Comment by Quezler** [comment]
there isn't, but this is a suggestion, not a functioning pull request 📚

**Comment by SnakkiZXZ** [comment]
ye-e-e-e-e-es, I realized I'd done something wrong.

**Comment by SnakkiZXZ** [comment]
I can draw large versions of the plants, but the question is, do you need Anuke?🤔

**Comment by Anuken** [comment]
If it's a feature request, post it in the suggestions repository.

**Pull request closed without merging**
