### PR TITLE
Fix plastanium conveyor linking

### LINKED ISSUE #4259: plastanium conveyor incorrectly blends with the armored one
**Platform**: Windows

**Build**: 122.1

**Issue**:

The plastanium conveyor next to the vault draws its edges incorrectly. There is an armored conveyor near it, which doesn't accept items from the side, so an edge should be drawn next to it.

**Steps to reproduce**:
- place this schematic:
`bXNjaAF4nEXNQQqEMAwF0N9olWE2Ax5h1rMRXXicYLso2FZqFby9qS6GLF7+hxC00IQ6sLfQ36EfJ7yN3ebk1uxiACrog/clo1sX3jIHt/vfHMNhz5jw4eRjsubfAC9AyRkpQdaCDIFKKtypkkTy+UE/NIULiM4YZQ==`

**Link(s) to mod(s) used**: none.

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/5765350/save.zip)

---

- [X] **I have updated to the latest release to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

### PR DESCRIPTION
**Pull request by skykatik**
Fixes #4259
Before:
image

After:
image

### CODE REVIEW

**Comment by Anuken** [comment]
But this is incorrect:
image

**Comment by skykatik** [comment]
Yes, I just noticed, I'm already fixing this

**Comment by Quezler** [comment]
neat 😍

**Comment by skykatik** [comment]
Fixed. I'm testing it now
image

**Comment by bvcbvc** [comment]
YES

**Comment by Quezler** [comment]
@skykatik here's another one for you 👀 

Screen Shot 2021-06-09 at 14 13 07

**Comment by USMP-lancer** [comment]
QuEz YoU mAdE tHoSe FiX tHeM yOuRsElF

**Comment by Quezler** [comment]
@USMP-lancer there have been a lot of changes to their blending post-merge, it has grown beyond my ability to comperhend

**Comment by USMP-lancer** [comment]
--if i do that kinda text im joking lmao--

**Pull request merged**
