### PR TITLE
Add TWS Attack server

### PR DESCRIPTION
**Pull request by Neba-MD**
With different preference in our community, we decided to operate a separate server exclusively for Attack maps.

Server is managed by TWS Admin team and automated mass-griefing script detection system.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
good

**Comment by Anuken** [comment]
image

The server looks down.

**Comment by Neba-MD** [comment]
Oops. Should be up.

**Comment by Neba-MD** [comment]
Hi, this message doesn't mean to urge you.
But I am wondering what else is missing or what I have to do before the approval?

As the weekend is coming and haven't heard a conclusion here, it would not be good to our community who look forward to our attack server not available for a long time.

Look forward to hearing for you :)

**Pull request merged**
