### PR TITLE
surge capacitor 2

### PR DESCRIPTION
**Pull request by Arkanic**
electric boogaloo

A higher tier battery for players with a lot of spare surge alloy, as i've noticed that players/servers at the endgame generally have fields of cheap but relatively low power storage batteries.
I re made the pull because the last one (#1191) has too many diffs for me to be bothered

the sprite isn't the best, it would be great if anyone could suggest some changes :)
surge-tower-1 png

### CODE REVIEW

**Comment by SnakkiZXZ** [comment]
большая батарея

**Comment by SnakkiZXZ** [comment]
большая батарея2

**Comment by Arkanic** [comment]
@SnakkiZXZ yeeeeees

**Comment by Anuken** [comment]
I'll keep this PR in mind and merge the sprites/code in when (if ever) I need to - no need for it to stay open.

**Pull request closed without merging**
