### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by JasonP01**
Fix owner forgetting to renew c-n.ddns.net

Hope these type of ip listings are allowed

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by phinner** [comment]
pvp and event is missing, Let me do that kind of PR myself.

**Comment by JasonP01** [comment]
> pvp and event is missing, Let me do that kind of PR myself.

@JasonP01 mb, ill add pvp, events isnt even online anyway so i didnt include it

**Comment by JasonP01** [comment]
@phinner ^

**Comment by phinner** [comment]
Done :ok_hand:

**Comment by phinner** [comment]
@Anuken merge pls.

**Comment by JasonP01** [comment]
I shouldn't have done that, probably made a conflict issue

**Comment by phinner** [comment]
You only pulled from master, I don't see any conflicts.

**Pull request merged**
