### PR TITLE
Add rule to control whether units can automatically rebuild destroyed blocks

### PR DESCRIPTION
**Pull request by Phinner**
This rule is quite useful. For players that want extra difficulty or specific Mindustry servers like lobbies or in my case a schematic showcase server (Clearing build areas without units rebuilding it).

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
The name is very misleading, it implies that it controls unit AI when the reality is that it controls whether "ghost" blocks appear at all.

**Comment by Phinner** [comment]
> The name is very misleading, it implies that it controls unit AI

I see. Hmm, now that I think about it, there is also the build tower affected by this.

What about renaming to `rebuildDestroyedBlocks`. It has the advantage to not specifically include units thus not directly implying that their AI is controlled.

Honestly, I don't have other ideas apart that.

**Comment by Anuken** [comment]
Renamed to "ghostBlocks", see commit.

**Comment by Phinner** [comment]
Many thanks

**Pull request closed without merging**
