### PR TITLE
Update bundle_pt_BR.properties

### PR DESCRIPTION
**Pull request by Rayanfhoula15**
Aegis description changed to remove shield breaker part (why tho? it sounds cool), but it may need some work. New description: The enemy is protected by shields.  Find a way to destroy them. Some holes in the translation have been patched. Mostly tutorials, block names and logic thingys have not yet been translated.

All of the turret's names have been changed back to english, was it on purpose?

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Rayanfhoula15** [comment]
please god tell me i havent fucked up this time

**Comment by Rayanfhoula15** [comment]
trying to test it but the game refuses to load it

**Comment by RayanZ22** [comment]
não traduza os nomes das armas e units

**Comment by Rayanfhoula15** [comment]
> não traduza os nomes das armas e units

ok

**Comment by Rayanfhoula15** [comment]
Updated to remove turret translations.

**Comment by Leo-MathGuy** [comment]
Please fix the conflicts or close the PR, it has been 2 years :(

**Pull request closed without merging**
