### PR TITLE
Update MapResizeDialog.java

### PR DESCRIPTION
**Pull request by BasedUser**
small change for insignificant ram usage

### CODE REVIEW

**Comment by imreallybadatnames** [comment]
ok

**Comment by Quezler** [comment]
now make minsize a multiple of 2 as well 👀

**Comment by summetdev** [comment]
~~how about remove map size limits~~

**Comment by Quezler** [comment]
_haha ram goes brrr!_

**Comment by DeltaNedas** [comment]
map size limits shouldn't be final so it's easy to change in f8 rather than recompile for a tiny change

**Comment by BasedUser** [comment]
how about I shoot your computer in the CPU

**Comment by Anuken** [comment]
The limit isn't 500 because of RAM limits, it's 500 because that's a nice round number that can easily be split into chunks of 100/50. There's no reason to use 512 here.

**Pull request closed without merging**
