### PR TITLE
Update bundle_zh_CN.properties

### PR DESCRIPTION
**Pull request by jixishi**
Hello author, all listed texts have been translated and u codes have been converted.

### CODE REVIEW

**Comment by rMuchan** [comment]
怎么全是unicode转义，甚至看不出来改了什么（

**Comment by liuxilu** [comment]
senseless u code 👎

**Comment by liuxilu** [comment]
For ref: [diff.pdf](https://github.com/Anuken/Mindustry/files/5763353/diff.pdf)

**Comment by rMuchan** [comment]
To developers: it looks like machine translated, and breaks several well-translated items. I would not suggest merging it.

To @jixishi :
扇 区
护 盾 健 康
本 地 部 门
不要用机翻啊（

**Comment by jixishi** [comment]
@rMuchan ?你的与我翻译的不一样啊

**Comment by rMuchan** [comment]
> @rMuchan ?你的与我翻译的不一样啊

没理解什么叫我的不一样。解码这堆unicode转义出错了？

**Comment by jixishi** [comment]
我翻译的护盾生命啊@rMuchan 。。。

**Comment by rMuchan** [comment]
image

**Pull request closed without merging**
