### PR TITLE
Return `Setting` value type for each `pref`methods.

### PR DESCRIPTION
**Pull request by SITUVNgcd**
Added return `Setting` type for these methods (instead of `void`):
- `CheckSetting checkPref()`.
- ~~`SliderSetting sliderPref()`.~~ Why these ones have return type and others not, before my PR?
- `TextSetting textPref()`.
- `AreaTextSetting areaTextPref()`.
- `Setting pref()`. Oh! For it, also!
- Optimized for calling overload methods.

---
- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
I don't see how?
In most cases where it doesn't get used the returned value can just be ignored.

Unless you're saying that old mods that don't increase the version of mindustry used for compiling will break because of this?
~~I really could just test this myself.~~

**Comment by Anuken** [comment]
> We can always just increase what version we use in compiling.

Yes, meanwhile every single Java mod a user has installed will crash the game on startup and have to be updated manually.

**Comment by MEEPofFaith** [comment]
*ah*

**Comment by SITUVNgcd** [comment]
@Anuken Ok, i can't change exsited method (signalture).
But how about add new method? Is this allowed?

**Comment by Anuken** [comment]
That would bloat the API and I don't see a good reason to do that.

**Comment by SITUVNgcd** [comment]
> That would bloat the API and I don't see a good reason to do that.

Ok! I will not do that.

**Pull request closed without merging**
