### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by HubsvVnMindus**
Good 👍

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by HubsvVnMindus** [comment]
Thank 😍

**Comment by HubsvVnMindus** [comment]
Hi Hello everyone, I hope you can join my server

**Review by JasonP01 — CHANGES_REQUESTED** [review]
Extra ] at the end, delete it, also why new line at the end

**Comment by Anuken** [comment]
The JSON is invalid, missing a comma, among other things.

**Pull request closed without merging**
