### PR TITLE
anukes favourite colour

### PR DESCRIPTION
**Pull request by DeltaNedas**
meow

### CODE REVIEW

**Comment by sk7725** [comment]
you beat me to it ;-;

**Comment by Anuken** [comment]
This is actually `Color.coral`.

**Comment by ThePythonGuy3** [comment]
That is the only easter egg that has value

**Comment by ThePythonGuy3** [comment]
:/

**Comment by DeltaNedas** [comment]
oh i am silly

**Comment by sk7725** [comment]
:\

**Pull request closed without merging**
