### PR TITLE
new statements are put in center of screen

### PR DESCRIPTION
**Pull request by DeltaNedas**
implements https://github.com/Anuken/Mindustry-Suggestions/issues/1555

TODO
- [X] initiate drag n drop
- [ ] actually put it in the center of the screen

### CODE REVIEW

**Comment by DeltaNedas** [comment]
hold up

**Comment by DeltaNedas** [comment]
ok so currently the issue is that i have no idea how to turn center of screen into a position for the new statement element

**Comment by Overblob** [comment]
Hi, I really don't want to bother you, but have you considered my proposal (written in your suggestion) ? I think it would be easier to implement and more user-friendly when it comes to add new statements in the middle of the script .

**Comment by DeltaNedas** [comment]
would require having a selection system which i dont even want to try

**Comment by Anuken** [comment]
Stale, re-open later if implemented.

**Pull request closed without merging**
