### PR TITLE
Add Mo Town servers to community servers

### PR DESCRIPTION
**Pull request by Momiro**
I have two dedicated servers running and I would like them to be visible in community servers. One is for maps that I make, another is a hexed pvp with no unit factories.

### CODE REVIEW

**Comment by Anuken** [comment]
> hexed pvp with no unit factories

How would that work?

**Comment by Momiro** [comment]
I have simply banned all of the unit factories with server rules.
If you mean how would the competitive gamemode work, players can use long ranged turrets to damage other players structures, capturing hexes still works. I would rather have a limit on how many unit factories can be placed at once, but I don't know of a way to do that.

The reason I made the no unit hexed pvp server is because I've seen people complaining that if they join in the middle of a hexed pvp game, they immediately get steamrolled by other players existing units.

**Comment by Anuken** [comment]
> they immediately get steamrolled by other players existing units.

Artillery sounds like even more of a disaster. It was banned because of constant spawnkilling and sniping.

**Comment by Momiro** [comment]
Hmm, is there a way to limit tge number of certain blocks spawning? Or would it be better to limit drones to a certain type?

**Comment by Anuken** [comment]
Neither are possible without custom plugins.

**Comment by Momiro** [comment]
The default server wrapper lets you ban certain unit factories, If I unban some of the less "OP" units, would that be more viable?

**Comment by Momiro** [comment]
Perhaps just add the server with my survival maps on it for now, until I come up with a better solution for a more beginner friendly Hex PvP?

**Comment by ActualWina** [comment]
If u can prevent players building next to each other, that hex pvp should work

**Comment by Momiro** [comment]
I would do that if I could. I could also give players a largsr starting supply of copper so they can build some basic defences first

**Comment by sk7725** [comment]
Making a newly spawned player 'immune'(Force projector-style force field that persists for 120 seconds) is a good way to discourage spawnkilling...Heck i should make a plugin for that later

**Pull request closed without merging**
