### PR TITLE
Make revealedBlocks also affect breakability

### PR DESCRIPTION
**Pull request by Ilya246**
Yes, i have actually compiled this small change and made sure it works properly, which it does

### CODE REVIEW

**Comment by Quezler** [comment]
ehmm, for which blocks is this needed?

**Comment by Ilya246** [comment]
if you want to make players able to build pines, you might want to make them breakable

**Comment by Quezler** [comment]
seems like a valid thing to want, but hijacking the `revealedBlocks` rule to make blocks breakable is a bad idea 🤔

**Comment by Ilya246** [comment]
I mean, you cooould add another rule that, instead, prevents blocks from being deconstructed

**Review by Quezler — CHANGES_REQUESTED** [review]
well in its current state i don't think this will/should be merged

**Comment by Anuken** [comment]
Blocks such as pines **should not** be broken. It is unsupported.

**Pull request closed without merging**
