### PR TITLE
Friendly Fire

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Why do you want this

Why do you want this

Video: https://cdn.discordapp.com/attachments/663853133587546138/888930968700854312/Friendly_Fire.mp4

- [X] Figure out why it doesn't work with normal bullets.
- [X] Figure out why normal bullets are hitting their owners anyways.
- [X] Figure out why normal bullets don't collide with units of the same team
- [x] Figure out why Point Bullets broke

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
What it currently is:
https://cdn.discordapp.com/attachments/663853133587546138/888911955170050109/Friendly_FIre_Broken.mp4

I don't know what the issue is and how to fix it.

**Comment by MEEPofFaith** [comment]
wait a sec

**Comment by MEEPofFaith** [comment]
Everything works EXCEPT for this.

https://user-images.githubusercontent.com/54301439/133910613-b5dad02d-3c6a-4398-bb1a-03081077e2cf.mp4

Why don't you work aaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by MEEPofFaith** [comment]
aaaaaaand that somehow made the friendly fire stop working on `PointBulletType`s

**Comment by Anuken** [comment]
Sorry, no, this complicates the code significantly, decreases performance & will most definitely break at some point, as I do not (and will not) use it in my own bullets.

**Comment by Kieaer** [comment]
@Anuken If server know the owner of the outgoing bullets, we can also create more interesting content on the server.
I think.

**Comment by Anuken** [comment]
> If server know the owner of the outgoing bullets

They already do.

**Pull request closed without merging**
