### PR TITLE
Ser-pew-lo Turret Animations

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Was bored, felt like doing something.

Very basic.

https://user-images.githubusercontent.com/54301439/236657657-50021347-b420-4636-844f-8821e0239391.mp4

Next up: idk
As for any other turrets, yea no idea.

If your pull request is ***n o t*** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
What if the entire scatter middle section moved back... or the two sides moved out like blades?

**Comment by MEEPofFaith** [comment]
> What if the entire scatter middle section moved back... or the two sides moved out like blades?

Disperse 2 electric boogaloo

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/236699847-9d60fddd-a245-4c16-8871-7f7fa3696e67.mp4

**Comment by MEEPofFaith** [comment]
hm should the recoil entirely be just the midsection, no movement in the sides

**Comment by Anuken** [comment]
image


...this really needs a resprite, I can't tell what I'm looking at honestly

**Comment by MEEPofFaith** [comment]
the barrel looks strange

**Comment by MEEPofFaith** [comment]
https://github.com/Anuken/Mindustry/assets/54301439/83b01d41-5e96-4f26-94ea-acc1f3d97d58

**Comment by Anuken** [comment]
This looks good so far, so I'd be fine with merging it as-is, unless you want to try it with more turrets.

**Comment by MEEPofFaith** [comment]
Sure.
I can always make another pr if I feel like doing more.

**Pull request merged**
