### PR TITLE
Update bundle_hu.properties - The finishing touches

### PR DESCRIPTION
**Pull request by summoner001**
Correction, completion and correction of errors in the Hungarian translation.

Sorry for the many commits, this is the first time I've done this.

This is the final corrections. If you find any problem, I will repair it asap.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
Let me know when this is ready to merge.

**Comment by summoner001** [comment]
> Let me know when this is ready to merge.

Hi Anuken! I think I'm done with the translation now. Of course, if I find any more mistakes or typos, I'll fix them, but for now it looks like the translation is done.

**Comment by summoner001** [comment]
Ready to merge

**Comment by summoner001** [comment]
> Let me know when this is ready to merge.

Ready to merge.

**Pull request merged**
