### PR TITLE
Moving to v7

### PR DESCRIPTION
**Pull request by MaxSMoke-Official**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
~~couldn't you have just done 1 pr with both edits?~~

**Comment by MaxSMoke-Official** [comment]
I dont know how

**Comment by TranquillyUnpleasant** [comment]
> ~couldn't you have just done 1 pr with both edits?~

Don't think browser editor supports editing more than one file per commit

**Comment by LeoSko** [comment]
@TranquillyUnpleasant @MaxSMoke-Official there is actually a built-in VS Code if you press dot . while inside the repo or go to github.dev instead of github.com which lets you do all that crazy stuff.

**Comment by MaxSMoke-Official** [comment]
@LeoSko @TranquillyUnpleasant i do this updates from mobile browzer

**Comment by LeoSko** [comment]
@MaxSMoke-Official Yeah it also works on mobile cool right?

**Comment by Darkness6030** [comment]
I i have to commit from mobile
I first create branch
Then i commit all changes to this branch
Then i make a PR

**Comment by MaxSMoke-Official** [comment]
@Darkness6030 tnx

**Pull request merged**
