### PR TITLE
Add Atomic to the server list

### PR DESCRIPTION
**Pull request by Atomic-Laboratory**

### CODE REVIEW

**Comment by Anuken** [comment]
Server is offline.

**Comment by Atomic-Laboratory** [comment]
@Anuken Server is be back online in port 30315.

**Comment by Anuken** [comment]
If one of the servers is offline, why have it?

**Comment by Atomic-Laboratory** [comment]
@Anuken I wanted to have an extra port for when I require an extra server for plugin testing purposes, where experimental plugin code can be pushed live, without compromising one of the core game modes.

**Pull request merged**
