### PR TITLE
Shift to prioritize build

### PR DESCRIPTION
**Pull request by blahblahbloopster**
Hold shift to prepend build request to queue instead of appending.  Note: I was unable to make it work for breaking requests.

### CODE REVIEW

**Comment by zethnest** [comment]
You mean the boost button? What if the player is boosting?

**Comment by Anuken** [comment]
I'm not a fan of hidden controls like this.

**Comment by sample-text-here** [comment]
Maybe it could be in the tutorial

**Comment by markozajc** [comment]
would be really neat to have

**Pull request closed without merging**
