### PR TITLE
Update servers_v6.json

### PR DESCRIPTION
**Pull request by MaxSMoke-Official**
Add a SMokeOfAnarchy

### CODE REVIEW

**Comment by MaxSMoke-Official** [comment]
If you have a question: welcome!

**Comment by KotMilk** [comment]
М?

**Comment by MaxSMoke-Official** [comment]
> М?

What

**Comment by Anuken** [comment]
Server is down.

**Comment by KirillcraftEX** [comment]
> Server is down.
🤔
Screenshot_20210222-191923208

**Comment by MaxSMoke-Official** [comment]
> Server is down.

No, it always up

**Comment by RebornTrack970** [comment]
Idk, all servers in Hub were down when i checked.

**Comment by MaxSMoke-Official** [comment]
> Idk, all servers in Hub were down when i checked.

Providers damn

**Review by osp54 — APPROVED** [review]
Nice server, but I don't understand why Dosixpore didn't add it

**Pull request merged**
