### PR TITLE
Update contributors

### PR DESCRIPTION
**Pull request by Volas171**

### CODE REVIEW

**Comment by summetdev** [comment]
Why put a new name at the top? It's better to put it at the end.

**Comment by Angel-24** [comment]
> Why put a new name at the top? It's better to put it at the end.

Why? Does it has an order?

**Comment by summetdev** [comment]
> > Why put a new name at the top? It's better to put it at the end.
> 
> Why? Does it has an order?

Yes.

**Comment by Angel-24** [comment]
> > > Why put a new name at the top? It's better to put it at the end.
> > 
> > 
> > Why? Does it has an order?
> 
> Yes.

ok

**Comment by Volas171** [comment]
ok

**Pull request merged**
