### PR TITLE
water extractors are sorta nerfed 2 electric boogaloo

### PR DESCRIPTION
**Pull request by DeltaNedas**
see old pr #1687

### CODE REVIEW

**Comment by DeltaNedas** [comment]
travis y u do this to me

**Comment by ma44** [comment]
What about making water extractors have a negative production modifier when placed on sand via negative affinity?

**Comment by Anuken** [comment]
Sand is often near water, so that won't make a lot of sense in many scenarios.

**Comment by MWestfall** [comment]
can we not please? There are -sooo- many schematics with water extractors in them.   It's going to waste so much space on maps because people will just build water farms and pipe the water over, and what exactly does this accomplish?  Adding the concept of "less water being available if more things are pulling it from the ground in the same area"???? /me checks something.  Yep Mindustry is a video game, not a liquid dynamics simulator.  It would be way cooler if someone could make like one way liquid t-junctions or liquid mass drivers or something.  I mean if I can take titanium turn it into energy, fly it around, and reassemble it later, why can't I do the same thing with liquid?

**Comment by HarzardGoose** [comment]
bad

**Comment by MetaMuffin** [comment]
Doesn't seem to Balance the game. I my opinion water-extractors are not overpowered and not nerfed. I would like to keep them the old way.

**Comment by ThatOneBepis** [comment]
Isn't ignarock and salt enough? Plus, you could just build away themself and place conduits. **You can't escape the extractors**

**Comment by keostar** [comment]
also what about the maps that are basicly only sand? what do you do then

**Comment by Highfire1** [comment]
To put in my two cents, I wouldn't mind a water extractor nerf, but this seems finicky and would fit better in a mod

**Comment by DeltaNedas** [comment]
oh ecan pulled a chinese goverment on me

**Comment by DeltaNedas** [comment]
https://cdn.discordapp.com/attachments/396416151032299521/704410655062491256/unknown.png saddest shit i ever seen

**Comment by MWestfall** [comment]
So it's "sad" that I engaged our community to come comment on this game mechanic change?  One of the people that saw that came here and posted in favor of it.  I simply brought the PR to the attention of people that may or may not have known about it.

What I find sad, is that your discussion on the subject has degraded to calling me the Chinese government and sad.  If you can't add something productive to the discourse and are simply posting for the sole purpose of calling me names and trash-talking, then why post at all?

You sent everyone in this thread two notifications with new messages doing nothing but trash-talking.  How is that productive in any fashion?

**Comment by DeltaNedas** [comment]
no need to ping everyone for a pull that shows up in #1520 leave politics out of your build perms server

**Comment by daxxog** [comment]
> oh ecan pulled a chinese goverment on me

Chinese government doesn't promote open discussion. Also I wouldn't have been aware this was being proposed if ECAN didn't point it out to me in their discord -- I don't check github that often.

**Comment by MWestfall** [comment]
Aight DeltaNedas, if your gonna keep throwing punches I'm going to throw them right back.

1) I didn't even bring this up on the ECAN Server, someone else did, so if you are going to be a bitch, you could at least be a correct bitch.

2) Is it just me or is it completely ironic that you are telling me I'm not allowed to post whatever the hell I want in my own discord server because someone else posted it on some other discord server?

3) What "Politics" are you talking about.  This is not in any shape form or fashion a political discussion nor was it ever, until yours truly mentioned the Chinese Government.

5) News agencies don't just report what nobody else already reported.  And before you say something asinine about how ECAN isn't a "news agency" I'm not saying we are, I'm drawing a parallel.  You seem to think that if anyone was interested in knowing what was going on with the Mindustry game development they should keep their face glued to Anuke's #github channel.....  Most people don't even understand what half that stuff means and there is a lot of information that flows through there.  If I choose to disseminate some or all of that information to my community members, that's my choice and my prerogative.  Plus I'll refer you back to #1 since you probably can't even remember what that said by now, but I didn't even bring it up, one of my community members did.

**Comment by DeltaNedas** [comment]
why did you say it in the first place, rallying up people who havent heard of this to parrot your opinion is scummy
i compared you to the chinese government as notepad++ had an update note that was sided towards taiw*n, followed by an army of chinese bots on github making issues and comments
your personal opinions on server you can ping everyone on (the build perms one ofc)

trying that at all and not backing down shows how scummy you are, please go somewhere else with your fleshy bot army
ok

**Comment by pyronie** [comment]
I think this probably would mess with schematics, but tbh a water extractor is kinda op when you consider it gets water out of apparently thin air at the only cost of power, unlike say a spore extractor which requires a large amount of water per second or an oil extractor, which requires sand to operate.
 Also, telling your entire community they should dislike a pull request is not the same as simply bringing it up.

**Comment by ma44** [comment]
I'd say that water extractors just pale in comparison to just pumping water out of the ground, water extractors is a 90 power consuming that takes up a whopping 4 tiles compared to say a rotary pump with a couple of pipes

**Comment by ifritdiezel** [comment]
Schematics are too easy to just paste everywhere right now. Nerfing extractors is a solution. 
This game is about building and engineering, not stupidly pasting the same schematics on all maps without any need for thinking.

**Comment by Anuken** [comment]
My opinion: Even *if* water extractors need to be nerfed, I don't think this mechanic is a good approach. It's complex, potentially confusing, and difficult to implement properly.

**Comment by MWestfall** [comment]
I obviously cannot control anyone or what they say, I just said "look at this, this sucks go comment yourself" in not so many words. Which there is nothing wrong with that.

If you think there is, maybe you should go to China yourself.

**Comment by ThatOneBepis** [comment]
With all due respect Deltanedas, but just letting a pr merge without the others' opinions will just hurt the playerbase

**Comment by Anuken** [comment]
There's nothing left to discuss here. I'll put up a poll seeing what people think about stat/requirement nerfs to water extractors sometime later.

**Comment by DeltaNedas** [comment]
closing til someone comes up with a better implementation

**Comment by DeltaNedas** [comment]
im not against  different opinions, but getting a bunch of people from gour sedver to parrot your views is wrong, which even zacbytes hasn't done afaik.

**Comment by kapzduke** [comment]
this whole comment section is a mess

**Pull request closed without merging**
