### PR TITLE
WIP Erekir Unit Descriptions

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Issues:
 - [x] I don't know how to describe Conquer's shoot pattern.
 - [x] Is "twisting" the best word to use for Avert and Obviate's helix shoot pattern?
 - [x] I don't know how to describe Tecta's wiggly bullets.
 - [x] Since Erekir core units don't actually attack, the "Defends the <tier> core" thing that Serpulo core units use doesn't work for them. I am not sure what to use instead.
   - [x] "Maintains and expands the base from the \<name> core." doesn't feel right.
 - [x] Quell and Disrupt have the exact same descriptions since both of them do the exact same thing (just Disrupt fires more missiles), change one of the descriptions to be slightly different.

### CODE REVIEW

**Review by stacktrace-error — COMMENTED** [review]
maybe remove the all in "fires <> at all nearby enemies?"

**Comment by MEEPofFaith** [comment]
> maybe remove the "all" in "fires <> at all nearby enemies?"

Well I just copied that from the Serpulo units.
Meant to signify if it shoots all targets or only ground targets.

**Comment by RbCaVi** [comment]
Erekir core units should say repairs buildings

**Comment by Catchears** [comment]
"Maintains and expands the base" for core units?

**Comment by Cry0flu1d** [comment]
maybe tecta's main weapon projectile can be described as "plasma missles"?
btw it should be "**arc** shield" , not just a "regenerating shield"

**Comment by Anuken** [comment]
I won't even be looking at this right now, as many units do not have abilities implemented yet, and several T4/5 units will have their weapons changed.

**Comment by Anuken** [comment]
This has been """merged""", with many changes to the phrasing. My old descriptions with "all nearby" and "enemies" have been adjusted as well.

**Comment by MEEPofFaith** [comment]
I see

**Pull request closed without merging**
