### PR TITLE
New Texture For Blast Mixer

### PR DESCRIPTION
**Pull request by Voz-Duh**
Since Blast Mixer and Pyratite Mixer were too similar, I decided that one of them needed a new sprite
image

### CODE REVIEW

**Comment by summetdev** [comment]
Lines in center are too narrow imo.

**Comment by Voz-Duh** [comment]
image
Better?

**Comment by DarkBrick** [comment]
image
He probably meant this

**Comment by Voz-Duh** [comment]
image

**Comment by Voz-Duh** [comment]
> image
> He probably meant this

I fix it

**Comment by genNAowl** [comment]
looks a bit... bumpy

**Comment by SteelBlue8** [comment]
Feels overdetailed, I'd simplify it- the lines don't need to be that bumpy, and those extra flat bits on the corners are- well,extra. Remove them.

**Comment by Voz-Duh** [comment]
image
Better?

**Comment by Anuken** [comment]
image

While this image you sent previously is over-detailed, I liked the 4 orange radial bars in the middle; they stood out in contrast to the pyratite mixer. Can you try to add these to your latest posted sprite?

**Comment by Voz-Duh** [comment]
Yea

**Comment by Voz-Duh** [comment]
image
Better?

**Comment by Anuken** [comment]
I meant with the bars only, not with the circle around the middle too.

**Comment by Voz-Duh** [comment]
Ok

**Comment by Voz-Duh** [comment]
image

**Pull request merged**
