### PR TITLE
What about more bullet appearance stuff?

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Similar to `bulletShrink`, but horizontal.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
welp, time to make a 6.0 mod to test this

**Comment by Anuken** [comment]
This doesn't compile; *test your changes before submitting them*.

**Comment by MEEPofFaith** [comment]
yes, i know. I'm jsut too lazy to swam Anuken/Mindustry with MEEPofFaith/Mindustry on my Github Desktop.

**Comment by MEEPofFaith** [comment]
btw, was overriding defaults changed at some point? the test mod I created doesn't actually seem to be overriding the copper bullets in the duo.

**Comment by MEEPofFaith** [comment]
unsure why despite `spinSpeed` being 0 by default the Alpha's bullets are spin.

**Comment by MEEPofFaith** [comment]
Ok, it seems to work properly.
[Squish](https://gyazo.com/748d8eda1b0eb82eaabf753a206f6e4f)
[Spin](https://gyazo.com/cf6979ed2572a01574a10edae4090188)

**Comment by MEEPofFaith** [comment]
Conflicts fixed

**Pull request closed without merging**
