### PR TITLE
GameOverMessage?

### PR DESCRIPTION
**Pull request by MindustryIDK**
I think it will be a good idea because it can help to localise or change GameOver message.
I didn't test it, will test later.

### CODE REVIEW

**Comment by MindustryIDK** [comment]
Can anyone approve running this workflow?

**Comment by Anuken** [comment]
ServerControl is not an accessible class.

**Comment by MindustryIDK** [comment]
🤔 so i need to move it?
For example to netServer

**Comment by MindustryIDK** [comment]
🤔 how can i use roundExtraTime variable in netServer?
Maybe move it?

**Comment by MindustryIDK** [comment]
Or there is a better idea?

**Pull request closed without merging**
