### PR TITLE
Phase Fabric ammo for Spectre

### PR DESCRIPTION
**Pull request by z0mbiesrock**
The Spectre is a 4x4 all-around turret with a limited selection of projectiles. By adding phase fabric as a form of ammunition, Spectre turrets have more meaning to their name, which results in bullets that do slightly less damage, but pierce through enemy units.

### CODE REVIEW

**Comment by genNAowl** [comment]
1. Why?
2. Who would use this anyway?
3. Why should phase fabric be an ammo? (I mean its a fabric. And it has "phase" properties. Using phase fabric as an ammo would be like launching T-shirts at enemies)

**Comment by genNAowl** [comment]
4. This doesn't even compile, you need to replace `reloadMultiplier = 1.1;` with `reloadMultiplier = 1.1f;`

**Comment by XEN0PHIL** [comment]
Agreed with genNAowl, phase should not be used as a projectile ammo.
If you want ammo diversity for Spectre, convince Anuke that titanium is a suitable material for bullets :thinking:

**Comment by genNAowl** [comment]
Or maybe silicon as a possible ammo? (to reflect on the fact that the Spectre is an upgraded duo/salvo)

**Comment by z0mbiesrock** [comment]
> Or maybe silicon as a possible ammo? (to reflect on the fact that the Spectre is an upgraded duo/salvo)

Isn't Phase Fabric made from sand, too?

**Comment by sk7725** [comment]
Oh *yes* phase ammo

**Comment by genNAowl** [comment]
> made from sand

Its a fabric. Not a hard material that you can just shoot. Silicon, on the other hand, is already used as an ammo in the Duo and Salvo, and since the Spectre are a high level version of the two, silicon ammo can be added, if only just for consistency.

**Comment by stuffyAI** [comment]
> hase fabric as a form of ammunition

I beg to differ, using phase to boost your entire factory by 250% is more valuable than wasting it as ammo on a dps turret.

**Comment by Anuken** [comment]
Nah.

**Comment by z0mbiesrock** [comment]
5d61aa2be1369

**Comment by Colonizor48** [comment]
check this out for a turret that uses phase https://github.com/Anuken/Mindustry-Suggestions/issues/721

**Comment by Colonizor48** [comment]
@z0mbiesrock The thing is we already kinda have a 3x3 turret that attacks multible enemies. Its called the meltdown.

**Comment by genNAowl** [comment]
> 3x3 turret that attacks multiple enemies. Its called the meltdown.

Last time I checked it was a 4x4.

**Comment by Colonizor48** [comment]
my mistake

**Pull request closed without merging**
