### PR TITLE
Add flarogus to the unit list

### PR DESCRIPTION
**Pull request by SMOLKEYS**
sus
~~spare me~~

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MHeMoTexHuK** [comment]
***you what***

**Comment by NemesisTheory** [comment]
ohno

**Comment by Arkine968** [comment]
mogus

**Comment by pluffie** [comment]
very sus

**Comment by KayWasTaken** [comment]
:flarogus:

**Comment by SMOLKEYS** [comment]
mfw the thing actually compiles:

**Comment by Darkness6030** [comment]
So we now can have flarogus?

**Comment by Darkness6030** [comment]
If anukus merge it

**Comment by EclipseTheOldOne** [comment]
ohno...

**Comment by MEEPofFaith** [comment]
where `flarogus-cell` sprite

**Comment by MissAmity** [comment]
h

**Comment by Rex-Hm** [comment]
it would be great if it were an easter egg

**Comment by Anuken** [comment]
I see a distinct lack of checked boxes

**Comment by SMOLKEYS** [comment]
> I see a distinct lack of checked boxes

oh no

**Comment by KayWasTaken** [comment]
does it compile

**Comment by Ccode-lang** [comment]
Someone test this now!!! Confirm that it works... ***very sus though***

**Comment by KayWasTaken** [comment]
the check passed, im pretty sure it compiles

**Comment by KayWasTaken** [comment]
~~oh wait the last checkbox is the functions~~

**Review by Mnemotechnician — APPROVED** [review]
perfect implementation

**Comment by EclipseTheOldOne** [comment]
~~why this thing got uodated~~

**Comment by Mnemotechnician** [comment]
> ~why this thing got uodated~

preparing for a merge

**Comment by Erisfiregamer1** [comment]
sus

**Comment by SMOLKEYS** [comment]
oh wrong branch

oh no

**Comment by DeltaNedas** [comment]
i have a sister pr ready for april 1th

**Comment by SMOLKEYS** [comment]
apologies, for i have accidentally made commits in the flarogus branch that break the game

i will create a new pr before april 1st

also

delta

> 1th

**Comment by Mnemotechnician** [comment]
noooo..

**Pull request closed without merging**
