### PR TITLE
Make PlayerInfo map public

### PR DESCRIPTION
**Pull request by Darkness6030**
Because I'm tired of using Reflect to access it (for example, to find a PlayerInfo by USID)

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
Maybe add methods to do what you want instead of exposing implementation details?

**Comment by Darkness6030** [comment]
> Maybe add methods to do what you want instead of exposing implementation details?

What is the best method name you can choose in your opinion? "getPlayerInfos" / "getPlayerInfoMap" / something else?

**Comment by Anuken** [comment]
No, I mean, to do things like

> find a PlayerInfo by USID

> getPlayerInfos

Adding a getter doesn't solve anything, since you can easily just mutate the map from there, and it still exposes the same implementation details.

**Comment by Darkness6030** [comment]
> exposes the same implementation details.

I don't think it's a problem. What really bad can happen if the plugin changes some entries ​​in this map? 👀

**Comment by Anuken** [comment]
> What really bad can happen if the plugin changes some entries ​​in this map? 

It won't get saved, or it will break plugins if the storage data structure ever changes. But if you're really fine with being able to shoot yourself in the foot with this in the future, sure.

**Pull request merged**
