### PR TITLE
Update servers_v6.json

### PR DESCRIPTION
**Pull request by Xasmedy**
Add mindustry.ddns.net servers. Till online and ready to go ;)

### CODE REVIEW

**Review by WilloIzCitron — COMMENTED** [review]
A custom ddns?

**Comment by Xasmedy** [comment]
> A custom ddns?

What you mean?

**Comment by Anuken** [comment]
Might need fixing later:

image

**Comment by Xasmedy** [comment]
> Might need fixing later:
> 
> image

Sup

**Pull request merged**
