### PR TITLE
Make chat show/hide setting vaiable

### PR DESCRIPTION
**Pull request by Kieaer**
I've thought of other ways, but nothing like that.

Usage
``NetClient.visual = true/false;``
If you want to show chat
```
Events.on(PlayerChatEvent.class, e -> {
    Call.sendMessage(e.message, colorizeName(e.player.id, e.player.name), e.player);
});
```

If you want bad words filtering
```
Events.on(PlayerChatEvent.class, e -> {
    if(!e.message.equals("where's your mom?"){
        Call.sendMessage(e.message, colorizeName(e.player.id, e.player.name), e.player);
    }
});
```

This can be a bad thing, but it's a must.

### CODE REVIEW

**Comment by Anuken** [comment]
Why not set chat visibility to 0% if you don't want to see it?

**Comment by Kieaer** [comment]
No no. This's used by plugins and mods.

**Comment by Kieaer** [comment]
ezgif com-video-to-gif

**Comment by Kieaer** [comment]
I came up with a better way than this.

**Pull request closed without merging**
