### PR TITLE
Battery Power Bar

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Adds power use bar to batteries.

https://user-images.githubusercontent.com/54301439/136485778-fd72972d-bf0a-42d7-9924-31f6b4e7f17e.mp4

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by begginerr** [comment]
this is mostly useless but cool

**Comment by Anuken** [comment]
This has a lot of node bar copy-pasting, so I'd rather avoid it.

**Comment by MEEPofFaith** [comment]
~~you think of a better way then :)))~~

**Comment by Anuken** [comment]
~~solution: do absolutely nothing~~

**Comment by MEEPofFaith** [comment]
~~aaaaAAAAAA~~

**Pull request closed without merging**
