### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@Quezler legit question (since you reacted to the issue), is it a typo or not?

`require restart` sounds weird to me.

**Comment by Quezler** [comment]
compare it to the english bundle to be sure ^

**Comment by TheEvilSkeleton** [comment]
I don't understand what you are talking about; can you explain it?

**Comment by Anuken** [comment]
This occurs in multiple bundles, so I'll fix it myself.

**Pull request closed without merging**
