### PR TITLE
[Bundle][ID] Updated translation

### PR DESCRIPTION
**Pull request by DaGamerFiles**
Sector names are reverted back to previous translation name along with the updated new sectors, Foreshadow block description, sector captured/attacked/lost popup, threats, stats, and other fixes. Ready to merge.

### CODE REVIEW

**Comment by DaGamerFiles** [comment]
@Quick-korkc @grimsoul10

**Comment by Quick-korkc** [comment]
@DaGamerFiles why still draft?

**Comment by DaGamerFiles** [comment]
There are a lot of untranslated strings earlier so I decided to set this as a draft. Will be opened soon.

**Comment by Quick-korkc** [comment]
alright then

**Pull request merged**
