### PR TITLE
el naval unit resprita

### PR DESCRIPTION
**Pull request by kapzduke**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Darkness6030** [comment]
why

**Comment by Auro-1** [comment]
please do not send email to me

**Comment by Anuken** [comment]
Some of my naval sprites definitely aren't the greatest, but this reminds me of corporate logo simplification a bit.

**Comment by BlueWolf3682** [comment]
these look better than the current sprites, especially naval support as naval support sprites are noisy and not too good
it may seem like simplification but at least the sprites have structure and make sense
that being said, aegires feels... off, a big egg doesnt shade well no matter what is done with it so it may be better to entirely clange its sprite design

**Pull request closed without merging**
