### PR TITLE
Barrel system for turrets so you can set where and the rotation that bullets spawn from.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
[Demonstration](https://youtu.be/bLPek-m7tZY)

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
[Now Applies to ChargeTurret](https://youtu.be/MeGuAUGDew0)

**Comment by MEEPofFaith** [comment]
Since the LaserTurret works by updating its bullet constantly while firing, I don't think doing barrel stuff on it is possible, and I won't even try.

**Comment by GlennFolker** [comment]
why not try, for loop exist

**Comment by BlueWolf3682** [comment]
(the video isnt that helpful, us a larger turret like the Wolf's Teeth)

**Comment by MEEPofFaith** [comment]
Note: I have no idea what the player and bullet .json things that changed are, they just happened on their own,

Also, Blue, no.

**Comment by BlueWolf3682** [comment]
then use a larger turret, the barrel code for the swarmer is simply too hard to see cause the turret is small

also, meep, yes

**Comment by MEEPofFaith** [comment]
I'm not gonna record another video, but if I somehow am forced to do it I'll use Spectre.

**Comment by MEEPofFaith** [comment]
If I have a `Time.run` thing inside of a for loop, how can I use the variable in the for loop?
Because what I currently have doesn't work.
```java
for(int i = 0; i < shots; i++){
  Time.run(burstSpacing * i, () ->{
    blah blah, coded uses i
  }
}
```
Has error

**Comment by MEEPofFaith** [comment]
[This is fun to mess with](https://youtu.be/jkaHf1BfqyE)

**Comment by sk7725** [comment]
Increase in calculations is not a good idea at all.

**Comment by summetdev** [comment]
In the future: don't edit the master branch, instead create a new branch and make a pull request.

**Comment by MEEPofFaith** [comment]
> In the future: don't edit the master branch, instead create a new branch and make a pull request.

I accidentally created it on master. I guess when you directly edit a file and let it make the fork for you it automatically puts it on the Master branch instead of creating a master and a separate branch for the suggested edits. Well, at least any branches I make are based on the master branch of `Anuke/Mindustry` instead of `MEEPofFaith/Mindustry`.

**Comment by MEEPofFaith** [comment]
Whoops, thought I was on `Anuken/Mindustry`, but instead I was on `MEEPofFaith/Mindustry`

**Comment by MEEPofFaith** [comment]
Gone stale, closing

**Pull request closed without merging**
