### PR TITLE
Lightning on tile collision

### PR DESCRIPTION
**Pull request by MEEPofFaith**

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Wait, was something changed between 5.0 and 6.0 with lightning? Seems to happen without my changes.

**Comment by Anuken** [comment]
I fixed this on my end; "lightining" was just a typo.

**Comment by MEEPofFaith** [comment]
The lightningDamage might be might though

**Comment by Anuken** [comment]
It might not be might.

**Comment by MEEPofFaith** [comment]
that sounds like an oh no to me.

**Pull request closed without merging**
