### PR TITLE
Updated tutorial text and added emojis

### PR DESCRIPTION
**Pull request by XEN0PHIL**
Changed lines from .intro to .launch

### CODE REVIEW

**Comment by XEN0PHIL** [comment]
1. Is there issues with an updated text?
2. Should I put brackets around all emojis?
3. Should I remove all brackets around emojis?
4. Should I add another space between the word and and emoji?

**Comment by Quezler** [comment]
question for anuke: which way of typing them is preferable?
-  "chinese style"
- \uf822 "unicode escape"
- https://github.com/Anuken/Mindustry-Suggestions/issues/18 "color tag-ish"

**Comment by Anuken** [comment]
I would use "chinese-style" for now. :emoji: style would be an improvement in readability, but requires some further consideration to determine how exactly it will be implemented.

**Comment by Anuken** [comment]
> Is there issues with an updated text?

There are some improvements in clarity, but I see numerous grammatical errors in your changes. I'll need to look over it.

**Pull request closed without merging**
