### PR TITLE
flarogus but without breaking everything

### PR DESCRIPTION
**Pull request by SMOLKEYS**
updated, and no more miscommits :pain:

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
#6657 sister pr

**Review by DeltaNedas — APPROVED** [review]

**Comment by Anuken** [comment]
The "hole" in the unit body should be shaded in, it'll cause problems otherwise.

**Comment by SMOLKEYS** [comment]
> The "hole" in the unit body should be shaded in, it'll cause problems otherwise.

flarogus

Is this better?

**Comment by Anuken** [comment]
yes

**Comment by MEEPofFaith** [comment]
I see a distinct lack of checked boxes

**Comment by SMOLKEYS** [comment]
the end

**Pull request closed without merging**
