### PR TITLE
Unit frags shouldn't keep velocity

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/156938030-5b74fd46-3c14-4475-803c-9003c67be30f.mp4

Alternative to #6623

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
~~The velocity of the unit transferring into a bullet's frags makes no sense.~~

**Comment by MEEPofFaith** [comment]
\*realizes I added to the wrong bullet\*

**Comment by mse-k** [comment]
it makes sense kinda, but should be alot less powerful on the frags, if a bullet were to hit something and it was moving really fast in one direction it would make sense for the frags to also have a little of that velocity too

**Comment by MEEPofFaith** [comment]
> it makes sense kinda, but should be alot less powerful on the frags, if a bullet were to hit something and it was moving really fast in one direction it would make sense for the frags to also have a little of that velocity too

But does this make sense?

https://user-images.githubusercontent.com/54301439/156938678-7797de4f-9e5b-442d-a4ae-a3b2c1cbf611.mp4

**Comment by mse-k** [comment]
wait it takes velocity from the unit not the bullet??

**Comment by MEEPofFaith** [comment]
always has been

**Comment by mse-k** [comment]
maybe have the bullet save the velocity of the unit when it shot its bullet in the bullet and use that for the velocity of the fragments

**Comment by Anuken** [comment]
If neither of these make sense, I can just make frag bullets get forced to keepVelocity = false everywhere as a default. As mentioned earlier, it's not a good idea to have broken behavior by default.

**Pull request closed without merging**
