### PR TITLE
var -> let

### PR DESCRIPTION
**Pull request by skykatik**
var deprecated, use let or const

### CODE REVIEW

**Comment by ThePythonGuy3** [comment]
Lovely how u didnt know that rhino doesnt support let

**Comment by ThePythonGuy3** [comment]
Please check your changes before making pull requestst

**Comment by skykatik** [comment]
Ok. Why he doesn't support?
This seems very strange

**Comment by summetdev** [comment]
> Lovely how u didnt know that rhino doesnt support `let`

Works well.

**Review by summetdev — APPROVED** [review]

**Pull request merged**
