### PR TITLE
Slider Togglable Unit Opacity

### PR DESCRIPTION
**Pull request by zethnest**
Peek 2020-05-12 18-07
It is as the title and GIF shows. This solves the problem where there are flying units nearby of where you want to build and you can't see what's underneath the unit.

The default key to toggle unit opacity is F7, right beside power line opacity and bridge opacity which are F5 and F6.

### CODE REVIEW

**Comment by zethnest** [comment]
Implements https://github.com/Anuken/Mindustry-Suggestions/issues/108

**Comment by Anuken** [comment]
Sorry, no.

- This significantly complicates unit rendering. Every single time I add a new function or custom drawing for a unit, I'll have to test make sure it renders correctly. Mods are guaranteed to break this if they use `Draw.color()` somewhere, and maintenance will be a general mess.
- It doesn't look very good.
- You should be able to move the units somewhere else instead of making them ghosts.

**Comment by zethnest** [comment]
> You should be able to move the units somewhere else instead of making them ghosts.
This works for land units but not flying units

**Comment by Anuken** [comment]
It *would* work for flying units, if you could control them. That's not possible right now, but it will be.

**Pull request closed without merging**
