### PR TITLE
Make peoples are possible to alliance. Hex war related.

### PR DESCRIPTION
**Pull request by player20033**
It passed to compile, however I don't know how to test or debug does it works.

### CODE REVIEW

**Comment by player20033** [comment]
I don't understand what it does means.
https://github.com/Anuken/Mindustry/blob/d6d6dc29dc5cca2d702a67e09c78b36b3b84996d/core/src/mindustry/ai/BlockIndexer.java#L158

**Comment by player20033** [comment]
Travis check is failed was false alarm.
So, I need people to help me testing the alliance function.
Related: https://github.com/Anuken/HexedPlugin/pull/2

**Comment by Arkanic** [comment]
this doesn't just affect hexWars, this affects all gamemodes that involve multiple teams, which is a real issue

example:
2 team PvP, if they make an alliance, the game will never end
it will literally never end

**Comment by player20033** [comment]
> this doesn't just affect hexWars, this affects all gamemodes that involve multiple teams, which is a real issue
> 
> example:
> 2 team PvP, if they make an alliance, the game will never end
> it will literally never end

I see, however I don't see a way to help me debug alliance function. and alliance function should be integrated on main game code.

**Comment by player20033** [comment]
I am give up for this, sorry.

**Pull request closed without merging**
