### PR TITLE
Power Source Power Generation Stat

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Adds power source power generation to its stats.

### CODE REVIEW

**Comment by joshuaptfan** [comment]
Why not reuse the "Base Power Generation" string instead of creating a new string?

**Comment by MEEPofFaith** [comment]
Power Source power generation doesn't change dynamically, so the power generation is a base that changes, but is instead constant.

**Comment by joshuaptfan** [comment]
Then at least name the string `stat.powergeneration` so that it can be reused for other constant power sources.

**Comment by liuxilu** [comment]
But it's not a 'generator' but a 'magic source'.
And there're other generators with unbootable output.

**Comment by MEEPofFaith** [comment]
🤔

**Comment by Anuken** [comment]
I'd rather not add another stat for this, it just seems unnecessary.

**Pull request closed without merging**
