### PR TITLE
Properly update map name and gamemode on steam

### PR DESCRIPTION
**Pull request by buthed010203**
This has been bugging me for the longest time but I've been too lazy to fix it, I finally got around to doing so.

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by LeoSko** [comment]
*codestyle \*cough\**

**Comment by Anuken** [comment]
`) {`

**Comment by buthed010203** [comment]
I swear to you i copy pasted it and didnt add the space, it added itself

**Comment by buthed010203** [comment]
@Anuken fixed

**Comment by Anuken** [comment]
IntelliJ has formatting rules that automatically apply, I believe you can make them project-specific.

**Comment by buthed010203** [comment]
~~I dont have those enabled, its probably just muscle memory~~

**Pull request merged**
