### PR TITLE
Cease node dumbness

### PR DESCRIPTION
**Pull request by buthed010203**
I'm so sick of placing nodes in a schematic and having them link to some random buildings instead of the correct ones, this should half fix the problem (will still break if the node is placed before any of the other buildings but I really can't be bothered at this point).

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
> I have ensured that any new features in this PR function correctly in-game, if applicable.

...but does it work?

**Comment by buthed010203** [comment]
> ...but does it work?

You tell me :^)

**Comment by buthed010203** [comment]
Actually.. I can make other improvements

**Comment by buthed010203** [comment]
It works

**Comment by bendnuts** [comment]
plz merge

**Comment by Anuken** [comment]
What's the point of the other new changes?

**Comment by buthed010203** [comment]
> What's the point of the other new changes?

The while loop change was just something I did, idk. The other thing allows you to hold shift when double clicking a node to add more links (clicking 4 times works but it often ends up exceeding ratelimits which is annoying)

**Comment by Anuken** [comment]
> The while loop change was just something I did, idk.

It looks like more code, so unless that old loop is specifically broken, please don't change it.

> I feel like i've asked this before but what are your thoughts on changing tileConfig to use Variant.both and then sending players the correct config when they get ratelimited? I think it would be a lot better to have it be eventually consistent for the player than for it to just desync even if it does feel strange.

Yes, that would be better than what it does now.

**Comment by buthed010203** [comment]
> It looks like more code, so unless that old loop is specifically broken, please don't change it.
Wouldn't the change I just proposed cause issues with the while loop running infinitely if the player has super low ping?

**Comment by Anuken** [comment]
No, since the config will always happen locally immediately, even if it is reverted later by the server.

**Comment by buthed010203** [comment]
Fair enough, now the only issue is that it still configs it on the server as well which is problematic

**Comment by buthed010203** [comment]
> I don't really see a better solution - it's the only action that needs manual reverting on the client end, so you need similar code _somewhere_.

Fair enough, this is what ive settled with, unsure if I should be using the player or null for `packet.player`:
image

**Comment by Anuken** [comment]
It's easiest to just merge one PR, so keep it as part of this one + the undone loop.

**Comment by buthed010203** [comment]
Cool will do, just gonna test it to make sure it works first

**Comment by Anuken** [comment]
Was fixed in the private branch, just ignore it for now.

**Comment by buthed010203** [comment]
Ok cool it works, it will probably look really weird on servers that have the ratelimit warnings off (by setting the kick to the same as the limit itself) since the configs will just undo themselves then you will get kicked but thats not a thing any ~~good~~ server really does anyways.

**Comment by Anuken** [comment]
That would be quite useful, but only after the private branch is merged - what needs to change?

...I should really hurry up with the private branch stuff after April 1st is over.

**Comment by buthed010203** [comment]
> That would be quite useful, but only after the private branch is merged - what needs to change?

Should *in theory* be as simple as `- uses: gradle/gradle-build-action@v2`, see https://github.com/gradle/gradle-build-action#caching for info

**Comment by Anuken** [comment]
Added it to the actions, will see if it explodes.

**Comment by buthed010203** [comment]
I think the main reason its still slow is because its recompiling the whole module anyways as this branch doesn't have incremental compiling working maybe? idk

**Comment by Anuken** [comment]
Yes, I know it doesn't, I'm just checking if it works at all.

**Comment by buthed010203** [comment]
`kapt.classloaders.cache.size=1` In the `gradle.properties` seems to make the tiniest difference in speed though its hard to tell

**Comment by buthed010203** [comment]
image
Its a lot faster when building the client with the caching stuff enabled, nice

**Comment by buthed010203** [comment]
hmm, I'm tempted to actually just move the configuration on place from the server to the client so I can change it in a custom client...

**Comment by buthed010203** [comment]
Or I could just do this server side
image

**Comment by buthed010203** [comment]
~~I actually lied, I tested the other change and it works so im gonna make another pr lol~~

**Pull request merged**
