### PR TITLE
Come back to v6

### PR DESCRIPTION
**Pull request by MaxSMokeSkaarj**
trying to back

### CODE REVIEW

**Comment by MaxSMokeSkaarj** [comment]
I thought there was an automerge after the jar build

**Comment by MaxSMokeSkaarj** [comment]
damn, host is down... Waiting for wounder.

**Comment by KotMilkMeoWtwo** [comment]
Cum

**Comment by SachaTending** [comment]
YAY

**Comment by MaxSMokeSkaarj** [comment]
btw host is up

**Comment by MaxSMokeSkaarj** [comment]
waiting for @Anuken(sorry for ping)

**Comment by MaxSMokeSkaarj** [comment]
merge plz

**Comment by Mnemotechnician** [comment]
be patient.

**Comment by MaxSMokeSkaarj** [comment]
> be patient.

i havent time, 21:34, Vladivostok

**Pull request merged**
