### PR TITLE
[modding] unit power cell position

### PR DESCRIPTION
**Pull request by Quezler**
https://discordapp.com/channels/391020510269669376/396416151032299521/661564554995695634

### CODE REVIEW

**Comment by DeltaNedas** [comment]
please merge god damn

**Comment by Qix-** [comment]
@Anuken Anything blocking this? Any feedback?

**Comment by Anuken** [comment]
Like all other changes to units, this becomes invalid with 6.0's rewrite of the entity system, so merging it would only lead to conflicts and eventual removal.

**Comment by Qix-** [comment]
@anuken does the new system have this functionality? Or can it be added to the new system?

**Comment by Anuken** [comment]
You can implement your own rendering of the power cell easily, so yes.

**Comment by Qix-** [comment]
Oh neat, thanks.

For anyone wondering: https://github.com/Anuken/Mindustry/blob/b0d65dcedb26014580632a9b0d8d597f0c7f8ccc/core/src/mindustry/entities/type/Unit.java#L383-L391

**Pull request closed without merging**
