### PR TITLE
Team Indicator For Plastanium Conveyor

### PR DESCRIPTION
**Pull request by Voz-Duh**
In this pull I create team indicator for plastanium conveyor
team-indicator-for-plastanium-conveyor

### CODE REVIEW

**Comment by Quezler** [comment]
does it need to look like a tail, or can you make the regions flush with the outer and inner circle?

**Comment by Voz-Duh** [comment]
Hm...
Yes i can

**Comment by Voz-Duh** [comment]
image

**Comment by Quezler** [comment]
oh wow, i'd expected a small dot flush with the end, but i like these wings a lot, ima test them ingame today 👀

**Comment by Voz-Duh** [comment]
/-/

**Comment by sk7725** [comment]
Make the ones on your team not display the wings, so you can enjoy the roomba raw

**Comment by Quezler** [comment]
i've tested it ingame, and they are moving to quick (even when not overdriven at all) to see the detailed wings, i think this pull would only make it in if the default speed of them is significantly slower & their item capacity a lot higher 🤔 (like 1/4th and 25)

**Comment by Voz-Duh** [comment]
> i've tested it ingame, and they are moving to quick (even when not overdriven at all) to see the detailed wings, i think this pull would only make it in if the default speed of them is significantly slower & their item capacity a lot higher 🤔 (like 1/4th and 25)

Press space-bar

**Comment by Voz-Duh** [comment]
> Make the ones on your team not display the wings, so you can enjoy the roomba raw

No

**Comment by MEEPofFaith** [comment]
maybe change the color of the front tip things, or naw.

**Comment by Quezler** [comment]
> maybe change the color of the front tip things, or naw.

those are eyes, and their color kinda needs to stay the same.

**Comment by MEEPofFaith** [comment]
i didn't know those were eyes.
~~Now give them colored laser vision.~~

**Comment by Voz-Duh** [comment]
Magic

**Pull request closed without merging**
