### PR TITLE
Make renderer shader final

### PR DESCRIPTION
**Pull request by LeoDog896**
Seriously, it shouldn't be editable.

### CODE REVIEW

**Comment by Anuken** [comment]
There are hundreds (if not thousands) of cases like this across the codebase, does it really matter?

**Comment by LeoDog896** [comment]
No, not really, just in the case of purpose. Feel free to close it then.

**Comment by Anuken** [comment]
In this case, it probably wouldn't do any harm, but in general I avoid `final` for many variables as it doesn't affect performance[1] and only leads to problems with modding in the future.


*[1]: yes I am aware that certain `static final` primitive/string fields are inlined, but those cases are quite rare*

**Comment by sk7725** [comment]
*oh no no no no no no*

**Comment by LeoDog896** [comment]
should we reverse the commit?

**Comment by sk7725** [comment]
tbh I wanted to change that to *public* entirely

**Comment by LeoDog896** [comment]
oH yeah feel free to edit it

**Comment by LeoDog896** [comment]
or make a PR with that, I'm sure no one would mind it :D

**Comment by Anuken** [comment]
> oh no no no no no no

Were you really thinking of touching the *IndexedRenderer* shader? What use could that serve?

**Comment by sk7725** [comment]
> Were you really thinking of touching the _IndexedRenderer_ shader? What use could that serve?

Sorry, I guess I misread.

**Pull request merged**
