### PR TITLE
[ImgBot] Optimize images - Lossless

### PR DESCRIPTION
**Pull request by ghostslayer989**
(When you want to do something but a bot automatically makes a PR.)
*Total -- 21,951.58kb -> 18,488.38kb (15.78%)

/core/assets-raw/sprites/blocks/extra/rubble-6-0.png -- 2.71kb -> 1.05kb (61.33%)
/core/assets-raw/sprites/blocks/extra/rubble-6-1.png -- 2.71kb -> 1.05kb (61.33%)
/core/assets-raw/sprites/blocks/extra/rubble-7-1.png -- 3.11kb -> 1.22kb (60.75%)
/core/assets-raw/sprites/blocks/extra/rubble-7-0.png -- 3.11kb -> 1.22kb (60.75%)
/core/assets-raw/sprites/blocks/extra/rubble-8-0.png -- 3.67kb -> 1.49kb (59.3%)
/core/assets-raw/sprites/blocks/extra/rubble-8-1.png -- 3.67kb -> 1.49kb (59.3%)
/core/assets-raw/sprites/zones/zone-overgrowth.png -- 32.55kb -> 15.92kb (51.1%)
/core/assets-raw/sprites/blocks/extra/rubble-5-1.png -- 2.19kb -> 1.10kb (49.93%)
/core/assets-raw/sprites/blocks/extra/rubble-5-0.png -- 2.19kb -> 1.10kb (49.93%)
/core/assets-raw/sprites/zones/zone-desolateRift.png -- 8.00kb -> 4.09kb (48.87%)
/core/assets-raw/sprites/zones/zone-tarFields.png -- 14.10kb -> 7.37kb (47.71%)
/core/assets-raw/sprites/zones/zone-nuclearComplex.png -- 14.68kb -> 7.69kb (47.59%)
/core/assets-raw/sprites/zones/zone-ruinousShores.png -- 19.04kb -> 9.98kb (47.55%)
/core/assets-raw/sprites/zones/zone-fungalPass.png -- 7.21kb -> 3.78kb (47.49%)
/core/assets-raw/sprites/zones/zone-saltFlats.png -- 15.08kb -> 7.94kb (47.36%)
/core/assets-raw/sprites/zones/zone-craters.png -- 9.72kb -> 5.13kb (47.23%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/7.png -- 570.03kb -> 303.71kb (46.72%)
/core/assets-raw/sprites/zones/zone-frozenForest.png -- 8.80kb -> 4.71kb (46.49%)
/core/assets-raw/sprites/zones/zone-stainedMountains.png -- 16.96kb -> 9.20kb (45.76%)
/core/assets-raw/sprites/blocks/walls/insulator-wall-large.png -- 1.59kb -> 1.08kb (32.39%)
/core/assets-raw/sprites/zones/zone-desertWastes.png -- 37.95kb -> 27.72kb (26.95%)
/android/res/mipmap-hdpi/ic_launcher_background.png -- 4.98kb -> 3.67kb (26.25%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png -- 582.71kb -> 430.82kb (26.07%)
/core/assets/sprites/sprites4.png -- 134.17kb -> 100.70kb (24.94%)
/core/assets-raw/sprites/zones/zone-groundZero.png -- 28.84kb -> 22.34kb (22.53%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/6.png -- 259.72kb -> 206.00kb (20.68%)
/android/res/drawable/ic_launcher_background.png -- 44.75kb -> 35.80kb (20.01%)
/android/res/mipmap-hdpi/ic_launcher_foreground.png -- 8.25kb -> 6.68kb (19.08%)
/ios/data/Default-Portrait@2x~ipad.png -- 2,167.13kb -> 1,762.43kb (18.67%)
/ios/data/Default-736h.png -- 2,080.05kb -> 1,693.94kb (18.56%)
/ios/data/Default-Landscape@2x~ipad.png -- 1,875.97kb -> 1,528.59kb (18.52%)
/core/assets-raw/sprites/units/reaper.png -- 23.52kb -> 19.19kb (18.44%)
/ios/data/Default-Landscape-736h.png -- 1,603.82kb -> 1,309.94kb (18.32%)
/android/res/mipmap-xhdpi/ic_launcher_foreground.png -- 11.84kb -> 9.74kb (17.71%)
/android/res/mipmap-mdpi/ic_launcher_foreground.png -- 5.10kb -> 4.20kb (17.66%)
/ios/data/Default-Landscape~ipad.png -- 631.88kb -> 520.52kb (17.62%)
/ios/data/Default-Portrait~ipad.png -- 725.26kb -> 598.55kb (17.47%)
/ios/data/Default-667h.png -- 905.14kb -> 748.15kb (17.34%)
/ios/data/Default-568h@2x~iphone.png -- 705.74kb -> 584.35kb (17.2%)
/ios/data/Default@2x~iphone.png -- 597.73kb -> 495.03kb (17.18%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-512.png -- 118.74kb -> 99.02kb (16.61%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-256.png -- 44.13kb -> 36.93kb (16.3%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-128.png -- 15.81kb -> 13.33kb (15.7%)
/core/assets-raw/sprites/blocks/drills/blast-drill.png -- 1.20kb -> 1.01kb (15.65%)
/ios/data/Default~iphone.png -- 204.04kb -> 172.40kb (15.51%)
/core/assets-raw/sprites/blocks/walls/insulator-wall.png -- 1.07kb -> 0.92kb (14.27%)
/core/assets-raw/sprites/units/lich.png -- 18.05kb -> 15.53kb (13.96%)
/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png -- 30.44kb -> 26.20kb (13.93%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-88.png -- 8.80kb -> 7.60kb (13.7%)
/android/res/mipmap-mdpi/ic_launcher_background.png -- 2.83kb -> 2.44kb (13.7%)
/android/res/mipmap-xxhdpi/ic_launcher_foreground.png -- 20.79kb -> 17.95kb (13.65%)
/core/assets-raw/sprites/blocks/environment/white-tree.png -- 13.03kb -> 11.35kb (12.95%)
/android/res/mipmap-xxhdpi/ic_launcher.png -- 16.93kb -> 14.78kb (12.67%)
/core/assets-raw/sprites/blocks/environment/white-tree-dead.png -- 13.75kb -> 12.11kb (11.95%)
/core/assets-raw/sprites/blocks/storage/launch-pad-large.png -- 1.20kb -> 1.06kb (11.84%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-64.png -- 5.52kb -> 4.92kb (10.84%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png -- 709.16kb -> 632.29kb (10.84%)
/core/assets/sprites/logo.png -- 19.85kb -> 17.73kb (10.67%)
/fastlane/metadata/android/en-US/images/sevenInchScreenshots/2.png -- 1,086.23kb -> 977.31kb (10.03%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png -- 1,086.23kb -> 977.31kb (10.03%)
/core/assets-raw/sprites/blocks/drills/blast-drill-rim.png -- 0.78kb -> 0.71kb (9.75%)
/fastlane/metadata/android/en-US/images/sevenInchScreenshots/1.png -- 889.74kb -> 803.05kb (9.74%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-main.png -- 251.46kb -> 227.38kb (9.58%)
/android/res/mipmap-xxhdpi/ic_launcher_round.png -- 20.25kb -> 18.42kb (9.04%)
/core/assets-raw/sprites/units/eradicator.png -- 1.95kb -> 1.77kb (8.92%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/4.png -- 952.20kb -> 867.90kb (8.85%)
/fastlane/metadata/android/en-US/images/sevenInchScreenshots/3.png -- 952.20kb -> 867.90kb (8.85%)
/fastlane/metadata/android/en-US/images/featureGraphic.png -- 649.19kb -> 592.05kb (8.8%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-196.png -- 38.61kb -> 35.45kb (8.19%)
/android/res/mipmap-xxxhdpi/ic_launcher.png -- 23.36kb -> 21.48kb (8.04%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-48.png -- 3.49kb -> 3.21kb (7.99%)
/fastlane/metadata/android/en-US/images/icon.png -- 69.57kb -> 64.26kb (7.63%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-180.png -- 32.93kb -> 30.54kb (7.25%)
/core/assets-raw/sprites/units/chaos-array.png -- 1.38kb -> 1.28kb (7.13%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-144.png -- 22.05kb -> 20.48kb (7.13%)
/core/assets/sprites/backgrounds/stars.png -- 76.88kb -> 71.46kb (7.05%)
/core/assets-raw/sprites/units/revenant.png -- 1.39kb -> 1.29kb (7.04%)
/core/assets-raw/sprites/effects/circle-shadow.png -- 9.62kb -> 8.95kb (6.98%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-152.png -- 25.08kb -> 23.40kb (6.69%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-120.png -- 16.90kb -> 15.79kb (6.56%)
/android/res/mipmap-xxxhdpi/ic_launcher_round.png -- 29.00kb -> 27.11kb (6.5%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-167.png -- 28.85kb -> 26.98kb (6.49%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-172.png -- 30.20kb -> 28.27kb (6.4%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-114.png -- 15.60kb -> 14.63kb (6.21%)
/core/assets-raw/sprites/blocks/distribution/mass-driver.png -- 1.28kb -> 1.21kb (5.86%)
/android/res/mipmap-xhdpi/ic_launcher.png -- 9.50kb -> 8.97kb (5.58%)
/core/assets-raw/sprites/blocks/walls/scrap-wall-gigantic.png -- 0.80kb -> 0.76kb (5.49%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-72.png -- 7.40kb -> 7.01kb (5.27%)
/fastlane/metadata/android/en-US/images/phoneScreenshots/5.png -- 642.48kb -> 608.86kb (5.23%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-80.png -- 8.45kb -> 8.05kb (4.83%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-87.png -- 9.98kb -> 9.52kb (4.64%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-100.png -- 12.60kb -> 12.01kb (4.63%)
/android/res/mipmap-mdpi/ic_launcher.png -- 4.07kb -> 3.89kb (4.58%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-76.png -- 8.18kb -> 7.82kb (4.37%)
/core/assets-raw/sprites/blocks/storage/core-nucleus.png -- 12.34kb -> 11.89kb (3.64%)
/core/assets-raw/sprites/blocks/power/impact-reactor.png -- 12.59kb -> 12.14kb (3.55%)
/android/res/mipmap-xhdpi/ic_launcher_background.png -- 7.42kb -> 7.17kb (3.4%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-60.png -- 5.75kb -> 5.59kb (2.79%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-55.png -- 4.77kb -> 4.65kb (2.6%)
/core/assets-raw/sprites/blocks/power/impact-reactor-plasma-0.png -- 0.68kb -> 0.66kb (2.59%)
/core/assets-raw/sprites/weapons/eradication-equip.png -- 0.91kb -> 0.88kb (2.59%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-32.png -- 2.07kb -> 2.02kb (2.36%)
/core/assets-raw/sprites/blocks/turrets/ripple.png -- 12.96kb -> 12.66kb (2.32%)
/android/res/mipmap-xxhdpi/ic_launcher_background.png -- 16.35kb -> 16.00kb (2.14%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-57.png -- 5.21kb -> 5.10kb (2.02%)
/android/ic_launcher-web.png -- 87.03kb -> 85.63kb (1.61%)
/core/assets-raw/sprites/effects/laser-end.png -- 8.09kb -> 7.96kb (1.59%)
/core/assets-raw/sprites/ui/nomap.png -- 6.72kb -> 6.61kb (1.54%)
/core/assets-raw/sprites/blocks/storage/core-foundation.png -- 9.60kb -> 9.46kb (1.42%)
/core/assets-raw/sprites/blocks/storage/launch-pad.png -- 0.82kb -> 0.81kb (1.31%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-50.png -- 4.33kb -> 4.28kb (1.17%)
/core/assets-raw/sprites/blocks/walls/scrap-wall-huge1.png -- 0.67kb -> 0.67kb (1.02%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-58.png -- 5.27kb -> 5.21kb (1%)
/core/assets-raw/sprites/blocks/distribution/mass-driver-base.png -- 0.83kb -> 0.83kb (0.82%)
/android/res/mipmap-xxxhdpi/ic_launcher_background.png -- 24.08kb -> 23.88kb (0.81%)
/core/assets-raw/sprites/blocks/units/revenant-factory.png -- 6.93kb -> 6.88kb (0.66%)
/ios/data/Assets.xcassets/AppIcon.appiconset/icon-40.png -- 3.10kb -> 3.08kb (0.47%)
/core/assets/sprites/backgrounds/planet-zero.png -- 266.06kb -> 265.47kb (0.22%)
/android/res/mipmap-hdpi/ic_launcher.png -- 6.13kb -> 6.12kb (0.13%)

Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>

### CODE REVIEW

**Comment by Quezler** [comment]
:ohno:

**Comment by ghostslayer989** [comment]
@Quezler I only sent  this due to the bot auto generating it.

**Comment by willis936** [comment]
These images use true color but only have a few unique colors each.  If you really want to shave bytes off, switch to indexed color.  This sometimes has compatibility issues with poorly written libraries and in reality likely provides no performance improvement.  I haven’t looked at the graphics settings in mindustry but most 2D games like this just load up a bitmap atlas into GPU memory rather than storing the png.  Optimizing PNGs usually just decreases the distribution size.

**Comment by Arkanic** [comment]
that's a good way to fake some lines into your commits list

**Comment by Anuken** [comment]
I'm not going to look through the images and see if the bot messed anything up - if I need to reduce the repo size, I can do it myself later.

**Pull request closed without merging**
