### PR TITLE
Changed adress to address

### PR DESCRIPTION
**Pull request by T4O2M0**
simple spelling error correction and added my name to contributors.

### CODE REVIEW

**Comment by GreyMario** [comment]
You _have_ no prior contributions, and a typo is hardly notable.

**Comment by Quezler** [comment]
50t2mu

(though jokes aside: a contribution is a contribution, no matter how small, i doubt anuke will make a fuss about this one 🤔)

**Comment by Quezler** [comment]
but apart from that, the current translation seems valid: (its the sv edish bundle after all) 😗 

Screen Shot 2021-03-08 at 07 58 54

**Comment by DeltaNedas** [comment]
bruh

**Pull request closed without merging**
