### PR TITLE
Crawler and Quad

### PR DESCRIPTION
**Pull request by D-player1**
h

### CODE REVIEW

**Comment by Anuken** [comment]
I don't agree with these values.

**Comment by D-player1** [comment]
Which one

**Comment by D-player1** [comment]
Crawler is a suicide robot, with it's damage, it needs 3 amount of crawlers to kill a single dagger, making them tankier and faster doesn't even change a thing. Their damage should also buffed
And for Quad, it's the weakest T4 unit, even though it has a decent amount of speed, Quad have 6000 health, it's just trading Mega's speed for a bigger HP, Mega have 250% building speed and faster than Quad, which makes Quad pointless, and Quad can't even heal blocks, with it's bomb, it suits more as an attacker, but with it's low HP, Quad just doesnt fit anywhere.

**Comment by Anuken** [comment]
> Crawler is a suicide robot, with it's damage, it needs 3 amount of crawlers to kill a single dagger, making them tankier and faster doesn't even change a thing.

Making it have *even more* health than the dagger when it is smaller and lighter makes no sense.

> And for Quad, it's the weakest T4 unit

It's *supposed* to be a fragile bomber. Its health is very similar to that of Antumbra already.

> Quad can't even heal block

It can.

**Comment by D-player1** [comment]
Antumbra has range, using bomber as an attacker is riskier than sniping enemy defense

**Pull request closed without merging**
