### PR TITLE
bundle_fil.properties

### PR DESCRIPTION
**Pull request by ritzip**
what do you want me to call it
Changed 25 lines

### CODE REVIEW

**Comment by Luxray5474** [comment]
i think the abbreviation is TL, so it's best to call it bundle_tl not fil. salamat po :3

**Comment by ritzip** [comment]
Wait you are a filipino???

**Comment by ritzip** [comment]
I accidentally wrote it as tranlation lol

**Comment by Luxray5474** [comment]
Opo, at isa pang bundle na ginawa ni raisen1920 https://github.com/Anuken/Mindustry/pull/353 

please continue his legacy po, he really worked hard on that but it slowed to a halt (partly my fault) 😬 

pinging @Raisen1920

**Comment by ritzip** [comment]
I did some research and it is fil,
I do think thats from ~b63 but heres another translation anyways

**Comment by Raisen1920** [comment]
Continuing this translation. The previous one was delicate and old, might not support the new version. I will submit a request for my translation, hopefully this week. Sorry for the delay.

_Ipapagpatuloy ko nalang ang pagsasalin nito. Maraming problema yung isa na luma, na baka hindi gumana sa mga iba pang bagong bersyon. Magsusumite ako ng request para sa aking pagsasalin, na sakaling maasahan ngayong linggo._

**Comment by ritzip** [comment]
You may just continue this but okay.

**Comment by ritzip** [comment]
I wont be able to continue this due to problems, mostly personal.

**Pull request closed without merging**
