### PR TITLE
tweak cultivator ratios to keep the designers on their toes

### PR DESCRIPTION
**Pull request by end-me-please**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] Frog

### CODE REVIEW

**Comment by Darkness6030** [comment]
No frog 🐸

**Comment by overdramaticpanromantic** [comment]
OH LORDY LORD

**Comment by KayyAyeAre** [comment]
april

**Comment by Anuken** [comment]
too much funny

**Comment by KirillRum** [comment]
Cringe

**Pull request closed without merging**
