### PR TITLE
make input fields public

### PR DESCRIPTION
**Pull request by DeltaNedas**
a thing was moved from public player to private input handler and broke my mod h

### CODE REVIEW

**Comment by ILiekMelons** [comment]
~~doesnt this mean you just need to fix your mod~~

**Comment by DeltaNedas** [comment]
yes which i cant do without this pull
how else can i get player's target?

**Comment by Anuken** [comment]
I'm not a fan of making half the fields public and half of them private with no particular order. It's inconsistent.

**Comment by DeltaNedas** [comment]
ok
also i forgot some cool line drag stuff too so it was a good idea to go over it again

**Comment by sk7725** [comment]
YES THANK YOU

**Pull request merged**
