### PR TITLE
Add `DamageSource` and `DamageEvent`

### PR DESCRIPTION
**Pull request by way-zer**
Add new interface `DamageSource`, Building/Unit/Bullet/StatusEffect extends it. And some special type.
Make all damage function accept `DamageSource`.
No BREAKCHANGE, all old functions using DamageSource.Unknown, and set `deprecated`

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
I can't merge this in right now, as it conflicts with private branch changes.

**Comment by MEEPofFaith** [comment]
*hissss*
image

**Comment by way-zer** [comment]
> _hissss_ image

idea auto import....
wait anuke finish his private branch.

**Comment by MEEPofFaith** [comment]
~~why are they in TitleCase and not camelCase~~
image

**Comment by way-zer** [comment]
> ~why are they in TitleCase and not camelCase~ image

~may because i'm used to kotlin `object`, which is singleton class, using TitleCase.~

**Comment by mse-k** [comment]
private branch conflict tag when, would probably make it easier to go and find all prs like these after v7 releases

**Comment by Anuken** [comment]
No, that wouldn't help at all.

**Comment by way-zer** [comment]
How about this pr?
Would it be merged if i adapt it to v136?

**Comment by way-zer** [comment]
It will modify all function about damage, which will be a big change even no break-change(with deprecated).
So It may be harder to change when release beta/stable.

**Comment by Anuken** [comment]
I've thought about this some more and I don't think it should be added at all. It's significantly more API breakage and maintenance burden for a feature most won't use.

**Pull request closed without merging**
