### PR TITLE
Blah Blah Longer Mass Driver Range

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Fixing my PR #2119

### CODE REVIEW

**Comment by zethnest** [comment]
It's still the same thing

**Comment by MEEPofFaith** [comment]
Well, at least it's no longer from `unknown branch`.

**Comment by MEEPofFaith** [comment]
If velocityScl and lifetimeScl do what I think they do, it'll work.

**Comment by zethnest** [comment]
You should test your PR

**Comment by MEEPofFaith** [comment]
Well, Anuke in `development` said that "Jitpack is down" so no one can compile right now.

**Comment by Anuken** [comment]
It's not down anymore.

**Comment by MEEPofFaith** [comment]
I'll do my homework first.

**Comment by MEEPofFaith** [comment]
I'll figure out how to use Jitpack later

**Comment by Anuken** [comment]
You don't "use" jitpack in this case; if it didn't work you'd just get a gradle error when compiling.

**Comment by zethnest** [comment]
To compile, you just follow the instructions on README.md

**Comment by MEEPofFaith** [comment]
i see, thx

**Comment by MEEPofFaith** [comment]
No more errors in gradle, so I assume it's good.

I'll let Cat or someone else more qualified to fix the Mass Drivers.

**Comment by Anuken** [comment]
Decided to change this myself.

**Comment by MEEPofFaith** [comment]
oh no

**Pull request closed without merging**
