### PR TITLE
Display frag bullet stats

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/110233891-f4818a80-7edb-11eb-8234-b4e54bc0d619.mp4

I feel like the code could be optimized but at least it works.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
bullets

**Comment by joshuaptfan** [comment]
If it's only going to display 1 stat most of the time (damage), then forego the collapsible arrow. Make "Frag Bullet" the same size as other headings like "Liquid", "Function", and then show the stats with an indent and no lines above/below.

**Comment by MEEPofFaith** [comment]
Hm yea enough recursive fragging makes it not look good, especially with the pileup of underlines.

https://user-images.githubusercontent.com/54301439/110238009-efc8d080-7ef3-11eb-844a-adb1b0c8145a.mp4

(Console is nice.)

**Comment by MEEPofFaith** [comment]
Is this better?
image

**Comment by joshuaptfan** [comment]
As I said before, please don't use a collapser.

**Comment by MEEPofFaith** [comment]
image

**Comment by MEEPofFaith** [comment]
aa why are the indents bigger each time

**Comment by stuffyAI** [comment]
Please keep the buff to duo so it frags recursively multiple times

**Comment by MEEPofFaith** [comment]
> Please keep the buff to duo so it frags recursively multiple times

die

**Comment by MEEPofFaith** [comment]
> Please keep the buff to duo so it frags recursively multiple times

Fun fact I did that with console.

**Comment by MEEPofFaith** [comment]
This pr seems to be dead, should I close it?

**Comment by Anuken** [comment]
I'm not merging any new feature PRs; it's not really dead, just on hold.

**Comment by MEEPofFaith** [comment]
oki

**Comment by Anuken** [comment]
Implemented, see commit.

**Comment by MEEPofFaith** [comment]
ohyes

**Pull request closed without merging**
