### PR TITLE
Can my servers be put in community list pls?

### PR DESCRIPTION
**Pull request by NyxainTro**
I dont know if I choosed the correct branch for pull request for this subject but here are the ip for my servers
Hex: 136.243.117.29:27225
PvP: 148.251.207.50:25613
Attack Sandbox: 148.251.157.45:25958
I will add more gamemodes soon 
and these servers currently offline I am adding maps to the PvP and AttackSandbox so pls add em :D the name of the community servers is GGdustry and the gamemodes are Hexpvp , normalpvp , attack sandbox

### CODE REVIEW

**Comment by joshuaptfan** [comment]
Nowhere in your PR have you added your servers. Also, do not merge the upstream commits into your branch after submitting your PR.

Look at the server-adding PRs of others for examples of how it should be done.

**Comment by NyxainTro** [comment]
They are online btw tho no one on rn sorry
but ok thanks

**Comment by NyxainTro** [comment]
I NEED HELP
How can I set a domain for the server? like whats the service name for setting the domain for the server in the srv record in dns management if the domain so I can set a domain , like minecraft game servers use _minecraft for the service name

**Comment by Quezler** [comment]
@NyxainTro ping me on discord in the `#multiplayer` channel and i'll try to help you further, meanwhile please close this 😗

**Pull request closed without merging**
