### PR TITLE
Distribution/PowerNode/TractorBeamTurret fields for modding

### PR DESCRIPTION
**Pull request by sk7725**
- PowerNode/TractorBeamTurret: `laserColor`(since RepairPoint had laserColor, I thought it would work for these laser blocks to have one too(for PowerNode it is split into `laserColor1` and `laserColor2`))
- Plastanium Conveyor: `loadEffect`, `unloadEffect`(effects now customizable)
- MassDriver: `shootSound`(just like the other turrets, Sounds.none by default)

*...This should be my last json-related PR for now, you've done lots well already, it was really hard trying to find PR-worthy stuff!*

### CODE REVIEW

**Comment by Quezler** [comment]
> nah, its fine, makes sense, and this was made with modding in mind :) ❤️

**Review by Quezler — COMMENTED** [review]
changing laser colors might be problematic since their sprites were tainted last time i checked 🤔

**Comment by sk7725** [comment]
@Quezler 
Yes, but it is better than nothing, also I wanted to make it use @-laser and @-laser-end instead but I couldn't figure oit how to change the atlas to rename the related sprites...

**Comment by Quezler** [comment]
fair enough 👍

**Comment by sk7725** [comment]
Also they don't look too bad even when tainted, I played with different colored lasers and they seem fine, the taint is ignorable. The only thing that might be a bit off is when different colored nodes connect to each other, but modders will learn to use JS to make colored nodes only connect to themselves or something. This is just so JSON mods will have more asthetics and JS mods less toil.

**Pull request merged**
