### PR TITLE
New Slag production block: Magma Drill

### PR DESCRIPTION
**Pull request by z0mbiesrock**
### magma-drill-icon Magma Drill
_"Drills deep underground using lots of power to extract molten slag."_

Sometimes scrap is hard to come by; this new structure allows one to reliably boost their slag input, especially when using disassemblers.

### CODE REVIEW

**Comment by Quezler** [comment]
i don't think its a good idea to make it obtainable on every map 🤔

**Comment by genNAowl** [comment]
Yeah I don't think scrap processing should be encourages unless the map actually requires it.

**Comment by z0mbiesrock** [comment]
> i don't think its a good idea to make it obtainable on every map 🤔

You still need scrap for disassemblers

**Comment by genNAowl** [comment]
In your last PR, you states: "Knowing my luck with PRs, I'm certain you're going to reject it..."

Here's a tip. Instead of focusing on your "luck with PRs", focus on the ideas you are trying to implement. 

For example, some things have a higher chance of being accepted than others:

Translations: 100%
Fixing Mistakes: 100% (unless its not a mistake)
Quality of Life features: 80%
Good Resprites: 75%
A popular block idea: 60% (like Quezler's plast conveyors)
Turrets: 40% (or less, now that Anuken is not accepting new 6.0 turrets)
An unpopular block idea: 15% (the category that this PR falls into)
An Uneeded block: 0% (Tunnels, 3x3 router, etc.)

**Comment by DeltaNedas** [comment]
fucking incredible sprite but then this just enables even worse power/surge cubes that don't need any thought to be used

**Comment by superbrias** [comment]
Just for transparencies sake, what is wrong with enabling scrap processing on every map? Is it the noob-trap aspect of people getting stuck doing one very inefficient thing  just because it is insanely simply to "understand" or just how cut and paste it can be or...?

**Comment by l-Luna** [comment]
it allows you to get every resource on every map, which is not supposed to happen.
you could prevent that by requiring scrap to build, or consuming scrap as an input, but I don't know how to justify that lore-wise.

**Comment by Anuken** [comment]
At this stage of development, I am very hesitant to accept *any* new content PRs at all. In terms of content, v6 is practically done - the only things that are missing are campaign-specific blocks (*which haven't even been decided on*).

> what is wrong with enabling scrap processing on every map

I don't like how the water & oil extractor (used) to be able to *produce resources from nothing*, and this is the same idea. Free slag anywhere on the map will lead to degenerate compact cube designs and de-value scrap as an ore. I don't think this is necessary.

**Comment by z0mbiesrock** [comment]
> At this stage of development, I am very hesitant to accept _any_ new content PRs at all. In terms of content, v6 is practically done - the only things that are missing are campaign-specific blocks (_which haven't even been decided on_).
> 
> > what is wrong with enabling scrap processing on every map
> 
> I don't like how the water & oil extractor (used) to be able to _produce resources from nothing_, and this is the same idea. Free slag anywhere on the map will lead to degenerate compact cube designs and de-value scrap as an ore. I don't think this is necessary.

It's not cheap to build though

**Comment by superbrias** [comment]
> It's not cheap to build though

hearing the reason for the thumbs down, price of block doesn't matter much to degenerates or the situation, at best just adds more frustration to them using it

**Comment by Anuken** [comment]
> It's not cheap to build though

So what? That's not going to stop people from spamming it.

**Comment by z0mbiesrock** [comment]
> > It's not cheap to build though
> 
> So what? That's not going to stop people from spamming it.

Literally ANY block can be spammed.

**Comment by Anuken** [comment]
> Literally ANY block can be spammed.

No. Nobody spams drills or random factories every inch of the map. They *do* spam oil/water extractors designs, because they have no requirements and can produce an output nearly anywhere.

I'm not going to be adding this.

**Comment by z0mbiesrock** [comment]
Then tag this as invalid

**Comment by z0mbiesrock** [comment]
> They _do_ spam oil/water extractors designs, because they have no requirements and can produce an output nearly anywhere.

Oil Extractors DO have requirements

**Comment by Anuken** [comment]
> Oil Extractors DO have requirements

not in v5

> Then tag this as invalid

this is not an invalid PR

**Comment by mse-k** [comment]
it should be required to be placed on magma tiles that way you cant spam it around as usually there isnt large spaces with magma but it makes it possible to get for say fueling into waves ect in maps without scrap or slag tiles

**Pull request closed without merging**
