### PR TITLE
Antumbra's sprite change, it's time

### PR DESCRIPTION
**Pull request by AzhurniyBaklan**
- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.
Basically, this PR tries to fix all the sprite bugs EoD has left in antumbra, which weren't adressed for quite a while.
image
 The list of changes includes:
-Less absolutely flat surfaces
-Angles are more straight, no more cursed ladders going into nowhere
-Decals on the sides are finally the proper color, not a different one
-<3 px details are (almost) no more
This PR does not change the -cell sprite, since it's fine and new sprite does not break anything related to it.

### CODE REVIEW

**Comment by Anuken** [comment]
I'm staring at both of these and I can't see any difference.

**Comment by Bottinator22** [comment]
The right one is a bit darker

**Comment by AzhurniyBaklan** [comment]
> I'm staring at both of these and I can't see any difference.

@Anuken 
image

**Comment by genNAowl** [comment]
Onion skin time

**Comment by AzhurniyBaklan** [comment]
> Onion skin time

image

**Comment by Anuken** [comment]
I did a bunch of swiping, and I can't really say the new version is better. Some of the details in the middle are thinner, which just looks worse. A couple details *are* slightly improved, but it's not worth the tradeoff in my opinion.

**Pull request closed without merging**
