### PR TITLE
Just a sussy resprite nothing else

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://github.com/Anuken/Mindustry/pull/6660#issuecomment-1076998187

https://user-images.githubusercontent.com/54301439/160218952-6d066db8-c576-4e29-bc85-056a06739692.mp4

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
oh hey I took 6666

**Comment by SMOLKEYS** [comment]
lmfao

**Comment by MEEPofFaith** [comment]
also the engine is not centered but I'm not gonna bother fixing that because funi
image

**Comment by Anuken** [comment]
sussy contributor

**Comment by MEEPofFaith** [comment]
:flushed:

**Comment by DeltaNedas** [comment]
when the the is sus! 😳

**Comment by SMOLKEYS** [comment]
> also the engine is not centered but I'm not gonna bother fixing that because funi
> image

big balls

**Comment by DeltaNedas** [comment]
dudududududu
dududu
dun dun
dudududududu
dudududududu

**Pull request closed without merging**
