### PR TITLE
Make Core units hidden

### PR DESCRIPTION
**Pull request by z0mbiesrock**
The Core Units (Alpha, Beta, and Gamma) appear in the Core Database, but there is no way to "unlock" them.
(Unlocking the core of that unit should have unlocked it, but nope.avi)

### CODE REVIEW

**Comment by Voz-Duh** [comment]
Oh no

**Comment by Voz-Duh** [comment]
Why???
image

**Comment by Anuken** [comment]
It's better to have these units be visible and unlockable.

**Comment by z0mbiesrock** [comment]
H

**Comment by z0mbiesrock** [comment]
> It's better to have these units be visible and unlockable.

Because you're eventually going to add them to be buildable?
And is there going to be T4/T5 Core units?

**Comment by Anuken** [comment]
1. No.
2. Probably not.

**Comment by z0mbiesrock** [comment]
> 1. No.
> 2. Probably not.

Memme guess; you _already_ have full descriptions for them

**Comment by DeltaNedas** [comment]
because why would someone want to read the database entry for core units?

**Pull request closed without merging**
