### PR TITLE
ui-lib patch version 4.X

### PR DESCRIPTION
**Pull request by deltanedas**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

testing grubhub actions because funny thing doesn't want to compile anymore???????

### CODE REVIEW

**Comment by deltanedas** [comment]
ok good to know not just me that cant compile

**Comment by deltanedas** [comment]
to be clear i have tested the mod, i have not tested the version check code at all i just assume its right

**Comment by Darkness6030** [comment]
@deltanedas you can't make an ObjectMap<String, int>
Only <String, Integer>

**Comment by LeoSko** [comment]
@Darkness6030, moreover, there is an `ObjectIntMap` for when the value is int.

**Comment by Darkness6030** [comment]
> @Darkness6030, moreover, there is an `ObjectIntMap` for when the value is int.

~~but nobody uses it anyways~~

**Comment by deltanedas** [comment]
@Anuken mindustry

**Comment by Anuken** [comment]
> Then it should be moved to vanilla, lib mods are a bad experience for users and I don't want some insignificant UI change causing widespread startup crashes again (why even move it outside ClientLoadEvent?)

**Comment by buthed010203** [comment]
> > @Darkness6030, moreover, there is an `ObjectIntMap` for when the value is int.
> 
> ~but nobody uses it anyways~

image

????

**Comment by deltanedas** [comment]
mindustry

**Pull request closed without merging**
