### PR TITLE
@firstitem on conveyors

### PR DESCRIPTION
**Pull request by hortiSquash**
@firstItem working on conveyors cause i got bored
image

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
What if it's empty?

**Comment by hortiSquash** [comment]
> What if it's empty?

then nothing
image

**Comment by Anuken** [comment]
image

No, *not* nothing. You never check for size = 0, and there's no reason to ever clear the array, so you are essentially accessing undefined data in that case.

**Comment by Anuken** [comment]
see commit

**Pull request closed without merging**
