### PR TITLE
add a invincibility field to blocks

### PR DESCRIPTION
**Pull request by bend-n**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
Is there a reason why setting `health = Float.POSITIVE_INFINITY` won't work instead? I believe some servers already do this.

**Comment by bend-n** [comment]
It feels a bit hacky to set it to infinity instead of just not taking damage, and I believe setting health to positive infinity is causing a crash somehow.

**Comment by Anuken** [comment]
> I believe setting health to positive infinity is causing a crash somehow.

Where?

**Comment by bend-n** [comment]
I get this:
```
[06-08-2023 10:55:19] [E] java.lang.ArrayIndexOutOfBoundsException: Index 29 out of bounds for length 25
    at mindustry.ai.BlockIndexer.addIndex(BlockIndexer.java:154)
    at mindustry.ai.BlockIndexer.lambda$new$1(BlockIndexer.java:53)
    at arc.Events.fire(Events.java:53)
    at arc.Events.fire(Events.java:43)
    at mindustry.world.Tile.fireChanged(Tile.java:643)
    at mindustry.world.Tile.changed(Tile.java:633)
    at mindustry.world.Tile.setBlock(Tile.java:271)
    at mindustry.world.Tile.setBlock(Tile.java:215)
    at mindustry.world.Tile.setBlock(Tile.java:280)
    at mindustry.world.Tile.remove(Tile.java:348)
    at mindustry.gen.Building.killed(Building.java:1874)
    at mindustry.world.Tile.buildDestroyed(Tile.java:717)
    at mindustry.gen.Call.buildDestroyed(Call.java:141)
    at mindustry.gen.Building.damage(Building.java:1545)
    at mindustry.world.blocks.storage.CoreBlock$CoreBuild.damage(CoreBlock.java:577)
    at mindustry.gen.Building.damage(Building.java:1550)
    at mindustry.world.blocks.storage.CoreBlock$CoreBuild.damage(CoreBlock.java:348)
    at mindustry.gen.Building.collision(Building.java:749)
    at mindustry.gen.Bullet.tileRaycast(Bullet.java:837)
    at mindustry.gen.Bullet.update(Bullet.java:897)
    at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
    at mindustry.gen.Groups.update(Groups.java:83)
    at mindustry.core.Logic.update(Logic.java:484)
    at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:87)
    at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
``It happens after I load a new map, sometimes.

**Comment by Anuken** [comment]
> It happens after I load a new map, sometimes.

Looks unrelated, that has to do with ores. Are you sure you're not operating on a clean fork with no other changes? How did you change the health? Does it happen without the health changes?

**Comment by bend-n** [comment]
Im not sure. Its stopped happening recently.

**Pull request closed without merging**
