### PR TITLE
Vietnamese language bundle (WIP)

### PR DESCRIPTION
**Pull request by Meltdown-Altair**
Quick work of the viet lang, expect me to change it some more

### CODE REVIEW

**Comment by YellOw139** [comment]
Did you test it in-game? As far as I know, the game's font doesn't support Vietnamese characters, which means they shouldn't show up.

**Comment by Meltdown-Altair** [comment]
ah well nope

**Comment by Meltdown-Altair** [comment]
will try

**Comment by YellOw139** [comment]
Ping me here or on Discord in #translations if it does or does not work, though I'm 100% sure it won't.

**Comment by Meltdown-Altair** [comment]
ah shit it doesnt even show up
sike

**Comment by NgLamVN** [comment]
... ?

**Pull request closed without merging**
