### PR TITLE
Update bundle_zh_CN.properties

### PR DESCRIPTION
**Pull request by nanmenyangde**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Review by xem8k5 — COMMENTED** [review]
`block.afflict.name = 烟花`
WTF?

**Review by xem8k5 — APPROVED** [review]
```json
setting.bloomintensity.name = 光彩强度
setting.bloomblur.name = 光彩模糊
```
```
setting.bloomintensity.name = 光效强度
setting.bloomblur.name = 光效模糊
```

**Review by xem8k5 — COMMENTED** [review]
```json
item.carbide.name = 硬质合金
```
item.carbide.name = 碳化物

这玩意目前还没有任何依据说明这是块合金，推荐还是保持原有吧

**Comment by nanmenyangde** [comment]
但我目前更倾向于碳化钨，因为E星大气是还原性，如果钨做催化剂那就没有别的原料了

**Comment by nanmenyangde** [comment]
氧化铍同理，不过这个我想暂定，等讨论一段时间的吧

**Pull request closed without merging**
