### PR TITLE
return map from WorldLoadEvent

### PR DESCRIPTION
**Pull request by Kieaer**
Probably for my plugin :eyes:

### CODE REVIEW

**Comment by Anuken** [comment]
This is misleading; the world can load without a map. Can't you call `world.getMap()`?

**Comment by Kieaer** [comment]
Always return "Editor playtesting"

**Comment by Kieaer** [comment]
I found why world.getMap() isn't working

**Comment by Quezler** [comment]
i'm currently on the trail of maps having `unknown` or `Editor playtesting` as a name when loading from a save instead of a map, any pointers to help in my research? 🤔 
wisdom_of_the_ancients

**Pull request closed without merging**
