### PR TITLE
Add filter reset keybind [J]

### PR DESCRIPTION
**Pull request by DeltaNedas**
A simple way to reset filters on sorters, unloaders and item/liquid sources.
Adds Trigger.resetFilters event that is fired when J (no thought it's just unused) is pressed.
Mods can use this in custom filterable blocks if they want.

TODO:
- Mobile button?

Replaces #1957

### CODE REVIEW

**Comment by Quezler** [comment]
or maybe just add it to `Q` since that clears the current build plan?

**Comment by Anuken** [comment]
Why not just double click?

**Comment by Quezler** [comment]
resetting sorter (and alike) blocks with a key seems a little more practical than placing one down and interacting with that in order to clear it

**Comment by Anuken** [comment]
I don't think pressing yet another random key is a good way of changing the next filter, either. There's also quite a lot of duplicated code involved here.

**Comment by Quezler** [comment]
> yet another random key

hence why i'm counter-suggesting just adding it onto **Q**

**Comment by Quezler** [comment]
if something like this is gonna be implemented at all, i'm requesting bridges to be added to it as well, placing down bridges is a bit of a pain if one of the axis somehow aligns with the last bridge placed, down here is a poor example but it illustrates the point, pressing _Q_ or something with my pinky while doing so would be lovely:

May-03-2020 17-12-50

**Comment by DeltaNedas** [comment]
as i said, i put 0 thought into what key is default as long as it wasn't taken already

**Comment by DeltaNedas** [comment]
hmm would it be possible to have an action unbound by default?

**Comment by DeltaNedas** [comment]
if i add bridge reset, should the feature be renamed to "block reset" or what?

**Pull request closed without merging**
