### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by SSTentacleSS**
please read to the end, Anuken

Anuken, I know you won't delete their servers, I know you'd rather ignore this request

we tried to develop the server, we paid money, we made plugins, we helped mindustry, we looked for bugs

and today I log in and see **THIS** on our discord server (this is the administrator of Omega (or Yeet), who made an attempt to remove us from the global list together with Darkdustry and Omega HUB)

image

yes, WE added this bot because we trusted one administrator, who, as it turned out, was behind the dark industry and omega hub

I just want to know your reaction, many people say "how bad we are", and then such moments come up ...

image

just for what, I'm really saddened by such an act, no joke...

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Kowkodivka** [comment]
lol, fuck omega 
I thought they were smarter

**Comment by Volas171** [comment]
> please read to the end, Anuken
> 
> Anuken, I know you won't delete their servers, I know you'd rather ignore this request
> 
> we tried to develop the server, we paid money, we made plugins, we helped mindustry, we looked for bugs
> 
> and today I log in and see **THIS** on our discord server (this is the administrator of Omega (or Yeet), who made an attempt to remove us from the global list together with Darkdustry and Omega HUB)
> 
> image
> 
> yes, WE added this bot because we trusted one administrator, who, as it turned out, was behind the dark industry and omega hub
> 
> I just want to know your reaction, many people say "how bad we are", and then such moments come up ...
> 
> image
> 
> just for what, I'm really saddened by such an act, no joke...
> 
> - [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
> - [x] I have ensured that my code compiles, if applicable.
> - [x] I have ensured that any new features in this PR function correctly in-game, if applicable.
> 

to be honest with you, such vague pull request to remove 2 server networks with no proof whatsoever seems like an attempt to spark drama, your admins hate you, one of them maybe nuked your server, the story that the bot was managed by darkdustry or omegahub can be proven wrong as no one in my server (omegahub) has created a bot in the last 48 hours or even created one in yeet hosting since 1 week ago.

**Comment by Volas171** [comment]
if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts

**Comment by SSTentacleSS** [comment]
> if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts

image

**Comment by Volas171** [comment]
> > if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts
> 
> image
> 

this can be created by editing a picture, if possible show any audit logs that may prove your claims

**Review by Kowkodivka — COMMENTED** [review]
Троих нахер послать с глобал листа, чтобы больше не срались 👍

**Comment by Kowkodivka** [comment]
> > > if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts
> > 
> > 
> > image
> 
> this can be created by editing a picture, if possible show any audit logs that may prove your claims

It's hard to fake I would say impossible lol

**Comment by Volas171** [comment]
> > > > if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts
> > > 
> > > 
> > > image
> > 
> > this can be created by editing a picture, if possible show any audit logs that may prove your claims
> 
> It's hard to fake I would say impossible lol 

f12 exists and anything is possible this days......

**Comment by SSTentacleSS** [comment]
image

**Comment by SSTentacleSS** [comment]
1. you have already deleted the bot
2. on the screen it is clearly indicated who executed the command, when such data can not be faked, alas, and we have nothing to do

**Comment by SSTentacleSS** [comment]
спасибо за поддержку @Kowkodivka

**Comment by Kowkodivka** [comment]
Volas has a plugin in his github with the same name as the channels on the omnidustry were called after the raid
The plugin protected from bots, but the bot did not
It's a little suspicious, don't you think?

**Comment by SSTentacleSS** [comment]
@Volas171 say something else? 
image

**Comment by SSTentacleSS** [comment]
this is just a dirty act, I have no idea how such servers can even exist, like yours, dirty, toxic to everyone except themselves and their own kind, we just wanted to be a quiet server until you came

**Comment by Darkness6030** [comment]
Волас буквально минут 30 назад сидел с нами в конфе и кодил плагины, ничего он не удалял. Не знаю откуда вы себе там проблемы напридумывали, но, пожалуйста, разбирайтесь с ними сами.

Да и вообще, если вы там что-то высрали в сторону Omega, то зачем сюда Darkdustry приплетать? Что за мода такая появилась?

**Comment by Kowkodivka** [comment]
Блять, как бы я не хотел с тобой сраться, но не дефай омегу, они похуже омнидастри

**Review by Kowkodivka — APPROVED** [review]

**Comment by Volas171** [comment]
> Volas has a plugin in his github with the same name as the channels on the omnidustry were called after the raid
> The plugin protected from bots, but the bot did not
> It's a little suspicious, don't you think?

Yes, the same situation as the Omnidustry bots, they have the name Omnidustry but apparently they aren't from Omnidustry?

**Comment by SSTentacleSS** [comment]
We don’t need this, we don’t need bots and your desire to get away now is just disgusting, you yourself wrote that you created a bot, I even threw off a screenshot where you personally, as a server, executed these commands and deleted Omnidustry

**Comment by Kowkodivka** [comment]
> > Volas has a plugin in his github with the same name as the channels on the omnidustry were called after the raid
> > The plugin protected from bots, but the bot did not
> > It's a little suspicious, don't you think?
> 
> Yes, the same situation as the Omnidustry bots, they have the name Omnidustry but apparently they aren't from Omnidustry? Little suspicious don't you think

I never trust o7 people. You could just set them up, knowing you.

**Comment by Volas171** [comment]
> @Volas171 say something else? 
> image
> 

yes, we infact have a bot

**Comment by Volas171** [comment]
But it does not have any of the commands you mentioned

**Comment by Volas171** [comment]
also it is pretty convenient that your server will be recovered "in 1 hour", it seems like you staged everything and hidden the channels to the public.

**Comment by Kowkodivka** [comment]
> But it does not have any of the commands you mentioned 

You think we're stupid, right? You could have just deleted the command lol. But you deleted the whole bot.

**Comment by Xeononyum** [comment]
> > > if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts
> > 
> > 
> > image
> 
> this can be created by editing a picture, if possible show any audit logs that may prove your c

Ты тупой хуйлан

**Comment by SSTentacleSS** [comment]
> also it is pretty convenient that your server will be recovered "in 1 hour", it seems like you staged everything and hidden the channels to the public.

image

**Comment by Xeononyum** [comment]
> Волас буквально минут 30 назад сидел с нами в конфе и кодил плагины, ничего он не удалял. Не знаю откуда вы себе там проблемы напридумывали, но, пожалуйста, разбирайтесь с ними сами.
> 
> Да и вообще, если вы там что-то высрали в сторону Omega, то зачем сюда Darkdustry приплетать? Что за мода такая появилась?

не оправдывай этого говнаря, твинковод ебучий

**Comment by SSTentacleSS** [comment]
screen from omegahub.. you deleted your bot
image

**Comment by Kowkodivka** [comment]
> > > > if you have anything else that can prove this claims let me know because I'm not aware of any person in my hosting doing such malicious acts
> > > 
> > > 
> > > image
> > 
> > 
> > this can be created by editing a picture, if possible show any audit logs that may prove your c
> 
> Ты тупой хуйлан

👍

**Comment by Kowkodivka** [comment]
> screen from omegahub.. you deleted your bot image

The audit log also shows that the bot has been deleted

**Comment by SSTentacleSS** [comment]
image

**Comment by AlexCnC1095** [comment]
Что тут происходит?

**Comment by Xeononyum** [comment]
> Что тут происходит?

хуйлан с омеги загриферил омни

**Comment by nekonya3031** [comment]
If you can't choose the administrators correctly, that's your own problem. Why you make this useless noise here?

**Comment by Kowkodivka** [comment]
No more words? Why are you so quiet? Volas

**Comment by Volas171** [comment]
> screen from omegahub.. you deleted your bot
> image
> 

1. no proof to that claim
2. even if i was to delete it, the "2" bots in question are not mine

**Comment by Kowkodivka** [comment]
LMFAO GENIUS

**Comment by Kowkodivka** [comment]
How many excuses will there be that screenshots can be faked?

**Comment by HizaGRT** [comment]
Злокет ты опять под пивом?

**Comment by Ademun** [comment]
1. Recieve a proof
2. Say that it is not a proof(us as many quotes as you can to make the proof seem like illogical and stupid)
3. Done

**Comment by Volas171** [comment]
> How many excuses will there be that screenshots can be faked?

if you want to show real proof of it happening, record your screen and scroll on the discordapp showing proof.

**Comment by Kowkodivka** [comment]
Wow Wow! Record a video and send the proofs that you cited above, otherwise we will not believe you
Lol.

**Comment by osp54** [comment]
Circus

**Comment by Ademun** [comment]
> Wow Wow! Record a video and send the proofs that you cited above, otherwise we will not believe you.
> Lol

I guess I will, probably 10 minutes later

**Comment by HizaGRT** [comment]
Злокет ты сам вспомни что говорил мактавишу image

**Comment by buthed010203** [comment]
🍿

**Comment by AlexCnC1095** [comment]
Кстати у меня бан в дс омни непонятно за что.

**Comment by Ademun** [comment]
> > Wow Wow! Record a video and send the proofs that you cited above, otherwise we will not believe you.
> > Lol
> 
> I guess I will, probably 10 minutes later

Lol, they deleted messages from the bot

**Comment by SSTentacleSS** [comment]
> Злокет ты сам вспомни что говорил мактавишу image

извиняюсь за свои слова тогда

**Comment by Ademun** [comment]
> > > Wow Wow! Record a video and send the proofs that you cited above, otherwise we will not believe you.
> > > Lol
> > 
> > 
> > I guess I will, probably 10 minutes later
> 
> Lol, they deleted messages from the bot

So the last message is like two days old
image

**Comment by SSTentacleSS** [comment]
image
image

Tima - admin on Omega

eyes eyes - added bot, that deleted our server

**Comment by Kowkodivka** [comment]
Мы не добьемся удаления их, но сделаем вывод, что таким дебилам, доверять не стоит
Жалко, конечно

**Comment by SSTentacleSS** [comment]
> Мы не добьемся удаления их, но сделаем вывод, что таким дебилам, доверять не стоит Жалко, конечно

Что-ж, правду говоришь, просто этот пулл будет такой маленькой пометкой для всех, кто хочет и будет знать истинную натуру Omega

**Comment by Volas171** [comment]
> image
> image
> 
> Tima - admin on Omega
> 
> eyes eyes - added bot, that deleted our server

wow thanks, we will take respective actions on this person.

**Comment by Xeononyum** [comment]
если гриф оказался правдой (о чудо), почему тогда надо считать пруф от злокета о воласе фейком?

**Comment by Anuken** [comment]
if y'all don't stop acting like a bunch of rabid monkeys slinging mud at each other, I will legitimately nuke every single server network involved (yes, [both](https://github.com/Anuken/Mindustry/pull/8206) [PRs](https://github.com/Anuken/Mindustry/pull/8343)) and be rid of this whole situation.

the behavior on both sides is, frankly, appalling. stop. I can't possibly know who is doing what, but omnidustry clearly has moderation issues and a lack of attention, while everyone else has a long history of messing with other servers. if this isn't addressed soon, everyone's going to get it. 

I'm not particularly interested in reading or engaging with any further arguments here. bye.

**Comment by KotMilkMeoWtwo** [comment]
Fuck omega

**Comment by KotMilkMeoWtwo** [comment]
Uffff. @Darkness6030 u remember how we delete Nexor server (rm rf) and i delete darkdustry))

**Comment by KotMilkMeoWtwo** [comment]
This was funny

**Comment by Kowkodivka** [comment]
Friends, let's remember the past, not here, please.

**Comment by heheeeeea** [comment]
Wait, what?

**Comment by heheeeeea** [comment]
> 

Remember what?

**Comment by Kowkodivka** [comment]
My english may be weird, nvm

**Comment by Taras4k** [comment]
🧠🤏

**Comment by buthed010203** [comment]
Why must people necropost

**Pull request closed without merging**
