### PR TITLE
Add Atanner Gaming V6 Server

### PR DESCRIPTION
**Pull request by AydenRennaker**
Auto Updating server to latest bleeding edge build.

### CODE REVIEW

**Comment by imreallybadatnames** [comment]
enterprise secrets

**Comment by AydenRennaker** [comment]
Decided to change to alpha build release. V105 is the version of the server.

**Comment by Anuken** [comment]
I'm going to wait until 106 before merging this; 105 has some serious (think server-destroying) bugs in it.

**Comment by Anuken** [comment]
@AydenRennaker Your server doesn't seem to have been updated for quite a while now, so I'll remove it from the list so it doesn't waste space for now.

**Pull request merged**
