### PR TITLE
Plugin YML

### PR DESCRIPTION
**Pull request by BagayRodolfo**
Simple edit on Pluigns.java

This creates new folder for each plugin before load.

(Will use fork next time)

### CODE REVIEW

**Comment by Anuken** [comment]
I don't think YML should be used as a standard config format; JSON would be preferable.

**Comment by BagayRodolfo** [comment]
Okay, Use JSON file named as <plugin_name>.json then put it on the same level of the jar file?

**Comment by Milinai** [comment]
How would this be useful?

**Comment by BagayRodolfo** [comment]
Some plugins requires configuration based on the owner of the server. This will offer more option ,flexibility and variety of each plugin.

For now, plugins cannot offer much, But i know someday it will be more useful.

**Comment by Kieaer** [comment]
My Essentialsis the only plugin I have that uses the settings file.
Plugins need to be very complex to be used...

**Comment by Anuken** [comment]
Implemented in f65ab002500258269abdf48a811569597dc7fe83 with a `getConfig()` method that can be used in a plugin's constructor, e.g.

`getConfig().writeString("{}");`

...would create a 'config.json' in a plugin-specific config directory with the contents "{}".

**Pull request closed without merging**
