### PR TITLE
Fix little sprite details

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Impact Top
Cyerce4
Cyerce3
Cyerce2
Cyerce1
Liquid Container Corners
Mass Driver Base
Launchpad Corners
Multi-Press Heresy
Unit Block Corners
Foundation Bottom
Nucleus Mid

(Also reign's cell is shifted up by a pixel)

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by EclipseTheOldOne** [comment]
moment

**Comment by MrAntlrr** [comment]
pog

**Comment by sk7725** [comment]
~~soon:~~

image

<details>
yeah I'm just kidding, this PR is great!
</details>

**Comment by Anuken** [comment]
- Most blocks: What you've done is removed the gray "gutter" pixels in-between shades, which were added for a reason. Having many contrasting colors next to each other can look too "sharp", so a lines of manual "antialiasing" can help. Removing these doesn't necessarily make it look better.
- Cyerce: Yes, there's a single pixel line, but you've extended the dark parts on the bottom for some reason, and now it looks worse. I would rather change it myself.
- Reign: Better. I wonder why EoD made the cell a different size.
- Foundation: Yeah, that's just wrong.
- Nucleus: It's supposed to be "blocky" in the middle. The lines are at a higher elevation.
- Thermal pump: I can't accept any changes to it, as the block is being renamed ("thermal pump" is an awful name) and recolored (it has nothing to do with heat)

I'll merge in the ones I mentioned manually.

**Comment by MEEPofFaith** [comment]
ok

**Pull request closed without merging**
