### PR TITLE
Move Bullet Ability

### PR DESCRIPTION
**Pull request by Voz-Duh**
I decided that units can fire not only with lightning when accelerating, but for example with laser, and that's what i did /-/
image
I used Flare for testing, thx Flare

### CODE REVIEW

**Comment by Gdeft** [comment]
~~The comments are a little bit h.~~

Shouldn't the lightning part also use `shootEffect` and `shootSound` rather than making it hardcoded? Also, why the too-many parameters? What if I just want to use the bullet part only and not the lightning part (or viceversa)?

**Comment by Voz-Duh** [comment]
> ~The comments are a little bit h.~
> 
> Shouldn't the lightning part also use `shootEffect` and `shootSound` rather than making it hardcoded? Also, why the too-many parameters? What if I just want to use the bullet part only and not the lightning part (or viceversa)?

I go fix it, thx

**Comment by Voz-Duh** [comment]
Stop, what? /-/
image

**Comment by Voz-Duh** [comment]
Waiting

**Comment by Soham-maiti** [comment]
can u pls help me with my mini 2d game

**Comment by Voz-Duh** [comment]
> can u pls help me with my mini 2d game

Please don't offtop in pulls

**Comment by Soham-maiti** [comment]
what u mean?

**Comment by Voz-Duh** [comment]
> what u mean?

Discuss everything about this pull but anything else

**Comment by Anuken** [comment]
Implemented.

**Pull request closed without merging**
