### PR TITLE
Keybinds follow CONTRIBUTING

### PR DESCRIPTION
**Pull request by LeoDog896**
Contributing.MD referenced keybinds as one that didn't follow contributing, well now it does.

### CODE REVIEW

**Comment by Anuken** [comment]
It's not that simple. Did you test:
- if it breaks translations
- if it breaks the english bundle
- if it breaks keybind saves from older versions

**Comment by LeoDog896** [comment]
No longer breaks the bundles after testing, now to add legacy support

**Comment by sk7725** [comment]
Great, now 5.0 JS mods are now butchered even more, and 6.0 mods are also affected.

Is this *really* that necessary?

**Comment by Anuken** [comment]
Closing due to stale-ness; adding legacy support is a lot of work and will either involve very specific string manipulation upon load, or a large translation table. I don't really think either are worth it.

**Pull request closed without merging**
