### PR TITLE
allow controlling @this

### PR DESCRIPTION
**Pull request by DeltaNedas**
- `control enabled @this 0` yes yes
- not really any other uses

### CODE REVIEW

**Comment by Anuken** [comment]
`control enabled @this 0`

why? that's an instant deadlock.

**Comment by GreyMario** [comment]
It enables a processor to run once and done without forcing itself into an infinite loop of noop. I had to stop and think about it.

**Comment by Anuken** [comment]
Not exactly. Once it disables itself, the action will time out eventually, since it isn't applied continuously. This leads to inconsistently periodic behavior.

**Comment by GreyMario** [comment]
Oh. Right. That's a thing.

🤔

..The hell is the use case, then?

**Pull request closed without merging**
