### PR TITLE
Bridge priority fix

### PR DESCRIPTION
**Pull request by Slava0135**
***BEFORE:***
before
***AFTER:***
after

### CODE REVIEW

**Comment by Slava0135** [comment]
however this prevents you from building other stuff if the bridge out of range.

**Comment by itcannotbe** [comment]
How is that a non-issue in mobile?

**Comment by Slava0135** [comment]
> How is that a non-issue in mobile?
> 
> The behavior is like after. Android 121.4

wdym

**Comment by itcannotbe** [comment]
The behavior on android is not like your before gif. But the behavior is your after gif on mobile.

**Comment by Slava0135** [comment]
> The behavior on android is not like your before gif. But the behavior is your after gif on mobile.

Behaviour on mobile is the same

**Comment by rodrigolitzius** [comment]
I made a issue saying the same thing, but it was closed... #3966

**Comment by itcannotbe** [comment]
> > The behavior on android is not like your before gif. But the behavior is your after gif on mobile.
> 
> Behaviour on mobile is the same

Quite literally can't reproduce the before gif on android though.

The behavior is the after gif.

**Comment by Slava0135** [comment]
> > > The behavior on android is not like your before gif. But the behavior is your after gif on mobile.
> > 
> > 
> > Behaviour on mobile is the same
> 
> Quite literally can't reproduce the before gif on android though.
> 
> The behavior is the after gif.

You have to be outside of the range or have not enough resources.

**Comment by Anuken** [comment]
I don't like this implementation - it's hacky and prevents requests from being prioritized properly. Bridges should somehow store their configs upon placement.

**Pull request closed without merging**
