### PR TITLE
Better zone naming in finnish

### PR DESCRIPTION
**Pull request by valtsu41**
Better zone naming and also some other stuff that will be useful when translating achievements.

### CODE REVIEW

**Comment by valtsu41** [comment]
@xzarfs and @TheJaaju what do you think? Any suggestions?

**Comment by TheJaaju** [comment]
Looks good to me

**Comment by xzarfs** [comment]
Looks good

**Comment by valtsu41** [comment]
I am not completely sure what I just did but it *seems* like i fixed the merge conflict.

**Pull request merged**
