### PR TITLE
Added the servers of the HiveMind

### PR DESCRIPTION
**Pull request by RebornTrack970**
The servers owner is Albert and the servers are for the youtuber currently known as D.A.R.K

### CODE REVIEW

**Comment by Quezler** [comment]
and are they all okay with it being on this public list?

**Review by Quezler — CHANGES_REQUESTED** [review]
invalid json

**Comment by RebornTrack970** [comment]
> and are they all okay with it being on this public list?

Albert says he is ok with it.

**Comment by RebornTrack970** [comment]
> invalid json

Forgot to add }

**Comment by DeltaNedas** [comment]
i disapprove

**Comment by DeltaNedas** [comment]
doesnt zacbytes already have mindustry.tk?

**Comment by RebornTrack970** [comment]
> doesnt zacbytes already have mindustry.tk?

These servers arent ZacBytes, they are Alberts.

**Comment by DeltaNedas** [comment]
great now zacbytes has 2 servers
this being merged would promote sub-io gameplay

**Comment by RebornTrack970** [comment]
> great now zacbytes has 2 servers
> this being merged would promote sub-io gameplay

I literaly said they are not ZacBytes.

**Comment by Volas171** [comment]
> great now zacbytes has 2 servers
> this being merged would promote sub-io gameplay

It isn’t zacbytes , zacbytes offered dark to host his server and that’s it , it’s just a rebrand of the old .tk

**Review by Volas171 — APPROVED** [review]

**Review by Volas171 — COMMENTED** [review]
uh please explain why is the owner not dark and why did you said the owner is dark

**Comment by BlueWolf3682** [comment]
oh no

**Comment by RebornTrack970** [comment]
> uh please explain why is the owner not dark and why did you said the owner is dark

The server owner is not Dark and i didnt say he is. Albert, also known as ShadowDude#1124, is the owner and he said he was making the Servers for the HiveMind. 

I dont know why you think the owner is Dark...


(im sorry, im not very good at explaining things)

**Comment by Volas171** [comment]
k

**Comment by DeltaNedas** [comment]
good

**Pull request closed without merging**
