### PR TITLE
Added russian translation

### PR DESCRIPTION
**Pull request by rmuhamedgaliev**
Translate some untranslated texts

### CODE REVIEW

**Comment by SnakkiZXZ** [comment]
why not add a description right away?

**Comment by rmuhamedgaliev** [comment]
> why not add a description right away?

Sorry, fixed.

**Comment by BasedUser** [comment]
> scanner

Think of a better word. The best fit word would be a translation of [this](https://en.wikipedia.org/wiki/Foreshadow).

**Comment by rmuhamedgaliev** [comment]
Upd translate

**Comment by rmuhamedgaliev** [comment]
@Anuken please check PR.

**Comment by rmuhamedgaliev** [comment]
> I could be wrong, but don't these words mean nearly the same thing? "Предзнаменование" doesn't seem better than "Знамение", it's just more of a mouthful.

Just close. I was created the PR before other changes were added to the translation into Russian

**Pull request closed without merging**
