### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by ArkSourcer**
here I have 3 servers for my Spanish mindustry community

### CODE REVIEW

**Comment by Anuken** [comment]
None of these are online.

**Comment by ArkSourcer** [comment]
> None of these are online.

**Comment by Anuken** [comment]
image

**Comment by ArkSourcer** [comment]
> image
> 

I'm sorry if I'm annoying but what could it be?

**Comment by Anuken** [comment]
Make sure the domain is properly set up and points to your IP, and you have port forwarding set up correctly.

**Comment by ArkSourcer** [comment]
resolved, but I won't upload the others until I see why they don't grab

**Pull request closed without merging**
