### PR TITLE
Rename omnidustry server to ohiodustry

### PR DESCRIPTION
**Pull request by piskabo**
You will ask why? Because this server is shit that violates the rules of the servers. For example, there is practically no administration, and their sandbox server is constantly in shit (NSFW).

### CODE REVIEW

**Comment by TheEt1234** [comment]
Instead of trolling anuke why not confact the server owners

**Review by Darkness6030 — APPROVED** [review]

**Comment by Def-Try** [comment]
> Instead of trolling anuke why not contact the server owners

They are aware of it, but thinking that "nothing could go wrong, there cant be a person that will kick out server from global" or something like that

**Comment by TheRadioactiveBanana** [comment]
I can confirm their sandbox server has a lot of stuff wrong.
-COPIOUS amounts of nsfw content, like im talking logic art, sorter art, canvas art, you name it.
(atleast 25% of the map is covered with it a lot of the time, unless someone sensible (usually not a moderator) comes and removes it.)
-No moderation whatsoever, i saw on the survival server, about 3 griefers who joined did their thing and left. people are absolutely swearing the heck out of these griefers and votekick spamming yet the griefers just leave when something bad is happening. No moderator ever came.

**Comment by Anuken** [comment]
NSFW content with no moderation is not acceptable, and as such I'll just remove the sandbox server until the issue is resolved.

To the owners: If you can't moderate such content, please just ban displays and canvas blocks in the server config.

@TheTrueInfinity (pinging since that's the person that last edited the omnidustry listing)

**Comment by SSTentacleSS** [comment]
@Anuken 

image

**Comment by Anuken** [comment]
It should have the canvas block banned too. People use it for NSFW too.

**Comment by code-explorer786** [comment]
(fyi during the time i'm writing canvas blocks are still not banned and can cause an issue too)

**Pull request closed without merging**
