### PR TITLE
Team Colors For Storage Blocks

### PR DESCRIPTION
**Pull request by Voz-Duh**
I did it very quickly
new-team-colors-1
new-team-colors-2

.

### CODE REVIEW

**Comment by Anuken** [comment]
I added your sprites, but I have no idea why you edited any of the container code at all. You don't need to change anything - insert the team sprites, and it just works.

**Comment by Voz-Duh** [comment]
> I added your sprites, but I have no idea why you edited any of the container code at all. You don't need to change anything - insert the team sprites, and it just works.

Real!? I don't know...

**Comment by Remint32** [comment]
> Real!? I don't know...

Читай существующий код внимательно

**Comment by Voz-Duh** [comment]
> > Real!? I don't know...
> 
> Читай существующий код внимательно

I read all code, and examples

**Pull request closed without merging**
