### PR TITLE
Fixed ore texture names

### PR DESCRIPTION
**Pull request by DeltaNedas**
ore-myore -> ore-myore-1.png not mydrop1.png

**DO NOT MERGE UNTIL ALL MODDERS ARE GIVEN A GOOD AMOUNT OF TIME TO UPDATE MODS**
(btw i made pr on examplemod too, it works nicely)
((btw works on my mod too))

### CODE REVIEW

**Comment by Arkanic** [comment]
interesting

**Comment by DeltaNedas** [comment]
ok arkanic didnt say its bad so modders pls fix your mods or theyll break its 99% official 100% official if/when our lord says its ok

**Comment by Anuken** [comment]
> DO NOT MERGE UNTIL ALL MODDERS ARE GIVEN A GOOD AMOUNT OF TIME TO UPDATE MODS

This isn't going to happen. Even if I publically announce this and personally ask everyone to do it, some mods will remain broken and users will complain. A single hyphen just isn't worth all this effort, and in my opinion defining new blocks is easier without it.

**Comment by DeltaNedas** [comment]
it also uses drop
which makes no sense, why would an ore use its drop name for texture?
maybe it would be possible to look for both old and new?

**Comment by Anuken** [comment]
> why would an ore use its drop name for texture?

Because it's simple and immediately recognizable. 'Ore' is unnecessary and inaccurate, as not all resources on the ground may necessarily be ores (coal ore? sand ore?)

**Comment by DeltaNedas** [comment]
ore prefix is for OreBlock which does `super("ore-" + name)`, for other stuff yea you could just have name-*variant*.png no `ore-`

**Pull request closed without merging**
