### PR TITLE
Allow for `SingleTypeGenerators` to use only liquid.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
For anyone's need for a power gen based on only liquid. Like @BlueWolf3682.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

(Implement more random things Anuke I'm starting to be a little tired of being enslaved repeatedly.)

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Dunno if the variable name is good.

**Comment by BlueWolf3682** [comment]
(i havent before touched power generation too badly, so the power section is really left out and actually hasnt changed much since v5)
though i have no clue why (only) liquid consuming generators werent a thing already
also that generateEffect randomization field.

**Comment by Anuken** [comment]
so does this actually work?

**Comment by MEEPofFaith** [comment]
Time to find out, console abuse time

**Comment by MEEPofFaith** [comment]
Seams like it works.

https://user-images.githubusercontent.com/54301439/131280132-8fa9a326-6615-497f-87ad-8e97dbde75ea.mp4

haha console abuse go brrr

**Comment by MEEPofFaith** [comment]
the efficiency changed as he amount of liquid dropped under the amount needed.

**Comment by MEEPofFaith** [comment]
Yep, definitely works. Tested with just liquid.
image

image

**Comment by SoMall-dumpling** [comment]
Then there will come tidal stream generator.
(Of course, +50% efficiency when placed on deep water, yeah)

**Pull request merged**
