### PR TITLE
Update mindurka ip

### PR DESCRIPTION
**Pull request by Darkness6030**
Mindurka.ru come back!)
[RU]Заспидранил восстановление сервера с нуля за один день!) Гений мысли...

### CODE REVIEW

**Comment by Darkness6030** [comment]
@Anuken, i need to change ip as fast as it you can...
Please, if you see this comment, do it immediately

**Comment by KotMilkMeoW** [comment]
No please, Noooooooooooo!!!!!!!!!!!!!!!! Don't return it. They have already changed the ip. And server very bad.

**Comment by Darkness6030** [comment]
> No please, Noooooooooooo!!!!!!!!!!!!!!!! Don't return it. They have already changed the ip. And server very bad

Bruh

**Comment by KotMilkMeoW** [comment]
В смысле пытался? Ты же сам разрешил.

**Pull request merged**
