### PR TITLE
Fix team color chaos caused by #8700

### PR DESCRIPTION
**Pull request by way-zer**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Slotterleet** [comment]
What. How does calling `Mathf.random()` thrice fix the colors?

**Comment by way-zer** [comment]
> What. How does calling `Mathf.random()` thrice fix the colors?

As team#6

**Comment by Darkness6030** [comment]
Bad idea. Just shift team IDs in your code.

**Comment by way-zer** [comment]
> Bad idea. Just shift team IDs in your code.

There are alreay many maps, the color is wrong.

**Comment by Mythril382** [comment]
> fix some breakchange of #8700

What broke? The only thing it did was to allow usage of the neoplastic team.

**Comment by way-zer** [comment]
> > fix some breakchange of #8700
> 
> What broke? The only thing it did was to allow usage of the neoplastic team.

color

**Comment by Slotterleet** [comment]
I still don't get it. Teams 7-255 were supposed to have randomized colors anyways.

**Comment by way-zer** [comment]
> I still don't get it. Teams 7-255 were supposed to have randomized colors anyways.

They are randomized, but it's better to keep colors consistent with old version.

**Comment by Mythril382** [comment]
> > I still don't get it. Teams 7-255 were supposed to have randomized colors anyways.
> 
> They are randomized, but it's better to keep colors consistent with old version.

No it isn't.

**Comment by way-zer** [comment]
> > > I still don't get it. Teams 7-255 were supposed to have randomized colors anyways.
> > 
> > 
> > They are randomized, but it's better to keep colors consistent with old version.
> 
> No it isn't.

There are maps broken

**Comment by BalaM314** [comment]
When neoplastic was added as team#6, the colors shifted. team#7 used to be the second randomly generated color, but now it's the first randomly generated color, likewise, all the numbered teams' colors shifted by one.
This PR fixes that by generating a random color and throwing it away, so team#7 is once again the second randomly generated color.

**Comment by BalaM314** [comment]
@way-zer i recommend adding a comment to explain that

**Review by BalaM314 — APPROVED** [review]

**Comment by Slotterleet** [comment]
> There are maps broken. And I don't want to reply again, let anuke decide.

How does changing colors fix or break anything? For 99.9% of mappers, the basic 6 teams is more than enough. And in custom gamemode plugins, teams 7-255 are very likely only used for FFA or HexPvP. As for mods, they can set colors for those teams internally.

**Comment by way-zer** [comment]
> > There are maps broken. And I don't want to reply again, let anuke decide.
> 
> How does changing colors fix or break anything? For 99.9% of mappers, the basic 6 teams is more than enough. And in custom gamemode plugins, teams 7-255 are very likely only used for FFA or HexPvP. As for mods, they can set colors for those teams internally.

Like https://www.mindustry.top/map/13866/latest.

And the colors don't mean to change when it's possible to keep consistent.

**Comment by Anuken** [comment]
Will use my own implementation with a for-loop.

**Pull request closed without merging**
