### PR TITLE
Command units to get onto payload conveyors

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/171073059-574108f1-8d05-4473-a146-6ccfed487d7c.mp4

https://user-images.githubusercontent.com/54301439/171305953-c8b343c8-8922-4381-89f7-710c7705c92d.mp4

Based on https://github.com/Anuken/Mindustry-Suggestions/issues/3580.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by SMOLKEYS** [comment]
~~ok now make mobile have the ability to set the move locations of units in unit factories~~

**Comment by BlueWolf3682** [comment]
\*image of locus walking itself into a deconstructor*

**Comment by MEEPofFaith** [comment]
> *image of locus walking itself into a deconstructor*

~~unfortunately payload conveyors do not extend off of PayloadBlock, so that'll take extra `instanceof` mess to make work.~~

**Comment by Anuken** [comment]
Why? This is what conveyors should be used for...

**Comment by MEEPofFaith** [comment]
idk I decided to look at some suggestions, saw a thing, and made something based on it.

**Comment by Anuken** [comment]
Unless someone comes up with more justification, I don't think that's a good enough reason, you should be using conveyors for transport, not automatic commands. This just unnecessarily complicates things.

**Pull request closed without merging**
