### PR TITLE
Tint tsunami pipes

### PR DESCRIPTION
**Pull request by Quezler**
> (partial) implementation of https://github.com/Anuken/Mindustry-Suggestions/issues/655

Screen Shot 2020-10-01 at 11 07 16

`added the top region with a 50% transparency `

(wave left unaltered since imo it looks strange)

### CODE REVIEW

**Comment by Quezler** [comment]
so apparently github decided that when i manually had to make a new patch branch to use the master branch of my fork that hasn't been synced for over like 3k commits, hence the merge conflict, not sure how i can cleanly resolve it via the web interface while keeping the branch 👀

**Comment by Quezler** [comment]
looks like it got fixed, but i'm not sure if merging it would not pollute the git history with a humongous merge, i would recommend squashing this pull request or even just adding it manually and closing it 🤔

**Comment by SnakkiZXZ** [comment]
I think it looks strange, if you add it, then you should add it to the `wave`, and if we don't add it to the `wave`, then you shouldn't add it here either

**Comment by Quezler** [comment]
i'll let anuke decide that, if he wants the wave to have it as well, all he needs to do is ask, it just looks better on here imo 🙂

**Comment by Anuken** [comment]
This doesn't look good, in my opinion.

**Comment by EyeOfDarkness** [comment]
looks strange.

**Comment by Anuken** [comment]
...Nah.

**Pull request closed without merging**
