### PR TITLE
Added logic sensor to unit spawned wave number

### PR DESCRIPTION
**Pull request by BlackDeluxeCat**
for mapping purposes

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by JasonP01** [comment]
What? @wave and @waveNumber are already a thing???

**Comment by ApsZoldat** [comment]
This allows to check in which wave was unit spawned

Still dunno why and for what

**Comment by JasonP01** [comment]
> This allows to check in which wave was unit spawned

9/10 times it would be from the previous waves tho?
10/10 times if u have wait for enemies toggled

**Comment by ApsZoldat** [comment]
It can still be useful when, for example, giving multiple status effects to a wave without doing more complex shenanigans. The only controversy about this feature may be that "it bloats the logic system with really niche features even more". Otherwise, in my opinion, this feature is fine

**Comment by Anuken** [comment]
This is incredibly niche, and increases the size of units over the network/on the disk.

**Pull request closed without merging**
