### PR TITLE
V6 Styled Turrets

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
Some friends and I created (What we call) v6 styled turrets. We took examples of your newest resprites and we tried to make them the most v6'ish that we could. I think it turned out very well.      

image

I dont know exactly what files changed when you pack the sprites, so I just changed the _**assets-raw/sprites/blocks/turrets**_ part. It compiles, as that image was took in a custom v6. (Just changed the sprites). We hope that you like them.

### CODE REVIEW

**Comment by Syncinus** [comment]
These look great, I think you should remove the Glare from the Wave though, it doesn't fit in too well.

**Comment by ThePythonGuy3** [comment]
Idk, I kinda like it...

**Comment by Anuken** [comment]
Some of these look slightly better, while others (most notably the ripple and spectre) look bumpier and messier to me.

**Comment by ThePythonGuy3** [comment]
OK then, we'll try to reredesign those!

**Comment by ThePythonGuy3** [comment]
I think I fixed those things. They look much better now.     
Shooting:
image     

Idle:
image

**Comment by ThePythonGuy3** [comment]
OK thank you, I will fix that as soon as I can.

**Comment by ThePythonGuy3** [comment]
Idk, I prefer it without those lobes, the shading of them also messes up when the turret rotates, maybe i can give them a different shading.

**Comment by Remint32** [comment]
> 
> 
> Idk, I prefer it without those lobes, the shading of them also messes up when the turret rotates, maybe i can give them a different shading.

shading in General, in principle, spoils when the head of any turret rotates, at least look [here](https://github.com/Anuken/Mindustry/blob/master/core/assets-raw/sprites/blocks/distribution/mass-driver.png):

изображение

I also thought so, but when testing in the game it turned out that it looks very much in style and does not stand out from the rest of the lighting in sprites.

If we want to completely solve the problem with the lighting direction, we need to use normal maps. I don't consider this a problem in principle at the moment with current sprites.

**Comment by ThePythonGuy3** [comment]
OK then, thx

**Comment by cosMICrus** [comment]
I am one of the turret spriter in this pull request, and i want to see how 1x1 turrets look like.

**Comment by ILiekMelons** [comment]
so uh

**Comment by ThePythonGuy3** [comment]
ded PR

**Comment by GlennFolker** [comment]
i wish to resprite the fuse a little bit

**Comment by GlennFolker** [comment]
where do i get the files

**Comment by Syncinus** [comment]
These look pretty nice

**Comment by Anuken** [comment]
These sprites still look slightly overdetailed and messy to me. I'll make some of my own revisions to the turrets; this won't be merged.

**Pull request closed without merging**
