### PR TITLE
Add core items on mobile

### PR DESCRIPTION
**Pull request by BasedUser**
Why?

### CODE REVIEW

**Comment by thedimas3007** [comment]
Hm, I think, this is good idea

**Comment by MEEPofFaith** [comment]
I think it has to do with space taken up. With some mods the item display could easily take up a large portion of your screeen.

**Comment by MEEPofFaith** [comment]
Progressed Materials has 11 items, which is already 3 rows added to it.

**Comment by joshuaptfan** [comment]
@BasedUser, you obviously haven't tested this PR, because if you did, you would know that core items would not have the space to display on mobile portrait.

**Comment by BasedUser** [comment]
UI scale and landscape mode are still a thing, by the way

**Comment by joshuaptfan** [comment]
> UI scale and landscape mode are still a thing

I know you haven't tested your new changes either, because now that you've fully allowed core items to display on mobile, testing would reveal that core items overlap the wave UI at the top on the screen in mobile portrait.

You're clearly intent on half-assing the PR, so I'm not here to spoonfeed you tips on how to implement it properly without testing.

**Comment by BasedUser** [comment]
This time however, I did test the changes.

**Comment by Anuken** [comment]
As mentioned above, this would cause significant overlap in portrait mode. Due to the layout changes in the 7.0 branch, any further commits in this region will cause conflicts. Re-open once 7.0 is merged in, and you have a valid strategy for dealing with overlap.

**Comment by Quezler** [comment]
ps, he can't re-open it himself since a maintainer of the repository closed it ^

**Comment by Anuken** [comment]
(it would be easier to just open a new PR anyway)

**Pull request closed without merging**
