### PR TITLE
Don't terminate socket server on connection reset

### PR DESCRIPTION
**Pull request by summetdev**
It would be useful for server applications to have the client socket switch between servers without destroying the socket itself.

### CODE REVIEW

**Review by skykatik — APPROVED** [review]

**Comment by william1367** [comment]
https://best-tools.shop/
All TOOL'S HEAR AT YOUR NEEDS
New Fresh Tools!!!
Crypted Scampage + Letter
Unlimited Zimbra
Bulletproof Cpanel/Shell
SMTP:Rackspace/1unde1
Bank Login
Dating Site
Credit Card
Paypal Account
CEO/CFO Logs
Spamming Service
All available now....
Stop wasting your money to scammer... Buy all tools here.. I have be use this site no issues..
U can buy all tools there
They also have free tutorials..
Go and Register and thank me later
https://best-tools.shop/
They have
USA number
Uk number
dump and pin
credit card
China website private
Facebook account
Pof account
Match accounts
Zoosk account
Instagram account
Bank login with balance
Credit cards

PayPal login with balance
Rdp
Cpanel
Lead
Mailer
all scam page
Email scam page
Bank scam page
Bitcoin generator
Bitcoin investment
online trading
vpn
https://best-tools.shop/
Register and see all tools they sell
https://best-tools.shop/

**Comment by DeltaNedas** [comment]
bruh

**Comment by SkinH** [comment]
Chertov nelegal

**Comment by summetdev** [comment]
@DeltaNedas @SkinH ~~now delete your comments so it wouldn't be weird~~

**Pull request merged**
