### PR TITLE
make arc cost silicon

### PR DESCRIPTION
**Pull request by DeltaNedas**
costs 20 here

reasoning: shock mine takes silicon, why shouldn't arc

### CODE REVIEW

**Comment by ILiekMelons** [comment]
no

**Comment by ifritdiezel** [comment]
I see this as a better way to nerf arc. Increasing power consumption doesn't affect it's overpowered mechanic anyhow and adding silicon cost at least makes it unusable in first waves.

**Comment by ThatOneBepis** [comment]
Congrats
you jxhn'd the concept

**Comment by ritzip** [comment]
hail time

**Comment by BasedUser** [comment]
do keep in mind that arc already costs a buttload of power

**Comment by Ilya246** [comment]
20 silicon is too much - it should be at most 10, considering the recent 3x power consumption increase

**Comment by ILiekMelons** [comment]
it's already going to delete our power and now it's trying to delete our silicon

**Comment by BasedUser** [comment]
> https://github.com/Anuken/Mindustry/pull/2383#issuecomment-677568008
silicon is already used way too much, i'm thinking titanium instead

**Comment by BlueWolf3682** [comment]
the arc is a powerful turret, yes, but if one has to make silicon then might as well just use lancers, as when used right they're much more powerful than arcs. as well as something else: combustion gens, small batteries, power nodes, they only cost copper and lead. the only way that this turret should be further nerfed is simply less damage.

**Comment by BlueWolf3682** [comment]
the arc is a powerful turret, yes, but if one has to make silicon then might as well just use lancers, as when used right they're much more powerful than arcs. as well as something else: combustion gens, small batteries, power nodes, they only cost copper and lead. the only way that this turret should be further nerfed is simply less damage.

**Comment by BlueWolf3682** [comment]
the arc is a powerful turret, yes, but if one has to make silicon then might as well just use lancers, as when used right they're much more powerful than arcs. as well as something else: combustion gens, small batteries, power nodes, they only cost copper and lead. the only way that this turret should be further nerfed is simply less damage.

**Comment by BlueWolf3682** [comment]
the arc is a powerful turret, yes, but if one has to make silicon then might as well just use lancers, as when used right they're much more powerful than arcs. as well as something else: combustion gens, small batteries, power nodes, they only cost copper and lead. the only way that this turret should be further nerfed is simply less damage.

**Comment by BlueWolf3682** [comment]
the arc is a powerful turret, yes, but if one has to make silicon then might as well just use lancers, as when used right they're much more powerful than arcs. as well as something else: combustion gens, small batteries, power nodes, they only cost copper and lead. the only way that this turret should be further nerfed is simply less damage.

**Comment by ILiekMelons** [comment]
blue calm down

**Comment by BlueWolf3682** [comment]
Wasn't supposed to send multiple times, I have encountered this issue before on discord

**Comment by markozajc** [comment]
20 seems a bit much since arc is an early to mid game turret after all, but I'm all in with the idea of making it cost silicon in the first place

**Comment by ritzip** [comment]
the problem is spam and less damage will either make it be spammed more or useless.

**Comment by ritzip** [comment]
this also makes arcs have a long build time(pvp lmao)

**Comment by gen-NA-owl** [comment]
How about make arc cost 5-10 silc and make lancers also take 25 titanium to build(so arcs are unlocked sooner than lancers)

**Comment by GlennFolker** [comment]
> costs much power
battery exists

**Comment by Anuken** [comment]
The power nerf is enough.

**Pull request closed without merging**
