### PR TITLE
Mod dependency resolution improvements

### PR DESCRIPTION
**Pull request by Phinner**
This pull request introduce some improvements and bugfixes for the dependency resolution mechanism introduced in #6328 with :

- Support for soft dependencies: This aims to make hooking into a soft-depended plugin safe by guaranteeing it's always initialized before the plugins that use it.
- A better resolution algorithm: Improved to give more information about invalid mods, avoiding to resolve them another time later in the code.
- Fixed a bug where the mod initialization order is not guaranteed to be kept after the initial resolution.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Phinner** [comment]
Tested on both server and client 👍

**Comment by Phinner** [comment]
**;-;**

**Comment by Anuken** [comment]
So unless I'm missing something, this is actually completely broken. `orderedMods()`, instead of returning only enabled mods, returns **all** of them, which means you get all sorts of issues with mods that you are not even using.

**Comment by Anuken** [comment]
`orderedMods()` is also called many times instead of getting cached once, which looks rather expensive.

**Comment by Phinner** [comment]
> So unless I'm missing something, this is actually completely broken. orderedMods(), instead of returning only enabled mods, returns all of them, which means you get all sorts of issues with mods that you are not even using.

😞 My bad, didn't notice this issue while testing.

**Pull request merged**
