### PR TITLE
Add server MINDUSTRY.RU

### PR DESCRIPTION
**Pull request by kf-games**
Add server MINDUSTRY.RU
Server 24/7 Online
380+ Maps
Have a motd
There are moderators
Server in uninterrupted operation since October 2019

### CODE REVIEW

**Comment by DeltaNedas** [comment]
+1, i have good ping somehow on .ru

**Comment by Anuken** [comment]
image

This discord link doesn't fit; players won't be able to see it very well. Move it into the description: `config desc <link>`

You also seem to have a space in the name, for some reason.

**Comment by Quezler** [comment]
@Anuken my eyes don't like this, to much color(s)/contrast/noise 👀 
Screen Shot 2020-01-28 at 19 23 27

**Comment by Anuken** [comment]
Might want to contact the server owner about that, then.

**Comment by Quezler** [comment]
Screen_Shot_2018-10-25_at_11 02 15_AM

**Comment by kf-games** [comment]
> @ Анукен, мои глаза не любят это из-за большого количества цветов / контрастности / шума
> Снимок экрана 2020-01-28 в 19 23 27

Changed to more neutral colors

**Comment by Quezler** [comment]
many thanks ❤️

**Comment by sk7725** [comment]
> +1, i have good ping somehow on .ru

@DeltaNedas oh no...

**Comment by Anuken** [comment]
> oh no...

Please stop, this situation is already enough of a mess without you bumping ancient pull requests. I get a notification for this, you know.

**Pull request merged**
