### PR TITLE
Add kr server

### PR DESCRIPTION
**Pull request by Kieaer**
# Server logic
Server logic

# Server screenshot (GIF)
Lobby server
Active servers have a border inside the entrance area.

# Server Functions
1. Nice performance (ECAN Server is 1st - Intel i7 9800x)
- Rizen 3 2200G / NVMe SSD / 8GB RAM 3.2k OC
- Maintain 60 frames with 2,000 heads of factory/turret/walls.
2. Using plugins developed directly by the server owner
* Level system
* Temporary ban
* Animated color nickname
* Go to a specific player
* Can see a lot of information for each player.
* Displays a motd when the player joined.
* Suicide available!
* Other language players can automatically translate what they say
* server to server chat features
* Can see the number of banned people on the server.
* Custom voting system
* Account System
* Real-time core resource/power monitoring features
* Lobby system
* Automatically adjust level of difficulty per player's
* Event Server features
* Server Ranking site
Address : http://mindustry.kr:25000/rank
* Custom spawn mob
* Team save feature when player disconnected of PvP

Plugin repository: https://github.com/kieaer/Essentials
This server maintence at 6 pm every Saturday.

### CODE REVIEW

**Comment by Kieaer** [comment]
Don't add now
Plugin has some bugs

**Comment by Kieaer** [comment]
캡처

**Comment by Kieaer** [comment]
The game currently has an average of 450 players, and all servers have about over 150 players.
Therefore, the developer thought he would not add more servers.

**Comment by Quezler** [comment]
lovely graph though 👍

**Pull request closed without merging**
