### PR TITLE
Kot milk meo w patch 1

### PR DESCRIPTION
**Pull request by KotMilkMeoW**

### CODE REVIEW

**Comment by Anuken** [comment]
these are the strangest changes I've seen in a while

**Comment by oinkymoo** [comment]
did they... just delete everything?

**Comment by Darkness6030** [comment]
Btw it works

**Comment by mnrsU** [comment]
This is a giant meme

I can't tell if the person made this as a joke or if they were actually serious

**Comment by KotMilkMeoW** [comment]
> This is a giant meme
> 
> I can't tell if the person made this as a joke or if they were actually serious

I clicked the wrong button and accidentally did it.

**Pull request closed without merging**
