### PR TITLE
New bundle key: Block can't build.

### PR DESCRIPTION
**Pull request by summetdev**
When translating into russian, we got a problem that the bundles key is the same for blocks and for units, so I decided to add a new one due to the ability to control the router.

image

### CODE REVIEW

**Comment by Anuken** [comment]
I don't think this is necessary; the message could just be changed to "can't build" by default.

**Comment by summetdev** [comment]
> I don't think this is necessary; the message could just be changed to "can't build" by default.

It looks better and clearer for the players.

**Comment by BasedUser** [comment]
@summetdev you never know when anuke will add a block that *can* build

**Comment by summetdev** [comment]
> @summetdev you never know when anuke will add a block that *can* build

There is "Unit can't build" string, but some units can build.

**Comment by BasedUser** [comment]
yes

**Comment by l-Luna** [comment]
also for turret control

**Comment by Anuken** [comment]
I still don't think this is necessary.

**Pull request closed without merging**
