### PR TITLE
🌡 Silicon furnace

### PR DESCRIPTION
**Pull request by Quezler**
Screen Shot 2019-10-28 at 09 40 38

Silicon setups don't scale very well once you need one or more blue belts of titanium 😗 
(and a plethora of other reasons)

This (obviously a draft) pull request adds a `multi-press` equivalent for the silicon smelter 😇 

But instead of requiring water it uses heat from its environment:

- source 1: magma tiles, up to roughly 2/3rd efficiency
- source 2: overheating thorium reactor, up to 3/3 efficiency

(the 2 sources are summed together for the final heat, but the reactor won't heat if its heat is less than or equal to what the magma tiles already provide)

Reasoning behind is that it would be to easy otherwise, these requirements demand some more planing/thought/placement 🔬 

- source 1: magma tiles are often sparse, and a 3x3 square of the _good_ ones tend to be rare, do note that the machine also works on less than perfect tiles, as long as at least something gives heat.
- source 2: having to create a controlled environment that slowly feeds thorium (or limits coolant) to get the reactor to overheat anywhere from 0 to 100% 

So the challenge this block provides is that you'd need to setup an overheating setup, the closer to annihilation the faster the machine becomes, so high risk high reward **or** if you're lucky the map will provide some heat 🏅 

Or of course use the normal ones as a fallback, but lose space in comparison, this would be neat in tight maps 🐁 

Oh and the `i/o` is the same as the smaller one, the batches are just larger, since this is just intended to safe space, but the subject is open for balancing ⚖️ 

Demo of several setups, note that i had disabled thorium reactor explosions locally, 100% efficiency is not exactly safe, but even the lesser speeds (and even more so with phase'd overdrivers) should be sufficient 🤔 
Oct-28-2019 11-39-34
[sprite source](https://github.com/Anuken/Mindustry/files/3778332/gimp-silicon-furnace.xcf.zip) 🖌[gimp](https://www.gimp.org/)

### CODE REVIEW

**Comment by Violet-Scarelli** [comment]
How about instead of an overheating reactor you could use slag or a differential generator or chunks of pyratite? Until we get proper logistics I'm pretty sure players alone would have a hard time perfectly balancing a reactor so it doesn't explode. Maybe a new heat exchanger block to run larger factories that takes fuel and turns it into heat for nearby blocks?

**Comment by Quezler** [comment]
@Violet-Scarelli [slag has been discussed](https://discordapp.com/channels/391020510269669376/396416151032299521/638337085568450570), pyratite may actually be a good idea, should return no waste product, and as for heat exchangers: mayby a bit to much outside this scope 🤔

**Comment by Violet-Scarelli** [comment]
pyratite honestly isn't a bad idea.

**Comment by Quezler** [comment]
I'll probably remove the nuclear heat (requires to much babysitting & way to griefable on servers in hingsight) and do some sort of magma rock + pyratite combo 😇

**Comment by Violet-Scarelli** [comment]
What really excites me (knock on wood) is that pull request suggestions tend to get closed but yours hasn't because A) it's got some real clout behind it (good code, good writing) and B) you've got good clout.

**Comment by Violet-Scarelli** [comment]
Ooh, secondary idea, you could make it such that feeding the smelter with just thorium allows it to use the nuclear decay heat of a near-critical lump of thorium to smelt things. No cooling, just thorium. Viable alternative if people either don't want to or don't have room to build a pyratite layout, or need the pyra for defense. If you did add this, thorium would produce 60% efficiency, but last an extremely long time (somewhat like the RTG)

**Comment by Violet-Scarelli** [comment]
One last post then I'll shut up. While you're about it, maybe you could add a version of this for the Kiln? Because more blocks require metaglass now, and it seems like two of these, well fed and fueled, could easily replace a row or two of regular smelters.

**Comment by Quezler** [comment]
@Violet-Scarelli 🌳 thanks, the way i see it: if i have or find a nice idea and it falls within my technical capabilities/understanding i might as well save anuke the time and effort to write it from scratch, and in that process i learn more about java & the game's codebase as well, its win-win 😎 (statistically the chances for a feature to be implemented increase when there is concept code 🤖)

@Violet-Scarelli 🍊 i have reworked the reactor heat to pyritite heat, this now stacks with heat from the ground, and to top it all off it no longer absolutely requires heat, its just annoyingly slow without 🐢 

@Violet-Scarelli 🔨 not sure if thorium decay is "hot enough" for silicon 🤔 

@Violet-Scarelli ⚖️ hmm, graphite does sound like a good idea, do you happen to know if its used in the real world that way? 😗 (would make a nice use for all that leftover graphite when lots of turrets are already up 😆)

@**everyone** as for the changes, they can be seen here, keep in mind that not all machines are at max in/output due to the vast quantities of sand/coal/silicon (and i haven't even touched overdrive projectors yet 😂)
Oct-28-2019 19-10-36
(@**Anuken** `ConsumeBoost` is just my temporary workaround on how to have required item input + optional item input 🙈)

**Comment by Quezler** [comment]
@Violet-Scarelli 👓 i don't think a supersmelter for glass is really necessary, more often than not 1 24/7 kiln is enough to last the entire game, and even if not ~4 would stockpile plenty, so i'm not sure if its needed at all 🤔 (compared to the insane amount of silicon that gets used 😄)

@Violet-Scarelli 📯 oh and by all means, keep commenting to your hearts content ❤️

**Comment by Quezler** [comment]
@**everyone** balanced its speed a bit, here's one with `0%` heat and one with `100%` ⚙️ 
Oct-28-2019 19-47-42
(receiving `67.5` heat from 3x3 _good_ magma + `50%` from pyritite, up to `100%` in total)

**Comment by Violet-Scarelli** [comment]
Well I looked it up and graphite is used to make polysilicon (???) and carbon electrodes are required to make silicon. But no graphite used in direct process. 

Also, thorium in liquid salt is more than hot enough to run a MSR/LFTR, so it might be hot enough to melt sand? Idk.

**Comment by Quezler** [comment]
@Violet-Scarelli 🎰 hmm, while it might be true, being able to fuel this thing with almost anything might be a bit overkill 🤔

**Comment by Violet-Scarelli** [comment]
Totally fair. I just thought the idea of a furnace running off of radioactive decay was kinda cool .3.

Little ideas (just some random individual ideas I had, most probably won't work or need tweaking):
Dilation Field Generator: makes all factories, turrets, etc in the field utilize drastically less energy/coolant/items, about 75% less at the cost of only 25% output/manufacturing, can be throttled via phase input where 1 phase adds 5% efficiency, up to a max of 75%. The field itself utilizes 35 power/sec, plus an additional 5 power/sec/block in the field it's damping. (thought this could be good to quickly suppress power consumption in an area if you need to reboot your power, or you just need a manufacturing plant without a huge amount of power consumption). The field CANNOT be overdriven, and overdrive generators do not work in the field. 

Compression Generator: baby Impact. Takes blast and water, generates 630 power/piece of blast through controlled detonation. Meant to be a kickstarter for Impacts, due to the fact that it does not require initial power. 

Fluid Mass Driver: almost exactly what it says on the tin. When linked to another fluid mass driver, will send magnetically-confined packets of fluid through the air (anywhere from 10 to 100 units of fluid per launch) while using the same amount of power as a mass driver.

Phase Compound: made by weaving phase and titanium together, applies the stun and slow effects when used as ammo, or can be used as a material. 

Phase Mine: when activated, damages and warps all enemies within a certain range back to the spawn point/their factory. Uses phase compound and silicon.

Phase Compound Wall: improved phase wall, can reflect beams now. 

Gravitic Generator: runs on phase compound and cryofluid. Has a unique startup sequence: singularity must first be initialized, needing 1k of any item (types can be mixed). Once it's full, phase compound, 
cryofluid and power must be fed in, and the generator will start. 


Again these are all just a bunch of random shotgunned ideas I had.

**Comment by Quezler** [comment]
True, mayby for a resource other than silicon 😗

Dialation: Hmm, interesting concept, took me a few readthougs to understand it 😅

Compression: looks like the differential generator, which could use some love as well 🤔

Fluid driver: was suggested somewhere before but if I recall anuke nuked it 🎆

Phase: futuristic, nice properties 🕚

Gravitic: sounds like griefers would love it as well 🤐

 (disclaimer: I'm not part of/associated with mindustry, am just a programmer that likes to make pulls for the sake of a challenge, wether or not something I suggested/pull/review/etc is not up to me, at all 😌)

**Comment by Violet-Scarelli** [comment]
Yea I got the "not associated" part. It does seem like you could earn a contributor role if you keep doing such good work though.

**Comment by Quezler** [comment]
@Violet-Scarelli well github grants it automatically once a pull gets merged, no clue what the criteria for said role are on the discord server 🤔 

@**everyone** change the code to not dirtily add an optional item input, but instead directly accept pirytite for a `10%` heat boost, that decays to a minimum of `0%` or `ground heat %`, whichever is greater 😗

**Comment by Quezler** [comment]
production speeds of `0%`, `45%`, `67.5%` & `100%` heat and info screen 🖥 

Oct-29-2019 10-29-47

Screen Shot 2019-10-29 at 10 32 38

**Comment by Quezler** [comment]
Ima change its status from draft to review, curious as to what @Anuken thinks of it :thinking:

**Comment by TheChosenEvilOne** [comment]
This feels like unnecessary bloat to me (and also the emojis you put to every message/comment annoys me way too much...)

**Comment by Quezler** [comment]
Well you could have asked nicely.

**Comment by Violet-Scarelli** [comment]
Typos/grammar changes (little things)
"A" not "An"
maybe put parentheses around 0% heat?

**Comment by Violet-Scarelli** [comment]
Also I was enjoying the emojis .3.

**Comment by Quezler** [comment]
@Violet-Scarelli typo has now been fixed, but as for the parentheses: the way @**Anuken** structured the code won't allow that, and i didn't want my pull to change to much, so instead I mimicked the power usage of the force projector 🛡

**Comment by Anuken** [comment]
I'm not going to be considering the addition of new "content" blocks until 6.0 is ready to begin, so this probably won't be merged/reviewed for a while.

**Comment by MWestfall** [comment]
Silicon factory uses coal and sand and a little power to produce silicon..... 

In real life, coal forges produce significantly more heat than propane forges even..... 

Pyratite and coal should both be usable to generate 'heat'. 

Slag seems viable as well. 

Just because coal is an 'ingredient' of silicon doesn't mean it can't also be used to produce heat at the same time.

**Comment by SnakkiZXZ** [comment]
can replace this sprite with this one? 
Screenshot_20200319_180838_io anuke mindustry

**Comment by Quezler** [comment]
the top & left black dots look imperfectly shaped ^

**Comment by SnakkiZXZ** [comment]
it's all skr errors. here's a normal sprite
big-silicon-smelter

**Comment by SnakkiZXZ** [comment]
oh sorry. I forgot about name-top
big-silicon-smelter-top

**Comment by Anuken** [comment]
This block is still on the Trello, but as the code here is no longer functional or mergeable, I'll implement it myself later.

**Comment by Quezler** [comment]
**PSA** this branch wasn't stale, i was just waiting for `6.0` to come closer to make it meaningful to update (just like the case with #1080), if you'd like me to update/polish it you can reopen it 🙂

**Comment by Anuken** [comment]
Implemented, with some modifications.

**Comment by Quezler** [comment]
lovely 🙂 (what are the most notable features/changes/differences?)

**Comment by Anuken** [comment]
It doesn't use pyratite as a heat source, only as a crafting ingredient - this simplifies crafting significantly. Heat is optional.

**Pull request closed without merging**
