### PR TITLE
Fix poly

### PR DESCRIPTION
**Pull request by JasonP01**
Fixed poly healing enemy phase walls #9651 
Poly bullet cant be deflected anyway, this only fixes the healing issue

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by BlueTheCube** [comment]
not a bug

**Comment by JasonP01** [comment]
> not a bug

You cant tell me poly is MEANT to be able to heal enemy phase walls, so no, intended behaviour is still a bug whether you like it or not

**Comment by MEEPofFaith** [comment]
> Poly bullet cant be deflected anyway, this only fixes the healing issue

I think what's happening is it *is* being deflected, which results in it immediately hitting the phase wall and hitting it. This is likely an issue with all bullets that can heal and should probably be solved in a different way than just `reflectable = false`.

**Comment by broganeuquoixe** [comment]
Exactly, poly's bullets are just the most noticeable ones because the healing out heals the damage dealt.

https://github.com/Anuken/Mindustry/assets/161990992/9e29d161-a8b2-492a-a47e-cdfe051b17bd

**Comment by JasonP01** [comment]
> Exactly, poly's bullets are just the most noticeable ones because the healing out heals the damage dealt.
> 
>  1711403903.mp4

Actually, poly is the only one as its bullet comp is the only one that can be reflected by default, quad bullet has reflectable as false, and mega is a laser bullet which is also false by default

**Pull request merged**
