### PR TITLE
Remove dead servers

### PR DESCRIPTION
**Pull request by Kieaer**
Check date: Friday 2:23pm (UTC +0)

### CODE REVIEW

**Comment by Phinner** [comment]
🤨 How come Xpdustry servers get yeeted ? They are still up.

**Comment by Kieaer** [comment]
> 🤨 How come Xpdustry servers get yeeted ? They are still up.

image

**Comment by Phinner** [comment]
I use SRV records, that's why it does not work.

**Comment by Anuken** [comment]
You should PR it back

**Comment by way-zer** [comment]
Oh, Why my server get deleted without any notification??
That is annoying.

**Pull request merged**
