### PR TITLE
swarmer resprite?

### PR DESCRIPTION
**Pull request by stacktrace-error**
looks like this ig
image

- [x] I have ensured that any new features in this PR function correctly in-game.

### CODE REVIEW

**Comment by overdramaticpanromantic** [comment]
looks a bit goofy

**Comment by Otamamori917** [comment]
Swarmer seems fine with current sprite maybe respite Salvo?
https://github.com/Anuken/Mindustry/pull/8562#issuecomment-1537719955

**Comment by stacktrace-error** [comment]
> ~Now change swarmer to using a `ShootBarrels` so that the missiles come from each chute.~

~~you do know it's a missile launcher, which are recoilless~~

**Comment by MEEPofFaith** [comment]
> > ~Now change swarmer to using a `ShootBarrels` so that the missiles come from each chute.~
> 
> ~you do know it's a missile launcher, which are recoilless~

~~I'm talking about how the chutes aren't aligned anymore but the bullet spawning still is.~~

**Pull request merged**
