### PR TITLE
add keys(AWSD) for moving ui for research dialog

### PR DESCRIPTION
**Pull request by neoedmund**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [o] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [o] I have ensured that my code compiles, if applicable.
- [o] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Darkness6030** [comment]
Nice idea, but...
What about code style?
Did you read [the contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md)?

**Comment by Anuken** [comment]
- Incorrect formatting. Read the guidelines.
- This looks broken. KeyDown triggers when the key is first pressed. Panning around by mashing WASD is not acceptable behavior.

**Comment by neoedmund** [comment]
> * Incorrect formatting. Read the guidelines.
> 
>     * This looks broken. KeyDown triggers when the key is first pressed. Panning around by mashing WASD is not acceptable behavior.

Yeah, I wonder if there is better way than using `KeyDown()` because it not repeat automatically.

**Comment by neoedmund** [comment]
It's not broken, without auto-repeat keys, it's not best, but better than none, useful when using laptop + track pad dragging.
@Anuken  as original developer, do you have some improvement advice?
I lied I did not read "contribution guidelines", I don't care about it especially "Style Guidelines".
If any thing make you feel angry or rejection attitude, I'm sorry about it.

**Comment by Anuken** [comment]
> I lied I did not read "contribution guidelines", I don't care about it especially "Style Guidelines".

You should read them first as the template says. If you don't care about the guidelines, just don't open the PR.

**Comment by neoedmund** [comment]
Hoho, the game is happy, the conversation is not.

**Pull request closed without merging**
