### PR TITLE
EntityMapping.map(this.name)

### PR DESCRIPTION
**Pull request by younggam**
kinda mod separation?

### CODE REVIEW

**Review by summetdev — COMMENTED** [review]
`this.name` is equal to `name`, so actually this PR change nothing

**Comment by younggam** [comment]
no, name is local variable and this.name is field.
this.name gets mod-name prefix contrast to name

**Comment by Anuken** [comment]
This doesn't actually accomplish anything. Constructors for modded units should be assigned manually.

**Comment by younggam** [comment]
it is but there can be possibility that confilicts with different mods' units.
Being assigned maunally is not point in this pr

**Pull request closed without merging**
