### PR TITLE
Merge pull request #2 from Anuken/master

### PR DESCRIPTION
**Pull request by Bohaska**
h

### CODE REVIEW

**Comment by Bohaska** [comment]
I wanted to update Bohaska/Mindustry, but I switched the order by accident

**Comment by BlueWolf3682** [comment]
lol

**Comment by DeltaNedas** [comment]
bruh
`git pull upstream master`
how hard is this

**Comment by Bohaska** [comment]
> bruh
> `git pull upstream master`
> how hard is this

@DeltaNedas I don't use git I use the web gui

**Pull request closed without merging**
