### PR TITLE
PlanetGrid stuff

### PR DESCRIPTION
**Pull request by DeltaNedas**
This pull does a few things
1. Makes PlanetGrid's constructor protected not pkg private :) 
2. Buildingount -> tileCount
3. Make random calculation helpers public (not that mess at the top though, I can't comprehend it)
4. Make the fields mutable, see 1 for use case.

### CODE REVIEW

**Comment by Anuken** [comment]
Why?

**Comment by DeltaNedas** [comment]
i want to make a planet with 1 sector

**Comment by DeltaNedas** [comment]
orbital ion router

**Comment by Anuken** [comment]
The calculations look very specific and can probably be re-implemented in other code if needed; make the package-private/private again.

**Comment by DeltaNedas** [comment]
okay

**Pull request merged**
