### PR TITLE
new contributor

### PR DESCRIPTION
**Pull request by GabyCostilla**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by GabyCostilla** [comment]
i am new collaborator for mindustry

**Comment by Anuken** [comment]
You have not made any contributions.

**Comment by GabyCostilla** [comment]
ok but i wanna help

**Comment by markozajc** [comment]
I thought you said you already made contributions when you talked about this in the channel on Discord.

**Comment by GabyCostilla** [comment]
not really, but I want to learn and collaborate on this project

**Comment by markozajc** [comment]
That's weird, because you sounded very sure that you've already made contributions in the past
image
image
image

**Pull request closed without merging**
