### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by githublover11**
Ignore build folder

### CODE REVIEW

**Comment by DeltaNedas** [comment]
what the fuck

**Comment by joshuaptfan** [comment]
You are spamming the Discord #github channel every time you reopen and close this PR. Stop.

**Comment by BlueWolf3682** [comment]
what did i just witness

**Comment by RouterChainsSuckk** [comment]
can anuke ban him

**Comment by MEEPofFaith** [comment]
### _**CEASE AND DESIST**_
**_Loads nuke_**

**Comment by MEEPofFaith** [comment]
image

**Comment by joshuaptfan** [comment]
[It's a bot.](https://github.com/githublover11/control) This is intentional abuse.

**Comment by Erisfiregamer1** [comment]
githublover cease and desist before I load my report nuke

**Comment by Erisfiregamer1** [comment]
you are spamming my email when I am waiting for an important email with the card number of a 100 dollar serve card for my birthday. stop.

**Comment by Erisfiregamer1** [comment]
ok I fired a spam nuke on them

**Comment by MEEPofFaith** [comment]
report sent

**Comment by Erisfiregamer1** [comment]
I have as well. Everyone unsub from this, and report the user.

**Pull request closed without merging**
