### PR TITLE
[AMENDED] Add diagonal symmetry compat

### PR DESCRIPTION
**Pull request by The4codeblocks**
Adds functionality for blocks with a diagonal symmetry axis (defined by `Block.diagonalSymmetry`).
_`Block.rotation` = 0 means facing top-right_

Amendments: Maintained legacy method signatures

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by The4codeblocks** [comment]
I only resent an amended PR because this guy said it was ok
https://discord.com/channels/391020510269669376/396416151032299521/1213229320483504249

**Comment by Anuken** [comment]
No, I still won't accept merging this, for the same reasons. This version is even worse, as it allocates arrays in the main loop and has broken formatting.

**Comment by The4codeblocks** [comment]
> No, I still won't accept merging this, for the same reasons. This version is even worse, as it allocates arrays in the main loop and has broken formatting.

Where is the broken formatting, and how didn't you notice the array allocation in the 1st place?

**Comment by Anuken** [comment]
It doesn't matter. I've already repeated myself many times: **I'm not interested in merging this**, go away.

**Pull request closed without merging**
