### PR TITLE
Make Distributor controllable

### PR DESCRIPTION
**Pull request by Darkness6030**
Co-authored-by: @xzxADIxzx

It works btw

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Darkness6030** [comment]
image

**Comment by Darkness6030** [comment]
@Anuken please say your opinion for this PR 👀

**Comment by Anuken** [comment]
The router is only controllable as a meme, and while it's a worthy meme, I think making other transport blocks controllable doesn't really serve a purpose and only causes more confusion.

**Comment by Slotterleet** [comment]
~~y'know, [Slotterleet/distributor](https://github.com/Slotterleet/distributor) exists~~

**Pull request closed without merging**
