### PR TITLE
Add config option to disable logging trace requests

### PR DESCRIPTION
**Pull request by BalaM314**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
You know, this isn't really important to begin with, maybe it should be false by default... or removed altogether.

**Comment by BalaM314** [comment]
yeah, it's kinda useless and just takes up space in logs
image
here it's filled up the entire window

Should I just remove it?

**Comment by Anuken** [comment]
Yes

**Comment by phinner** [comment]
Can't it be moved to debug ?

**Pull request merged**
