### PR TITLE
Better Team Indicator For Turrets

### PR DESCRIPTION
**Pull request by Voz-Duh**
In this pull I created power cell for turrets this show health of turret
image
image

### CODE REVIEW

**Comment by sk7725** [comment]
@Voz-Duh this feature had been Pull-Requested a *LOT*, I recommend checking those out.

Also, make it not draw in your team's turrets, just like the normal team indications(so your defense lines don't scream yellow; this was a problem Anuke pointed out).

**Comment by Voz-Duh** [comment]
But units don't hide their team's cell
image

**Comment by Anuken** [comment]
Units are designed with their team cell in mind, turrets are not.

**Comment by Voz-Duh** [comment]
That is, if I want to add such cell for the turrets, then I need to redraw all the turrets?

**Comment by l-Luna** [comment]
these indicators look kinda bad tbh

**Comment by Voz-Duh** [comment]
Ok ._ .
I close it and go create new pull

**Pull request closed without merging**
