### PR TITLE
remove newline

### PR DESCRIPTION
**Pull request by tezlm**
removes a stray newline

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by GlennFolker** [comment]
Pretty sure it's not only in this file

**Comment by tezlm** [comment]
I'm sure there are many more stray newlines, though I find any in the future I'll merge formatting changes into one bigger pr.

**Comment by Arkanic** [comment]
> Pretty sure it's not only in this file

@GlennFolker 
That is a fatalist argument
If we start by removing one newline, we can work towards the bright future of having no newlines.

The war is not lost!

**Comment by tezlm** [comment]
hm, im not sure about the formatting. after running a regex (`\)\{\n\n`), a lot of methods/constructors have newlines after them. Then again, a lot dont (see: blocks.java). I'm going to hold off on any other formatting PRs for now.

**Comment by MEEPofFaith** [comment]
> > Pretty sure it's not only in this file
> 
> @GlennFolker That is a fatalist argument If we start by removing one newline, we can work towards the bright future of having no newlines.
> 
> The war is not lost!

Yes lets make an entire java file with no new lines in it at all.

**Comment by Anuken** [comment]
This makes the code less readable. No thanks.

Refrain from making PRs that change formatting, especially tiny ones.

**Comment by tezlm** [comment]
ok

**Pull request closed without merging**
