### PR TITLE
Gramatical bugfix

### PR DESCRIPTION
**Pull request by Quezler**
(though actually just to get pr 3k)

### CODE REVIEW

**Comment by DeltaNedas** [comment]
anukeanukenanukeanukeanukenanukeanukeanukenanukeanukeanukenanukeanukeanukenanuke

**Comment by DeltaNedas** [comment]
Grammatical*

**Comment by ThePythonGuy3** [comment]
A grammatical fix PR with grammatical errors, how ironic

**Comment by Anuken** [comment]
The old comment looks grammatically correct to me.

**Comment by ThePythonGuy3** [comment]
ohno PR 3k wasted

**Comment by z0mbiesrock** [comment]
PR is still open though

**Pull request closed without merging**
