### PR TITLE
[Ready to merge] add leds

### PR DESCRIPTION
**Pull request by LeRoiDesKiwis**
I made the idea of @Arkanic from #545 👍 
image

## Todo

- [x] Support save and load (actually you lost the color when you reload the world)

- [x] Fix hitbox bug
- [x] remove the texture "oh no" in the background

## What does it looks like
gif

### CODE REVIEW

**Comment by Luxray5474** [comment]
Awesome execution! Can't wait for the texture :+1:

**Comment by LeRoiDesKiwis** [comment]
> Awesome execution! Can't wait for the texture 👍

You want a texture ? I think it's better to don't use a texture and to totally fill the block with the color

**Comment by LeRoiDesKiwis** [comment]
I think the conflicts is not a problem because i added the led texture. You can change the texture if you want, i just put a white texture, i'm a very bad graphist ^^.

**Comment by LeRoiDesKiwis** [comment]
Just a preview : 
gif

**Comment by Arkanic** [comment]
@LeRoiDesKiwis this wasn't my idea, but @xslendix 's. i merely referenced his thoughts from an older issue.
:)

**Comment by J-VdS** [comment]
I don't know Anuke is going to merge. But you can adapt you code and make a small mod (if possible). https://github.com/Anuken/TestMod He would probably use this method for the steamworkshop. But it is still early alpha.

**Comment by Arkanic** [comment]
@LeRoiDesKiwis i think you may need a texture for it, even if it's only a border, as a solid colour makes it look kind of unfinished.
:)

**Comment by Luxray5474** [comment]
If you could add a bloom effect for blocks and not effects these would be 2x better :)

**Comment by Anuken** [comment]
To be honest, I... don't really understand what the point of LEDs is. Since there is no day-night cycle, they can't provide any real light, and as they consume power, making pixel art isn't viable-- the power beams would make a mess. Even if the power requirement were removed, couldn't you just use sorters for a 16-color palette...?

**Pull request closed without merging**
