### PR TITLE
armor to serpulo blocks

### PR DESCRIPTION
**Pull request by Esoteric-Feline**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

I would compile and run this but given how you need to buy a license to do so I am unable to, but given how this is a small change it should be fine

### CODE REVIEW

**Comment by Anuken** [comment]
What is the point of this?

> how you need to buy a license to do so

You don't, I don't see what gave you such an impression.

**Comment by Esoteric-Feline** [comment]
erekir walls have armor, serpulo walls don't, same goes with cores

**Comment by Anuken** [comment]
That's not a justification for changing the balance of the game. I've never heard anyone request this.

**Comment by BlueWolf3682** [comment]
No. Consult experienced members of the community before PRing balance changes.

**Pull request closed without merging**
