### PR TITLE
bundle_pt_BR.properties

### PR DESCRIPTION
**Pull request by Rayanfhoula15**
Added missing translations,most for the world tab. Remember to add the translator role to @What on the mindustry discord server.

### CODE REVIEW

**Comment by Pietro303HD** [comment]
> aqui,perto das montanhas, Até
are you serious?

**Comment by Pietro303HD** [comment]
and there are 4 @Whats. specify your tag/id

**Review by Pietro303HD — CHANGES_REQUESTED** [review]
> aqui,perto das montanhas,Os esporos

i don't even have to say what's wrong with this

> Florestas Congeladas

frozen forest is a single sector.

> Complexo de produção nuclear

missing uppercase

> Montanhas manchadas
> Fachada desolada

seems like you google translated some text... "montanhas manchadas". Also "fachada desolada" seems fishy.

- For the best of portuguese translations. Glory for translation.

**Comment by Rayanfhoula15** [comment]
I will solve those problems. Mobile typing sucks lol. I used the translator only on desolate rift,because i dont know what its supposed to mean.
I will specify my tag here after the changes are done.

**Comment by Pietro303HD** [comment]
> rift,because

omw to brazil

**Review by Pietro303HD — CHANGES_REQUESTED** [review]
hello,im,using,commas,the,wrong,way

**Review by Pietro303HD — COMMENTED** [review]
Nuclear Production Complex should become `Complexo de Produção Nuclear`. CPN remain uppercase

**Comment by Rayanfhoula15** [comment]
> > rift,because
> 
> omw to brazil
Sério,o que isso quer dizer?????
Não tive outra opção kkkk
Pras montanhas manchadas, só foi uma tradução literal mesmo.

**Review by Pietro303HD — APPROVED** [review]
seems alright, fix the no-space commas
ex: no-space,commas
after a comma there should always be a space.
ex: space, commas

**Comment by Rayanfhoula15** [comment]
> seems alright, fix the no-space commas
> ex: no-space,commas
> after a comma there should always be a space.
> ex: space, commas

huh. Never learnt this in school. Will do.
My tag is @what#0001

**Comment by RayanZ22** [comment]
tem umas coisa errada ai irmão, e tem parada em inglês ainda

**Comment by Anuken** [comment]
#3647
#3926
#3612
#2964

Which one should be merged?

**Comment by Anuken** [comment]
Too many conflicts, please re-open if necessary.

**Pull request closed without merging**
