### PR TITLE
Boss (Guardian) Status Sprite

### PR DESCRIPTION
**Pull request by sk7725**
Because why not.
+ I do not think it will show up, but I hope it does; CONTRIBUTING did say not to touch the atlas.
+ Korean bundle included.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
> CONTRIBUTING did say not to touch the atlas.

Does it still say that? The atlas is ignored, so that shouldn't be relevant.

**Comment by sk7725** [comment]
> > CONTRIBUTING did say not to touch the atlas.
> 
> Does it still say that? The atlas is ignored, so that shouldn't be relevant.

so should I go more steps to make my sprite show up ingame, or is this (just upload to raw) enough for this PR?

**Comment by Anuken** [comment]
It's probably enough.

**Comment by sk7725** [comment]
status-boss
image

**Pull request merged**
