### PR TITLE
Remove EscoCorp Sandbox server

### PR DESCRIPTION
**Pull request by 5GameMaker**
- Stole a map
- Removed all watermarks
- Left no contacts
- Contacted via alternative means, no answer
- Literally the only map on the server anyway
- It's been 2 days, could've swapped it already

This server uses ChatGRT's map for Mindurka. We nor the creator were never notified and we want either our map removed from the server or the server to be removed from global list.

Original ChatGRT comment: https://github.com/Anuken/Mindustry/pull/10142#issuecomment-2332328411  
The only map on the server screenshots (I've never seen /rtv to ever switch to another map lol):
- image
- image

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by nicknamewhat801** [comment]
ok,but
изображение

**Comment by nicknamewhat801** [comment]
no one messaged me on discord,and this map was suggested by member of discord server

**Comment by nicknamewhat801** [comment]
If you have any complaints, you can write me on discord and we will solve all problems.
изображение

**Comment by 5GameMaker** [comment]
Pls enable frs for a moment 🙏🏻 
image

**Comment by 5GameMaker** [comment]
> ok,but изображение

I see
image

**Comment by nicknamewhat801** [comment]
> Pls enable frs for a moment 🙏🏻 image

done.

**Comment by 5GameMaker** [comment]
( things are getting resolved the normal way, so closing )

**Pull request closed without merging**
