### PR TITLE
Implementing Mindustry-Suggestions#4959

### PR DESCRIPTION
**Pull request by S0meM**
https://github.com/Anuken/Mindustry-Suggestions/issues/4959
Note that the title beneath here is wrong. This is mindustry-suggestions#4959, not mindustry#4959.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
This PR doesn't do anything. The stat it adds is unused.

**Comment by hexagonrecursion** [comment]
I tested this PR. There is no observable change:

image

It looks like you forgot to add a line in setStats():

https://github.com/Anuken/Mindustry/blob/0a50e7dc4859cc411b43cc2eb757a2ab2608406e/core/src/mindustry/world/blocks/defense/turrets/Turret.java#L148-L157

**Comment by hexagonrecursion** [comment]
I also think it would be less confusing for the player if instead of using "ammo" quantities all turret stats were described in terms of items or shots. Turrets consume items - the player can see and understand items, turrets shoot - the player can see the turret shooting, but "ammo" is a strange quantity that is _indirectly_ related to both the number of items consumed and the number of times that a fully loaded turret can shoot - this is additional complexity that I do not understand the point of exposing to the player.

On the one hand a fully loaded Breach can only shoot 15 times because it uses 2 ammo per shot - ammo is only indirectly linked to the number of shots that a fully loaded turret can make. On the other hand it only takes 10 items to fully reload Disperse because it has "ammo multiplier" 3.

The questions I expect players to want to know:
* How many items does it cost to shoot the turret once?
* What is the damage per second, damage per shot, damage per item?
* How many items per second does the turret consume?
* How many shots can a fully loaded turret make before it is empty?
* How many items does it take to fully reload a turret?

I am **not** suggesting that the game should display all of this redundant information - everyone has a calculator. I have listed the questions a player is likely to care about to make a point: **none** of this questions directly mention "ammo". As it currently stands **every** useful question about item consumption or capacity of a turret would have to involve a manual calculation.

# How I would like turret stats displayed:
Note: I would like the "ammo use" and "ammo multiplier" stats removed from the user interface in favour of the below:

Turret | Items per shot | Max shots
-|-|-
Breach | Berillium: 2, Tungsten: 2 | **15**
Diffuse | 3 | **10**
Titan | 4 | **3**
Disperse | 0.33 (1/3) | 30
Scathe | 15 | **2**
Smite | 2 | **15**
Duo | Copper: 0.5, Graphite: 0.25, Silicon: 0.2 | 30
Scatter | Lead: 0.25, Metaglass: 0.2, Scrap: 0.2 | 30
Scorch | Coal: 0.33, Pyratite: 0.17 (1/6) | 30
Hail | Graphite: 0.5, Silicon: 0.33, Pyratite: 0.25 | 30
Swarmer | Surge: 0.25, Blast: 0.2, Pyratite: 0.2 | 30
Salvo | Copper 0.5, Graphite: 0.25, Thorium: 0.25, Silicon: 0.2, Pyratite: 0.2 | 30
Fuse | Titanium: 0.25, Thorium: 0.2 | 30
Ripple | **Graphite: 1, Silicon: 0.66 (2/3), Plastanium: 1, Blast: 0.5, Pyratite: 0.5** | **15**
Cyclone | Metaglass: 0.5, Plastanium: 0.25, Surge: 0.2, Blast: 0.2 | 30
Foreshadow | 5 | **8**
Spectre | Graphite: 0.25, Thorium: 0.5, Pyratite: 0.33 | 30

Alternatively we can display "shots per item" instead of "items per shot". In that case only the following would have non-integer stats:
* Breach (Berillium: 0.5, Tungsten: 0.5)
* Diffuse (0.33 (1/3))
* Titan (0.25)
* Scathe (0.07 (1/15))
* Smite (0.5)
* Ripple (Silicon: 1.5)
* Foreshadow (0.2)

**Comment by hexagonrecursion** [comment]
Upon further consideration I retract my suggestion to replace "ammo use" and "ammo multiplier" stats because almost all vanilla turrets use only one or the other. Therefore "ammo multiplier" can usually be interpreted by the player as "shots per item" while "ammo use" as "items per shot". The only exception is Ripple.

Note that I still think it is best to display "Max shots" (see table above) instead of "Max ammo" as suggested in the pull request

**Comment by S0meM** [comment]
> I tested this PR. There is no observable change:
> 
> image
> 
> It looks like you forgot to add a line in setStats():
> 
> https://github.com/Anuken/Mindustry/blob/0a50e7dc4859cc411b43cc2eb757a2ab2608406e/core/src/mindustry/world/blocks/defense/turrets/Turret.java#L148-L157

Sorry, I've never worked on Mindustry before. I'm new to Java, and I can't install the oracle java compiler on a school laptop. Does anyone know something else I could use, like a web compiler that will turn it into a .exe to download?

**Comment by S0meM** [comment]
And I didn't find the setstats function. Thanks for the input.

**Comment by hexagonrecursion** [comment]
Can't install oracle java compiler? How about [OpenJDK](https://adoptium.net/en-GB/temurin/archive/?variant=openjdk17&jvmVariant=hotspot&version=17) then? It's what Mindustry [README.md](https://github.com/Anuken/Mindustry/blob/master/README.md) recommends.

**Comment by Anuken** [comment]
> Does anyone know something else I could use, like a web compiler that will turn it into a .exe to download?

Java programs don't compile to .exe files, they compile to .jar files. If you cannot install Java, you will be unable to run or test your changes.

Moderate knowledge of Java and a compiler are crucial for working on Mindustry - I think it's best that someone I (or someone else) handle this feature.

**Comment by S0meM** [comment]
Ok

**Comment by S0meM** [comment]
Also, can someone explain the 
`import mindustry.gen.*;`
? 
They are everywhere, but there isn't a folder like that.

**Comment by Anuken** [comment]
It's generated code, you won't see it in the repository. It is created when the game compiles.

**Pull request closed without merging**
