### PR TITLE
`fragChance`

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Someone in #modding-general asked if there was a `fragChance`.
I said no, then went ahead and implemented it.

0-1 chance that a bullet will create frag.

original mesage

### CODE REVIEW

**Comment by sk7725** [comment]
if a bullet has 2 frag bullets, and .5 fragChance, it should spawn 1 bullet 50% of the time, none 25% ott, two 25% ott. It should follow a general distribution or something, i'm not a statistics man tho

**Comment by MrDuck557** [comment]
I have no idea what this would be used for lmao

**Comment by Anuken** [comment]
What's the point?

**Comment by 1ARC1** [comment]
itd make more sense tbh, having the same amount of frags every single bullet seems off when you really think about it

**Comment by MEEPofFaith** [comment]
Someone asked if it was possible so I did it because it wasn't.

I guess at least one person out there would like their bullet have a chance to not create frag.

**Comment by stuffyAI** [comment]
I'd much rather the frag is balanced by its type and not by a chance, like instead of giving it a 50% chance to frag just make the frag deal 50% damage...
I don't see how this is not unnecessary inconsistency

**Comment by Anuken** [comment]
Eh.

**Comment by MEEPofFaith** [comment]
Eh.

**Pull request closed without merging**
