### PR TITLE
ConsumeItemList

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Just an items consumes where you can just define a lists of potential items to consume.

20240613-133352-javaw

[test-mod.zip](https://github.com/user-attachments/files/15828456/test-mod.zip)

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
How does `ObjectMap` parsing (like turret ammo) work since it's not in `ContentParser`?
The game doesn't parse `ObjectFloatMap` so things like the item multipliers in this as well as drill multipliers in drills don't work with json.

**Comment by MEEPofFaith** [comment]
> How does `ObjectMap` parsing (like turret ammo) work since it's not in `ContentParser`?

In Arc. Well appear there soon.

**Review by BlueTheCube — APPROVED** [review]
this is a small step for advanced cross-compatibility for mods

**Review by BlueTheCube — COMMENTED** [review]
where's `ConsumeLiquidList` for consistency?

**Comment by MEEPofFaith** [comment]
wh- why are power tests failing

**Pull request merged**
