### PR TITLE
Disable unitLand Effect For Metal Floors

### PR DESCRIPTION
**Pull request by Voz-Duh**
I think what `isHard` bad name for this boolean but I don't have more ideas for this /-/
[video](https://user-images.githubusercontent.com/61590217/109904220-ef3ef880-7cad-11eb-8c94-9cb877102b60.mp4)

### CODE REVIEW

**Comment by joshuaptfan** [comment]
How about `isFirm`?

**Comment by Voz-Duh** [comment]
> How about `isFirm`?

Hm... I think what this name better what `isHard`

**Comment by Anuken** [comment]
This doesn't seem necessary. Metal can still have dust on it; things don't look any better without the effect.

**Comment by sk7725** [comment]
Better suggestion: add
```
public Effect landEffect = Fx.none;
```
and make the metal floors have "sparks" (like Fx.despawn) so it looks like metal hitting metal.

**Comment by joshuaptfan** [comment]
Sparks would be too distracting, it would look like there's something combat-related going on or the unit is taking damage, when it's just walking.

**Pull request closed without merging**
