### PR TITLE
Add RCR

### PR DESCRIPTION
**Pull request by romanin-rf**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by romanin-rf** [comment]
Let's go back!

**Comment by SachaTending** [comment]
oh yes, new work

**Comment by Anuken** [comment]
reopen to fix conflict / once server is back  up

**Comment by romanin-rf** [comment]
> reopen to fix conflict / once server is back up
All right!

**Pull request closed without merging**
