### PR TITLE
protected->public for mod supports

### PR DESCRIPTION
**Pull request by younggam**
validating `new Conveyor, foo.requirements(), bar.ammo()`
and
how about using below way instead of double braces initialization?
```
public <T extends Block> Block newBlock(Prov<T> constructor, Cons<T> setter){
    Block target = constructor.get();
    setter.get((T) target);
    return target;
}

foo=newBlock(()->new Conveyor("foo"), (Conveyor t)->{
    t.requirements(...);
    t.health=100;
    .
    ..
});
```

### CODE REVIEW

**Comment by DeltaNedas** [comment]
why not
````
foo = new Conveyor("h") {{
    requirements();
};
```
its much shorter

**Comment by younggam** [comment]
it is but it creates an anonymous class

**Comment by GlennFolker** [comment]
Who cares? Anuke uses it all the time

**Comment by younggam** [comment]
It is well known that anonymous classes cause performance decrease.
But yes, nobody seems care about it.
and main content of this pr is just changing access level.

**Comment by Anuken** [comment]
> It is well known that anonymous classes cause performance decrease.

What is your source for that?

**Comment by younggam** [comment]
https://stackoverflow.com/questions/924285/efficiency-of-java-double-brace-initialization
I heard it affects startup and garbage collections from here. eh, i dunno how much it affects in mindustry.

**Comment by Anuken** [comment]
In my case, none of those objects should be garbage collected anyway, and while there *is* a startup cost to creating so many anonymous classes, it should not affect runtime performance at all.

**Comment by younggam** [comment]
Oh, I understand.
then will you reject thus pr?

**Comment by Anuken** [comment]
No, it seems simple enough.

**Pull request merged**
