### PR TITLE
fix impact & compress images

### PR DESCRIPTION
**Pull request by bendnuts**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
- This fails CI, some of your PNGs can't be read.
- Compressing these images accomplishes nothing, as it pollutes the diff and increases the overall git size of the repo. Most of these images are packed into an atlas that is not included in git, so you are not decreasing the overall file size of the game.
- I am aware of compression tools like zopflipng and have used them myself.

**Comment by bendnuts** [comment]
What about the impact issue? @Anuken

**Comment by Anuken** [comment]
I don't know what impact issue you're talking about and I can't check because of the 920-file diff.

**Comment by bendnuts** [comment]
ah.

**Comment by bendnuts** [comment]
> I don't know what impact issue you're talking about and I can't check because of the 920-file diff.

https://github.com/bendnuts/Mindustry/commit/229a4761cbc9e8f870ac0c4b64c2530ada0d1f6a

**Comment by bendnuts** [comment]
Ill make a pr specifically dedicated to that part

**Comment by Anuken** [comment]
I set the zoom to 250% and spammed the onion skin slider, but I still can't see a difference between those two images.

**Comment by GrandTeki** [comment]
I took a closer look at the impact sprite, and found what @bendnuts has been talking about:
image
I think the fix is to center that small bit of detail. The proposed version of the image has it properly centered. I recoloured the background to black for easier visibility:
image
image

**Comment by hortiSquash** [comment]
> I set the zoom to 250% and spammed the onion skin slider, but I still can't see a difference between those two images.

image
these two parts are moved a tiny bit for consistency with the others glass reflections of the sprite
its hard to see because its transparent on a white background

**Comment by Anuken** [comment]
(how do you even see that in-game without someone pointing it out?)

**Pull request closed without merging**
