### PR TITLE
More Visually Pleasing Parallax Sprite

### PR DESCRIPTION
**Pull request by Violet-Scarelli**
I heard a while ago that the Parallax sprite was not as visually pleasing as the other sprites in the turret category, because it did not take up nearly as much room on its base as the other turrets. I've remedied that with a new sprite that is more proportionate to the other turret sprites, while still fitting in thematically with the electric defense turrets.

### CODE REVIEW

**Comment by summetdev** [comment]
Could you show a preview in the game, please? 👀

**Comment by Voz-Duh** [comment]
@Violet-Scarelli this bad sprite
1. Overdeatiled
2. Small
3. Parallax sprite already in game

**Comment by Catchears** [comment]
Don't include packed files with your PR.

Before:
image
After:
image

**Comment by Slava0135** [comment]
overdetailed

**Comment by MEEPofFaith** [comment]
Doesn't quite fit the original shape.

**Comment by GlennFolker** [comment]
*More Visually Torturing Parallax Sprite

**Review by Erisfiregamer1 — APPROVED** [review]
New sprite looks nice!

**Comment by Goobrr** [comment]
Front part looks too thin and fragile, bottom is too wide and square, overdetailed.

**Comment by EmanuelG-Gaming** [comment]
Looks like the WW2 gun (the new sprite) while the old sprite looks like a compact shape...

**Pull request closed without merging**
