### PR TITLE
Made power nodes retain connections in schematics

### PR DESCRIPTION
**Pull request by KSean222**
https://feathub.com/Anuken/Mindustry/+42
Still working out all the kinks in the code, leaving this here to see what y'all think.
Demonstration of power node link memory

### CODE REVIEW

**Comment by KSean222** [comment]
Should probably rework the code to avoid copious use of `Call` when connecting nodes

**Comment by KSean222** [comment]
Helps with https://feathub.com/Anuken/Mindustry/+42

**Comment by ado1928** [comment]
I see this being abused using many connections to overload players on a server with connection packets

**Comment by Ajedi32** [comment]
IIRC, each node can only have 20 connections each (30 for large nodes). Is that really _that_ much more data than the schematic itself would be?

**Comment by CA6** [comment]
Eh due to size of schmatics it can't be abused to gard

**Comment by Quezler** [comment]
a variation on this (without looking at the code prior) can be found [here](https://github.com/Anuken/Mindustry/compare/master...Quezler:scidustry) 🙂

**Comment by Anuken** [comment]
Implemented in 6.0 branch.

**Pull request closed without merging**
