### PR TITLE
Phase Fabricator(T2 phase weaver)

### PR DESCRIPTION
**Pull request by Colonizor48**
Continuing the trend of new t2 variants of building. Takes 4 plastanium, 10 thorium and 18 sand to make 4 phase fabric every 1.5 seconds. Takes 700 power per second.
(Note i know that this is using a placeholder texture. If anyone could make a sprite feel free to. Also if my 5 minute notepad++ code isn't formatted right feel free to give feedback.)
pls give feedback. This is kinda my first major pull request.
TODO:
[] add sprite
[] balance this better
UPDATE turned this into a draft as it isn't quite ready yet.
EDIT made it take more materials and make the amount of power it takes more precise(the decimal is a repeating decimal)

### CODE REVIEW

**Comment by Colonizor48** [comment]
Wait let me fix this. I forgot to push

**Comment by Colonizor48** [comment]
Should i turn this into a draft?

**Comment by Colonizor48** [comment]
UPDATE turned this into a draft as it isn't quite ready yet.

**Comment by unjown** [comment]
honestly we dont really need a T2 phase

**Comment by unjown** [comment]
a plast version will be ok

**Comment by Spfwniw** [comment]
you should type 700 / 60 for power insteas of 11.6666667

**Review by Spfwniw — CHANGES_REQUESTED** [review]
change consumes.power to

consumes.power((float)(700 / 60))

i guess this is the way you do it but basically the consumed power should be 700 / 60 in any way instead of 11.6666667

**Comment by Spfwniw** [comment]
> honestly we dont really need a T2 phase

current t1 phae fabric is really slow and consumes alot either it should be buffed or a new and better phase weaver should be added

**Comment by unjown** [comment]
> > honestly we dont really need a T2 phase
> 
> current t1 phae fabric is really slow and consumes alot either it should be buffed or a new and better phase weaver should be added

Yes ik its slow but building t4 5 will get too easy esp. If t2 cryo comes. Also overdrive

**Comment by Spfwniw** [comment]
> > > honestly we dont really need a T2 phase
> > 
> > 
> > current t1 phae fabric is really slow and consumes alot either it should be buffed or a new and better phase weaver should be added
> 
> Yes ik its slow but building t4 5 will get too easy esp. If t2 cryo comes. Also overdrive is there

but getting surge and phase is hard even if we add t2 phase weaver there is still surge problem. it also takes alot of time to build

**Comment by superbrias** [comment]
isn't part of the thing about T2 crafters is they require a good bit of what they craft, thus only making it easy to get more of the stuff, not get the stuff in the first place? I am all for strong things being hard to get but I also don't like being held back when I get to that level.

**Comment by SnakkiZXZ** [comment]
I'm not really sure that @Anuke will add this to the game, I think that a large phase plant is not a good idea since the phase is rarely used and is not required in large volumes. I always had 1-2 factories during the game, but still I don't mind if it appears in the game.

faseFabricator
faseFabricator-top
faseFabricator-bottom


hey i see you don't have a texture so i made it for you, even if this request gets closed you can still use texture for your mods.

**Comment by Colonizor48** [comment]
Well for the new t4 and t5 units you do kinda need alot of phase fabric.

**Comment by Anuken** [comment]
*Good, that's the point.*

**Comment by Colonizor48** [comment]
I think if t

> 
> 
> > > > honestly we dont really need a T2 phase
> > > 
> > > 
> > > current t1 phae fabric is really slow and consumes alot either it should be buffed or a new and better phase weaver should be added
> > 
> > 
> > Yes ik its slow but building t4 5 will get too easy esp. If t2 cryo comes. Also overdrive is there
> 
> but getting surge and phase is hard even if we add t2 phase weaver there is still surge problem. it also takes alot of time to build.
> 
> but if it is easy for alot of people. then there should be nerf to them and maybe t6 units.
> 
> Here is a t6 unit idea: a long worm that crawls upon the sector and does damage by either its weapons or its body.
> 
> Another t6 unit idea: a flying unit that dashes fastly and has long dash range, when dashing he leaves alot of bombs behind, kinda like horizon and quad but too much better. It's sprite should be that potential boss concept sprite in concept art channel in discord.
> 
> Anuke won't probably make t6 units since it takes alot of work, scripting and thinking of t6 units. So the alternative idea which is nerf to reconstructors has more potential even though they are too underpowered for me since it takes alot if it is op or something for most people then it should be nerfed.

i think if we get t6 units they should be campaign only. They would be planet bosses that you would have to fight after capturing an entire planet. And once you beat the boss you would unlcok them. But you could only have 1 at a time for the entire map.

**Comment by unjown** [comment]
T6 will not be really neceasarry cuz T5 already wrecks all (Excpet campaign) 

Phase doesnt actually need a T2 cuz its gonna get EZ.
t4 and 5 will be EZ

**Comment by Colonizor48** [comment]
Phase does kinda need a t2 in my opinion. Plast is getting a t2 soon why not phase?

**Comment by unjown** [comment]
> Phase does kinda need a t2 in my opinion. Plast is getting a t2 soon why not phase?

cuz phase will be easier to get and looses its catch of being "rare"
@Colonizor48

**Comment by Colonizor48** [comment]
> 
> 
> > Phase does kinda need a t2 in my opinion. Plast is getting a t2 soon why not phase?
> 
> cuz phase will be easier to get and looses its catch of being "rare"
> @Colonizor48
so will plast with the pull request that looks like its going to be added. Also you need massive amounts of phase for phase conveyors which i did tests with and are actually better then plast conveyors unless you have a lot of a material that you need to transport.

**Comment by SnakkiZXZ** [comment]
only 2-3 phase factories are enough for phase conveyors, I have never used more than 2 phase fabric factories as it is almost never used

**Comment by unjown** [comment]
the usuall phase is 2 facs :smile:
and its enought to build a t4/5 and some conveyer/condult
so i dont really think we need this

**Pull request closed without merging**
