### PR TITLE
Update bundler launcher java

### PR DESCRIPTION
**Pull request by Anubhav-developr**
As there is no need to put // inside the  " " it will work fine with  single / reducing time complexity.

### CODE REVIEW

**Comment by Anubhav-developr** [comment]
Changed some time consuming elements

**Comment by SnakkiZXZ** [comment]
why is it? how will this affect the gameplay?

**Comment by SethiPandi** [comment]
Might as well just delete the method call at that point? :thinking: :thinking: :thinking:

```java
.replace("\n", "\n")
```

Probably just Hacktoberfest spam.

**Comment by l-Luna** [comment]
dumb spam

**Pull request closed without merging**
