### PR TITLE
Make the flame optional on GenericSmelter Blocks.

### PR DESCRIPTION
**Pull request by TechFish3000**
May not work, i only have a basic understanding of java.
Default flame is on, change doFlame to customize.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
if you dont want the flame just use genericcrafter???

**Comment by TechFish3000** [comment]
I still want to be able to use a topRegion, to go over it while processing.

**Comment by DeltaNedas** [comment]
fair enough

**Comment by TechFish3000** [comment]
should i request anuken?

**Comment by Anuken** [comment]
Set `flameColor` to a clear color instead. There's a check for that right next to the extra code you added.

**Comment by TechFish3000** [comment]
oh ok, didn't realise.

**Comment by TechFish3000** [comment]
this doesn't render the topRegion though? could you maybe move the topRegion renderer outside?

**Comment by TechFish3000** [comment]
Would this work?

**Comment by TechFish3000** [comment]
wait

**Comment by TechFish3000** [comment]
nevermind, ill create a seperate fork

**Pull request closed without merging**
