### PR TITLE
Nerf block lighting, buff illuminator

### PR DESCRIPTION
**Pull request by MEEPofFaith**
After some discussion in balancing, we decided that illuminator is underused because everything else already creates enough light that there's no reason to build them.
image
This weakens light produced by other sources, and buffs illuminator light proudction.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Note: Still have no idea how to fix illuminator stopping producing light when off screen.

**Comment by Anuken** [comment]
> Note: Still have no idea how to fix illuminator stopping producing light when off screen.

This is precisely why the illuminator doesn't have a bigger radius. There is no reasonable way to prevent it from clipping off the screen in 6.0.

> everything else already creates enough light

I'd rather not make everything darker. Nights are annoying enough as is.

**Comment by MEEPofFaith** [comment]
Well, we need some way to give an incentive to use illuminator

**Comment by Anuken** [comment]
I increased its radius in the 7.0 branch when better culling was implemented, but making *other* sources dimmer is not the right way to go.

**Pull request closed without merging**
