### PR TITLE
Update Menus.java

### PR DESCRIPTION
**Pull request by SSTentacleSS**
The commit is aimed at the ability to remove listners that we do not need, which can potentially be a huge number and which can cause the GC to not work as expected

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Phinner** [comment]
This approach would break all menus since the ids will be shifted. Use an `IntMap` to store the menus instead with an incrementing id so it never happens.

**Comment by Darkness6030** [comment]
Зачем это вообще нужно? Ты можешь регистрировать одно меню для всех игроков

**Comment by Darkness6030** [comment]
В любом случае на сервере не будет больше 5-10 меню, ну в крайнем случае 20. Зачем может пригодиться удалять их, это же не сильно влияет на память

**Comment by SSTentacleSS** [comment]
> This approach would break most menus since the ids will be shifted. Use an `IntMap` to store the menus instead with an incrementing id so it never happens.

yea, good

**Comment by Anuken** [comment]
PR is broken as mentioned above

**Pull request closed without merging**
