### PR TITLE
Rotate slider in the mirror filter.

### PR DESCRIPTION
**Pull request by TranquillyUnpleasant**
Allows applying 180 degree rotation within the mirror filter.

With mirror:
image

With rotate:
image

### CODE REVIEW

**Comment by TranquillyUnpleasant** [comment]
Map filter options dont have a checkbox atm

**Comment by TranquillyUnpleasant** [comment]
I added a button on my local branch instead of a slider, can push if thats preferable
image

**Comment by LeoSko** [comment]
@TranquillyUnpleasant, all I mean that the effect that you get with this flag is more that you *flip* the mirrored part rather than *rotate*. *Rotate* in terms of *mirroring* makes no sense to me (but I'm not native speaker so I might be wrong).

**Comment by TranquillyUnpleasant** [comment]
A 180 degree rotation is literally a combination of two flips... unsure how that makes it not a rotation?

**Comment by TranquillyUnpleasant** [comment]
Converted it to a checkbox, new Filter Option called ToggleOption for this purpose (name subject to change of course)

**Pull request merged**
