### PR TITLE
bundle_ar.properties

### PR DESCRIPTION
**Pull request by RGOTI-Official**
UNFINISHED, will continue working on it.

### CODE REVIEW

**Comment by RGOTI-Official** [comment]
Sorry for not completing it i have an online meeting to do.

**Comment by YellOw139** [comment]
The game's font doesn't seem to support arabic characters. Have you tested your translation in-game to see if the characters show up?

**Comment by Anuken** [comment]
RTL languages are not supported by the font system, or the font itself.

**Comment by o-osos** [comment]
@YellOw139
Hello ` I wanted to know how I could try the language in the game file.? 
On Android, apk

**Comment by YellOw139** [comment]
@o-osos First off, please do not revive old PRs. Secondly, see you on Discord in #translations (https://discord.gg/8GbuWXeF).

**Pull request closed without merging**
