### PR TITLE
Eradication Mindustry IP change

### PR DESCRIPTION
**Pull request by TheRadioactiveBanana**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Yo0o0o** [comment]
image

**Comment by Ilya246** [comment]
i can say with reasonable confidence that erad isn't working with volas and won't let him come back, he's just letting omega's good staff migrate to his server
all should be fine

**Comment by TheEt1234** [comment]
> ...omegahub was previously maintained by volas (he 'deleted' your server node), and now you want to circumvent the ban under new name in which... still has volas controlling it
> Screenshot 2023-11-05 154856
> 

does it still have voll controlling it??? @TheRadioactiveBanana

**Comment by TheRadioactiveBanana** [comment]
It was volas NOT ME

**Comment by Dofuscan** [comment]
...omegahub was previously maintained by volas (he 'deleted' your server node), and now you want to circumvent the ban under new name in which... still has volas controlling it
Screenshot 2023-11-05 154856

**Comment by Yo0o0o** [comment]
> Were not circumventing a ban here, simply me taking some of their gamemodes and other data as volas just left it to rot suddenly, i felt a moral obligation to take it. Everybody in the community is fine with it.

image

**Comment by TheRadioactiveBanana** [comment]
Co owning doesnt mean he has to be in power

**Comment by TheRadioactiveBanana** [comment]
all he has is just the co owner role

**Comment by NexitySecond** [comment]
https://github.com/Anuken/Mindustry/assets/89518595/4c04a6ca-7233-467e-b60d-c83895177093

**Comment by Celestemysterios** [comment]
> image

no it is this
volas_ddos

**Comment by Anuken** [comment]
On second examination, no thanks. It's the same exact servers with the same people that let it happen in the first place.

**Pull request merged**
