### PR TITLE
Allow custom launch pods (Attempt 2)

### PR DESCRIPTION
**Pull request by z0mbiesrock**
#3777 failed _miserably_ because of a barrage of syntax errors

### CODE REVIEW

**Comment by z0mbiesrock** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!! SYNTAX ERROR!!!!

**Comment by z0mbiesrock** [comment]
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:192: error: cannot find symbol
        Draw.color(podEngineColor);
                   ^
  symbol:   variable podEngineColor
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:194: error: cannot find symbol
        Fill.light(cx, cy, 10, 25.0F * (rad + scale - 1.0F), Tmp.c2.set(podEngineColor).a(alpha), Tmp.c1.set(podEngineColor).a(0.0F));
                                                                        ^
  symbol:   variable podEngineColor
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:194: error: cannot find symbol
        Fill.light(cx, cy, 10, 25.0F * (rad + scale - 1.0F), Tmp.c2.set(podEngineColor).a(alpha), Tmp.c1.set(podEngineColor).a(0.0F));
                                                                                                             ^
  symbol:   variable podEngineColor
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:201: error: cannot find symbol
        region = podRegion.found() ? podRegion : podRegionDefault;
        ^
  symbol:   variable region
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:201: error: cannot find symbol
        region = podRegion.found() ? podRegion : podRegionDefault;
                 ^
  symbol:   variable podRegion
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:201: error: cannot find symbol
        region = podRegion.found() ? podRegion : podRegionDefault;
                                     ^
  symbol:   variable podRegion
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:201: error: cannot find symbol
        region = podRegion.found() ? podRegion : podRegionDefault;
                                                 ^
  symbol:   variable podRegionDefault
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:202: error: cannot find symbol
        float rw = region.width * Draw.scl * scale;
                   ^
  symbol:   variable region
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:203: error: cannot find symbol
        float rh = region.height * Draw.scl * scale;
                   ^
  symbol:   variable region
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:205: error: cannot find symbol
        Draw.rect(region, cx, cy, rw, rh, rotation);
                  ^
  symbol:   variable region
  location: class LaunchPayload
/home/runner/work/Mindustry/Mindustry/core/build/generated/sources/annotationProcessor/java/main/mindustry/gen/LaunchPayload.java:209: error: cannot find symbol
        Draw.rect(region, cx + Tmp.v1.x, cy + Tmp.v1.y, rw, rh, rotation);
                  ^
  symbol:   variable region
  location: class LaunchPayload
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by Anuken** [comment]
As I *literally just said* - **Don't open pull requests until they're tested!** You should not be using the CI for this. Please stop. Install an IDE, import the project and learn Java there.

**Comment by z0mbiesrock** [comment]
> As I _literally just said_ - **Don't open pull requests until they're tested!** You should not be using the CI for this. Please stop. Install an IDE, import the project and learn Java there.

OH FFS **IT WAS GOING TO COMPILE!**

**Comment by z0mbiesrock** [comment]
> Install an IDE, import the project and learn Java there.
If I had a strong enough computer, I could 😬
@DeltaNedas will probably berate this failure
And you'll probably even end up doing this yourself ¯\_(ツ)_/¯

**Comment by GlennFolker** [comment]
Dude can you literally program java

**Comment by DeltaNedas** [comment]
ok use nano and gradle - or hell write a makefile to test it

**Pull request closed without merging**
