### PR TITLE
Alphabetize contributers list

### PR DESCRIPTION
**Pull request by Yoru-Kitsune**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Phinner** [comment]
🤨 Mate, you have no guarantee future updates to the list will respect the order, you better edit the contributor menu code to sort them instead.

**Comment by Anuken** [comment]
They are generally sorted in contribution order. I don't see a reason to make them alphabetically sorted here.

**Comment by Phinner** [comment]
> They are generally sorted in contribution order. I don't see a reason to make them alphabetically sorted here.

:thinking: Mmmh, if that's the case, what about this person that added himself at the top of the list (https://github.com/Anuken/Mindustry/commit/aefcb7746a48e8f2ec382ad1e77071ddbb9e4bf5) ?

**Comment by Anuken** [comment]
Yeah that should be at the bottom.

**Pull request closed without merging**
