### PR TITLE
Make bloom be accessible

### PR DESCRIPTION
**Pull request by sk7725**
Alternative way: `public Bloom bloom;`  

Make the bloom that is being used in the renderer be public or accessible.
+ The bloom's bloomIntensity, originalIntensity, threshold can be set.  
+ Certain mods can modify it, such as a "high-res" mod or realistic mod(like minecraft's).  

(Also, after tinkering with the bloom I would PR something that implements https://github.com/Anuken/Mindustry-Suggestions/issues/918 later... even if you reject that I can at least make it so in my mods)

### CODE REVIEW

**Comment by sk7725** [comment]
also, the function name is renderedBloom() and not bloom() so rhino js does not go brrrrr

**Comment by Quezler** [comment]
can't you just read it directly from the config? or do mods not have access to that?

**Comment by sk7725** [comment]
> can't you just read it directly from the config? or do mods not have access to that?

config? I do not think so, since unless something is explicitly public, js mods do not have access to it(exceptions are the weird comps that lurk in gen).

**Comment by sk7725** [comment]
Correct me if I'm wrong, but do JAVA mods have access to private variables in classes?

Also please explain what is "config" that you are talking about? I have yet to see a mod that uses something remotely similar.
Also utilizing your own Bloom class is different from utilizing **the** bloom instance that the Renderer uses.

**Comment by Anuken** [comment]
Bloom should just be public, I frown upon getters.

**Pull request closed without merging**
