### PR TITLE
Healing Buildings does not run `hit(b)`

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Just watchin' Blue streaming and he mentions this.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by sk7725** [comment]
I'd rather have them not run `hit(b)`, as it can cause harm to allied blocks, such as puddles or fires

(Also I think this change makes vela light ally buildings on fire)

**Comment by Anuken** [comment]
It's not hitting `b` in the normal sense, it's healing them - it creates entirely different effects. This has **serious** consequences.

**Comment by MEEPofFaith** [comment]
> It's not hitting `b` in the normal sense, it's healing them - it creates entirely different effects. This has **serious** consequences.

However, @BlueWolf3682 has mentioned to me that hitting a building does not produce frags, have hit effects, or anything else and just poof out of existence, which is why I made this pr in the first place.

**Comment by Anuken** [comment]
> does not produce frags, have hit effects, or anything else and just poof out of existence

That's the point, it's not supposed to do any of those.

**Pull request closed without merging**
