### PR TITLE
Custom shadow offset

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Allows for customization of the turret shadow offset.

### CODE REVIEW

**Comment by joshuaptfan** [comment]
Wouldn't this lead to graphical inconsistencies if mods start putting weird values in here? With too high of an elevation, shadows become impossible to associate with their sources.

**Comment by MEEPofFaith** [comment]
Well then that's the mod creator being an idiot.

**Comment by joshuaptfan** [comment]
There are certain things that should not be moddable to maintain Mindustry's graphical style.

**Comment by MEEPofFaith** [comment]
But    **c u s t o m i s a t i o n**

**Comment by sk7725** [comment]
> There are certain things that should not be moddable to maintain Mindustry's graphical style.

Mindustry's graphical style was ***thrown out of the window*** the moment we could draw our own sprites for our mods.

**Comment by MEEPofFaith** [comment]
> > There are certain things that should not be moddable to maintain Mindustry's graphical style.
> 
> Mindustry's graphical style was _**thrown out of the window**_ the moment we could draw our own sprites for our mods.

*cough* heresy sprites *cough*

**Comment by Anuken** [comment]
Where would this actually be used?

**Comment by joshuaptfan** [comment]
I think OP intends for this to be used to make blocks look like they are levitating.

**Comment by MEEPofFaith** [comment]
> Where would this actually be used?

Just one less thing that needs scripting to do. It may or may not look bad if a modder uses this, but that's their issue.

**Comment by Anuken** [comment]
> Just one less thing that needs scripting to do. It may or may not look bad if a modder uses this, but that's their fault for putting it up too high.

That doesn't really answer my question.

**Comment by MEEPofFaith** [comment]
If a modder wants to make their turret appear to sit slightly higher they can increase the shadow offset.

**Comment by Voz-Duh** [comment]
I think this not needed
You can make custom shadow in JS script

**Comment by MEEPofFaith** [comment]
What if whoever is doing it doesn't know how to script.

**Pull request merged**
