### PR TITLE
[Aesthetic] Turret idle turning

### PR DESCRIPTION
**Pull request by MEEPofFaith**
I'm just making this so that I can get an error message from Travis. The error I have on my end seems to not do with my code.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
The mass of reverts is from me checking previous code since it did work previously. I still got the same error, so whatever it is it doesn't have to do with my code.

**Comment by Anuken** [comment]
This introduces a lot of configuration and visual noise, so no thanks.

**Comment by MEEPofFaith** [comment]
oh

**Comment by MEEPofFaith** [comment]
A closed request won't stop me from at figuring out why it doesn't work when it used to.

**Comment by MEEPofFaith** [comment]
It seems to affect all my branches since I can't compile a previously working thing anymore.

**Comment by MEEPofFaith** [comment]
and it's not a duplicate Arc this time

**Comment by MEEPofFaith** [comment]
> This introduces a lot of configuration and visual noise

what does this mean?

**Pull request closed without merging**
