### PR TITLE
Improved console commands reader

### PR DESCRIPTION
**Pull request by osp54**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

https://user-images.githubusercontent.com/76648940/183297928-a2380099-8f0d-495e-99e9-31240c15738a.mp4

### CODE REVIEW

**Comment by osp54** [comment]
**Features**
1.  Console input always on bottom. (The game logs will not interfere with the input of commands.)
2. Using the arrow keys, you can change the command, enter the previous one.

**Review by Kowkodivka — APPROVED** [review]
nya

**Comment by Phinner** [comment]
Are you sure its necessary to directly implement jline ? The fields affected by the changes can be modified by a Plugin (by overriding `logger` and `serverInput`)

**Comment by Anuken** [comment]
I will not accept PRs that add new dependencies, especially ones that use JNA.

**Comment by osp54** [comment]
Bye bye:)

**Pull request closed without merging**
