### PR TITLE
`ammoMultiplier` does nothing for `PowerTurret`s, so don't display it.

### PR DESCRIPTION
**Pull request by MEEPofFaith**

### CODE REVIEW

**Comment by QmelZ** [comment]
using a bullet with `ammoMultiplier` on a `PowerTurret` crashes the game, so this sounds pointless to me

**Comment by MEEPofFaith** [comment]
fun fact: ammoMultiplier is 2 by default
I have no idea how you are crashing.

**Comment by MEEPofFaith** [comment]
I've ctrl + f in `Turret`, `PowerTurret`, and `LaserTurret`, `ammoMultiplier` is only used in `ItemTurret`s.

**Comment by MEEPofFaith** [comment]
> using a bullet with `ammoMultiplier` on a `PowerTurret` crashes the game, so this sounds pointless to me

image

**Comment by Anuken** [comment]
This was already fixed in 7.0.

**Comment by MEEPofFaith** [comment]
h

**Pull request closed without merging**
