### PR TITLE
Created a bundle for translation to Serbian

### PR DESCRIPTION
**Pull request by AleksaDjrodjic**
Currently im at 27th Line , i will continue translating it later ...

....i wanted to continue it now .... i cant ..... i must submit it first i guess ?

### CODE REVIEW

**Comment by Anuken** [comment]
You can continue to edit it by editing the file in your branch.

[Try editing this.](https://github.com/Anuken/Mindustry/blob/81d7ed430e01b6915bbf7d3e0ddbcd9287b6ff1d/core/assets/bundles/bundle_sr.properties)

**Comment by AleksaDjrodjic** [comment]
> You can continue to edit it by editing the file in your branch.
> 
> [Try editing this.](https://github.com/Anuken/Mindustry/blob/81d7ed430e01b6915bbf7d3e0ddbcd9287b6ff1d/core/assets/bundles/bundle_sr.properties)

Yeah , i know , i did , im at the 85th line

**Comment by AleksaDjrodjic** [comment]
Sorry ,  i wasn't updating it .... i stooped playing Mindusty :/ 
I will update (and finish) it later !

**Comment by Anuken** [comment]
Alright. You can take your time; I just wanted to know if things were still active.

**Comment by AleksaDjrodjic** [comment]
Can you remove this pull request ... a lot of stuff has been getting in the way, and i havent had time to finish or even work on it :/

**Pull request closed without merging**
