### PR TITLE
Nerf overflows.

### PR DESCRIPTION
**Pull request by ritzip**
set overflow speed to be the same as titanium conveyors

### CODE REVIEW

**Comment by ZkyLB** [comment]
hamburger

**Comment by bitt0008** [comment]
why

**Comment by ritzip** [comment]
This aims to stop unhealthy "sneks" that have op throughput.
unknown

**Comment by ado1928** [comment]
oh come on ritzip

**Comment by ph3rr3t** [comment]
There was no problem before with Overflows & Sorters/Inverted.  What changed?  I only noticed this after Underflows were added.  If Over/Unders be nerfed, have it be a max of 41 items per second.  Why 41 and not 40/30/60?  Close to 4 full Titanium Belts worth of items is all I was ever able to pass through Overflow Sorter chains before we got Inverted or Underflows.  Any designs that used this mechanic before it got out of hand would still function.  I knew it was inevitable, but completely removing the mechanic altogether kills a lot of design compaction.  Just my thoughts on the matter.

**Comment by ritzip** [comment]
Screenshot_20200331-205000~2

**Comment by ph3rr3t** [comment]
The problem currently is that you can pass an infinite amount of items through a single chain right?  Input any material you want at any point, and output it at any point?
Well to keep if from being a true snek, just limit to about what it was before, that is to say, close to 50-51 items per second.

**Comment by ado1928** [comment]
No. Items are passed every frame, allowing for 60 items/s. IMO that is good enough, and can take 5 titanium conveyors

**Comment by ado1928** [comment]
Also, no the throughtput didnt change after the addition of underflows, as long as i know, it has always been 60/s

**Comment by ph3rr3t** [comment]
Serdar informed me that it wasn't until this fix that it changed:
https://github.com/Anuken/Mindustry/issues/776

**Comment by Anuken** [comment]
There is a [line in the source code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/Sorter.java#L92) that can prevent chaining if uncommented. It hasn't been implemented due to controversy.

This PR has negative side effects, so I'd rather not merge it.

**Comment by ZkyLB** [comment]
cute cat

**Comment by Anuken** [comment]
stop

**Pull request closed without merging**
