### PR TITLE
Reopen Of #4864

### PR DESCRIPTION
**Pull request by Voz-Duh**
file_1
*Textures can differ from the #4864 textures*

### CODE REVIEW

**Comment by oinkymoo** [comment]
i can't really tell what changed

**Comment by genNAowl** [comment]
A lot of old sprites have curves or lines that weren't a multiple of 45 degrees. Voz-Duh generally makes PRs fixing these style mistakes to help make the texture match the current style.

**Comment by oinkymoo** [comment]
> A lot of old sprites have curves or lines that weren't a multiple of 45 degrees. Voz-Duh generally makes PRs fixing these style mistakes to help make the texture match the current style.

ah thank you i thought it would be something in the transitions between the tile types

**Comment by Humanoid-X** [comment]
Thanks,  I now know how to make Mindustry styled sprites :-D

**Pull request merged**
