### PR TITLE
Add ALEX v6 servers to servers_v6.json

### PR DESCRIPTION
**Pull request by alexpvpmindustry**
title says it all. one pvp, one survival.
the survival server has essentials.jar plugin installed.
sooooo excited to launch this xD

### CODE REVIEW

**Comment by Slava0135** [comment]
Screenshot_20201211-184735_Chrome

**Comment by Slava0135** [comment]
One more PR and I will report it as spam

**Comment by Slava0135** [comment]
Consider making changes in this PR amd not making a mess.

**Comment by Slava0135** [comment]
> sorry... i dont intend to spam.. i thought that commits of editing is undesirable. if you want i can edit the old PR instead.
> so sorry.

I guess you can continue here. Just listen what others say.

**Review by WilloIzCitron — COMMENTED** [review]
Uh you server it's offline but server must be 24/7 (sorry it's online)

**Review by WilloIzCitron — APPROVED** [review]

**Comment by alexpvpmindustry** [comment]
> Uh you server it's offline but server must be 24/7 (sorry it's online)

im sorry if it goes offline once in a while. we are still quite new so theres not alot of admins looking over the server. Currently, its only me and my co-owner having direct access to the server. when we have more staff, we will ensure that the server is well moderated and high uptime. 
the current anti-griefer moderation is to require discord registration via the Essentials plugin from Kiaer. but in the near future, we will not require players to have discord registration. instead, we will have a "safe-mode" that can be triggered by admins if there is a griefer who is able (vpn and uuid-change) ban evade. in the "safe-mode", only discord registered players can build/deconstruct, and non-registered players would not.

**Comment by Volas171** [comment]
good server, its 24/7 most of the time and if it shuts down the most time it goes offline is like 1 hour or less

**Review by Volas171 — APPROVED** [review]

**Comment by unjown** [comment]
add this pls

**Comment by alexpvpmindustry** [comment]
thank you for adding our server into the public list!
look forward to engage more players who wanna play with their friends!
More content to come!! 👍 :D

**Pull request merged**
