### PR TITLE
[formatting] add newline to file(s)

### PR DESCRIPTION
**Pull request by Quezler**
> tries to add newlines to please the github diff, not sure if this does not break anything 😗 

Screen Shot 2020-02-04 at 10 45 45
> pull includes the script i used to achieve it, its filter could use improvements 👀

### CODE REVIEW

**Comment by Anuken** [comment]
Why?

**Comment by Quezler** [comment]
its just cleaner to end files with a newline `¯\_(ツ)_/¯`

not exactly a law, but generally seen as a good/git practice 🤔 [citation needed]

**Comment by Quezler** [comment]
> [citation needed]

- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by Quezler** [comment]
\+ git & github tend to get upset with diffs if lines do not properly end, and thus spew warnings 😗

**Comment by Arkanic** [comment]
reminds me of the time when i backslashed all of the apostrophes in `bundle.properties` to make the text highlighting to look solid

**Comment by Quezler** [comment]
did that get merged? 🙂

**Pull request merged**
