### PR TITLE
make backRegion nullable

### PR DESCRIPTION
**Pull request by DeltaNedas**
null checker broke routorio h

### CODE REVIEW

**Comment by DeltaNedas** [comment]
@Anuken

**Comment by Anuken** [comment]
This shouldn't be nullable.

> @Anuken

I get notifications for every PR and every commit anyway.

**Comment by DeltaNedas** [comment]
why did this break turrets and units in every mod then

**Comment by DeltaNedas** [comment]
actually should i just make it default to clear and be normal

**Pull request closed without merging**
