### PR TITLE
World Sensors

### PR DESCRIPTION
**Pull request by TripleToxic**
Add some sensors getters that can only access through world processor because they have high chance to become overpower in regular processor, the names are self-explanatory
``@currentAmmoType``
``@velocityX``
``@velocityY``

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x]  I have ensured that my code compiles, if applicable.
- [x]  I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by TripleToxic** [comment]
hold on, I need checks

**Comment by rd-zf-zfy** [comment]
After pulling the code, I found that it was missing the code in the mindustry/gen directory. How did you develop and test the submission?

**Comment by rd-zf-zfy** [comment]
After pulling the code, I found that it was missing the code in the mindustry/gen directory. How did you develop and test the submission?

**Comment by Anuken** [comment]
- I don't see how these are any more overpowered than existing sensors. They should not be separate, and there is no need for a WorldSensorStatement.
- Style is incorrect, space before brace.

**Comment by TripleToxic** [comment]
> * I don't see how these are any more overpowered than existing sensors. They should not be separate, and there is no need for a WorldSensorStatement.
> * Style is incorrect, space before brace.

hmm, I will review and change
close for now

**Pull request closed without merging**
