### PR TITLE
PvP server hosted in Poland

### PR DESCRIPTION
**Pull request by Dexapnow**

### CODE REVIEW

**Comment by Anuken** [comment]
image

This name is too simple and doesn't look very professional.

image

What's up with this map choice?

**Comment by Somka000** [comment]
Hi
I am the owner of this server, I played with the best players (desktopone, dexapnow) since b67 on indielm pvp, we created the beginnings of the pvp strategy (dagger rush, junction control) and we told you what is wrong with pvp and we wrote, among others that alpha/delta need a nerf.
I never lost a 1v1 fight, it was us - PH won with USMP. I hope I have proved to you that we are professional players and we are going to create a professional server pvp. So that it most resembles  indielm pvp (the best server), which is offline. I want to create a server similar to indielm pvp, where admins will teach players how to play and ban noobs. I can't watch the players play on ddns[*] and io and they are getting worse players, "ohhh rusher, admin pls ban him!!!111".
I will also try to play pvp events and tourments on mindustry.pl
I know the name "the worst pvp server" looks unprofessional, I did it on purpose, but actually the server will be very professional.
Yea, I know that there are not many maps and they are of poor quality, but tomorrow I will update them with my better maps and from indielm pvp (I got permission).
I wanted to make a pvp on mindustry 6.0 server first but server crashing by power nodes and bridge, well...

**Comment by Somka000** [comment]
I created a poll and players say this name is not cool and I changed it for he new they liked the most + I added a desc

**Comment by Anuken** [comment]
That's much better, but I would still suggest:
- shortening the description; how about *no rules; no modifiers* to keep it brief?
- adding some sort of contact method in the MOTD, e.g. `[lightgray]Hosted by @Somka#0000 on Discord`.

**Comment by Somka000** [comment]
Done

**Pull request merged**
