### PR TITLE
Discord Button In Desktop Menu

### PR DESCRIPTION
**Pull request by Voz-Duh**
I wondered why the desktop menu doesn't have such a convenient button as the Discord button? Well, here's what it led to:
image
image
in:
image

### CODE REVIEW

**Comment by Quezler** [comment]
that's where the update button for bleeding edge sits 😅

**Comment by Anuken** [comment]
image

You know, now that Mindustry has proper SVG icons, this... *thing*.. should probably be removed.

**Comment by summetdev** [comment]
I don't think that putting BE update button on top is a good idea

**Comment by Voz-Duh** [comment]
> image
> 
> You know, now that Mindustry has proper SVG icons, this... _thing_.. should probably be removed.

I can make new texture

**Comment by Voz-Duh** [comment]
But, not in the pull 😅
I just deleted the fork

**Comment by Voz-Duh** [comment]
> I don't think that putting BE update button on top is a good idea

In my opinion, this is just the right place for this

**Comment by Catchears** [comment]
And where do you suggest the update button goes?

**Comment by Voz-Duh** [comment]
She's on top now

**Pull request closed without merging**
