### PR TITLE
Merge item void and liquid void into "void".

### PR DESCRIPTION
**Pull request by Catchears**
Simple change to merge Item and Liquid Void. Here's the suggestion: 
https://github.com/Anuken/Mindustry-Suggestions/issues/351

I left it as "ItemVoid" in the code because I can't call it "Void".

### CODE REVIEW

**Comment by Anuken** [comment]
I don't see what problem this solves. Having separate voids isn't useful in most cases, but there may be times when you want a block to only accept only items or liquids, e.g. when there's limited space and you want an item void next to a liquid tank.

This would also break saves and schematics with voids in them.

**Comment by Zenith-LY** [comment]
> I don't see what problem this solves. Having separate voids isn't useful in most cases, but there may be times when you want a block to only accept only items or liquids, e.g. when there's limited space and you want an item void next to a liquid tank.
> 
> This would also break saves and schematics with voids in them.

Makes sense.

**Comment by z0mbiesrock** [comment]
Why not a sandbox-only Incinerator that doesn't rewuire power?

**Comment by Anuken** [comment]
> I don't see what problem this solves.

**Pull request closed without merging**
