### PR TITLE
Remove Team#6, confilct with neoplastic

### PR DESCRIPTION
**Pull request by way-zer**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by way-zer** [comment]
Is this bug or purposive? Two team with the same id seems bad

**Comment by Anuken** [comment]
Yeah it's a bug.

**Comment by way-zer** [comment]
Should it be added to baseTeams?
```
        if(id < 6) baseTeams[id] = this;
```

**Comment by Anuken** [comment]
No, it's for internal use only.

**Pull request closed without merging**
