### PR TITLE
Vela resprite

### PR DESCRIPTION
**Pull request by Goobrr**
A resprite of the Vela unit made to look similar to Corvus' style, as the current sprites are ~~horrendous~~ weird according to me and several other people in the discord server. 

old

new

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
*Casually yoinks Goob's screenshots out of `#modding-general`*
image1
image2
image3

**Comment by Kowkodivka** [comment]
I like it

**Comment by Darkness6030** [comment]
Oh yes

**Comment by MrDuck557** [comment]
the new files are pretty big
check the encoding efficiency?

**Comment by MrDuck557** [comment]
vela-cell
vela
vela-weapon-heat
I saved all of them in paint 3d
significant filesize decrease

**Pull request closed without merging**
