### PR TITLE
Ground Zero tutorial based on Onset tutorial

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://cdn.discordapp.com/attachments/393111111853146112/1017683611090169886/G0_Tutorial.mp4

(If you don't want to download the video, just watch it in [#mapping](https://canary.discord.com/channels/391020510269669376/393111111853146112/1017683614546280492) instead.)

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
*wh- what do you mean check failed*

**Comment by Anuken** [comment]
I'm guessing you making copper and such not auto-unlocked breaks tests.

**Comment by MEEPofFaith** [comment]
bruh

**Comment by MEEPofFaith** [comment]
Ah, I see.

The application tester uses ground zero, and it happens that where the blocks are being placed is *outside* the map border because I limit the area at the start.

**Review by RayanZ22 — APPROVED** [review]

**Comment by Anuken** [comment]
Merged manually with many changes on top.

**Pull request closed without merging**
