### PR TITLE
Team Light For Core And Units

### PR DESCRIPTION
**Pull request by Voz-Duh**
Maybe this looks a strange... But I think what this can very help in nightly PVP maps
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by joshuaptfan** [comment]
These applications of team color are getting rather random.

**Comment by sk7725** [comment]
The units do make sense since the lights&engine are team colored, which are the only things that are logically emitting light.

Idk, I expect this to be rather festive; christmas lights!

**Comment by Jammo2000** [comment]
I don't think this is a good idea. It would make the game more visually cluttered, and reduce visibility.

**Comment by MEEPofFaith** [comment]
The light color change is subtle, so I think it's fine.

**Comment by joshuaptfan** [comment]
It's not about how subtle or not it is... it's that OP seems to specialize in team color PRs that apply them in random places with no consistent style or pattern, only cramming them wherever they can possibly fit, as well thought out as a search-and-replace for `Pal.*`.

I do sympathize with the sentiment that Mindustry needs more team coloring, but it should be applied primarily to buildings and units (y'know, those specific things that _belong to a team_), not to animations, environmental effects like lighting, or random UI elements.

> Idk, I expect this to be rather festive; christmas lights!

That's exactly the wrong compliment for any PR that is not purposefully Christmas-themed; the word _garish_ comes to mind.

**Comment by sk7725** [comment]
> It's not about how subtle or not it is... it's that OP seems to specialize in team color PRs that apply them in random places with no consistent style or pattern

Id normally critisize this too, but this PR makes perfect logical sense; the only parts of a unit that actually emits light *is* the cell and engine thruster, and both are team-colored. 

If you had a light bulb that is team-colored, you'd expect the lights to be team-colored.

**Comment by joshuaptfan** [comment]
> Id normally critisize this too, but this PR makes perfect logical sense; the only parts of a unit that actually emits light _is_ the cell and engine thruster, and both are team-colored.

I understand your reasoning, but as I see it that only applies to player units. The core has a light radius, but it is not a light bulb. Its team-colored parts are not LED strips, they're just painted.

Also, it only so happens right now, with the limited team coloring in-game, that only player units and cores have team color; but I envision a day when every building has team color regions. Where does team color lighting end? At that time, should _every_ building have team color lighting? It would be very distracting.

Also, colored lighting makes it harder to distinguish blocks due to everything in the lighting area getting color shifted towards the team color.

**Comment by WilloIzCitron** [comment]
a another team can indentity of team lain with team light

**Comment by sk7725** [comment]
> > Id normally critisize this too, but this PR makes perfect logical sense; the only parts of a unit that actually emits light _is_ the cell and engine thruster, and both are team-colored.
> 
> I understand your reasoning, but as I see it that only applies to player units. The core has a light radius, but it is not a light bulb. Its team-colored parts are not LED strips, they're just painted. You can see that the colored parts have shadows just like the rest of the building.
> 
> Also, it only happens to be right now, with the limited team coloring in-game, that only player units and cores have team color; but I envision a day when every building has team color regions. Where does team color lighting end? At that time, should _every_ building have team color lighting? It would be very distracting.
> 
> Also, colored lighting makes it harder to distinguish blocks due to everything in the lit area getting color shifted towards that color.

yes, I dislike the cores too

**Comment by Voz-Duh** [comment]
> It's not about how subtle or not it is... it's that OP seems to specialize in team color PRs that apply them in random places with no consistent style or pattern, only cramming them wherever they can possibly fit, as well thought-out as a search-and-replace for `Pal.*`.
> 
> I do sympathize with the sentiment that Mindustry needs more team coloring, but it should be applied primarily to buildings and units (y'know, those specific things that _belong to a team_), not to animations, environmental effects like lighting, or random UI elements.
> 
> > Idk, I expect this to be rather festive; christmas lights!
> 
> That's exactly the wrong compliment for any PR that is not purposefully Christmas-themed; the word "garish" comes to mind.

Maybe this bad idea and I just wrote 'team.color', but I really have problems on nightly PVP maps

**Comment by Voz-Duh** [comment]
> > > Id normally critisize this too, but this PR makes perfect logical sense; the only parts of a unit that actually emits light _is_ the cell and engine thruster, and both are team-colored.
> > 
> > 
> > I understand your reasoning, but as I see it that only applies to player units. The core has a light radius, but it is not a light bulb. Its team-colored parts are not LED strips, they're just painted. You can see that the colored parts have shadows just like the rest of the building.
> > Also, it only happens to be right now, with the limited team coloring in-game, that only player units and cores have team color; but I envision a day when every building has team color regions. Where does team color lighting end? At that time, should _every_ building have team color lighting? It would be very distracting.
> > Also, colored lighting makes it harder to distinguish blocks due to everything in the lit area getting color shifted towards that color.
> 
> yes, I dislike the cores too

Yes... For cores it looks bad and not logical, probably I did it because I was sleepy

**Comment by bvcbvc** [comment]
i think that its quite fine, but blocks should not emit team colored light

**Comment by catatagun** [comment]
When is the anuker gonna answer this

**Comment by bvcbvc** [comment]
> When is the anuker gonna answer this

he dont replay to these anymore, nor does he close incorrectly formatted ones, he dont have the time nor energy, you will know if he adds it, as you will see ingame

**Comment by MEEPofFaith** [comment]
~~Why core emit light in the first place?~~

**Comment by bvcbvc** [comment]
~~maybe the center is just a really strong light~~

**Comment by bvcbvc** [comment]
> ~Why core emit light in the first place?~

~maybe the team color is some sick leds~

**Comment by MEEPofFaith** [comment]
why was this closed ;-;

**Comment by WilloIzCitron** [comment]
explain about this closed

**Comment by bvcbvc** [comment]
> explain about this closed

idfk, i doubt voz is looking at this tho

**Pull request closed without merging**
