### PR TITLE
Add real name of creator

### PR DESCRIPTION
**Pull request by Bohaska**
I'm not very sure if Anuke wants this but I think it should be added

### CODE REVIEW

**Comment by Bohaska** [comment]
i probably need to learn some more github

**Comment by joshuaptfan** [comment]
If he wanted this, he would have done it himself.

**Comment by unjown** [comment]
btw where did you get his real name?

**Comment by joshuaptfan** [comment]
> btw where did you get his real name?

Let's not have this discussion. It would be cyberstalking.

**Comment by genNAowl** [comment]
Anuken's real name has remained unknown for me and probably 90% of the community.

Why would you give it out in a PR?

Like Joshuaptfan said, giving personal information is a decision made by the person, not you, or anybody on the internet.

**Comment by Bohaska** [comment]
Sorry, I was afk, didn't see these comments

**Comment by Bohaska** [comment]
how do you delete a pull request, wipe it out from existence and make sure no one ever sees this again?

**Comment by Quezler** [comment]
only anuke can delete the pull if he so chooses, but you'll have to delete your own branch yourself

**Comment by Bohaska** [comment]
I already deleted the branch, thankfully

**Comment by nichrosia** [comment]
> btw where did you get his real name?

It's literally on his own website. It would hardly be qualified as cyberstalking

**Comment by liuxilu** [comment]
It's a "cyber" "talking" lol

**Comment by Anuken** [comment]
My real name is only listed in places where it is absolutely required, or related to my professional resume/portfolio.

Adding it in a public PR without even asking first is a baffling move, especially considering that I would have been perfectly capable of adding it myself if that was ever necessary. Respect my privacy, thanks.

**Pull request closed without merging**
