### PR TITLE
[QoL] Add Unit Factories to the Common Block Group.

### PR DESCRIPTION
**Pull request by summetdev**
Closes Anuken/Mindustry-Suggestions#1017. (see more info in issue)

Yet another QoL feature.

Preview:
preview

### CODE REVIEW

**Comment by summetdev** [comment]
Closes Anuken/Mindustry-Suggestions#1016 too, it's the same.

**Comment by Anuken** [comment]
That group should include reconstructors.

**Comment by summetdev** [comment]
> That group should include reconstructors.

Would it be better to add group to `UnitBlock`?

**Comment by Anuken** [comment]
Probably.

**Pull request merged**
