### PR TITLE
Test cases for previous code smells fix

### PR DESCRIPTION
**Pull request by hmgtech**
These are the test cases added for the pull-request #9313 where I have refactored the code.

I know, according to the contributing guidelines, "Small changes that 'clean up' or 'test' code without increasing performance, removing code or adding features are not helpful towards project bug fixes".
But, as a professional, I am adding test cases to my previous code which might be useful in the future.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

Thank you.

### CODE REVIEW

**Comment by eeve-lyn** [comment]
oh my god

**Comment by JasonP01** [comment]
I think bros grade depends on you merging it 💀

**Comment by Anuken** [comment]
You sure you're not a robot? Adding unhelpful test cases to unhelpful code doesn't make it any more helpful. You can't just say you've "read the contribution guidelines" and then fail to actually follow them.

**Comment by hmgtech** [comment]
@eeve-lyn I am trying to understand this complex yet great project. Hopefully, one day, I will find and fix a bug
@JasonP01 It's okay, if it is not merged 
@Anuken No bro, I am not a robot. I have read your contributing guidelines, and I think it is the first step that every person will do before contributing. It's just a bit of refactoring to follow standard principles. I will avoid such merge requests 👍 Thank you for the comment 😃

**Comment by Anuken** [comment]
> I have read your contributing guidelines, and I think it is the first step that every person will do before contributing.

Okay, but:

- You create unnecessary methods by splitting up code, which you are explicitly told not to do.
- You do not follow the formatting standard at all.
- You do not use wildcard imports.

Why do you say that you have read the guidelines **if you are not following them?**

**Pull request closed without merging**
