### PR TITLE
More random unit effects

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Before:

https://user-images.githubusercontent.com/54301439/118756728-68b3a500-b820-11eb-922f-7c794a9cba61.mp4

https://user-images.githubusercontent.com/54301439/118757688-6f431c00-b822-11eb-93a1-0bbfb33b7618.mp4

---

After:

https://user-images.githubusercontent.com/54301439/118756739-6cdfc280-b820-11eb-9e79-a52c9910cd7d.mp4

https://user-images.githubusercontent.com/54301439/118757702-7407d000-b822-11eb-9955-b24731fd43c6.mp4

### CODE REVIEW

**Comment by BlueWolf3682** [comment]
What about status effects? they also only show in a circle.

**Comment by BlueWolf3682** [comment]
Nice.

**Comment by MEEPofFaith** [comment]
~~And this is the part where Anuke says "Already in 7.0"~~

**Comment by BlueWolf3682** [comment]
~~it actually looks a lot better than i thought it would lmao~~

**Pull request merged**
