### PR TITLE
Fix Tetrative Reconstructor's sprite odd 1-pixel error

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
It just enraged me every time.

### CODE REVIEW

**Review by Quezler — APPROVED** [review]

**Comment by Anuken** [comment]
What's the difference?

**Comment by Quezler** [comment]
the top left "circle" is moved down in its entity by one pixel it seems

**Comment by ThePythonGuy3** [comment]
i marked the thing with this image https://media.discordapp.net/attachments/656612099128164362/833013239347806218/unknown.png

**Comment by ThePythonGuy3** [comment]
apparently the whole circle was off

**Pull request merged**
