### PR TITLE
allow units to mine coal and sand

### PR DESCRIPTION
**Pull request by bend-n**
- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

https://github.com/Anuken/Mindustry/assets/70787919/0742ff4c-b17e-4f2a-89be-65e828cc8773

<sup>sorry, i had to significantly compress the video to upload it to github</sup>

### CODE REVIEW

**Comment by Mythril382** [comment]
...You can just put coal and sand in `mineItems`...

```
mineItems: [
    coal
    sand
]

**Comment by Anuken** [comment]
This should not be in vanilla.

**Comment by bend-n** [comment]
Any reasoning? You just want people to have to use mining logic instead of allowing units to natively mine sand and coal? Why?

**Comment by ApsZoldat** [comment]
I think new players who don't understand why do you even need coal/sand in your core will come to Mindustry-Suggestions and... yeah

**Comment by Anuken** [comment]
Coal and sand aren't building materials, mining them is a waste of time unless you have a special setup for that.

Funneling crafting resources into your core to extract them later is a degenerate building strategy.

**Comment by bend-n** [comment]
Okay, so im guessing I cant add beryllium either?

**Comment by Anuken** [comment]
No, AI mining wall ores isn't tested or supported anyway.

**Comment by bend-n** [comment]
tested or supported sure-- but on a fundamental level, are you opposed to ai mining walls?

**Comment by MEEPofFaith** [comment]
Or, just, you know, add it on units where its intended to. That Seq is only the defaults, so just because an item isn't in there doesnt mean it can't mine it.
And besides, there are no monos on Erekir anyway.

**Comment by bend-n** [comment]
okay, so like, i know we deny the existence of mixtech here, but, you know, mixtech

**Comment by MEEPofFaith** [comment]
Your soul Hand it over

**Pull request closed without merging**
