### PR TITLE
check if Votekick's voteRequired has been reached every vote

### PR DESCRIPTION
**Pull request by blackassasin1234**
As the title implies, this PR makes it so that it doesn't check if the votes are more than required only when the timer has ran out, but also when someone votes.

### CODE REVIEW

**Comment by XEN0PHIL** [comment]
Votekick should NOT kick as soon as it reaches 3/3 because there might be people who want to vote against the kick.

**Comment by DeltaNedas** [comment]
this
no, closed permanently

**Comment by Anuken** [comment]
I'm going to use my own implementation.

**Comment by Quezler** [comment]
what do you roughly have in mind?

**Comment by Anuken** [comment]
basically the same thing, but with some more testing

**Pull request closed without merging**
