### PR TITLE
Ignore Control Weapons

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Allows weapons to ignore mass control, such as `singleTarget = true`, commander control, or player control.
[Video](https://youtu.be/HKTzDHnVBgQ)

### CODE REVIEW

**Comment by Violet-Scarelli** [comment]
Time to add point defense to the Oct

**Comment by MEEPofFaith** [comment]
> Time to add point defense to the Oct

ohyes

**Comment by Anuken** [comment]
Interesting idea, but has the same problem as #4281: the code isn't great; weapon overrides would be preferable.

**Comment by MEEPofFaith** [comment]
Yea it's a bit too much duplicated code.

**Pull request closed without merging**
