### PR TITLE
Add a keyPress operation to the Jump logic statement

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
Pretty self-explanatory. Jumps if the <value> index key (KeyCode indexes) is pressed.

Test Schematic:
> bXNjaAF4nGPgYOBhZGDJS8xNZWApSS0uYWbgSc4vStXNK03OSS0tZuDPzUwuytctKMpPTi0uzi9i4M3JT89M1k3JLC7ISaxkYGBgZmBgAkIGRiCbmw9IZFfMSU5JSJgxKWhKxLoJcybPiliSkJK1KoFBtXECt8rUacFRcxZOmBQZM2FyROaJqaGzohckLJowN0oyYEpUzJxZixJS1iWkMAqaB3jo6vieCTQIMXhyyOBaQ8NCN49Zje+SUh40nDTe8Pc/M8OUWiNJoMVsDOwMDACu0UTf

The display goes red when you press the 0 key (not the numpad one)

### CODE REVIEW

**Comment by Anuken** [comment]
This doesn't make any sense on a headless server or in multiplayer. Use in-game buttons for input.

**Comment by ThePythonGuy3** [comment]
Imo this would be very useful if its limited to singleplayer, and i think a lot of people agree with me.

**Comment by Legomonster33** [comment]
this seems unnecessary and relatively useless, if you need inputs from anywhere you can set up a network of switches (or some other form of input).

**Comment by Anuken** [comment]
Everything in the logic system either uses built-in variables or gets state from the world it's in. Key presses have nothing to do with the world, they're client-side events that the logic system should have no way of knowing. *Logic is not scripting.*

**Comment by DeltaNedas** [comment]
if you only want to use it in singleplayer, make it a dedicated inputs block (or leave as instruction) in its own mod

**Pull request closed without merging**
