### PR TITLE
Added myself to the contributor list (Spanish translator)

### PR DESCRIPTION
**Pull request by Angel-24**

### CODE REVIEW

**Comment by Anuken** [comment]
Why not have this as part of the spanish PR?

**Comment by Angel-24** [comment]
> > Why not have this as part of the spanish PR?
> 
> 



> > Why not have this as part of the spanish PR?
> 
> Sorry, what's a "PR"? 🙁 Does it mean Pull Request? Yes, I think it is.

So, I should upload this file alongside the translation bundle. Is this the correct way to do it?

**Comment by Anuken** [comment]
Yes.

**Comment by Angel-24** [comment]
> Yes.

Ok

**Comment by Angel-24** [comment]
Thanks, and sorry for the inconvenience. 😅

**Pull request closed without merging**
