### PR TITLE
Unit Factory And Reconstructor Team Indicator

### PR DESCRIPTION
**Pull request by Voz-Duh**
image
Idk why my other branch that in I saved this pull was deleted .__ .
But, Anuken say:
> Why close this?

### CODE REVIEW

**Comment by DeltaNedas** [comment]
good

**Comment by Slava0135** [comment]
I like it but it looks weird with those orange indicators on units...

**Comment by joshuaptfan** [comment]
Not in favor of team coloring the build animation. Sides of the building are fine.

**Comment by Voz-Duh** [comment]
@joshuaptfan if you want I can delete it

**Comment by Voz-Duh** [comment]
> I like it but it looks weird with those orange indicators on units...

Hm...... Maybe, I can do it

**Comment by Slava0135** [comment]
> > I like it but it looks weird with those orange indicators on units...
> 
> Hm...... Maybe, I can do it

I guess the most reasonable option is to make factories themselves being colored and nothing else.

**Pull request closed without merging**
