### PR TITLE
Add mindustry.tk (UPDATED)

### PR DESCRIPTION
**Pull request by ZacBytes**
.tk is now hosted on Microsoft Azure and is now one of the best performing servers. There is a new staff mod team that is dedicated and can moderate the server well. .tk also has an active community server. Please consider adding it.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
why did you need 2 commits
also windows vm bad

**Comment by DeltaNedas** [comment]
h h

**Comment by egg-chad** [comment]
egg NOT approve

**Comment by iczero** [comment]
well-known griefer

**Comment by ado1928** [comment]
Well now we definitely know the almighty cat wont add it, because you literally attempted to ruin mindustry.io's business, thinking you could just get away with it

**Comment by KSean222** [comment]
Ditto, you weren't exactly known for being all that nice before either

**Comment by ZacBytes** [comment]
@Delta

First commit made a typo lol
Also, whether i run out of money or not is not your problem so

**Comment by ZacBytes** [comment]
I fixed the first commit where I changed 3000 to 2000 like 6 minutes after i realised smh people 🤦‍♂️

**Comment by iczero** [comment]
why'd you touch it in the first place

**Comment by ZacBytes** [comment]
> why'd you touch it in the first place

because i copy pasted the top part but didn't see 3000

**Comment by Kieaer** [comment]
It's operated by the griefer owner.

**Comment by ZacBytes** [comment]
> It's operated by the griefer owner.

what accusations

**Comment by DeltaNedas** [comment]
iczero says youre a griefer and hes a lot more reliable than someone who buys a pi without knowing what to do with it (which is most people sorry lol) ...

**Comment by iczero** [comment]
it's not that you *might* be a griefer, it's that you've griefed so much that almost everyone who runs a mindustry server knows that you're a griefer

**Comment by KSean222** [comment]
not entirely related, but:
Moments after I accidentally sent him an invite to a server:
ZacBytes trying to ping everyone
He immediately tries to ping everyone.
Needless to say he doesn't feel like a very nice person.

**Comment by iczero** [comment]
image
also a member of fire o7

**Comment by ZacBytes** [comment]
S̷̢̨̧̢̢̢̡̢̡̢̨̡̨̢̡̛̛̛̛̛̛̛̛̰̝̞͖̼̻̯̘͍̞̺͇̼͓͉͇͇͔̦̮͈̻̼̦̠̰̺̣̲̹̪̬̮͓̻̺̦̙͇̞̜̪̹̖̯͍̗̳̰̻̤͈̩͍̤̣̙̠͖̞͍͚̘̜̼͈̻̞̼̜̻̜̖͓̬̼͈̼͖̗̰̳͇̺̯̺͕͖͔̯̤̭̭̣̘̯̲͇̅̄̍̏͑̌͋̏̈́͗͋̂̈̆́̾͋̉̐̓̔̑͒̊͛̓̀́́̽͛̿͌̍̋̐͌͗͂̓̔̃̋̓́͐̓̑̿̋͆̉̑̽̒̔͐͛̂̔͑̄̿̾͊͌̽̿̈́̏̈́̊̎̒̂̅́͌͗̓͐͊̈́͋̍̈́̓͒͋̉̊͒̋̅͋̀̄̃̔̆̂͆̑͆̿͌̆́̀̊́̈́́̑̊͒̾̀̅̔̃̿̈́͑̒̓̐͌̉̔̾́̏͌̓̈́̔͊͛̃̈͋̃̉̅̇͂̽̿̈́̾̀̏̽͂́̄̎̒̏́̐̈̐͂̎͆͊̃̾͛̔̓̆̾̒̊̓͛̍̂͊̂͛̌̍̓̇͒̀͐̑̄͌͒̆̄̿̓͐͒̿̍̉̍̈́̈́̈́̑͂̆̈́̑̆̌̂̍͗̐̾́̾̏͊͊́͋̏͆́̈́̏͒̔̇̓͒́͋͐̑̆͐̾̀̋̚͘̚̚̕̕͘̕͘͘̕̚̚̕͘̕͘͜͜͜͜͝͝͠͝͠͝͝͝͝͝͝͠͠͝͠͝͠͝͠͝͝͝͠͠͠ͅͅͅͅh̷̛̛̛̛̛̛̬̘̱̲͚̓̑́͐̏̈̈́́͋̓̉̔́͋̌̆̓̈̀̄̍͋̈́͛̇̐̿̀̒͊̈́̅͒̏̂̈́̊̒͑̈̈́̋̃̈̓̈́̆̒̆̉̏͆̈́̑͐̂̈́͑͒̓̃͑̿͗̀̊̆͛͗͑̒̏̓́́̏̌̏̎̊͌́̍͒̐̓̒̇̾̒̓̈́̌̃͂̓̎̈́̂̇̍̀̌͂̏̃͛̃̑̕̕̕͘͘̚̚͝͝͠͝͝ͅư̶̢̢̨̨̢̧̨̡̨̧̛̛̛͉̼̰̬̻̳̩̩̫̯͚̖͔̙̣͔̰̗̦͈̩͚̰͈̖̱͍͓̭̳̤̝̞̱̺͈͍̹͖̞͖̞̳̝͎̥̰̹̠͇͍͙̳̘͖̣̻͖͚̱̦͙̰͍̯͈̮͇͕̝̩̣̲͖̫̟͖͔̤̯̰̹̝̪̌̀̌̐͌̿̎̊͒͑̈́̈́͗͑̉̌̓͐̎͂̋̒̌̃͗̂͐̄̊̓̾̍̈́̀̾̍͆́͗̏̾̾̏͗̐̂̽̽̋͗̑͊͊̌̿̆̍͂͊̊̒͆͗̂̇̈̆̒̈́͂̉̓͑̄̋̉́̔̀̏̌̿̈́̽͊͆̀͌̑̎͐͌͌̋̌̔͐̾̓̈͐͗͒̉̀̑̃͂̄͊́̆̃̋̔͒̔̆̾̈́̀̽͌͂̔̐͂̍͌̌́̈̈́̈́͆̀͐͋̀̄̿̃͑̂̂̑̓́́̓͌̇́̔̀́̄̈̀̓͛͋̏̓̓̔̈́̓̐̑̈́̍͌̑̿͆͐͛̇͋̂̆̀̔͛̈́̊̏̅̒̿̆̓͒͛̓̚̚̚̕͘͘̚̕͘͘͜͜͜͠͝͝͝͝͠͝͝͝͠͠͝͝͝ͅͅţ̵̡̢̧̨̡̢̡̱̯̝̥̱̼̳̣̼͇̫̘̬͖̼͕̹̟̻̗̠̜̱͙̼̩̗̯̝̫̞̝͖̳̻̦̺͍̹̹̲̘̯̩̼͓̣̱̱͙̘̟̘̱̭͖̤̤̰̝͕̲̪͍͙͎̝̪̟̺̲͚̹͍̺̣̦̳͙͖̻̣͓̣̦̮̼̯̣̝̙̩͔̻̩̺͆̀̑͋͛̎̇̽͊̽͋͊̃̿͑̀̽̾̀̋͂̓̄̃͊͛̚͜͠͝ͅ ̸̧̧̡̡̧̡̧̧̨̨̡̜͔͙͇̻̝͇͚̤̫̟̫̬̝̬̜̩̙̳̗͉̺͚͚̹̳̤͙̯͚̰̻̜̖̲͖̗͙͉̪̠̙̹̹̣͙̩̠͉̱͍͉̰̠̬͙̬̜̹̻̫̥̙̫͚̩͚̤̤̜͉̦̞̫̠̙̥̤̟̹̠̪̼̲͚͔̲̦̬̭̘͖͎̗̙̫̠̩̞̜͍̤̬͙̞̥̙̲͇̯̞̠̪͇̞͕̻̘̻̮̙̯͚̺͉̗͎̭̤͚͔̣͈̗̠͔̘͕͋͆͆̎̄́͌̏̿͐̔̅̉͌͒̉̉̀̐̈͑͒̄̔̔̌͆̓͘̕͜͜͜͜͜ͅͅͅų̵̢̨̢̡̡̡̨̨̧̨̨̨̧̢̡̢̨̨̨̢̢̡̢̡̧̨̨̡̡̢̡̡̧͎̲̖͇̥̠̮͚͔̥͖̼͎̠͉̩̺̙̙̹̟̲̳̩͍͈͈̖̼̬͖̗̤̹̖̻̜̞̮͎̪̱̗͎͈̗͉̮̺̩̰̥̰͇̠̟̟̩̹̬͕̦͇͓̬̠̱̺̣͙̺̯̯͉̥͉̰̭͖̹͙̺̠͓͚͉̩͙̙̻̘̝͍͇̳̱̲̺̟̻̺͓̝̬̝̦̲̦͓̰̖̳̘̲͔̲͎̹͎̟̙͖̥̙͍̹̭̖̮̫͓̘͔̻̯͙̬̫͎̯̠̪̝̥̬̜͚͖̦̳̠̱̞̪̯̼̤̺̫͍͕͉͈̗̥͔̭̱̺͈̣̱̗͔̝͙̝̟͈̲̫̘͔͖̭̖̭͓͓̘̦̙͇̼̪̣̟̼̯̺̗̱͖͇̝͎̱̹̞̳͎̼̦͚̗̘̹̘̖̺͔̼̯̺̞͍͍͈̣̭̠̲̠̪̭̤͔͍̙̟̠͎̲͙̟̮̲̻͎̣̬̤̖̜̂̓͐̋̾̀̎͐́͒̅̂̿̍̊̃̀̇́̉͛͌̐̾̀͗́͋͑͑͌͐̎̽͂̆̑̄͋̌̇̍͑̈͗̄̒̐͆̽̎̄̈̆̓̈́̇̈́̈̆̂̀̅̎̎̈́͂̋̌̑͑͑͒̒͗̌̅̄̎̏͐̔͐̾̕̕̚͘͘̕̚͜͜͜͜͜͜͝͝͝ͅͅͅp̵̨̧̨̢̡̡̧̢̛̛̛̞̙̹͉̳̙̠̲̳̯̞͕̺̪̘̝̪̗̪̹̤͙̭̙̮̫̻͍͓̫̥̘̹̰̫͔̙̘͉̗̝̱̜͉̺̺̮̩̦͚̞̖̙̠͎͎̞̗̲͚͚͔͕̫̻̼͈͔̖̙̮̺̺̪̰̩̠̬̠͚͎̳͍͉̦̣͖̆͊̈́͗̾̏̿̐̀̏̅͌̊͊͆̀̓̓̓̔̈̐̂̀̃́͆̈́͛͗̇̂͛͑͛̋̎͂́̋̏̓̄̀̈́̋̓̽͊͆͆̽̏̌̒̓̐̌́̏̃̂̀̅̾͛̊̽́͛̃͆̀̌̽̾̇͗͊͛͆̆͑̓̕͘̚̚͘̚̕͜͜͜͜͜͝͝͠͠͠͝͠͝͝͠ͅͅ ̵̡̢̧̡̧̢̨̨̢̨̡̨̢̨̧̡̧̨̛̛̛̘̖̩̻̗͚͓̰̙̮̣̰͕̝̞̯̥̙̮͔̜͕̤̠̭͎̝̘̹̺̘̜̗̰̮͇͔͚̮̝̩͓̫̻̬̱̼̜̼̩̣̝̖͖̦̯͖̗̩͍͓̣͍͇̟̮̰̼̞̯̘̣͍͈̦̼͚͎̱̙̻̠͍̺̖̻̦̪̜̦͔̰̱̝͙͎̳̺̤̝̥̮̠͙̦͚̜̲̞̳̠̰̮̱̻̪̲͔̜̟͕̘͎̠͎̤͎̠͈̫̙͇̝̪̺͓̮̫̤̟͔͉̣͖͕̦̺͎̦͈̩̼̗̘̜̱̩͎̖̣͎̩̦̼̯̙͚̩̳̬̘̖̘͚̜̩̩͚̱̈́̈́̊̈̀̉̅̀̐̍͋̏͛̃̏̀̐̆̌̈́̌̑̂͊̆̆̅̌̉̃̀̄̅̈́̂͗́̑͌̆̇̆̈́̇̊́̈́͊̐̓̔̑̃́̒̉̅͛̍͂͗͌͒̍͊͌͂̌̈́̚͘̕̕͘͜͜͜͜͜͜͜͝͝͠͝ͅͅͅͅs̸̢̢̨̨̨̨̡̧̧̧̡̨̢̢̡̨̧̢̨̧̧̢̛̛̛̭̮̜̩̘̺̙̤͕͍̹͇̣̞͈̖̝͍̟̭̬͍̩̦̭̝̩͔̪͇͇̙͕̖͔̥̠̠͓͇͓̗̝͚͖̟̙̖̬̞̱͉̳̘̰̮̱̼̼̝̤̰͓̩̼̘̦̰͍̙͍͙̖̩̩̝̝̹̙͕͎̫̱͈̫̦̼͙̟̣̻̱̗̯͉̻̬͎̲̺̦̮͇̝̥͎͎͚̥̳̝̼̥̮̟̱̯̼̼̦̻͖͕͕̮̺̯͖̮͖̠̯͔̘̲͚̠͚̱̦̩̤̳͕͖̻̮̥̖͓̭̥̬̦͖͙͈̠̠̗̫͓͇̭̭̝̟̰̱͙̗̤͈̘̳̗̳͎͖͕̰̖̗͕̲̅̈́̇͛͆̄̒̀̃̈́̈́̍͒̋̆̇͑̉̿̓̇̊̋͛́̊̿̿̒̈́̑̊́̀͌́̍̿̽̂̆͛͑̑͌̿̏̃́̈́͋̈́͗̀̓̿́̔͌̒̑̽̏͊̅͌͆͛̑̃͊͐̾̍̀͆̓̅̌͆̉͛́́̈́̕͘͘͘̕͘͘̚͜͜͜͠͝͝͝͝͝͠͝͝͝ͅͅͅͅͅͅͅţ̴̨̡̢̨̨̧͚̮͍̯͎̱̙̻̠̘̪̝̟̖̻̗̦̘̱͎̰̰̘̬̭͙̝͓̰̰̩̠̘͓̺̯̭̥͓̩̺̣͕̺̻̝̥̹̠͚̥̯͙͍̱͍͕̤̥͉͔̩̟̝͙͚̓̍͜͠ͅờ̷̡̨̧̢̛̛̛̛̲̖̹͙̠͖̺̥̫̖̩̫̲̻̣͉͚̭̱̲͓͈̠̖̱̻̯͔̟̻̣̦̠̻̇́͐̑̒̂̓̈͂̏͐̾͊̅̇͋̉̋͑̾͂̏̌͋̓̂͊̎͋̈͋̌̑̀̍̈́̃͐͊̆̄̊̉̈́̓̍̊̌̊̄̋̏͒̾̂̋̔͗͒̊̑̉͒̓͛̀̌̿͐̄͂̑́͆̽͊̎̊̐̋́̂͆̓̃́͋̓͐͒͋̏̊̇̾̀͌̈́̊͆͋͌͆̉͌̀̊̂̅̌̇̕͘̕̚͝͠͝͝͠͝p̵̢̢̡̡̧̧̢̡̧̢̧̨̧̡̡̢̡̩̲͍̦̪̠̣͇̰͚̘̹̗͈͚͚̪͚̻͚̝͔͉̼̻̖͍͚̜̗̗̺̙̦̥͓͔͚̝̩̱̻͔̦̦͓̝͖͙͚͖͚̗̭̟̙͈͎̯̬̯̣̫̦̱͉̬͚̗̭̜͍̭̯̮̬͕̝͖̞͈̥͈̯̘͚̫͙͓͔̰̰̦̥̫̻̬̬̱̩̰͖̟͚̼̺̘̗̹͈͖̙̘̬̘̘̣̦̬̫̮͚͙̠̩͕̲͓͚̙̠͕̰̙̹͕̠͙̪̪̩̞̠̜̜̳͓̬͈̝̮̘̹̱̰̓̂̈̆͋̿͋͂̅̑͌̈̄̒̄̍͛́̈́̑̇̓̈́̃̾̈̋̍͂̈́̊͘̕͜͜͜͜͜͜͠͝ͅͅͅͅ ̷̢̡̡̧̧̡̡̧̢̢̛̻̝̜̭̤̦̱̩̹̟͚̭͖̻̖̪̼̥͖̼͎̰͇͔͍̥̳̭͍̩̜̫̹̞̠̬̠̟͔̣͓̤̣̤͔̺͔͉̗͓͕̫̗̠̓͆̒̍͊̓̀̋̈́̿̓̏̃̌̎̏̄̔͂͛͛̌̋͌́̽͛̋̓̅̊̈́̔̆̅̈́͊̿͒̾͘̚̚͜͠͝͝͝b̸̧̧̨̢̧̧̨̧̧̢̢̢̢̨̨̧̛̛̛̛̛̛͔̻͓̟̪̗̘̱̟̹̱͍̳̫̗̪͙̳͓̙̩͉̬̳̬̘̰͎̼͔̙̣̣̦̤̦͓̳̭̮͖̟̠̲̘̤̯̲̫̱̝̯̖͉͚̯̠̘̯̬̼̟͓̼̝̞͙̭̯̮̮̗͔̺̲̫̱̙̯͈͍̘̭͎̯͙̹͍̼̝͕͚̺̱̻̪͉͙̭̠͇̯̻̯̥͇̦̥̤̳̦͍̲̞̘̘̱̻̩̠̞̺̬̙͈̫̳͈̭̯̪͍͇̺͔̟̟̦̞̙͙͓̝̤̙̗̩͎̪̲̳̫̲̫͈̜͔͖̥̻̭͎̳̫͙̥̪̜͙̘̣̳̮͖͚̻͎̞̥͉͇̞͍̩̻̏͋̓͌̎̅̾̈́̓̉͗͆̑̎̿͂̇̈́̊̈́̎̂̿̐̈́̈̿̈́͗̏̾̿̎̀̎͑̊͊̈́̓́͊̅̓̃̎̋͒̉̌͒̽̏̌̔̈́̂̑̎́͗͛͋̽͗̂̉̿̊̉̀͌̂̆̅͆̏̀̓̋͌͗̿̊͐̀͂̍͗͆̐͗͗̈́̌̆͑͗̅̓̎̎̇̒́̀͌̄̈͊͒̋̍̽̆́̃͗͐̏͋͗̓̓́̊̌̃̏̂͆̍́̔͋͑̌͌̾̀̍̄͂̇̀̅̓͒̌͑́͂͒̒͛̊̍̊̊̈́̎̓͆͌́͗͂̋͛̐͑͛͒͌̈́͌͐͊̅͛͒̄͌͆́̔̅̔̎̾̈́͑̐̓͌́̈̇̈́̿̕͘̕̕̚̕͘͘͘͘̚͘̕̕̕͘͘̚̕̚͘͘͘͜͜͠͝͠͝͝͝͝͝͝͠͠͠͝͝͝͠͝͝͠͝͝͝͝͝͠ͅͅu̸̡̢̢̡̧̡̡̡̢̢̡̡̧̡̨̢̢̡̨̨̧̧̢̨̡̧͚̞̻̗̭̼͓̘̠͔͇͓̭͓̟̖̖̥̥̻̖̘̳̤͖̫̝̪̪̻̤̹͍̘̲͖̼̥͉͔͉̫͔͖̖͓̘͕̜͇̬̦͚̲̖̩̲̞̟͉̮̪͈̜͖͙̬͓̯̗̫̳͙͕͔͔̤̯̥̥̥̩̩̖̳͔͔͍̩͓̹͙͔̳̹̦̘̱̠̣͉̠͕̰̙̟̰̤̘̳͖͓̞̤̯̹̬̳̠̭͙͔̣͎̹̼̮̳͍̺̭̲̤̱̪̩̣͍̮͚̦̠̤͕̟̻̥̼̼͍̫̥̻̬̘̻͈̣̹͈͕͎͇͖͖͇̠͈͖̘͕̰̙͔̹̭͖̫̳͕̦͉̞̯͕̯͕̠̭̣̮͎̹̘̳̩̺̦̩̭̤͍͎̳̥͎͕͚̯̦̗͙̞͇͚͈̳̣̣̬̖͉̣̯͚͍͌̓̐̀͒͐͐͑̍̑̍̿̋̀̔͐̄̊͗̇̐̑̏̈́̔̋̓̉͒̐̐͆̇̐͆̽́͒̎͗̋͑͐̒͒̓̀͛͛̏̑͊̂͆̓͛̚͘͜͜͜͜͜͜͜͜͜͜͠͠͠͝͝͠͠ͅͅļ̸̢̢̧̧̧̢̨̢̡̨̡̨̨̡̧̛̛̛̛̛̛̩̮̲͕̯̝̜̫̰̳̬͇͍̲̣̯̞̬͓̯̟͕̤͙̥͔̮̳̠̺̺̣̪͉͍̠̯̪̜͓͙͍̗̯͕̻̗̩̠̞̤̗̥̜̟̫͕̭͔̠̪͔̗̭̻̹͍̬̲͓͕͇̫̳̰͎͇̰̤̰̗̭̤̜̥͕̲̱͎̝̬̯͔̤̩̲͎̗͔̲̮̣̗͔̭̮̩̺̳̠͓̞̯͕̬̰̭͇̰͚̦͓͉͉͉͕̩͓͓̬̖͉̻̭̬̫̰̗̜̈́͛̈́̍̈̍́͋̑̈̇̄̋̏̏̌̅̆͂̾̀̔̅̂̆̃̎̃̄̀̐̉̓̊̓̇̇̇̀͗̃̌͒͐̾̆̔̉͋̇̓̊̿̓̐̏̔͗͛̉̃̆̈́̂͋̉̓̎̊̄̽͆̂̔̍͒́̿̽̈̑̆͊̾̈̐̎̓̀̉͋͒̈́̎̇́̿̃͊̽̃̒̂̽́̍͑̂̊̎̈́́̇̏́̈́̾̔̊̀̈́̅͐͋͆̽͐̓̾̓̽̕͘̚͘̚̕͘̚͘͜͝͝͝͝͝͠͝͠͝͝͠ͅͅl̴̡̨̨̢̡̨̛̛̛̛̝̝̞͓̦͎̼̙̺̱̠̤͕̻͇͚̹̥̮̣̯̬̖̼̼͕̺̰̠͕̦̮̣̲̯̼͈̺͔̥̙͍͈̪̙̹̦̖̼̮͍̝̞̥͇̼̲̙̰̦͇͇̳̟͍̖̝̺͓͈͚̹̫͇̲̥̰̻̬̫̬̮͙̜̳̩̬̻͖̻̩̞̝̗̄́̄̾͐̐̉̽͐̍̃̉͒͑́̆̽̉͋͂̃͒̓̋͛̆̑͂̊̂̇͑̿̅̀́̑͌͐͆̎͌͊̇̈́̅͛̊̄͐̀̃͊̈́̈́̏̓̊̾̐̑̃̀͒̉̆̈́̀̈̆̈́̑̀͐͗̿̄͊́̔̊͆̾̈́̏̃̏̒̆́̈̍͌̈́͂̌̍̇̈̿̇́̈͐̅̒̓̇́̏̇̊̌͗͗̋̈̐͌͊̍͐̈́͛̍͌̀͑̄̑̌́̽̿̎̆͒̈́̂̈̐͗͑́̈́̃͑̔̆͑̍̋̽͑́̓̂̿̔͒̾͗͂̈́̂̀̍̄͆̓̆͆̍̔̆̋̍͒̃́̿̍̀̊̎̐͋̋̍̏͌̓̇͑͐̄͌̅̂͑͊͐̽̐͌̌͐͋̃̾̒̈́̑̓̓̈́̓̑͒̋̈́̓̌̈̌̎̍͂̋̎͌͆̐̾͋̇̌̂̈́̓̊͑͌̌̿̀̚̕̚͘̚̕̚͘͘͘͘̕̕̚̕͜͜͜͝͝͝͝͝͝͠͝͠͝͝͝͠ͅͅͅͅy̸̨̨̢̢̡̡̨̧̢̨̢̡̢̨̡̨̢̢̛̛̛̛̛̛͚̦̥͔̣̩̬̱̳̩͔̯͎̯͎̠̻̗̗̲̫̼̠̦̦̙̰̙̺̝̺̱͔̥̥̤͕̠̠̦̜̫̲̮̳̣͉̮̙͖̦̜̯͚̥̭̙͈̫̜̱͖̺̤̙̫̱̻̝̖̥̘͔̩̥̞̰̫̘̣̪̟̫̜͈̼̱̹̹̪̼̭͚̼̫̖̹̟̟̻̞̥͉͖͓̳̞̹̼̝̩̤̳͚̫̬̣̟̲̖͓̜̲̖̞̥̫͎̝͉̤̠̙͇̜͍͕̗̼̙̹̩͓̖̟͇͈̫̜̫͍̰͖͍̗̮̮͉̖̜͈̲̺̬͉̬̘͍͔̞͉̫̣̯͓̹̹̖̝̰̰̮͐̀̅͒͋̎̈́̌͑̈̎̄͛̌̿̆̈́͛̑̎̄́̎̀̔̆͋̊̀̇̋́́̏̈́̋͂̃͂̄̇̈́̇̑̂̒͋̄̒̅̅̊̂̏́̓̊̃̔͐̈̃̉̅͂́̀͆̏̄͆̾̈́̌̄̒̀̂͋́̀͐͒͋̿͂̈́̔̿͋̀̈́̊͋͂̓̾̎̔̓̊͌̈́̏́͐̌͋̉̔̒͗͋̋̐̍̉̓́͆͊̃̅̊̄̿̇̂̍̏̎̌̏̌̄̓̾̔͑̎̈́̈̌̓͒͒͐̃̋́͑̔̍̎͌͊̀̉̏̆͋͂̏̎̍̊͂̽̅̃̍̀̍̐̔̒̽͑̋̉͆̎̾̇͛̒̀̀̈͗̀͊̿̀̔̂̍̋̑̊͗̉̌̿͆͑̑̋̾͛̿͐͛̈́̈̂̕͘͘̚͘̕̚̕̕͘͜͜͜͜͜͜͜͜͝͝͠͠͠͠͝͝͝͝͠͠͝͠͝͠͝͝͠͝͝͠͝ͅͅͅį̴̨̢̢̨̨̢̨̧̡̡̡̡̡̡̢̡̢̨̨̨̢̨̨̢̛̛̛̗̦͕̦̺̖̣͖̳̳̣͔̩̭̲̲̫͖̯̟̘̪̝͇͈͖͍̙͙̞͖͕̠̞͓̱͔͙͇̤͔̯̱̮̲̼̠̳̻͙̰̮͚̲̗͚̙̝͕͖̱̦͓̩͇̻͎̺̳͇̜̥͇̹̘͍̗̭̻̺̤̖̱̯͓̬̦̖̮̳̙̠͖̘̳̣̝̰̜̘̞͕̪͖̯͚͇̗̣̮͉͈̖͚̰̘̜̦̪̰̞̫̯̰͇͇͖̘̬͍͔̩͕̦͇̠̙̪̪̟͕̯͉̟̞̲͙͔̞̲̦̽͛̀̀͊̓̽͒̒̔͋̄̈̃́̄́͐̑͗͒̓̇̓̔̍̓̀̈̒̊̈̀͑̅͐̄̄̾̈́͗̇͌̒͋͛͂̇͛̇͆͂͆̀̆̿̔̏͗̔͂̊͊͌̑̓͗͑͛̆̋̄̉̄͛̎̔̏̉̌͋̓́̃͂̒͑̆͆̇̄̋͌̋͆̔̈́̇̽͛̅̓̂̃̊́̀̒̔̋͆̐̅̊͂̊͒̏͌̈́̓̓̏̆́̌̀̍̓́̀̌͛̃̑́̈́͌́̅͗͌̎̀͛̌̏͛̐̃͋̐̔͑̒̉̈́͑̈́́͂͆̆̅̐̌̋͌̃̏̓̇͗̄̔͛̃͗̃̍̓̿̊͑̑́͂́̐̐͛́́̂̇̆̓̽͌̿̔͛̃͆̑͌̓̉̋̇͂̅͂̽̈̓̂͒̊́̐͋͒̚͘̕͘̚̕̕̚̕̕͘͘̕̚̚̕̚͘͜͜͜͜͜͝͝͝͝͝͝͠͝͝͝͝͝͝͝͠͝ͅͅͅņ̵̡̧̛̛̛̛͖̫̲̖̘̙̪̟̪̙̮͈̯̯͙͇͙̠̫̪̥̲̟͉̗̟̭̠͙͚̭̪̠̭͚̦̬̩̜͚̣̞̥͍͎̩͚̞̺̝̯̰͔̱̠͔̹̪́͆̂̑́̈́̃̌͒͒̃̈̔͋̑̊̇̾̃̄̅̆̏̿̌͌̾̃̏̊̀̈́̈́͊͑̿́̑̾̈́͗̆͛̈́̒̌̓̅̅̆͛̔̈́̏̐̂͊̐̒͋̃́͋̏̈́̆̓̔̓̆̑͐̒̑̄́̈̉́̿̃̈̆̃̾̾͌̓̈̆̌̌̈́̌̈́̓̋̓͐̈́̾̆̊̈̿̏́̋̀͘͘̕̚͘̚̚͘͜͜͠͠͝͝ͅg̴̡̢̡̧̡̢̨̡̨̧̧̨̡̧̢̛̛̱̩̳̰̥͍̲͕̭͚͎̳͇̙͔̼̱̦̰̼̠̝̺̗̫̪̗͉̤̲͙͇̞̬͎̥̥̫̜͚̮̳͓͙̮͙̦̥̼̮͎̝̯̖̖͇͚̭̗̖̼̰̰̖͇͍̬̬̩̲̣̺̣̖̳̳͍̟̮̹̠͈̲͎̮͔͇̘̲̲̙͙͔̘̞͓̙̟̗̞͇͔̬͉̘͚̊̂̏͂͑̃̒̾̓͋̃́̅̀̈̎̂̅̇͛͋̐̍̈́͑͒̄́̇͑͌͒̌̽̔͋͘̕̚̕̕̕̚͜͝͝͝͝ͅͅͅͅ ̸̧̢̨̨̧̨̧̨̡̧̧̨̨̧̨̡̢̢̢̢̢̛͇̮̣̮̯͉̰̥̱̺̥͖̖̼̠̘̣͈̘̟̲̜͖̺̻͓̼̯̰̩̭͎̲̜̯̬͇̱̱̫͙̝̙͕̠̜̝̺̭̰̠̰̣͕̜͎̣̹̞͖̭̻̰̮͙̱͕̤͍̭͓̳̣̩̜̮̯̗̭̪̦̬͈̜͖͓̜͙͓͖͇͉̼̣̤̣̜̣̣͎̻̪̘̫̜̝̤̼̲͙̗̟̳̪̦͈̲͇̹̹̠͖̦̼̗̹̪̺̦̘̼̭̠͔͓̲͚̠͓̪͚̖̼̰̮̲̱̣̺̠̤̩̯̲͖͖͖̯͓̹͙͍̹͙͍̬̭̳̖̹̹̹̳͙͍̼̤̦͎̣͍͈̤͎̳̺̲̗̫̻͉͇̠͔͓̳͚̪̬̲̗̗̦͇͖̗̲̗̫̘̮̱͇̞̮̟̦͔͈͉͍̣̗̹̭͇̺̖̹̫̱̟̓̅̈̽͒͐̒͂̂͊̈́͊̈́̎̄̈́͌͒̀̑̓̾̎̊̌͐̽̚͜͜͜͜͜͜͝͠ͅͅͅm̶̡̡̡̨̧̢̡̨̨̢̡̡̨̢̛̛̤̭͎̝͚̞̰̲̬̯̬̥͕̮͔̯͎̟̭͙̝͙̻̹̫͎̗͇͓͓͖̝̳̠̬̞͔̘̻̖͍̪̮͖͉̤̖͎̜͓̮̝̞̪̞͓͙̝̹̦̲̱̹̬̝̲̬͇̟͙͚̳̯̝͙̗͚̦̠̳͇̼̯͓̪̩̥̱̮̩͕̲͎͔̘͉͓̘͓̟̯̰̥̬̲͎͚͖̦͔̹̲̥̖̖̄́͐̑̎̎̃͆́͛̒̓͂̑̈́̑͆̽̈́̆̐͌́̃̒͌͋̋̈̽͛̍̂̀͛̈́̅̈́̈́̈́̊̏̈͗̿̀̆̈́͆͆̈͗̔̓̅͋̽͛̎̊͑̍̿͊͆̅́̀̉̈́̋̍̐̽̔̿̂͒̈̈́͌̀̉̿͆̈́̽̋͆̈́͒͂̐̆̃̎̈́͌̓̀͋̔̔͊̒̾͂͑̂͋̒̽͊͗̅̆̔́̾̾̈́͆̐̆̎̉͑̎́̈́̃͆͆̎̌͑̌̇̆̑̑̈́̀͑̀̉͌͒̓́̾̉͆̈́̉̃͆̌̉̎̄̿͛̐͋͋̒̃̉́̈͑̾̓̍͂̂̒̅̀̋̈́͗͐͑̌̐̊̿̃̃̀̓͗͛̊́̔͑̀͌̒͋͘͘͘̚̕̚͘͘͘̚͘̚̚̚̕̕͘͜͜͜͜͜͝͝͝͝͝͝͝͠͠͠͝͠͝͝͝͝͠͝ͅͅͅè̷̢̡̢̢̨̡̢̡̡̢̡̢̛̛̛̘͚̟̱̬̺̺͎͕͍̯̦̗̞̬͉̫̲͇̲̩̟͓̦̠͎̤̗̫̟̙̺̼̙͇̦͍̜̼͇͉͍̰͈̖͈̼̜͔̥͔̟̙̣͕̺̞̞͓̠͚̙͖̲̤̭̼̬̼͇̤͓̥͍̟̖̗̤͉̻̩̤̼͙͚͚̹̩̻̟͙͍̺͇̻͈̺̳̪̙̜̩͚̠̬̰͉͔͈̝͔̝̝̺͙̲̞̜̭̭͎̳̤͍͐͗̓̉̽͗́͐͆̑͛͊̉̈́́͆͗̈́͆̑̍̈́̌̐̔͗̈́̈́̃̀̉̌̇̀́̀̉̋̇̔̀͒̾̃̓̉͊̆̂̒̀́͐͐̇̉̒̇̽̓̑͒̍̈́͑͒̽͌͗͛͊̌̃̂́̀́̀̆̓̾̈́̈́̔̀͊͂͒͐̄̔͛͗̉͛̃̋̃͌̿̀͛̀͊͐̈́̀̆̓͆̒̀̍̈̆̽͋́͑̑̊̊́̍͊̚̕̚̕̕̚̚̚̕͜͠͝͝͝͝ͅ

**Comment by DeltaNedas** [comment]
pi server pi server

**Comment by DeltaNedas** [comment]
no

**Comment by KSean222** [comment]
Way to ruin this thread, @ZacBytes

**Comment by pyronie** [comment]
you haven't even closed your previous pr

**Comment by pyronie** [comment]
image

**Comment by pyronie** [comment]
and I still maintain the opinion that a well-known griefer shouldn't have his server be put on the official server list, ignoring the rumours of him griefing his own server and his grief advertisements on other servers. (yes, putting dozens of draug miner spawns is griefing, along with all the other times you have deconstructed the areas near spawn and defence)

**Comment by Anuken** [comment]
I won't be able to add this server. Even disregarding issues of performance and hosting providers, I only accept servers with mature hosts that have a decent (or at least neutral) reputation in the community. Neither of those criteria seem to be met here.

**Pull request closed without merging**
