### PR TITLE
[unholy] item teleport

### PR DESCRIPTION
**Pull request by Quezler**
> scidustry inspired teleporter, in response to the recent poll

- texture based on mass driver & item source blocks
- needs full power to transfer (like phase bridges)
- configures like mass drivers (with unlimited range)
- transfer isn't instant (buffered for a tick)
- sandbox only (for obvious reasons)

> (copied mass driver code instead of reuse to avoid lots of conflicts upstream in 6.0)

of course @Anuken mentioned he didn't like the idea of teleporters, but this would at least put the aforementioned community at ease a bit if the poll does end up in its removal, i believe the chance of this getting merged is fairly low (target branch is also questionable), so i will just leave it here for now 🙂 (close it if you so please*)

Screen Shot 2020-04-04 at 19 06 23
Screen Shot 2020-04-04 at 19 09 06
Screen Shot 2020-04-04 at 20 28 41
Screen Shot 2020-04-04 at 20 37 26
Screen Shot 2020-04-04 at 20 28 48

### CODE REVIEW

**Comment by KK6DOC** [comment]
#Amazing

**Comment by garyType1** [comment]
#routerrific

**Comment by PetruCHIOrus** [comment]
Nice idea, it's a very useful block. This will free the game from a huge number of pipelines and give a new one just for the schemes.

**Comment by Eldoofus** [comment]
Nice. Hope it gets merged soon.

**Comment by BlueWolfGaming** [comment]
isnt this just the teleporter from Mindustry Classic but modernized?

**Comment by itcannotbe** [comment]
Yes it is like that teleporter from Classic.

But in classic, power was consumed per item teleported.

**Comment by Quezler** [comment]
interesting, wasn't aware of how exactly they worked in classic ^

**Comment by Arkanic** [comment]
it's a snek except it is partially shifted into a fourth dimension

**Comment by MEEPofFaith** [comment]
:ohno:

**Comment by SnakkiZXZ** [comment]
there's a little idea about the sprite, I can tweak it a little bit or redraw it.

**Comment by SnakkiZXZ** [comment]
Screenshot_20200421_120634_io anuke mindustry
телепорт

**Comment by BasedUser** [comment]
routerporter

**Comment by Quezler** [comment]
i might clean this up for 6.0

**Comment by Anuken** [comment]
I'm not sure if this will be necessary after proper logic is added.

**Comment by Quezler** [comment]
then i'll close it for now

**Pull request closed without merging**
