### PR TITLE
Fix a ui bug on desktop

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**
The buttons on menu will be weird if you try to put more than 8 buttons.

Before
java_vEGWaGlPhv

After
java_NXB18kjEAk

### CODE REVIEW

**Comment by Quezler** [comment]
this is probably a horrible solution, and anuke would likely want to do it himself if he ever wants more buttons on the menu 🤔

**Comment by ThebestkillerTBK** [comment]
This can be a temporary solution before anuke done the ui.

**Comment by Quezler** [comment]
your code currently looks like a mess, so i doubt he will use it as a temporary solution 😅

**Comment by sk7725** [comment]
.row()

**Comment by Anuken** [comment]
> This can be a temporary solution before anuke done the ui.

There is no need for any solution at all. This is not a bug; the game doesn't **have** more buttons in the menu. If you make a mod that adds more, it is your responsibility to get it working properly *in the mod*.

**Pull request closed without merging**
