### PR TITLE
more servers

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**

### CODE REVIEW

**Comment by Quezler** [comment]
are they all yours, or do you officially represent them all?

**Comment by ThebestkillerTBK** [comment]
social servers,not mine

**Comment by Quezler** [comment]
whilst not defined explicitly in [`SERVERLIST.md`](https://github.com/Anuken/Mindustry/blob/master/SERVERLIST.md) it does give the impression that the owner of the server must submit it himself. (or at the very least consent to his server being added, please feel free to correct me on this if i'm wrong @Anuken 🤔)

**Comment by ThebestkillerTBK** [comment]
I will temporarily close this issue. If this is true, Anuken should declare the rules in serverlist.md

**Pull request closed without merging**
