### PR TITLE
Pyratite -> Firelite

### PR DESCRIPTION
**Pull request by AmateurPotion**
How about this

ps. Don't take my joke too seriously.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
not funny didnt laugh

**Comment by AmateurPotion** [comment]
sorry :(

**Comment by sk7725** [comment]
This is the essense of Ajushi

**Comment by AmateurPotion** [comment]
::cry::

**Comment by Anuken** [comment]
what

**Comment by Gdeft** [comment]
> This is the essence of Ajushi

oh no

**Pull request closed without merging**
