### PR TITLE
Remove Tendhost

### PR DESCRIPTION
**Pull request by way-zer**
The domain is reported as virus.
https://s.threatbook.com/report/file/734c26179a753a5bcf52d19f740eb5b0daf0c5ecec9066df2a3a1543c65a61fd

https://x.threatbook.com/v5/domain/tendhost.ddns.net

---
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Kieaer** [comment]
https://www.virustotal.com/gui/url/d85fe54f76fd864f7e1db1e310fb0f5ffd1c241dfa5863a6699e7c9332466a8f?nocache=1

ddns.net is sharded domain
if something problematic in a.ddns.net, it will apply to the entire ddns.net.

It's a problem with the way the site is analyzed.
The current tendhost.ddns.net and the IP in the report are different.

**Comment by way-zer** [comment]
> Contributor

That report is for subdomain `tendhost.ddns.net` not `ddns.net`.

And the report date is after server added, so I think the domain belong to the server when report.

**Comment by way-zer** [comment]
The server don't have online players, and the owner don't give any explanation.

**Comment by way-zer** [comment]
And, this threat database is widely used. I have gotten banned from Campus network many times due to this host.

**Comment by SachaTending** [comment]
i changed domain of server

**Pull request closed without merging**
