### PR TITLE
Remove Omnidustry from servers_v7.json

### PR DESCRIPTION
**Pull request by BasedUser**
this server is extremely shady in what they do, and the discord doesn't help the situation either; *also* violating guideline 2 routinely

i'd much rather not help cultivate a negative playerbase either  
P.S. we should start either limiting server slots or expanding the lobby UI, it's getting way too long

------------

*If you're here to engage with drama regarding either of the servers, you might want to choose a platform DIFFERENT from GitHub, or forward it to the other numerous PRs both servers have already.* I'm not changing my stance.

### CODE REVIEW

**Comment by TheEt1234** [comment]
"remove cringe" goofy commit name

**Comment by JojoFR1** [comment]
I don't see what Darkdustry did, it's a pretty good server.

For Omnidustry, eh, heard a lot about it but never played so I don't know.

**Comment by SSTentacleSS** [comment]
Router, could you finally calm down?

**Comment by code-explorer786** [comment]
please close this or possibly get three servers nuked

**Comment by code-explorer786** [comment]
oh well, i'm just going to wait and see what happens in the future

**Comment by Def-Try** [comment]
damn

**Comment by Kieaer** [comment]
+1

**Comment by StalkerBaran** [comment]
Omnidustry is one of the worst server EVER. They are stealing a maps and all those who are against having their maps stolen are banning on the server (Discord). Their moderators and admins do not follow their own rules, constantly insulting the participants and toxic. Example, I'm a Blackberry, have my own maps. Omni stole my map "Devil's Cave". They banned me on his own server and blocked (its a 3rd time when they are stealing MY maps). Today they are steal map of my friend "Quantum Storage" by Hazarder. I'm can send a proofs if you want

**Comment by BasedUser** [comment]
> Omnidustry is one of the worst server EVER. <...>

***Take it to another PR.*** The context is already known.

**Comment by code-explorer786** [comment]
> > Omnidustry is one of the worst server EVER. <...>
> 
> ***Take it to another PR.*** The context is already known.

*Don't. Don't even mention about drama anyway.*

**Comment by SSTentacleSS** [comment]
> this server is extremely shady in what they do, and the discord doesn't help the situation either; _also_ violating guideline 2 routinely
> 
> i'd much rather not help cultivate a negative playerbase either P.S. we should start either limiting server slots or expanding the lobby UI, it's getting way too long
> 
> _If you're here to engage with drama regarding either of the servers, you might want to choose a platform DIFFERENT from GitHub, or forward it to the other numerous PRs both servers have already._ I'm not changing my stance.

1. image

2. +1 PR

**Comment by Volas171** [comment]
they are also doing more shady tactics such as infringing copyright law.... but well..... time will tell what happens here

**Comment by code-explorer786** [comment]
> > this server is extremely shady in what they do, and the discord doesn't help the situation either; _also_ violating guideline 2 routinely
> > 
> > i'd much rather not help cultivate a negative playerbase either P.S. we should start either limiting server slots or expanding the lobby UI, it's getting way too long
> > 
> > _If you're here to engage with drama regarding either of the servers, you might want to choose a platform DIFFERENT from GitHub, or forward it to the other numerous PRs both servers have already._ I'm not changing my stance.
> 
> 1. image
> 
> 2. +1 PR

I'm confused. What does this mean exactly?

**Comment by Def-Try** [comment]
dont discuss it here. please.

**Review by TimaHappy — APPROVED** [review]

**Review by RebornTrack970 — APPROVED** [review]

**Review by littelcat456 — APPROVED** [review]
DOWN WITH THE CROOKS

**Comment by Leo-MathGuy** [comment]
If I remember correctly they also bot attacked everyone a year or so ago

**Pull request closed without merging**
