### PR TITLE
Add large launch pad

### PR DESCRIPTION
**Pull request by Voz-Duh**
image
image

_Idk but maybe this can work_

### CODE REVIEW

**Comment by Voz-Duh** [comment]
Yey!

**Comment by Quezler** [comment]
this causes no problems?
https://github.com/Anuken/Mindustry/blob/be4c466a2fc173293f0bf70235498d453c3f0022/core/src/mindustry/world/blocks/campaign/LaunchPad.java#L205

**Comment by Voz-Duh** [comment]
Oof

**Comment by catatagun** [comment]
Maybe it should cost more power now as launch pad was really good like 900 or 600

**Comment by catatagun** [comment]
I really miss the large launch pad even tho i never used it

**Comment by Voz-Duh** [comment]
@catatagun if you want to it merged you can approve theses changes
image

**Comment by Anuken** [comment]
This block is slated for removal. It won't be added.

**Comment by Voz-Duh** [comment]
Oof
I lost 1 day for make it

**Comment by Voz-Duh** [comment]
@Anuken, if I delete large pad textures you can merge it?

**Comment by Voz-Duh** [comment]
Oof

**Comment by Voz-Duh** [comment]
But this part of code really needed for moding

**Comment by Voz-Duh** [comment]
Okay

**Comment by catatagun** [comment]
No large launch pad is die

**Pull request closed without merging**
