### PR TITLE
Accurate Lancers

### PR DESCRIPTION
**Pull request by MEEPofFaith**
~~This can't possibly be unbalanced.~~

https://user-images.githubusercontent.com/54301439/117496248-a0bb0e00-af2b-11eb-9ae5-6917273a6e0f.mp4

(Daggers made speedy for demonstration purposes.)

It can still be inaccurate if it aims at something, then that something dies ~~which happens a lot in the video.~~

Hehe I'ma just sit here and watch the comments go chaotic.

image

### CODE REVIEW

**Comment by OnyxFinger** [comment]
actually good lancers..
lancers were usable already though, I prefer to see them more as a situational gun, it's just better in general : learning what to use in what situations is a better way of doing things, especially since knowledge in this game is informational for most.
also it would totally not be unbalanced INDDDEEEEEEEEEEEEEEEEEEEDDD SIR

**Comment by Anuken** [comment]
While this seems nice in theory, I don't like the balance implications.

**Comment by OnyxFinger** [comment]
balancing is hard and lancers are pretty much find as they are right now in my opinion, no need to touch them.

**Comment by MEEPofFaith** [comment]
¯\_(ツ)_/¯

Anarchy.

**Comment by Anuken** [comment]
at the same time, balancing something by making it stupid is not good design

**Comment by OnyxFinger** [comment]
> Well, lancer doesn't really need balance. I created this more of to see how it would be, knowing there will be people who like it and people who don't.

and you placed it in a place where you're supposed to report bugs / send suggestions or talk about balance :/

**Comment by MEEPofFaith** [comment]
eh, let the opinions roll in

**Comment by WilloIzCitron** [comment]
but lancer cant aim crawler because crawler is **TOO FAST**

**Comment by sk7725** [comment]
I think that there should be a way to utilize this behavior in logic.

**Comment by notrealn** [comment]
Considering that this could possibly be implemented with logic, I think merging this would make it more accessible for everyone.

**Comment by LeoSko** [comment]
Please yes.

Logic is better to support strategy decisions (e.g. choosing to attack enemy with highest HP) and not tactics where you make something inaccurate - accurate, something with low range - high range or something stupid - smart.

As a potential balance impact - there is practically none, since you previously could place lancers in such a way that would still make it hit fast units, but now you just won't have this headache of finding correct place/angle.

**Comment by OnyxFinger** [comment]
Well yes. It would mean lancers need a damage nerf however, their innacuracy is their only issue (they can't hit air but you can just place scatters or another AA gun and woo, now you can hit air, so it's not an issue)

**Comment by MEEPofFaith** [comment]
~~Dumb people friendly~~

**Comment by Markty07** [comment]
Please no

**Comment by Anuken** [comment]
Implemented as an optional parameter, in case it ever becomes necessary, or a mod decides to change it.

**Comment by MEEPofFaith** [comment]
ight

**Pull request closed without merging**
