### PR TITLE
allow modders to customize vanilla AIs..?

### PR DESCRIPTION
**Pull request by Uenhe**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by BlueTheCube** [comment]
anuke what do you think

**Comment by Slotterleet** [comment]
My opinion: This PR is utterly useless.

**Comment by Slotterleet** [comment]
If you want to customize vanilla AIs, just make a new one. It is possible for a long time now.

**Comment by Uenhe** [comment]
> If you want to customize vanilla AIs, just make a new one.

:( so any example?

**Pull request closed without merging**
