### PR TITLE
Add: Malay(Malaysia) Translation

### PR DESCRIPTION
**Pull request by WilloIzCitron**

### CODE REVIEW

**Comment by Humanoid-X** [comment]
is it possible to contribute to exsisting pulls

**Comment by Phinner** [comment]
> 
> 
> is it possible to contribute to exsisting pulls

yes, by adding the people as contributors to your own Mindustry fork.

**Comment by Phinner** [comment]
Keep going my dude, you doing great !

**Comment by WilloIzCitron** [comment]
Translation are delayed soon

im do a school final exams on my school, i'm a student.

**Pull request closed without merging**
