### PR TITLE
New Logo

### PR DESCRIPTION
**Pull request by Voz-Duh**
I thought that Mindustry needs a new logo, probably this is a very sharp change, because no one has changed this logo since Mindustry ceased to be a Mindustry classic, I would not be surprised if many people don’t like it, but I still insist to change the old logo to a new one that match style 6.0
new-logo

### CODE REVIEW

**Comment by Voz-Duh** [comment]
I expected that not everyone would like it, but in my opinion this pull is simply ignored

**Comment by Anuken** [comment]
It just looks messier, in my opinion.

**Comment by sk7725** [comment]
It looks not bad but too thick; make the letters(notably D) thinner

**Comment by DeltaNedas** [comment]
this is h and somehow made travis cry

**Comment by summetdev** [comment]
You somehow made regions broken.

**Comment by Quezler** [comment]
> When making a pull request that changes or adds new sprites, do not add the modified atlas & spritesX.png files to your final pull request. These are a frequent source of conflicts.

**Comment by Voz-Duh** [comment]
image
Better?

**Comment by Voz-Duh** [comment]
> It looks not bad but too thick; make the letters(notably D) thinner

Thx, i fixed it

**Comment by Voz-Duh** [comment]
> > When making a pull request that changes or adds new sprites, do not add the modified atlas & spritesX.png files to your final pull request. These are a frequent source of conflicts.

Thx, I fixed it

**Comment by Quezler** [comment]
> Thx, I fixed it

the 2 files still show in https://github.com/Anuken/Mindustry/pull/3185/files though 🤔

**Comment by Voz-Duh** [comment]
I updated comment

**Comment by Voz-Duh** [comment]
Idk why it showed
image

**Comment by Quezler** [comment]
try downloading those 2 files from the master branch and recommitting them to your `new-logo` branch, that might work 🤔

**Comment by Voz-Duh** [comment]
Ok /-/

**Comment by Quezler** [comment]
victory 👍

**Review by Quezler — APPROVED** [review]

**Comment by ThePythonGuy3** [comment]
i love this logo, good job

**Comment by Voz-Duh** [comment]
Thx

**Comment by Voz-Duh** [comment]
This is final version of the logo, me need wait only

**Comment by Voz-Duh** [comment]
@Anuken check this pull now

**Comment by Voz-Duh** [comment]
Don't say me why and others

**Pull request closed without merging**
