### PR TITLE
Move slider values to the right of the slider

### PR DESCRIPTION
**Pull request by buthed010203**
This is a minor change but prevents the slider from shifting around constantly which can be rather annoying.
Before: https://discord-cdn.is-terrible.com/53W3H4pMT.webm
After: https://vexera.is-ne.at/53W2dq2ev.webm

### CODE REVIEW

**Comment by Anuken** [comment]
A better way to display slider text (and save space) would be to display the text *on top* of the slider, likely with a different style:

image

**Comment by buthed010203** [comment]
I agree, ~~the minecraft way~~ that way is significantly better

**Comment by buthed010203** [comment]
I tried with 2 rows in a table and it looks horrible, guess a stack is better here

**Comment by Anuken** [comment]
I'm trying to make the bars "boxy" first, but the margin isn't being calculated properly.
image

**Comment by buthed010203** [comment]
Fair enough

**Comment by buthed010203** [comment]
It doesnt look *terrible* in its current state with them stacked, the text is pretty hard to read though. The text isnt centered either here but thats a really easy fix. https://extremely.questionable.link/543NPKUrb.webm

**Comment by Anuken** [comment]
New implementation:
image

**Comment by Phinner** [comment]
My god, that's beautiful.

**Pull request closed without merging**
