### PR TITLE
"Smarter" targeting for Turrets

### PR DESCRIPTION
**Pull request by Killian-LeClainche**
Some of my friends and I had been playing the PVP multiplayer and found that you can confuse the turrets by spamming copper walls on top of the opponents turrets and then turret push.

I felt like this reduces the competition of the PVP. Let me know your thoughts, thanks!

### CODE REVIEW

**Comment by indielm** [comment]
I think this is fine because it only works outside the base radius circle, which is adjustable with the map.

**Comment by Anuken** [comment]
Maybe this functionality should be implemented for *all* units and blocks by putting the extra turret targeting step in `Units`? I feel like targeting walls when there's turrets available is a dumb idea in general.

**Comment by Killian-LeClainche** [comment]
I like that, but ideally you'd weight the units/blocks around you and target accordingly. To explain further, air units would want to target anti-air turrets over ground turrets, etc. Just some food for thought for the future.

Also, some ramifications of doing this is that bombers, which (in my playthrough) ignore anti-air defense, would be less likely to behave the same. That means they won't attack the production lines if your air defense doesn't cut them down quickly.

**Comment by Anuken** [comment]
Implemented configurable targeting priority in edfd402ccd1a9bc5d1c083977f90c0f9aa2407d2, so this should no longer be needed.

**Pull request closed without merging**
