### PR TITLE
Effect spawn delay

### PR DESCRIPTION
**Pull request by MEEPofFaith**
image

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

I should probably test this.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Yep, it works.

https://user-images.githubusercontent.com/54301439/135146362-2645a6dc-5962-4b99-9285-adbae45fbf25.mp4

**Comment by Anuken** [comment]
Problem is that this adds a delay to *every single particle effect*, regardless of whether the delay is 0 or not. This means every particle effect will only spawn next frame, and has significant garbage collection / performance implications.

**Comment by BlueWolf3682** [comment]
I'd recommend an \@Nullable field for this - that way it doesn't affect effects without the delay field.

**Comment by MEEPofFaith** [comment]
> Problem is that this adds a delay to _every single effect_, regardless of whether the delay is 0 or not. This means every particle effect will only spawn next frame, and has significant garbage collection / performance implications.

~~This is the part where you do it yourself and it results in something much cleaner than my creation.~~

**Comment by MEEPofFaith** [comment]
nice

**Pull request closed without merging**
