### PR TITLE
[QOL] Searchable Maps

### PR DESCRIPTION
**Pull request by zatnas**
screenshot200518195002537043020

Update 1:
Peek 2020-05-19 06-51

Update 2:
Peek 2020-05-19 11-27

Implements https://github.com/Anuken/Mindustry-Suggestions/issues/182

TODO:
- [x] add search icon
- [x] implement Gamemode filter

### CODE REVIEW

**Comment by zethnest** [comment]
If https://github.com/Anuken/Mindustry/pull/2079 is merged, allow me to add fuzzy searching to this.

**Comment by Summet-V** [comment]
How about adding a search icon?

**Comment by zethnest** [comment]
Currently don't have the time and luxury to resolve conflicts. Drafting

**Comment by Anuken** [comment]
FYI the reason I haven't merged this yet is because it cuts into the already-tiny vertical space on mobile when in landscape orientation.

**Comment by zethnest** [comment]
I see. I'll see to it whenever I have the time.

**Comment by zethnest** [comment]
At long last, I have finished this QOL.
Peek 2020-12-23 08-51
I made the maps along with the search and filter to be able to be scrolled. Sorry this took half a year for such a simple feature add. I didn't have the time to do so.

**Comment by zethnest** [comment]
@Anuken Do you have anything to comment on for this newest change?

**Comment by DeltaNedas** [comment]
cut down on searching boilerplate and use SearchBar with a custom input function to have fuzzy search

**Comment by zethnest** [comment]
@DeltaNedas I'll see to it when I have the time again.

**Review by RebornTrack970 — APPROVED** [review]

**Pull request closed without merging**
