### PR TITLE
Add mindustry.io to servers.json

### PR DESCRIPTION
**Pull request by fuzzbuck**
- huge community (~1.5k members)
- anti-grief measures (discord bot <-> in-game moderation)
- huge map pool (50+)
- stable, powerful server based in europe

### CODE REVIEW

**Comment by ZacBytes** [comment]
Disapprove

**Comment by pyronie** [comment]
> Disapprove

image

**Comment by Kieaer** [comment]
io server is good

**Comment by ado1928** [comment]
> Disapprove

image

Opinions are obviously illegal here

**Pull request merged**
