### PR TITLE
Basic unitsorts for hjson

### PR DESCRIPTION
**Pull request by MEEPofFaith**
image

Tested by modifying `railgun` in Exotic Mod.
`unitSort: strongest`

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
> how do I test this

Make a modded unit in a test mod. It only takes a couple minutes, you don't need sprites or anything.

**Comment by BlueWolf3682** [comment]
Attach a unitsort to one of my turrets.

**Comment by MEEPofFaith** [comment]
> Attach a unitsort to one of my turrets.

fair enough

**Comment by MEEPofFaith** [comment]
~~Alright @BlueWolf3682 start suggesting other sorts~~

~~Ideas I have are: "Lowest current health" and "Highest current health"~~

**Pull request merged**
