### PR TITLE
Simple fix for delayed weapons.

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
Makes the shootSound sound when it *actually* shoots, not when the shoot sequence starts. (PS: sorry for 3 PRs in an hour, i feel somehow inspired today)

### CODE REVIEW

**Comment by Anuken** [comment]
For delayed weapons, the idea is that you have a sound effect with a "charge-up" sequence so it matches the charging of the bullet.

**Comment by ThePythonGuy3** [comment]
oh okay. what about 2 sounds?

**Comment by ThePythonGuy3** [comment]
@Anuken maybe you like it now?

**Comment by Anuken** [comment]
This breaks compatibility. Weapons without a delay will use the charge sound.

**Comment by ThePythonGuy3** [comment]
oh true, missed one thing, sorry

**Comment by ThePythonGuy3** [comment]
now its all compatible, and as long as they dont override load completely (and if they do they *should* know how to add chargeSound) just with shootSound is enough.

**Comment by ThePythonGuy3** [comment]
@Anuken if this is way off what you had in mind just let me know

**Comment by Anuken** [comment]
I'll just do this myself.

**Pull request closed without merging**
