### PR TITLE
Unjank the Plated Conduit sprites.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
For some reason, the transparrent part was, like, [5 or so shades of colors](https://gyazo.com/dc59600fad032ec0450cbeb9ac40929e). Of course, you couldn't see them, but they werere there.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
I don't know why the custom cells from earlier are still here.

**Comment by BlueWolfGaming** [comment]
I'm afraid that the transparency shouldn't affect how the sprite is saved, though re-uploading should fix it. Possibly a viable solution to #1952.

**Comment by MEEPofFaith** [comment]
Well, it's fewer colors to load.  And maybe the things I did in Paint.net might fix the weird corruptedness.

**Comment by BlueWolfGaming** [comment]
It may be fewer, yet the transparent colours exist in all sprites with transparency. Check the other sprites.

**Comment by DeltaNedas** [comment]
re encode as 8 bit rgba to fix jank

**Pull request closed without merging**
