### PR TITLE
fix pt br translation

### PR DESCRIPTION
**Pull request by DeltaNedas**
pls give me translation role on discord thanks

### CODE REVIEW

**Review by DeltaNedas — COMMENTED** [review]
a

**Comment by ThatOneBepis** [comment]
No. Just no.

**Comment by DeltaNedas** [comment]
> No. Just no.

which line is wrong pls tell me im new to this

**Comment by ThatOneBepis** [comment]
you are deleting the whole file lol

**Comment by DeltaNedas** [comment]
yes i am fixing pt br

**Comment by XEN0PHIL** [comment]
You, sir, deserve a smack with a rolled up newspaper.

**Pull request closed without merging**
