### PR TITLE
Add Bangla

### PR DESCRIPTION
**Pull request by Oymate**
I haven't translated much of anything but just to make sure there's an entry

### CODE REVIEW

**Review by WilloIzCitron — COMMENTED** [review]
wait your translation isnt complete make it draft

**Comment by TheMrAlbert** [comment]
Unfortunately, when testing the bundles that I downloaded. It broke...
image

**Comment by WilloIzCitron** [comment]
but itsnt support libgdx

**Comment by WilloIzCitron** [comment]
> Arabic and similar RTL languages are not supported, because LibGDX doesn't support. If you want to add RTL language you need to implement font support + font rendering support + translated text.
> Details: 

- Prosta4ok_ua

**Comment by TheMrAlbert** [comment]
> but itsnt support libgdx

Actually, Audiowide font don't support Bangladesh language.

**Comment by TheMrAlbert** [comment]
Wait no...

**Comment by WilloIzCitron** [comment]
oh 

audiowide doesnt support bengali

**Comment by WilloIzCitron** [comment]
make it latin one

**Comment by TheMrAlbert** [comment]
> oh
> 
> audiowide doesnt support bengali

I just realized this wasn't the case, because some other languages such as Chinese, Japanese, etc. does shows up in Mindustry.

**Comment by Oymate** [comment]
Umm it's LTR

**Comment by TheMrAlbert** [comment]
> Umm it's LTR

Great. Now you just need the fonts specially for Bangladesh. Try to start the discussion in Discord about the fonts, I guess.

**Comment by Oymate** [comment]
https://github.com/Anuken/Mindustry/pull/5194

**Pull request closed without merging**
