### PR TITLE
add shebang to convert_sounds.sh

### PR DESCRIPTION
**Pull request by DeltaNedas**
title

### CODE REVIEW

**Comment by Anuken** [comment]
Does this fix anything specific? I've never had a problem without it.

**Comment by mRebornM** [comment]
Im not sure if it fixes something but it defitely makes a difference

**Comment by Anuken** [comment]
Right, but can you provide a specific example of the script failing to execute correctly due to absence of that line? I'd like to know if this was caused by a real problem that someone had, or if it's just 'standard practice'.

**Comment by Quezler** [comment]
mostly depends on if the file is executable or not, so the os knows which to run when launched by hand iirc 🤔

**Comment by mRebornM** [comment]
Why would you launch it by hand?

**Comment by Anuken** [comment]
You wouldn't. This script is only supposed to be run through Gradle during iOS compilation.

**Pull request closed without merging**
