### PR TITLE
formatting en bundle with backslash apostrophe

### PR DESCRIPTION
**Pull request by Arkanic**
just cleaning the properties code

### CODE REVIEW

**Comment by Anuken** [comment]
Why? This doesn't change any of the displayed text.

**Comment by Arkanic** [comment]
@Anuken 
just tidying the code

**Comment by Anuken** [comment]
If the file already works fine without backslashes, how does adding them make it more tidy?

**Comment by Arkanic** [comment]
@Anuken you can close the pull request, i just made it because it makes the file look strange in code editors because section of it appear as strings, but you are right, it is quite pointless.

**Comment by Anuken** [comment]
I haven't encountered that issue in IntelliJ or the Github source preview, so whatever incorrect syntax highlighting you could potentially be getting is probably a bug in the editor. Properties files don't have quoted strings.

**Comment by Arkanic** [comment]
@Anuken this is probably to late, but yeh, one of my eclipse plugins had a setting with "display strings on .properties"

**Comment by Arkanic** [comment]
looking back at me i did a lot of ping spam

**Comment by Anuken** [comment]
image

Well, commenting on any PR does the same.

**Pull request closed without merging**
