### PR TITLE
Readme: Formatting

### PR DESCRIPTION
**Pull request by summetdev**
**Before:**
... [here.](https://youtube.com/watch?v=dQw4w9WgXcQ)

**After:**
... [here](https://youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

**Comment by Anuken** [comment]
Why?

**Comment by summetdev** [comment]
In my opinion, this is more correct, because the link refers to the word (in this case, "here") and the period does not related to the link or word, it is just the end of the sentence.

**Review by Quezler — APPROVED** [review]

**Comment by BlueWolf3682** [comment]
thanks for the double rickroll

**Comment by Anuken** [comment]
> In my opinion, this is more correct

That's just nitpicking. Removing the period may seem 'more correct', but it also makes the markdown slightly less readable and the link a little harder to click. In general, I'm fine with formatting changes, but making an entire PR just to move a period is "*hacktoberfest hall of shame*" material.

**Pull request closed without merging**
