### PR TITLE
remove stray newline

### PR DESCRIPTION
**Pull request by buthed010203**
its ugly

### CODE REVIEW

**Comment by Anuken** [comment]
can't you consolidate all these single-character PRs into one big change?

**Comment by buthed010203** [comment]
I fix them as I find them, I don't think I have any other prs like this open rn

**Comment by joshuaptfan** [comment]
Catch all the trailing spaces while you're at it too.

You should automate this with a search-and-replace.

**Comment by buthed010203** [comment]
~~sounds like too much work~~

**Pull request merged**
