### PR TITLE
Same USID for same IP

### PR DESCRIPTION
**Pull request by Darkness6030**
⚠️ Needs discussing
- Will it work for IPv6?
- Will it be safe?
- What will happen with old USIDs?
- It will reset all admin or whitelist statuses.

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
> It will reset all admin or whitelist statuses.

I don't think this is acceptable.

**Comment by Darkness6030** [comment]
> I don't think this is acceptable.

I just don't see any good idea how to sync player data between servers without the risk of being hacked. 
UUIDs are stolen all the time, so this is not an option.

**Comment by squi2rel** [comment]
Some different panel servers are using the same IP address. The only difference is the port. It's not so good to do this

**Comment by BalaM314** [comment]
It would be possible to keep old USIDs, by looping through each settings key and converting them.
However, I don't think this is a good idea. USID should be unique to each server, not just IP address.
Playerdata sync problems can be solved by storing USID as a Record<ip, usid>, then have the server determine its ip on startup.

**Comment by buthed010203** [comment]
The best solution I can think of to reliably link a player's account across servers would be to send them from one server to the next via a command or something and just look for a player with the same uuid joining on the other server. Not the greatest solution but would probably work decently

**Pull request closed without merging**
