### PR TITLE
[Translations/Filipino] Changes & additions

### PR DESCRIPTION
**Pull request by r4isen1920**
• Some existing translations have been changed/tweaked
• More translations have been added 

More progress will be done as soon as I have the time.

### CODE REVIEW

**Comment by JrTRinny** [comment]
seems like bundle_fil is a very incomplete bundle, Keep it up man!
I've checked, around 400 sentences are missing, and half of the sentences in the bundle are not translated, I'll check and add something in the review

_note: no, I'm not Filipino, just a translator buddy_

**Comment by r4isen1920** [comment]
Keep in mind that this is a draft translation, some things still needs to be curated and properly re-checked.

**Comment by EclipsePlays** [comment]
What a coincidence, I was also making a reformation of bundle_fil...

**Comment by EclipsePlays** [comment]
> seems like bundle_fil is a very incomplete bundle, Keep it up man!
> I've checked, around 400 lines are missing
>

Its **1120 lines**

**Pull request closed without merging**
