### PR TITLE
Improvements to the Schematics UI

### PR DESCRIPTION
**Pull request by JniTrRny**
Just another random UI PR, but apparently the schems one gets the most changes somehow.

Added a search message text to the search bar, and make the buttons overlay-ed.

image

Changed the styles of these buttons so they won't show ugly square around the icon when you click it.
image

Also improved the edit tags dialog, to make it more fancy and organized, now with 4 buttons (and probably just that, well because there is not enough place to put another button right now)
image

Added Export and Edit button into the info dialog of the schematic, so you can export or edit right away when you save a schematic.
image

also renamed the "rename schematic" to edit schematic, to better reflect what it does (and also resized the save and cancel button)
image

Added icons to icon tags, I dunno why this doesn't existed in the first place but it's here now.
image

On to the map load dialog, this one is smaller than the schems one, but it sure does change a lot.
Make use of the `makeButtonOverlay()`, changes button width and style, pretty much changes everything I guess (still looks the same.)
image

lastly, correctly adjusted the width of the search bar of the content selection.
image

I should also mention that https://github.com/Anuken/Mindustry-Suggestions/issues/4443 is a very interesting suggestion to consider, but right now I don't know how to approach it.

###### I should stop doing UIs somehow, but these things don't break anyone's game when something gone wrong sooo

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
~~I see a distinct lack of gray bo-~~

**Comment by JniTrRny** [comment]
~~if only there's grayTogglet~~

**Comment by Anuken** [comment]
Lots of cleanup commits here recently, is it ready for review?

**Comment by JniTrRny** [comment]
Okay now it's ready.

**Pull request merged**
