### PR TITLE
unblacklist ui-lib, its fixed

### PR DESCRIPTION
**Pull request by deltanedas**
as of 3.16.8 its fixed and both stops crashing and works

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
No, the old version still crashes, and there's no way for people to update it.

Is this mod really necessary?

**Comment by BlueWolf3682** [comment]
(no, lib mods in general for this game are completely and utterly useless)

**Comment by deltanedas** [comment]
old version still crashes: blacklist the old version
necessary as the functionality isnt in vanilla and good few mods use it

**Comment by Anuken** [comment]
Then it should be moved to vanilla, lib mods are a bad experience for users and I don't want some insignificant UI change causing widespread startup crashes again (why even move it outside ClientLoadEvent?)

**Comment by deltanedas** [comment]
for funny reasons including Core.app.post(() => Core.app.post(() => ... sneks having to be dealt with because too lazy to make a custom mod menu buttons button that hides when no custom buttons exist................. its pr time

**Comment by deltanedas** [comment]
oh nevermind there is already a thing for custom menu buttons, will just remove the dialog thing

**Comment by deltanedas** [comment]
ok making new pr

**Pull request closed without merging**
