### PR TITLE
[mods] Let mechs/units override drawShadows

### PR DESCRIPTION
**Pull request by DeltaNedas**
Does what it says on the tin.
Default is how player did it before, except its in mech now so mods can override it.
See it in action: [vid](https://cdn.discordapp.com/attachments/653292618406690847/673902650420363284/Capture_144813.mp4)

---
let unit do more stuff mechs can, now you do square engine enemies!

### CODE REVIEW

**Comment by DeltaNedas** [comment]
wait dont merge

**Comment by DeltaNedas** [comment]
now (should) let mods change engine size and inner color (default still white)

**Comment by DeltaNedas** [comment]
square engine [square engine](https://cdn.discordapp.com/attachments/653292618406690847/674016063855525904/Capture_221841.mp4)

**Comment by Anuken** [comment]
I'm hesitant to add anything to mechs/units when both of them will no longer exist as classes in the future.

**Comment by DeltaNedas** [comment]
will repeat for entities too hold on

**Comment by DeltaNedas** [comment]
abandoned
cat is slep

**Comment by Anuken** [comment]
I'm just not too interested in merging a feature that's [already been implemented in 6.0](https://github.com/Anuken/Mindustry/blob/6.0/core/src/mindustry/type/UnitDef.java#L111), as it will only cause merge conflicts and won't be compatible with this version anyway.

**Comment by egg-chad** [comment]
yes please close

**Pull request closed without merging**
