### PR TITLE
Finishing french translation for release

### PR DESCRIPTION
**Pull request by Phinner**
Mmmmh, the release date is approaching and there's a lot of text to translate.
If a kind French passing by wish to help, translate beginning from the end of the file, please ;-;.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by PainOchoco** [comment]
Hello there, how can I help?

**Comment by Phinner** [comment]
Ok, I made a TODO list of sections to translate and verification :

- [ ] Translate 1775 to 1794

- [ ] Translate 1796 to 1816

- [ ] Translate 1841 to 1858

- [ ] Translate 2011 to 2101 (big one, split in half)

  - [ ] Translate 2011 to 2051
  
  - [ ] Translate 2052 to 2101

- [ ] Verify the translated strings of this PR

- [ ] Verify the overall file

@PainOchoco, pick one you wish to do and don't forget to verify the hard translations with [LanguageTool](https://languagetool.org/).

**Comment by Phinner** [comment]
I will translate 1796 to 1816 today.

**Comment by Phinner** [comment]
Bruh, I translated the wrong range...

**Comment by PainOchoco** [comment]
Alright, i'll translate from 2011 to 2101

**Comment by PainOchoco** [comment]
Translation done, how do I push to your branch?

**Comment by PainOchoco** [comment]
Also I think that setting up a Crowdin would be some much easier to track translations progresses and makes the translator job easier @Anuken.

**Comment by Anuken** [comment]
I believe I already looked at Crowdin as a solution, but the "open source" plan it offers doesn't apply to Mindustry due to its commercial use, and the word count doesn't look like it would accommodate the amount of text in Mindustry.

**Comment by Phinner** [comment]
@PainOchoco Sorry for my response time, looks like I did not received the notification of your comment. Well either you post it here as a comment or you PR it to the (erekir-end)[https://github.com/Xpdustry/Frenchdustry/tree/localization/erekir-end] branch.

**Comment by Phinner** [comment]
@PainOchoco This would be a really good time to submit your translations here.

**Comment by Anuken** [comment]
~~It's actually significantly sooner than that~~

**Pull request merged**
