### PR TITLE
Temporary PR

### PR DESCRIPTION
**Pull request by sk7725**
PR'd to make your github thingy make this into a jar file.

If draft PRs get the .jar treatment too, tell me so I can draft it.

### CODE REVIEW

**Comment by sk7725** [comment]
Wait, do we get jars for PRs? I remember seeing that feature but now I cannot seem to find it, huh

**Comment by Blockzilla101** [comment]
check the pr checks tab

**Comment by DeltaNedas** [comment]
drafts are built

**Comment by Anuken** [comment]
The JAR has been built, so I don't see why this should be kept open.

For future builds, you could just make a fork and set up CI there.

**Comment by sk7725** [comment]
> check the pr checks tab

thx

> For future builds, you could just make a fork and set up CI there.

The what now? ...okay...?

**Pull request closed without merging**
