### PR TITLE
Temporary Omega Server Change

### PR DESCRIPTION
**Pull request by RebornTrack970**

### CODE REVIEW

**Comment by Quezler** [comment]
was moving it up in the list really necessary?

**Comment by Darkness6030** [comment]
Yes, why?

**Comment by RebornTrack970** [comment]
> was moving it up in the list really necessary?
> Yes, why?

it wasnt, but why not.

**Comment by summetdev** [comment]
outstanding move

**Comment by Anuken** [comment]
Don't move the server on the list.

**Comment by RebornTrack970** [comment]
> Don't move the server on the list.

k, fixed???

**Comment by RebornTrack970** [comment]
But i rememebr MD putting it on top before... Smh

**Comment by Anuken** [comment]
> But i rememebr MD putting it on top before... Smh

I moved it back.

**Pull request merged**
