### PR TITLE
Better Team Indicator For Unit Factory

### PR DESCRIPTION
**Pull request by Voz-Duh**
The only thing I can say is that it looks cool
It will also help a lot when playing with other players.
image

### CODE REVIEW

**Comment by summetdev** [comment]
@Voz-Duh it doesn't compile.

**Comment by Voz-Duh** [comment]
> @Voz-Duh it doesn't compile.

Fixed

**Comment by Voz-Duh** [comment]
@Anuken you can pay attention to this pull?

**Comment by 5382Ander2** [comment]
I like this

**Comment by Voz-Duh** [comment]
> @Anuken you can pay attention to this pull?

**Comment by Quezler** [comment]
i would recommend not pinging anuke on github daily, he stated he gets all notifications, so just leave this open and alone for him to make his move :)

**Comment by genNAowl** [comment]
Yeah; Here's a system of equations to help clarify the point
much pinging = wrath of Anuke 
wrath of Anuke = scary

**Comment by Voz-Duh** [comment]
As Anuken told me - "Some pull I just don't see" _these are not exact words of anuken but the meaning is preserved_

**Comment by Anuken** [comment]
Why close this?

**Comment by Quezler** [comment]
> Why close this?

@Anuken looks like he deleted his fork, which for some strange reason closes all pull requests while still showing the diff 🤔

**Comment by Voz-Duh** [comment]
Oh, idk why but I can't reopen it, why this deleted???
If you want i can make new pull

**Pull request closed without merging**
