### PR TITLE
Duo

### PR DESCRIPTION
**Pull request by Twcash**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Twcash** [comment]
accidentally posted early

**Comment by JasonP01** [comment]
No ilya 👍 its joever

**Comment by JasonP01** [comment]
Are you sure anuke will approve serp having the erekir mechanic of range change, its entirely erekir specific and limited to gas ammo

**Comment by Twcash** [comment]
it's not limited to gas ammo look at tungsten breach

**Comment by Twcash** [comment]
also this PR was messed up I apologize. Posted another with proper stat changes and video

**Pull request closed without merging**
