### PR TITLE
Added \n and translated sentence

### PR DESCRIPTION
**Pull request by Vojtak42**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Vojtak42** [comment]
The sentence doesn't fit screen also in english

**Comment by Anuken** [comment]
It fits on *my* screen, but if there's a wrapping issue it should be fixed in the dialog, not by inserting newlines.

**Comment by Vojtak42** [comment]
Ok, I left only translation without \n but unfortunately I don't know how to fix it in dialogs.

**Comment by Anuken** [comment]
Wrapping fixed in master branch.

**Pull request merged**
