### PR TITLE
STOP ASKING ME

### PR DESCRIPTION
**Pull request by MEEPofFaith**
EVERYONE STOP ASKING ME TO MAKE HIDEDETAILS FALSE BY DEFAULT
(why can't you guys just pr it yourself...)

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by TranquillyUnpleasant** [comment]
Isn't this basically saying screw you to anyone who doesn't want blocks to be spoiled?

**Comment by Anuken** [comment]
This is a very messy solution; if it's really a problem for mods, just remove the hideDetails flag altogether and make it only apply to vanilla items.

**Comment by sk7725** [comment]
The *worst* case would be to strip this feature away from mods entirely,as  it was a nice feature for mods with actual lore, and gives incentive to play modded campaign.

**Comment by MEEPofFaith** [comment]
*There're reasons why I was against the like 3 people who kept asking me to make it false by default.*

**Pull request closed without merging**
