### PR TITLE
Beep boop add f-droid

### PR DESCRIPTION
**Pull request by Quezler**
Full credit to @ZacBytes for the [initial](https://github.com/Anuken/Mindustry/pull/1086) implementation.

Screen Shot 2019-11-18 at 20 21 12

### CODE REVIEW

**Comment by Arkanic** [comment]
i was just about to do that

**Comment by Arkanic** [comment]
also, what
image

**Comment by Quezler** [comment]
the large + - is due to the sprites being regenerated ^

**Comment by Arkanic** [comment]
oh ok

**Pull request merged**
