### PR TITLE
so i made a slag heater

### PR DESCRIPTION
**Pull request by BlueWolf3682**
dont mind the commit spam i am a mess

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
JAVA BLU WOOOOOO

**Comment by Cry0flu1d** [comment]
<strike>in fact I want to make this too</strike>

**Comment by EclipseTheOldOne** [comment]
BLU DOING JAVA???

**Comment by GlennFolker** [comment]
~it's just json in a form of java h~

**Pull request merged**
