### PR TITLE
unit/building specific targeting and collision for turrets and bullets

### PR DESCRIPTION
**Pull request by MEEPofFaith**
More turret specialization I guess.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by BlueWolf3682** [comment]
now do hitUnits and hitBuildings for bullets because you cant actually make a bullet only hit structures, it still hits ground

**Comment by MEEPofFaith** [comment]
> now do hitUnits and hitBuildings for bullets because you cant actually make a bullet only hit structures, it still hits ground

oh boy time to make a ton of code changes that'll make anuke not want to accept the pr

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/140705003-6ad6255e-ff26-423a-a862-bd3433bc0735.mp4

**Comment by MEEPofFaith** [comment]
now to bloat some code to make it work with lasers

**Comment by LeoSko** [comment]
The bullet flies **above** flying unit and doesn't hit it, from ground-standing turret?

**Comment by MEEPofFaith** [comment]
> The bullet flies **above** flying unit and doesn't hit it, from ground-standing turret?

That's just draw layer, nothing I can do about that.

**Comment by MEEPofFaith** [comment]
Surprisingly no code bloat needed.

https://user-images.githubusercontent.com/54301439/140707471-2d159409-2ea5-4576-bc75-3543ec435db6.mp4

**Comment by MEEPofFaith** [comment]
what

**Comment by sk7725** [comment]
at this point you are making something that should not be able to work with json work with json, causing code bloats that i am unsure Anuke will ever use (or any individual besides bluewolf).

**Comment by MEEPofFaith** [comment]
I have escaped the basement

**Comment by Anuken** [comment]
This is super-conflict-y now, so I'll be closing it. Not sure if still relevant anymore.

**Comment by MEEPofFaith** [comment]
~~I can't remember why I made this~~

**Comment by Anuken** [comment]
good

**Pull request closed without merging**
