### PR TITLE
Finishing pt br translation

### PR DESCRIPTION
**Pull request by JeanJPNM**
I finished translating everything i could and i also polished a few sentences

### CODE REVIEW

**Comment by Pietro303HD** [comment]
prepare to die

**Comment by Pietro303HD** [comment]
everything is wrong

**Comment by JeanJPNM** [comment]
> everything is wrong

oh shi-

**Comment by JeanJPNM** [comment]
guess i will die

**Comment by JeanJPNM** [comment]
I would like to say that the translation back to english could not have quite the same meaing because i had to use the names in portuguese defined before in the file rather than just pasting the text into an translator

**Pull request closed without merging**
