### PR TITLE
bring back block select timeout

### PR DESCRIPTION
**Pull request by DeltaNedas**
not sure why it was removed...

### CODE REVIEW

**Comment by Anuken** [comment]
How about setting it at a default sane value instead?

**Comment by DeltaNedas** [comment]
the default is the same as it was before, no?

**Comment by Anuken** [comment]
Yes, but it's not good if people need to change it.

**Comment by AbbyNode** [comment]
Personally, I prefer to keep it around 300-400ms but I'm not sure if that's the same with everyone. A hard-coded value that feels comfortable to one person may seem too fast or too slow to someone else. I think having the option is nice, at least for accessibility if nothing else.

**Comment by DeltaNedas** [comment]
ok how about 500ms? nice and round

**Comment by AbbyNode** [comment]
That would be better than 700ms, but I would really like to have the option to fine-tune it on the client. :)

**Comment by Kyllingene** [comment]
>Yes, but it's not good if people need to change it.

@Anuken, why is that? Was there some performance issue? This purely affects client-side, so no multiplayer problems are apparent. Why was it removed?

**Comment by Anuken** [comment]
> why is that?

Because defaults should be reasonable values. Does anybody use it at 700ms?

> Why was it removed?

I never used it, I wasn't the one who added it, and it wasn't clear if anyone needed it.

**Comment by Kyllingene** [comment]
Well, I guess unused features are simply RAM and storage space waste.

**Comment by Anuken** [comment]
It was just a big obvious slider at the top of my list of options with no clear purpose.

**Comment by Kyllingene** [comment]
That's fair.

**Comment by Anuken** [comment]
I'll keep the default at 400ms and see if someone else has issues with it.

**Pull request closed without merging**
