### PR TITLE
Fixed #4791 since it is 100% a bug

### LINKED ISSUE #4791: Auto bridge doesn't respect conveyor rotation
**Platform**: Windows

**Build**: BE build 20820

**Issue**: The newly added auto bridge doesn't rotate the bridge links when the conveyor is rotated with the scroll wheel.

**Steps to reproduce**: Just try placing a conveyor and rotating it, the bridges will link backwards: https://aethex.is-a.fail/Dw8vEZ.webm

**Link(s) to mod(s) used**: NA

**Save file**: [338.zip](https://github.com/Anuken/Mindustry/files/6046280/338.zip)

**(Crash) logs**: NA

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

### PR DESCRIPTION
**Pull request by buthed010203**
This fix is somewhat janky as it checks if the rotation matches the exact original rotation but the likelihood of someone needing bridges along a belt rotated 1 or -1 times is super low. https://aethex.is-a.fail/t13ETd.webm

### CODE REVIEW

**Comment by buthed010203** [comment]
Ok I changed it so it now only rotates the bridges when the belt is rotated twice

**Comment by Anuken** [comment]
1. This doesn't look like it actually works. Rotation happens after placement lines are calculated.
2. Doesn't match style guidelines.
3. Doesn't check for nulls (use an IDE, it warns about `@Nullable`) or empty lists. May crash.

> it is 100% a bug

It is not. Bridges **do not rotate.**

**Comment by buthed010203** [comment]
> It is not. Bridges do not rotate.

@Anuken I understand that but it just makes sense for the links themselves to be in reverse order to match the direction in which items are flowing.

Always forget about style guidelines, intellij says absolutely nothing about any of this being nullable, I don't see how my code could cause any crashes that the existing code couldn't.

**Comment by Anuken** [comment]
> intellij says absolutely nothing about any of this being nullable

You likely need to configure Mindustry's `Nullable` annotation to show up in the settings.

> I don't see how my code could cause any crashes that the existing code couldn't.

`tile()` can be null.

**Comment by buthed010203** [comment]
> `tile()` can be null.

Ah yeah that was totally an oversight on my part.

@Anuken The rotation happens after the line is calculated but that shouldn't really be a problem considering that the line is recalculated every time the line is rotated anyways

**Comment by buthed010203** [comment]
Ok that should be everything

**Pull request merged**
