### PR TITLE
Weapon Upgrade Rework

### PR DESCRIPTION
**Pull request by Anuken**

### CODE REVIEW

**Comment by Luxray5474** [comment]
~~Weren't you gonna be gone fore two days? lol~~

**Comment by Anuken** [comment]
@Luxray5474 I was, but now I'm back.
~~also you literally replied to this merge 2 seconds after I made it, _what the heck_?~~

**Comment by Luxray5474** [comment]
Email notifications. And it's kinda weird how GitHub tells me so fast... 🤔

**Comment by Luxray5474** [comment]
Also I guess it was because i didn't scroll down in #announcements on the discord server

**Pull request merged**
