### PR TITLE
Melter & Pulverizer Fix

### PR DESCRIPTION
**Pull request by Voz-Duh**
image

### CODE REVIEW

**Comment by Anuken** [comment]
image

cursed sprites

**Comment by Quezler** [comment]
ah, so its not just me github failed to load the previews for ^

**Comment by Anuken** [comment]
Yeah, I even refreshed several times, with no results.

**Comment by Quezler** [comment]
seems to be a github wide issue: https://github.com/Anuken/Mindustry/pull/999/files?short_path=88d9a63

**Comment by Voz-Duh** [comment]
> image
> 
> cursed sprites

Problem not in my sprites

Please click it:
image

image

**Comment by bvcbvc** [comment]
the issue seems fine now, and i think this deserves to be merged

**Comment by Anuken** [comment]
Keep this open, I'll merge it in 7.0.

**Comment by bvcbvc** [comment]
That's gonna be some time, but I'll wait

**Pull request merged**
