### PR TITLE
Enable mining of sand when double click to mine is enabled

### PR DESCRIPTION
**Pull request by buthed010203**
Since the only reason sand is un-mineable in the first place is because accidentally mining it is annoying, it should be enabled for double click to mine.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
> Since the only reason sand is un-mineable in the first place is because accidentally mining it is annoying, it should be enabled for double click to mine.

Have you actually confirmed if that's the reason?

**Comment by buthed010203** [comment]
> Have you actually confirmed if that's the reason?

I havent asked anuke but based on the javadoc it would seem so yes, I have had double click mineable sand in my client for quite a while and it works with no issues.

**Comment by Thankyou69** [comment]
yay its getting up there

**Comment by catatagun** [comment]
Yes

**Pull request merged**
