### PR TITLE
Color Picker Text Input

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/178862406-38f3553c-67a7-4263-a60f-418201badea1.mp4

~~No I will not bother pausing my music.~~

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.
- [ ] TODO: Make the slider/text update when the other is changed. I don't know how I'm gonna do that.

### CODE REVIEW

**Comment by Anuken** [comment]
I feel like this is unnecessary when the whole RGB picking system is bad. It should use hex input instead.

**Comment by MEEPofFaith** [comment]
I thought about making a hex input, but then didn't know how I would make it check if it's a valid hex or not.

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/178908284-3b315cac-4e26-45ee-b6c9-51ae91fba6b1.mp4

Oh cool typing in an invalid hex code does not crash the game.

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/178910042-d7a4f4c6-94ab-4c1c-8791-6fef528acce4.mp4

**Comment by GlennFolker** [comment]
You know, I thought about revamping the whole color picker UI entirely do that it uses HSV instead (or probably have it as an "other option"), but never ended up doing it. I wonder if someone else would do the job?

**Pull request closed without merging**
