### PR TITLE
Add mindurka to v7 list

### PR DESCRIPTION
**Pull request by Darkness6030**

### CODE REVIEW

**Comment by Quezler** [comment]
i'm not sure anuke is implying his is to be the only one on the list or not 🤔 

Screen Shot 2021-06-25 at 11 04 46

**Comment by Darkness6030** [comment]
Bruh

**Comment by osp54** [comment]
> i'm not sure anuke is implying his is to be the only one on the list or not 🤔
> 
> Screen Shot 2021-06-25 at 11 04 46

I don’t think so.

**Comment by Quezler** [comment]
yea i suppose

**Comment by Darkness6030** [comment]
Closed cuz made new

**Pull request closed without merging**
