### PR TITLE
Option to parentize status effect effects

### PR DESCRIPTION
**Pull request by MEEPofFaith**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by sk7725** [comment]
Note: ***do not make the default value true please***

**Comment by MEEPofFaith** [comment]
> Note: _**do not make the default value true please**_

Did you not read the code you h.

**Comment by MEEPofFaith** [comment]
> Note: _**do not make the default value true please**_

~~Did you not see the word "Option" you h~~

**Comment by buthed010203** [comment]
~~Did you forget that you replied already and reply again?~~

**Pull request merged**
