### PR TITLE
Vietnamese translations

### PR DESCRIPTION
**Pull request by NgLamVN**
* This PR was tested in-game and is ready to merge at any time (unless marked as draft).
* Thanks to @YellOw139 for making vietnamese charactor.

* Everyone can make PR in my folk to help this project complete faster.

### CODE REVIEW

**Comment by NgLamVN** [comment]
Lol now i haz 1k+ lines to do left :v

**Comment by Anuken** [comment]
image
image

https://github.com/Anuken/Mindustry/pull/3524
https://github.com/Anuken/Mindustry/pull/3219
https://github.com/Anuken/Mindustry/pull/3167
https://github.com/Anuken/Mindustry/pull/3167
https://github.com/Anuken/Mindustry/pull/3073
https://github.com/Anuken/Mindustry/pull/3262
https://github.com/Anuken/Mindustry/pull/3253

This is getting out of hand.

**Comment by YellOw139** [comment]
Technically there's 3 authors, so you can count that as 3 PRs.
Out of which if you look in the bundle, #3167 is the least translated, so I'd scrap that.

There's still #3524 and #3219. If I were you, I'd try to pick the one that can be ready for v6 and is accurate. How you are going to choose the best one is to be sorted out by you and the 2 translators. 

All I know is that NgLamVN is the one that has requested the Vietnamese character set, and the one who started translating before the game had the characters. He clearly showed understanding of both English and Vietnamese, as he knew which characters I needed to make, and even recommended me software to type them out. He also seems to know what draft PRs are. The others never marked anything as draft despite me telling them to and even how to, so how much so they care to do this right after all?

Now it's up to you who you trust.
I know nobody asked me, but I care, because I too worked on this.

P.S.: BTW what's with _vi and _vn? Which one is correct after all?

**Comment by NgLamVN** [comment]
I haven't learned Java yet, so i transalate this game.

**Comment by NgLamVN** [comment]
#3219 I am very sure he is using Google Translate.
For example, if "wave" is mean "sóng", why he translate wave defeated to "wave bị đánh bại" instead of "sóng bị đánh bại" ????

P.:S.: in vietnamese language, google translate is very "SUCK".

**Comment by YellOw139** [comment]
Hmm... I checked and the other PR doesn't even have the new tutorial. Now it's up to you whether you think a new translation needs a tutorial to be admitted.

As far as I know, your game changes itself to the system language automatically, and a new non-English-speaking player without a tutorial could be very confused.

**Comment by NgLamVN** [comment]
May be i need to translate tutorial instead.

**Comment by NgLamVN** [comment]
About 60% complete.

**Comment by NgLamVN** [comment]
800/1500

**Comment by NgLamVN** [comment]
About 500 lines left... but it really hard to translate correctly, so it cost me more and more time to do that.

**Comment by NgLamVN** [comment]
65% complete.

**Comment by NgLamVN** [comment]
Will I complete this before v6 release ? 
I dont know but i need more than 3 days to complete.
Speed Up.

**Comment by LeTuanVN** [comment]
Im not a programer but i could transalate quite good
Could i join

**Comment by NgLamVN** [comment]
@LeTuanVN Just make pull request to my folk repository ~~

**Comment by NgLamVN** [comment]
> Im not a programer but i could transalate quite good
> Could i help?

Just translate and make pull request on my folk repository.

**Comment by NgLamVN** [comment]
@JINODK

**Comment by JINODK** [comment]
maybe?

**Comment by NgLamVN** [comment]
Yay. Help me translate some description from line 1286 to 1490 👍

**Comment by NgLamVN** [comment]
Ready to merge ~~

**Pull request merged**
