### PR TITLE
add some suggested mods

### PR DESCRIPTION
**Pull request by DeltaNedas**
currently
- my routorio and anuke-logic
- sk commands and time control
- nothing by gdeft

if you have suggestions for solid v6 mods post em

### CODE REVIEW

**Comment by routuer** [comment]
bleach is too good to be in suggested mods.

**Comment by DeltaNedas** [comment]
hmm i agree
@Gdeft input?

**Comment by Slava0135** [comment]
R E V I S I O N

**Comment by Slava0135** [comment]
Roses are red
Violets are blue
Revision has more stars
Than routorio mod do

**Comment by Bohaska** [comment]
Add dev mode

**Comment by XTeamXeno** [comment]
A utility mod for multiplayer

**Comment by sk7725** [comment]
please add sk7725/TimeControl, a mod that controls the Mindustry play speed.

**Comment by sk7725** [comment]
Also, shouldnt it be sorted by alphabetical order to prevent possible arguments/conflicts? And maybe use a separate text file for it?

**Review by sk7725 — CHANGES_REQUESTED** [review]
Suggestion: Sort mods by 1.user name order(so mods by DeltaNedas are nect to each other) and 2. repo alphabetical order(self explanetory)

**Comment by BlueWolf3682** [comment]
what is the point of this? its literally just advertisement.

**Comment by sk7725** [comment]
> what is the point of this? its literally just advertisement.

We need trustworthy modmaker sources in 6.0, since 6.0 features jar mods that can contain hell-knows-what malicious code. Suggested mods will greatly help newbies steer clear of those mods.

**Comment by sk7725** [comment]
No such mods exist yet, well not even jar mods themselves, but that is a potential issue. And of course, 6.0 is just a day old, so of course they don't exist *yet*...Better safe than sorry, tbh

**Review by Bohaska — CHANGES_REQUESTED** [review]
Add DeltaNedas/dev-mode

**Comment by summetdev** [comment]
> Add DeltaNedas/dev-mode

Not many people know how to use console, and for common players it would be useless.

**Comment by Bohaska** [comment]
> > Add DeltaNedas/dev-mode
> 
> Not many people know how to use console (js), and for common players it would be useless.

but still, it should be built into mindustry because common sense.

**Comment by sk7725** [comment]
If you want a dev-mode but more accessible for common players, sk7725/Testers if for you!

Features: GUI and schematic saving, dedicated blocks for certain regions(ex. Draw and UI), and other weird stuff ~~such as cursed force~~

**Comment by Gdeft** [comment]
You don't need dev-mode or testers if you already have gdeft/bleach.

**Comment by Legomonster33** [comment]
instead of haveing mods built in to the game, have some mods availbe on the mod menu with a little download button
like an in game mod browser with anukes top mods at the top

**Comment by DeltaNedas** [comment]
ok i agree with having it as a list like servers but not too sure how to do it
@sk7725 ok

**Review by Slava0135 — CHANGES_REQUESTED** [review]
slava0135/revision

**Comment by summetdev** [comment]
> instead of haveing mods built in to the game, have some mods availbe on the mod menu with a little download button
like an in game mod browser with anukes top mods at the top

there's already PR for it https://github.com/Anuken/Mindustry/pull/2288.

**Comment by Legomonster33** [comment]
> ok i agree with having it as a list like servers but not too sure how to do it
> @sk7725 ok

steal the code from the server list, do some merge it with the mod menu, do some fancy code magic, voila you now have ~~working~~ mod menu

**Comment by DeltaNedas** [comment]
ok snip snipped some code its now in /suggested_mods.txt like server list

**Comment by DeltaNedas** [comment]
> slava0135/revision

done

**Comment by Bohaska** [comment]
Sort the mods first by name of author, then alphabetically.

**Comment by sk7725** [comment]
why the URL?  Cant you just Fi?

**Comment by Gdeft** [comment]
> why the URL? Cant you just Fi?

Just in case that when the txt file is updated you won't have to wait for the next release to get the updated suggested mods(?)

**Comment by DeltaNedas** [comment]
^, like how servers update for every version rather than on the next release

**Review by Bohaska — APPROVED** [review]
Extend suggested mod list into a ‘verified’ mod list and have a description saying that these mods have been verified as free of malware (suggested mod list is a subset of verified mod list and will be more prominent). Also add a search function for the mods (you can grab one from schematics code)

**Comment by Bohaska** [comment]
Whoops, I meant I wanted to request some changes

**Comment by Anuken** [comment]
Honestly, now that I think about it, suggested mods probably should not exist at all.

**Comment by Bohaska** [comment]
Change it from suggested mods to verified mods, cuz suggested mods sounds like advertising like what BlueWolf said

**Comment by Bohaska** [comment]
Anuken, would you accept it if the list was a list of verified mods that contain no malware instead of suggested mods?

**Comment by Anuken** [comment]
I cannot verify any such mods.

**Comment by Bohaska** [comment]
> I cannot verify any such mods.

Ok, makes sense.

**Comment by DeltaNedas** [comment]
theres basically 1 case for a mod to be malware, if you are scared read its code before installing it

**Comment by BlueWolf3682** [comment]
the chat went from advertisement to literal one upping each other to gain the highest standing

**Comment by Legomonster33** [comment]
Have a warning pop-up when first opening the mod browser, saying that third party add-ons might not be safe, continue at your own risk.

**Pull request closed without merging**
