### PR TITLE
Merge Shooting Functions to Use Multiple at Once

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/115444521-84983c80-a1c9-11eb-958f-d056717bc991.mp4

More turret customization go brrr.

### CODE REVIEW

**Comment by Anuken** [comment]
`shots` and `spread` are used extensively by mods, you can't just remove them.

**Comment by MEEPofFaith** [comment]
they still exist, I just split their purposes.
Shots did barrels and number of shots, separate that to 2 separate variables.
Spread did barrel spacing and angle spacing, separate that into 2 separate variables

**Comment by MEEPofFaith** [comment]
there isn't really an easy way to make them not ruin anything, which is kinda an issue.

~~but at least it works, unlike other things I create~~

**Comment by sk7725** [comment]
You must find a way to keep it compatible; I do not see a reason for it to be impossible.

**Comment by MEEPofFaith** [comment]
no idea how, I'm not big brained enough

**Comment by sk7725** [comment]
> no idea how, I'm not big brained enough

that's the equivalent of saying "my pr doesn't work properly, but I have no idea how to fix it, so here it is anyways"
You should be more responsible for your PRs

**Comment by MEEPofFaith** [comment]
Thing is it does work proporly.

**Comment by sk7725** [comment]
> Thing is it does work properly.

your definition of proper is wrong.

**Comment by MEEPofFaith** [comment]
> > Thing is it does work properly.
> 
> your definition of proper is wrong.

Does "properly" not mean that it works right and doesn't crash or anything?

**Comment by MEEPofFaith** [comment]
this'll never get merged

**Comment by MEEPofFaith** [comment]
Who's gonna ever need a burst spread charge alternate turret anyways?

**Comment by BlueWolf3682** [comment]
uh, me

**Comment by MEEPofFaith** [comment]
The issue with getting something like this merged is, well, breaking any mod that uses a turret.
Which is almost all of them.

**Comment by BlueWolf3682** [comment]
Then do it in a way that doesn't break everything.

**Comment by MEEPofFaith** [comment]
I have no idea how, since making spread and shoot spacing separate requires splitting one variable into 2.

**Comment by MEEPofFaith** [comment]
unless you want to keep it to 1 variable, and make shoot spread and barrel spacing tied to each other.

**Comment by MEEPofFaith** [comment]
~~Or maybe we could have Anuke do this himself if he has the time.~~

**Pull request closed without merging**
