### PR TITLE
[implementation] grey out unaffordable schematics

### PR DESCRIPTION
**Pull request by Quezler**
> an implementation of https://github.com/Anuken/Mindustry-Suggestions/issues/95 authored by @Katsute

Screen Shot 2020-04-13 at 10 00 53

> hopefully the ui code is good enough for anuke, i just threw science at the wall until it sticked

### CODE REVIEW

**Comment by Anuken** [comment]
This seems a bit too invasive; I wouldn't want most of my schematics library to get grayed out by default. How about an icon next to the name, or in the corner?

**Comment by Katsute** [comment]
Maybe icons indicating which resources are insufficient?

**Comment by Anuken** [comment]
Implementing a `number / required` numerical display with a red tint for missing resources in the schematic info shouldn't be difficult.

**Comment by Anuken** [comment]
image

**Comment by Quezler** [comment]
whoops, guess my mailbox was to flooded to notice this thread had activity 😅

**Pull request closed without merging**
