### PR TITLE
More Vietnamese language

### PR DESCRIPTION
**Pull request by nguyenphong9815**
More Vietnamese language
I cannot translate correctly because the game does not support signs and words :( ê ê ê ề ê)

### CODE REVIEW

**Comment by YellOw139** [comment]
@nguyenphong9815 What is your Discord username?
I am the guy who made the Vietnamese letters for the game, and I would like to know what doesn't work and help if needed. So I'd like to discuss this on Discord with you if possible. You can PM me: @YellOw#5623

**Comment by YellOw139** [comment]
Apart from the tilde on Ễ which I just noticed it's being a little weird (could try adjusting that), everything works for me. BE 10967
image

Could you please show me a picture of what's not working for you?

**Comment by YellOw139** [comment]
Also see this. Lots of characters which weren't in the game's font before have been recently added.
image
Which version are you on BTW?

**Comment by YellOw139** [comment]
BTW, the path of your file should be core/assets/bundles/bundle_vn.properties . Don't translate "core", "assets" etc. Doesn't work that way.

**Comment by nguyenphong9815** [comment]
Untitled

after translating the game does not show accented letters

**Comment by YellOw139** [comment]
That's weird. Which version are you on?
You need at least v6 Beta 111 or BE 10900 or something for the characters to show up.
The accented letters will not show up in Mindustry v5.

**Comment by YellOw139** [comment]
You can download the latest beta from here: https://anuke.itch.io/mindustry/download/eyJleHBpcmVzIjoxNjA0Mjk1MDQ4LCJpZCI6MTQwMTY5fQ%3d%3d.syz0Q4hNGP80bFBSNKh003J06LI%3d

**Comment by nguyenphong9815** [comment]
Untitled67
 
đã là b

**Comment by YellOw139** [comment]
Turns out my font commits didn't make it to Beta 111. Sorry. I really thought they did.
https://github.com/Anuken/Mindustry/compare/v111...master
See 'Delete font.woff' and 'Add new font.woff'. They are listed, which means they are newer than Beta 111, and have a smaller file (3,850,324 bytes Beta 111 vs 3,853,828 bytes BE 10990), which doesn't contain the new characters.

The new characters will likely appear in Beta 112. Until then, you can test your translation on the latest BE version.
Get it from here: https://github.com/Anuken/MindustryBuilds/releases

It should work on the BE builds. In case anything weird comes up though, leave a message here, I'll be watching this PR.

**Comment by YellOw139** [comment]
Beta 112.1 was released. Seems to work fine on the beta builds now.

**Comment by NgLamVN** [comment]
This translation is outdated.

**Pull request closed without merging**
