### PR TITLE
RockTheVote for server

### PR DESCRIPTION
**Pull request by Arkanic**
probably borked in about 50 ways

I need some help with the variables, they seem to be too global
i'll probably move them into the event

is < Player > necessary for non-plugin commands in this case? I think it's good to make sure things are working, but it might not be necessary in this case.

### CODE REVIEW

**Comment by Arkanic** [comment]
is half a good amount or does it need a increase?

**Comment by Anuken** [comment]
Read the [contributing guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md), you've violated a few of them here.

**Comment by Arkanic** [comment]
i felt like i did

**Comment by Arkanic** [comment]
i don't have a way of testing the commit though

**Comment by Arkanic** [comment]
@Anuken what would i have to do to remove the boxing? i'm honestly not too sure what i'd do

**Comment by Anuken** [comment]
You don't have any boxing there. I was mostly referring to how it doesn't compile (or, if it did, it wouldn't work)

**Comment by Arkanic** [comment]
i'm assuming that was with HashSet rather than ObjectSet
i forgot to import it

**Comment by Arkanic** [comment]
@Anuken does ```ObjectSet``` have a size or length function?

**Comment by Anuken** [comment]
1. No, but it does have a variable.
2. Are you using IntelliJ? If not, get it. You won't need to ask questions like that with autocomplete around.

**Comment by Arkanic** [comment]
yeah, i'm kinda giving up on eclipse with it's caches that don't auto update

**Comment by Arkanic** [comment]
i'll fix this later, just becoming stale right now

**Pull request closed without merging**
