### PR TITLE
thêm group máy chủ theo lời của router

### PR DESCRIPTION
**Pull request by gttfx**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Phinner** [comment]
You are kinda sus sir

**Comment by gttfx** [comment]
merge help me ?

**Comment by gttfx** [comment]
hehe

**Comment by NgLam2911** [comment]
You should write ur PR in English bruh...

**Pull request closed without merging**
