### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AmateurPotion**
hey?

### CODE REVIEW

**Comment by Quezler** [comment]
why hello there 👋

**Comment by AmateurPotion** [comment]
> why hello there 👋

**Comment by AmateurPotion** [comment]
> > why hello there 👋

**Comment by AmateurPotion** [comment]
In a Windows environment, sometimes errors occur when bat is not used.

**Comment by DeltaNedas** [comment]
in CMD (not powershell) the path looks for *.exe, *.bat, *, doesnt it?

**Pull request merged**
