### PR TITLE
S

### PR DESCRIPTION
**Pull request by rodrigolitzius**
a "S" that is not supposed to be there.

### CODE REVIEW

**Comment by SnakkiZXZ** [comment]
what?

**Comment by rodrigolitzius** [comment]
"a "S" that is not supposed to be there."... i just removed the S, probably is a typo

**Comment by Volas171** [comment]
> "a "S" that is not supposed to be there."... i just removed the S, probably is a typo

that S was supposed to be there , see what it says below this comment

**Comment by TheMrAlbert** [comment]
Seems like it's just very tiny translations fix. The question is:
Are you sure that translations is correct which is in Portuguese (Brazil)?

**Comment by rodrigolitzius** [comment]
> Seems like it's just very tiny translations fix. The question is:
> Are you sure that translations is correct which is in Portuguese (Brazil)?
> 
> P.S. I do not translate Portuguese (Brazil). Just saying that if the translation is correct or not.

yeah, it's correct, if you look, all the large walls (i think)
are with "Ocupa múltiplos blocos." but playing the game, i saw an S, "SOcupa múltiplos blocos." that doesn't make sense. i have 99% sure that is a typo.

**Comment by rodrigolitzius** [comment]
> > "a "S" that is not supposed to be there."... i just removed the S, probably is a typo
> 
> that S was supposed to be there , see what it says below this comment

how did you know that is correct? do you speak portuguese?

**Comment by TheMrAlbert** [comment]
> > > "a "S" that is not supposed to be there."... i just removed the S, probably is a typo
> > 
> > 
> > that S was supposed to be there , see what it says below this comment
> 
> how do you know that is correct? do you speak portuguese?

No! I do translate Indonesian language instead. I have inspected bundle.properties first and compare it with this change. For the change you have made as I see, it don't break anything in-game.

**Comment by TheMrAlbert** [comment]
It's just seems like a small typo fix.

**Comment by rodrigolitzius** [comment]
yeah, it's just a typo fix.

**Review by RandomTNT — COMMENTED** [review]
Yes, a small typo

**Pull request merged**
