### PR TITLE
Add capacity indicator to vaults and containers.

### PR DESCRIPTION
**Pull request by SummetDev**
This is how they will look:
mindustry-vault-capacity
mindustry-container-capacity

### CODE REVIEW

**Comment by itcannotbe** [comment]
Have you considered that vaults can actually hold more than 1 item which has it's own limit?

**Comment by TheSlaylord** [comment]
I think indicators will work just like an indicator in the core.

**Comment by Summet-V** [comment]
Ok, now it works the same as with cores.
mindustry-vault-capacity-fixed

**Comment by itcannotbe** [comment]
Wouldn't this cause confusion? Since technically the limit is still 1000 for vaults and 300 for containers.

Doing Capacity * Known Items would confuse more people than help them especially when used not connected to the core.

**Comment by Summet-V** [comment]
Last change: It will show how much vault/ container holds for one resource, and the green bar will show the capacity for all items.

**Comment by summetdev** [comment]
Conflicts resolved.

**Pull request closed without merging**
