### PR TITLE
Update bundle_ru.properties

### PR DESCRIPTION
**Pull request by jeronimoCat**
There were a lot of grammar errors an Google-like translations and it was bugging me, so I corrected them. And I'm not done yet.

### CODE REVIEW

**Comment by BasedUser** [comment]
Other than metal floor 5, you've done well

**Comment by Remint32** [comment]
> 
> 
> Other than metal floor 5, you've done well

https://github.com/Anuken/Mindustry/issues/661

**Comment by jeronimoCat** [comment]
> Other than metal floor 5, you've done well

Thanks, i will come back to it later

**Comment by Anuken** [comment]
What is the status of this PR? Should it still be merged?

**Comment by jeronimoCat** [comment]
> What is the status of this PR? Should it still be merged?

No, because I want it complete and I don't have time to do it right now.

**Comment by YaFou** [comment]
The pull request looks like stale. I think you should close it because the author (@jeronimoCat) is inactive for a few months. And others pull requests are merged like #1104 or #1172.

**Pull request closed without merging**
