### PR TITLE
unit capacity typo

### PR DESCRIPTION
**Pull request by liuxilu**
<del>AFAIK, it's `Unit Modifiers`
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ai/BlockIndexer.java#L335-L345</del>

Full spelling, I thought unit wearing caps.

### CODE REVIEW

**Comment by Cherriodude** [comment]
Cores itself is correct, afaik you can only increase unit cap with cores.

**Comment by Cherriodude** [comment]
Cores itself is correct, afaik you can only increase unit cap with cores.

**Comment by liuxilu** [comment]
Sorry, my fault, `unitModifier` refers to `unit capacity modifier`.

**Comment by XEN0PHIL** [comment]
Also look into:
1. Max = Maximum;
2. Ammo = Ammunition.
/s

**Comment by liuxilu** [comment]
Well, but these two do not make confusion.
Fine, this is not welcomed.

**Pull request closed without merging**
