### PR TITLE
6.0/multiForge

### PR DESCRIPTION
**Pull request by SnakkiZXZ**
How about combining improved furnaces? I propose to put on a _large silicon oven_, with a _large furnace metaglass_. 
This will reduce the number of improved versions of the furnaces and diversify the game
miniGif_20200512232506
Here I have united two ovens, and made a choice of the right recipe with the help of buttons. My code is far from going and requires refinement.

Sprites I'll attach here
multiForge

> it's recycling my old request

### CODE REVIEW

**Comment by zethnest** [comment]
File name is wrong. It's not in the correct directory/folder. This is not how you make a pull request.

**Comment by SnakkiZXZ** [comment]
I used JavaScript, I don't know where to put it😥

**Comment by zethnest** [comment]
What you're doing is a mod. You should create your own repository. If you are to contribute to this repository, you'd need Java.

**Comment by Anuken** [comment]
This block just doesn't belong in the game.

**Pull request closed without merging**
