### PR TITLE
[rules] custom mech

### PR DESCRIPTION
**Pull request by Quezler**
> prototype (warning: overrides existing "alpha" factories to spawn "darts")

This pull adds an option in the custom rules to select which mech players spawn in by default.
(and ensures a mech pad exists that can spawn darts, and reorders them neatly in the build menu)

Screen Shot 2019-12-21 at 16 36 01
Screen Shot 2019-12-21 at 16 34 16
Screen Shot 2019-12-21 at 16 36 31

https://feathub.com/Anuken/Mindustry/+96

### CODE REVIEW

**Comment by DeltaNedas** [comment]
god damn anuke please

**Comment by BasedUser** [comment]
```Dart Mech Pad```

pls fix

**Comment by Quezler** [comment]
@BasedUser dart mech pad is fixed in this pull 😗(if i can read your mind that is)

**Comment by CA6** [comment]
hmmmmmmmmmmmmmmmm....would make (if mechs were properly balanced) a interesting way of fast pvp or higher level cores could spawn higher tier mechs  and would/could have an intresting impact on a expanded campaign

**Comment by Anuken** [comment]
Not applicable anymore in 6.0.

**Pull request closed without merging**
