### PR TITLE
Upload game data to custom cloud 

### PR DESCRIPTION
**Pull request by hhjxx**
1. Export and upload the game data to a http server.
2. Download and import the data from the http server.
Storage server sample: https://github.com/hhjxx/CloudSave

### CODE REVIEW

**Comment by Darkness6030** [comment]
bro
thats amazing, but anuke usually doesnt accept PRs with new libraries
is it possible to make this without any new libraries, only with ARC?

**Comment by hhjxx** [comment]
> bro thats amazing, but anuke usually doesnt accept PRs with new libraries is it possible to make this without any new libraries, only with ARC?

thanks for your advice, let me try replace it with ARC

**Comment by Anuken** [comment]
As I understand it, this requires a user to host their own server for cloud saves. I think very, very few users would utilize such a feature. It's far easier to just set up folder sync with an existing cloud storage provider.

**Comment by hhjxx** [comment]
> As I understand it, this requires a user to host their own server for cloud saves. I think very, very few users would utilize such a feature. It's far easier to just set up folder sync with an existing cloud storage provider.

How about using github as a cloud storage provider, upload the zip data to a repository and download from it then import it. @Anuken can you advise?

**Comment by Anuken** [comment]
That sounds like a horrible idea still, and very few would use it regardless.

**I do not wish to add cloud storage to the game itself.** Just use folder sync.

**Pull request closed without merging**
