### PR TITLE
Update bundle_ja.properties

### PR DESCRIPTION
**Pull request by ulwepo**
I'm ulwepo from Sakura server.
It is a translation file with the same content as the Japanese Mod in the repository below. Thank you.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
So I merged a different translation, and now there are 56 conflicts. Which is better?

**Comment by ulwepo** [comment]
@Anuken 
Thank you for confirming. 
I have also checked. 
There will be no problem if you use the translations I pushed.
Thank you.

**Comment by Takeno-hito** [comment]
Ok sorry, "no destructive change" is my miss-understanding. I checked the master-branch, and still I think this pr is better.

**Comment by Anuken** [comment]
Merged manually.

**Review by Takeno-hito — COMMENTED** [review]
I forgot to send my review. But all of these are not major miss-translation. I will update file at a later date.

**Pull request closed without merging**
