### PR TITLE
Fix tree branch overlap

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Before:
Mindustry_p9x0DhCN7S
After:
javaw_0Va6p3KeXB

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
image


"But at what cost?"

**Comment by MEEPofFaith** [comment]
oh no

**Comment by MEEPofFaith** [comment]
that is... quite the mess

**Comment by MEEPofFaith** [comment]
I'll look into it

**Comment by MEEPofFaith** [comment]
~~You know it really doesn't help that I have no idea how tech tree draw even works.~~

**Comment by MEEPofFaith** [comment]
Yea I have no idea what I'm doing.

**Pull request merged**
