### PR TITLE
add ContentInitEvent

### PR DESCRIPTION
**Pull request by DeltaNedas**
fired after ContentLoader#init() is called

allows for stuff like
```
Events.on(ContentInitEvent, () => {
    Vars.content.blocks().each(b => {
        b.health = 1;
    });
});
```

### CODE REVIEW

**Comment by DeltaNedas** [comment]
i will test it dont worry

**Comment by DeltaNedas** [comment]
h are the eventtype imports manually defined

**Comment by DeltaNedas** [comment]
now catching errors so i dont need to check stdout to debug mod

**Comment by DeltaNedas** [comment]
@Anuken it works please merge

**Comment by DeltaNedas** [comment]
example mod DeltaNedas/ldb, DeltaNedas/override-lib

**Comment by summetdev** [comment]
~~how about squashing commits after fails?~~

**Comment by DeltaNedas** [comment]
~~lazy~~

**Comment by DeltaNedas** [comment]
@Anuken ready to merge

**Pull request merged**
