### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by VNdustryComeback**
i want add a server for Vietnam people lowest ping !

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
Server is offline

**Comment by VNdustryComeback** [comment]
> Server is offline

Sorry, damn the server rental company is not reputable at all, please reconsider I changed the provider

**Comment by VNdustryComeback** [comment]
> i want add a server for Vietnam people lowest ping !
> 
> If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:
> 
> * [x]  I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
> * [x]  I have ensured that my code compiles, if applicable.
> * [x]  I have ensured that any new features in this PR function correctly in-game, if applicable.

Screenshot_20240603-093304_Mindustry
Low Ping

**Comment by VNdustryComeback** [comment]
@Anuken can u add server ?

**Pull request merged**
