### PR TITLE
Complete translation and full italian bundle

### PR DESCRIPTION
**Pull request by Diegator04**
I worked on this for several hours checking and revising the already existing translation and the new ones. I added some **missing descriptions, details** and the newest elements (_of V6_) with their **suitable translation** into Italian. I always used my knowledge but if I wasn't sure about one translation I consulted **Collins Dictionary as reference** and sometimes others sources. I hope you appreciate my work and the rendering that **is currently "synchronized" with main bundle.**
I've already tested it and I didn't notice **any problem.**

### CODE REVIEW

**Comment by Anuken** [comment]
Why close this?

**Comment by DeltaNedas** [comment]
the cia got to him

**Comment by Diegator04** [comment]
> Why close this?
https://travis-ci.org/github/Anuken/Mindustry/builds/743011363?utm_source=github_status&utm_medium=notification tells that failed so i was gonna to try again.

**Comment by Diegator04** [comment]
@Anuken am i doing something wrong?

**Comment by Anuken** [comment]
Travis CI fails rather often; it's not related to translation bundles.

**Comment by Diegator04** [comment]
> Travis CI fails rather often; it's not related to translation bundles.

So what i should do?

**Comment by Anuken** [comment]
Nothing, it's not a problem.

**Comment by Diegator04** [comment]
> Nothing, it's not a problem.
Ok, so if it isn't a problem...how works exactly? Is this gonna be implemented?

**Comment by Anuken** [comment]
Yes.

**Comment by Diegator04** [comment]
> Yes.
Thx 👍 
Did somebody already check that (i mean the correctness) ? Or the checks (only about conflicts) are done only by Travis and java CI ?

**Comment by Catchears** [comment]
>Did somebody already check that (i mean the correctness) ?

People tend to request changes or approve the changes you've done. Travis just makes sure the game compiles.

**Comment by Diegator04** [comment]
> > Did somebody already check that (i mean the correctness) ?
> 
> People tend to request changes or approve the changes you've done. Travis just makes sure the game compiles.

Yeah, I understood that. So if this is approved, it will be added to Mindustry, won't it?

**Comment by Catchears** [comment]
Correct.

**Comment by Mindustry-Merda** [comment]
HAHAHAHAH, have you really wasted time on this shit game?!?! HAHAHAHAH, Mindustry is the evil of the world, like Diegator04...

**Comment by Mindustry-Merda** [comment]
> Ci ho lavorato per diverse ore controllando e revisionando le traduzioni già esistenti e quelle nuove. Ho aggiunto alcune **descrizioni mancanti, dettagli** e gli elementi più recenti ( _di V6_ ) con la loro **traduzione** in italiano. Ho sempre usato le mie conoscenze, ma se non ero sicuro di una traduzione ho consultato il **Collins Dictionary come riferimento** e talvolta altre fonti. Spero che apprezziate il mio lavoro e il rendering che **attualmente è "sincronizzato" con il bundle principale. **
> L'ho già provato e non ho notato **alcun problema.**

What are you doing???? Am I scaring you??? Answer at my comment idiot!!!

**Comment by Mindustry-Merda** [comment]
> I worked on this for several hours checking and revising the already existing translation and the new ones. I added some **missing descriptions, details** and the newest elements (_of V6_) with their **suitable translation** into Italian. I always used my knowledge but if I wasn't sure about one translation I consulted **Collins Dictionary as reference** and sometimes others sources. I hope you appreciate my work and the rendering that **is currently "synchronized" with main bundle.**
> I've already tested it and I didn't notice **any problem.**

HAHAHAHAH, didi you really waste time at this shit game??? Mindustry is the evil of the world, like Diegator04..... I'm shocked....

**Comment by DeltaNedas** [comment]
a lil birdie told me this uses google translate

**Comment by Diegator04** [comment]
@DeltaNedas are you serious? Why are you thinking that? I used only Collins Dictionary and common sense :).

**Comment by Anuken** [comment]
> a lil birdie told me this uses google translate

Can anyone else confirm/deny this?

**Comment by Diegator04** [comment]
> > a lil birdie told me this uses google translate
> 
> Can anyone else confirm/deny this?

Nevermind, he's joking

**Comment by Diegator04** [comment]
Now fixes, improvements and **names of units** (_early version, they'll be improved_) are applied thanks to the collaborations with italian persons who compared thoughts, opinions and ideas. I want to give special thanks to @GioIacca9 for his suggestions and his bundle that I review and I found some mistakes but nothing dramatic (Furthermore unit's names weren't translated). We hope we will able to work together for a better translation. 
@Anuken, this bundle is ready to be *merged* (I don't want people see that mistakes in main and official version of Mindustry)

**Comment by Anuken** [comment]
@GioIacca9 (or any other person qualified to comment): Can we come to an agreement about this? I'm concerned about this comment, which was made some time ago on Discord:

image

Are you still of the same opinion?

**Comment by GioIacca9** [comment]
We (@Diegator04 and me) have come to a conclusion, so don't merge this PR. He will make another PR with some important changes for unit names and some crappy translations I made :)

**Pull request closed without merging**
