### PR TITLE
Drills Textures Cleanup

### PR DESCRIPTION
**Pull request by Voz-Duh**
Before:image
After:image

_Linear Filtering - off_

### CODE REVIEW

**Comment by 7rodo** [comment]
bruh

**Comment by Quezler** [comment]
looks a bit overly detailed & straight 🤔

**Comment by zethnest** [comment]
I agree with Quezler. I still prefer the current version in this case. Were there any mentions of needing to remodel drill textures or this is only a suggestion?

**Comment by Voz-Duh** [comment]
> looks a bit overly detailed & straight 🤔

Hm.... Okay i go fix it

**Comment by Voz-Duh** [comment]
@Quezler better?
image

**Comment by Voz-Duh** [comment]
> I agree with Quezler. I still prefer the current version in this case. Were there any mentions of needing to remodel drill textures or this is only a suggestion?

I discussed this in Anuken's DM

**Comment by sk7725** [comment]
> @Quezler better?
> image

Laser looks worse, airblast looks better than vanilla.

**Comment by Erisfiregamer1** [comment]
The airblast is great, the laser needs work.

**Comment by Voz-Duh** [comment]
Better?:    image

**Comment by Erisfiregamer1** [comment]
Yes, much.

**Comment by Quezler** [comment]
not sure if i'm a fan of those 4 "handles", but if the others like it i suppose its fine by me 🤔

**Comment by Catchears** [comment]
I wouldn't shade (I don't know if that's the correct word, I mean having two different colours based on the position) the bit that spins because I think the "shading" is meant to create some sort of shadow and it wouldn't really make sense for that to spin.

**Comment by YellOw139** [comment]
Shading on the moving parts looks illogical.

> image
I prefer this iteration of the laser drill. The moving parts still look overdetailed IMO. Otherwise it looks fine, better than vanilla.

I don't like the current airblast whatsoever. The new red lines' design looks better than vanilla, but the drill overall looks way too overdetailed. The middle diagonal rectangles look out of place. The corner "sunk" rectangles look weird when shaded. I'd remove them completely. The moving parts look overdetailed. 

It's like when things are more detailed my mind can't comprehend the drill's shape anymore. The overall detail level doesn't seem to match the other drills (sure, higher tier drills can get more details, but I feel like you overdid it with the airblast). Try taking a photo of all the drill tiers. They don't look well beside each other.

**Comment by WilloIzCitron** [comment]
yes too better
than old

**Comment by WilloIzCitron** [comment]
mechanic drill and preumatic drill?

**Comment by Voz-Duh** [comment]
@WilloIzCitron no, I don't want redo mechanic drill and preumatic drill

**Comment by WilloIzCitron** [comment]
> @WilloIzCitron no, I don't want redo mechanic drill and preumatic drill

Ok

**Comment by WilloIzCitron** [comment]
Its resprite

**Comment by SnakkiZXZ** [comment]
it's not a good idea, of you a mediocre artist

**Comment by the-kido** [comment]
> of you a mediocre artist
that really was not necessary

**Comment by XEN0PHIL** [comment]
> > of you a mediocre artist
> 
> that really was not necessary

ruining sprites is not necessary

**Comment by Erisfiregamer1** [comment]
Hey, I liked them.

**Pull request closed without merging**
