### PR TITLE
Updates rotary & thermal pump liquid region sprites

### PR DESCRIPTION
**Pull request by Quezler**
before and after: (makes it feel more at home with the recent changes to the drill center sprite)
Screen Shot 2020-12-21 at 15 03 30
Screen Shot 2020-12-21 at 15 13 57

### CODE REVIEW

**Comment by Quezler** [comment]
before someone comments on the two weird protrusions on the diagonal axis of the thermal pump, its part of the sprite itself:

Screen Shot 2020-12-21 at 15 18 42

**Comment by Quezler** [comment]
updated screenshot:

Screen Shot 2020-12-21 at 18 00 21

**Comment by QmelZ** [comment]
looks too big, the old one is better if you ask me.

**Comment by Quezler** [comment]
maybe it would look better with some "glass stripes" over it?

**Comment by joshuaptfan** [comment]
I like that the shape matches the block aesthetic, but the small one still looks better. Maybe you could blend the two by making the diamond one smaller?

**Comment by Quezler** [comment]
then i'd probably have to change the bases texture 🤔

**Comment by Quezler** [comment]
**PSA** consider this pull abandoned atm, anuke: feel free to either merge or close this, or perhaps even adapt, who knows 🤔

**Comment by Anuken** [comment]
The smaller ones look better here, I think.

**Pull request closed without merging**
