### PR TITLE
add liquid-distributor block

### PR DESCRIPTION
**Pull request by Arkanic**
basically just a larger liquid router, this allows for easier liquid chaining for things like defense and recursive factory layouts.

~~(the sprite is pretty bland)~~

Screenshot (6)
I could probably add some kind of detail to the top of the block

### CODE REVIEW

**Comment by Anuken** [comment]
Why not just use 4 routers?

**Comment by Arkanic** [comment]
quezler told me the same thing

**Comment by Arkanic** [comment]
tbh the liquid system just means that it evenly distributes

**Comment by Arkanic** [comment]
it has more capacity now, giving it an actual reason to be built

**Comment by Anuken** [comment]
If you want capacity, there are tanks, and if you want distribution, there's routers. I don't think this block is really needed.

**Comment by Arkanic** [comment]
that's fine by me, i'll just find something else to make

**Comment by geoffrey1900** [comment]
hey this is a good idea if so why is the the distrbutor in the first place

**Comment by geoffrey1900** [comment]
examples bad but i actualy really want this lol

**Comment by geoffrey1900** [comment]
so we dont have to deal with the powers problem as much of using router chains that each input is half the last and it doesent work well of say (still makes me sad f) i had som thor reactors and i put dow some cyro flow to 5 of them and the 5th blew up from getting like no cyro and deleted front line and i died

**Comment by geoffrey1900** [comment]
so even fluid flow would be nice lol

**Comment by geoffrey1900** [comment]
*add it*

**Comment by Anuken** [comment]
Use better piping instead. I won't be adding this.

**Comment by Arkanic** [comment]
reviewing this, i can agree with anuke, this idea wasn't too well thought of.

**Pull request closed without merging**
