### PR TITLE
New Units for the Omura

### PR DESCRIPTION
**Pull request by Violet-Scarelli**
Two simple new units I created specifically for the Omura, so that it won't hog the Flare cap when it's built. The new units (names pending changes) are the Echo, a slightly tankier version of the Flare that has flak cannons, and the Ghost, a light bomber that's supposed to play the role of a support.

### CODE REVIEW

**Comment by Syncinus** [comment]
Shouldn't it just spawn one type of unit, it spawning two is weird, especially since it's from two different places.

**Comment by Anuken** [comment]
> so that it won't hog the Flare cap when it's built

Why is this a problem, though? I specifically didn't create new units because there are so many in v6 already, and I didn't think new ones were necessary.

**Comment by Syncinus** [comment]
Yeah, the reconstructors don't actually shut off when it hits unit cap, therefore there is no real limitations to it doing that.

**Comment by Violet-Scarelli** [comment]
Hunh did not realize that

**Comment by Voz-Duh** [comment]
Violet, i don't like you sprites, i can create new sprites if you want

**Comment by Violet-Scarelli** [comment]
Please, I'm not that great at spritingSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: VozDuh <notifications@github.com> Date: 9/21/20  5:09 PM  (GMT-08:00) To: Anuken/Mindustry <Mindustry@noreply.github.com> Cc: Violet-Scarelli <alphaone150@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Anuken/Mindustry] New Units for the Omura (#2649) 
Violet, i don't like you sprites, i can create new sprites if you want

**Comment by genNAowl** [comment]
There is an alternate solution, and that is that each Omura can up the flare cap by 2 or 4. I tried implementing this myself, and was going to put a suggestion in about it.

**Comment by Anuken** [comment]
> solution

Why do we need a solution to a problem that doesn't exist?

**Comment by Violet-Scarelli** [comment]
Honestly that's a better idea than the one I had. I thought that the Omura making a unique unit type could be cool but that's probably better.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: genNAowl <notifications@github.com> Date: 9/21/20  5:38 PM  (GMT-08:00) To: Anuken/Mindustry <Mindustry@noreply.github.com> Cc: Violet-Scarelli <alphaone150@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Anuken/Mindustry] New Units for the Omura (#2649) 
There is an alternate solution, and that is that each Omura can up the flare cap by 2 or 4. I tried implementing this myself, and was going to put a suggestion in about it.

**Comment by genNAowl** [comment]
> problem that doesn't exist?

The problem here is that you can't stop the Omura's from constructing flares, unlike with air factories.

**Comment by Anuken** [comment]
Why is construction of flares a problem?

**Comment by genNAowl** [comment]
> construction of flares a problem?

There is a unit cap, which means that if is reached, you will no longer be able to construct flares in air factories to upgrade to other units.

**Comment by YellOw139** [comment]
And this effectively blocks you from having high tier air units and high tier naval units at the same time.

Once you get Omuras, you can no longer build as many high tier air units, which simply renders Omura weaker than intended. You effectively block the player from getting benefits for his own investment in high tier air units once he also builds high tier naval units.

**Comment by Anuken** [comment]
> you will no longer be able to construct flares in air factories

No, that's not how factories work anymore. It was changed some days ago.

**Comment by genNAowl** [comment]
> No, that's not how factories work anymore

Wait really? Welp never mind then. I don't always keep track of the updates. Sorry.

**Pull request closed without merging**
