### PR TITLE
Better light blending

### PR DESCRIPTION
**Pull request by Agzam4**
- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

image
image

### CODE REVIEW

**Comment by Anuken** [comment]
If it were that simple, I would have done it long ago. Additive blending completely ruins the effect with stacked sources.

Before:

Screenshot 2024-04-21 at 10 25 48 AM

After this PR:

Screenshot 2024-04-21 at 10 26 57 AM

**Comment by BlueTheCube** [comment]
we must find the solutions

**Comment by Agzam4** [comment]
> we must find the solutions

Maybe button in settings to switch blending mode?

Im also want this mode as settings button for xool screenshot

**Comment by Agzam4** [comment]
> we must find the solutions

Maybe button in settings to switch blending mode?

Im also want this mode as settings button for xool screenshot

**Comment by Anuken** [comment]
No. If you want that, add it in your own custom build.

**Pull request closed without merging**
