### PR TITLE
Merge shooting methods

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Merges burst shooting, alternate shooting, and spread shooting together.
Also adds support for eject sprites (v5 salvo sides)

### CODE REVIEW

**Comment by Anuken** [comment]
Have you tested this with all the turrets?

**Comment by MEEPofFaith** [comment]
Yes

**Comment by MEEPofFaith** [comment]
@Anuken and here's a video of all the turrets working perfectly fine.
https://youtu.be/hGDokIHAs78

**Comment by genNAowl** [comment]
Oh don't pack the sprites; They are a frequent source of conflicts, and if you do, deselect the changed files when you commit.

**Comment by MEEPofFaith** [comment]
> Oh don't pack the sprites; They are a frequent source of conflicts, and if you do, deselect the changed files when you commit.

Fixed.

**Comment by Anuken** [comment]
Disregarding the conflicts, I don't want to merge this, as it introduces unnecessary capture-related allocations and will inevitably break things (even if it's not immediately obvious).

**Pull request closed without merging**
