### PR TITLE
Parentize most ability effects

### PR DESCRIPTION
**Pull request by MEEPofFaith**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
this is really something that needs testing

**Comment by MEEPofFaith** [comment]
yes it is

**Comment by BlueWolf3682** [comment]
(actually hyped for this, cause it adds a lot for me to mess around with)

**Comment by Anuken** [comment]
Mostly implemented.

**Pull request closed without merging**
