### PR TITLE
sand water outputs sand

### PR DESCRIPTION
**Pull request by ThatOneBepis**

### CODE REVIEW

**Comment by YaFou** [comment]
Can we more information about this pull request @ThatOneBepis?

**Comment by ThatOneBepis** [comment]
its self-explanatory

**Comment by WaterRatje** [comment]
Do you mean that water can output sand?

If so, how?

**Comment by YaFou** [comment]
But why this change? Why do you want output sand from sand water?

**Comment by ThatOneBepis** [comment]
@WaterRatje yes

@YaFou its dumb to not drill sand in water NEAR SAND WITHOUT WATER (or in general)

**Comment by WaterRatje** [comment]
oh, you mean just with a mining drill...

**Comment by ThatOneBepis** [comment]
yes

**Comment by Anuken** [comment]
Shelving this for now. Drilling sand that's underwater doesn't make a *whole* lot of sense, but the main issue is that this breaks the displayed resources for sectors and may affect balance in those areas. This may be reconsidered for 6.0.

**Comment by ThatOneBepis** [comment]
Understood

**Pull request closed without merging**
