### PR TITLE
Support for custom menu buttons

### PR DESCRIPTION
**Pull request by Mnemotechnician**
Added support for custom main menu buttons, similarly to custom categories in SettingsMenuDialog. Mods can register new menu buttons by using one of the `MenuFragment.addButton` methods, e.g. `Vars.ui.menufrag.addButton("die", Icon.none, () -> throw Error())`. For convenience, the quit button is always kept in the bottom right / bottom part of the menu, so the custom buttons are inserted between it and other buttons.

MenuFragment.Buttoni was made public and is now used to store the registered "button definitions"... I'm not sure if this is the best approach, but it works.

For example, running the following code in the console
Miserable_situation_20220918_170317
Results in this:
Miserable_situation_20220918_174142

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
This can be problematic, because there is absolutely no mechanism for scrolling the buttons, and even ~2 new buttons can easily get cut off on certain screens.

**Comment by Mnemotechnician** [comment]
Uh, maybe just make the container a scroll pane?

**Comment by Mnemotechnician** [comment]
Well, idk, i tried to make the scroll pane look better but couldn't think of any way... However, normally the menu shouldn't be big enough to be scrollable, so i think it's ok


https://user-images.githubusercontent.com/69920617/190924594-6df49073-bfe7-4f57-b443-485b4b789687.mp4

**Comment by SMOLKEYS** [comment]
what about vertical screens

**Comment by Mnemotechnician** [comment]
> what about vertical screens

Same thing. ScrollPane supports scrolling in both directions by default, so it will be scrollable vertically (but i doubt anyone will ever need that)

**Pull request merged**
