### PR TITLE
Leg mass for spider units.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Adds `legPayloadMass`, which is the mass taken up per leg.

Reason: It makes sense for the legs to take up payload space, but also since some of the vanilla spiders have smaller `hitSize`s because most of their size is leg (example: Toxopid, which is about the same size as Zenith)

### CODE REVIEW

**Comment by Quezler** [comment]
does this change the balance of certain units being able to get picked up by any if the 3 payload air tiers at all?

**Comment by MEEPofFaith** [comment]
> does this change the balance of certain units being able to get picked up by any if the 3 payload air tiers at all?

Oct can only carry 2 Toxopids now ;)

**Comment by MEEPofFaith** [comment]
though all the other tiers were kinda random because I don't know how to balance.
I'm sure Anuke would be better at balancing that.

**Comment by joshuaptfan** [comment]
Payload capacity is not measured in mass, but size. `legPayloadMass` should be `legPayloadSize`, and `legMass` should be `legSize`.

**Comment by BlueWolf3682** [comment]
This would change the somewhat not well known fact that a quad can currently pick up a toxopid. That's about it.

**Comment by Quezler** [comment]
i suppose that would be an acceptable balance change ^

**Comment by Anuken** [comment]
Leg unit hitboxes were already small for their body size; with the 7.0 adjustments this isn't necessary anymore.

**Pull request closed without merging**
