### PR TITLE
Mouse Control For Desktop

### PR DESCRIPTION
**Pull request by Voz-Duh**
image
image

### CODE REVIEW

**Comment by DeltaNedas** [comment]
doesnt pc already use mouse

**Comment by Voz-Duh** [comment]
> doesnt pc already use mouse

This **only** mouse controls (but you can use w, a, d, s, etc)

**Comment by summetdev** [comment]
It's already implemented in game, see Settings - Controls - Follow Mouse. ❤️

**Comment by Voz-Duh** [comment]
Okay

**Pull request closed without merging**
