### PR TITLE
[chat] dynamic team color

### PR DESCRIPTION
**Pull request by Quezler**
> prototype, this can be done way better and less hacky, probably, this gets the ball rolling

All this does is replace `[teamcolor]` in the player's name with the color of the team they are in at the time of sending a message, though dynamic variables such as those should probably use something shorter and be usable without typing it yourself, also it shows the tab menu wrongly now, obviously 😗 

Screen Shot 2019-12-21 at 17 07 29
Screen Shot 2019-12-21 at 17 11 44

https://feathub.com/Anuken/Mindustry/+487

### CODE REVIEW

**Comment by DeltaNedas** [comment]
why not just [team]

**Comment by Quezler** [comment]
probably to generic, and i just copied from the feature suggestion 😛

**Comment by CA6** [comment]
i like it and would make it easier to identify team mates by chat but then again /t

**Comment by Anuken** [comment]
This won't truly be viable unless I rewrite the font renderer to allow for more complex tags. Shelving for now.

**Pull request closed without merging**
