### PR TITLE
Proper trails for point lasers

### PR DESCRIPTION
**Pull request by MEEPofFaith**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
needs testing

**Comment by MEEPofFaith** [comment]
You know something moves really slowly when this is a trail length of 30

https://user-images.githubusercontent.com/54301439/211215710-53f7a1d2-f2fe-4f2d-8ff5-e70c6d538851.mp4

**Comment by moocowswag** [comment]
Would it be possible to lower the opacity of the trail? It might look nicer if instead of covering the ground it tries to mimic the look of the ground being heated up.

**Comment by MEEPofFaith** [comment]
it's called changing the trail color

**Pull request merged**
