### PR TITLE
Effect Rotate With Parent

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://user-images.githubusercontent.com/54301439/133350770-c2fddd38-a8d8-4888-8158-064ca10a9844.mp4

I did some experimenting to see if I could fix the bullet direction and location, but it didn't work right. The only way I can think of to fix this is to move the location and angle calculations to inside of the `shoot` method. Which'll break a lot of stuff.

---
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Rot 1
Rot 2

**Comment by MEEPofFaith** [comment]
Request Summary

**Comment by BlueWolf3682** [comment]
:han
oh wait that hand reaching for you like a claw doesnt exist as a global emote
anyways i heavily need this so please and hopefully thank

**Comment by MEEPofFaith** [comment]
~~Why do I feel like Anuke's gonna do this himself in a way that's much better than what I did.~~

**Comment by BlueWolf3682** [comment]
ill take any sort of implementation, i really need this for so many projects

**Comment by MEEPofFaith** [comment]
poggers

**Comment by Anuken** [comment]
It's a bit of a minor detail, and I haven't added any charge weapons yet so it hasn't been a problem.

**Pull request merged**
