### PR TITLE
add among to midustry

### PR DESCRIPTION
**Pull request by DeltaNedas**
happy april 1

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
april 1st, just a week away

**Comment by SMOLKEYS** [comment]
@DeltaNedas ~~give it a sprite~~

**Comment by Anuken** [comment]
~~I would actually like to merge this but it would break item IDs everywhere~~

**Comment by DeltaNedas** [comment]
> @DeltaNedas ~give it a sprite~

i did

**Comment by DeltaNedas** [comment]
> ~I would actually like to merge this but it would break item IDs everywhere~

ok maybe i should have just retextured copper

**Comment by DeltaNedas** [comment]
oh #6660 good

**Pull request closed without merging**
