### PR TITLE
mfw quad still has no sound

### PR DESCRIPTION
**Pull request by z0mbiesrock**
Anuke: Added new sounds to most of the units and blocks

Also Anuke: forget to add sounds to quad's bombs

Me: Fine, I'll do it myself

### CODE REVIEW

**Comment by Violet-Scarelli** [comment]
Boi where's the "EEEEEeeeeeeeBOOM"

**Comment by Anuken** [comment]
It's.. not a laser, though, it needs a different sound.

**Comment by z0mbiesrock** [comment]
> It's.. not a laser, though, it needs a different sound.

br_UUUUGGGGGHHHHHH_ seriously? You going to make a new sound for it yourself, I guess?

**Comment by Anuken** [comment]
[Yes.](https://github.com/Anuken/Mindustry/commit/538f1d7330be9f571ac19ea7f1309ab51e3769d1)

**Pull request closed without merging**
