### PR TITLE
Add serverControl listener

### PR DESCRIPTION
**Pull request by Darkness6030**
It will be very useful for some plugins

### CODE REVIEW

**Comment by summetdev** [comment]
More global variables for the god of global variables!

**Comment by Phinner** [comment]
This change is kinda nice, I used to use that hacky code to get the `ServerControl` instance.
```java
public static ServerControl getServer(){
    return (ServerControl)Core.app.getListeners().find(listener -> listener instanceof ServerControl);
}
```

**Comment by Darkness6030** [comment]
Ok lets make global variables for EVERYTHING

**Comment by Phinner** [comment]
wow, you sure about that ? You don't need to expose everything in this class.

**Comment by Darkness6030** [comment]
I am tired of using Reflect :-/

**Comment by Darkness6030** [comment]
@Anuken pls review :eyes:

**Comment by Anuken** [comment]
These are mostly implementation details; they should either be set up with setters and validation code, or not exposed at all.

**Comment by LeoSko** [comment]
Not sure about "implementation details" but I had to specifically rebuild server with ***all*** those properties to match my preferences, +`dateFormatter` because milliseconds matter. (~~who the hell keeps logs with sizes as low as 512kb, not configurable in any way?~~)

**Comment by Anuken** [comment]
> who the hell keeps logs with sizes as low as 512kb

512kb is pretty large for a plain text file, some editors start lagging at those file sizes... and in any case, if someone wanted it configurable, making a *static final* field public isn't the answer, it's pointless and confusing - `Config` should be used instead.

Cryptic undocumented fields like `lastTask` or `suggested` should definitely not be exposed.

**Comment by LeoSko** [comment]
Completely agree on `Config` point for that. (and surely they are not supposed to be final anymore) Also, `logFolder` might be a good idea to un-finalize as well.

> some editors start lagging at those file sizes

Out of curiosity: What software are you trying to use? I'm working with log files every day for the past several years with sizes anywhere between 50Mb to 1Gb and had no issues opening them in either notepad++, less or vi - if you have lags, try those options.

**Comment by Anuken** [comment]
I have gedit, which doesn't handle large files well, although that seems to be more related to text-dense documents rather than long ones.

**Pull request closed without merging**
