### PR TITLE
Add RoomServers to the server list

### PR DESCRIPTION
**Pull request by RoomServers**
Add a "RoomServers" to the server list, in the future there will be more servers, now only 3

### CODE REVIEW

**Review by osp54 — APPROVED** [review]

**Review by Quezler — CHANGES_REQUESTED** [review]
a few dozen spaces to many

**Comment by Darkness6030** [comment]
Oh no

**Comment by thedimas3007** [comment]
Server seems to be offline. 
Also please change JSON style like other servers:
* Change `адрес` into `address`
* Remove unnecessary spaces, it should be only one after `:`

**Comment by thedimas3007** [comment]
Why didn't you remove unnecessary spaces? Just look at another server and make your JSON style like their

**Comment by Darkness6030** [comment]
Btw he is Nexor

**Comment by Quezler** [comment]
> Why didn't you remove unnecessary spaces? Just look at another server and make your JSON style like their

he removed some, not all

**Comment by thedimas3007** [comment]
> Btw he is Nexor
@Darkness6030 
why do u think so?

**Comment by Darkness6030** [comment]
> > Btw he is Nexor
> 
> @Darkness6030 
> why do u think so?

I KNOW

**Comment by Darkness6030** [comment]
> > > Btw he is Nexor
> > 
> > @Darkness6030 
> > why do u think so?
> 
> I know. Just join Roomserver's Discord server. And you'll see

**Comment by thedimas3007** [comment]
You server is pretty new and I'd recommend you to search some good plugins/gamemodes. Also I jonied the Hub and only survival is online. And add `rtv` command using which players can skip the map

**Comment by RoomServers** [comment]
Сервер не поддерживается, пулл закрывается

**Pull request closed without merging**
