### PR TITLE
Update bundle_th.properties

### PR DESCRIPTION
**Pull request by JrTRinny**
My first time here. someone requested in discord so I made this.
-overhaul the translation to v6 (and a little v7)
this means:
-v6 hints
-fixed typos (of course)
-v6 turrets, units, stats, descriptions etc.
-make the translation more smooth and natural
-fixed some weird translation lines
*(Exclusive) -added scrap walls descriptions (why not?)

Also:
I am native speaker.
this was tested in-game, worked correctly (in the test).
new commits everyday if I find some flaws.

### CODE REVIEW

**Comment by JrTRinny** [comment]
@ballgamer56 @Molovtov please review :D

**Comment by JrTRinny** [comment]
no-one respond back ;(  is there any active thai translator?

**Comment by ballgamer56** [comment]
> no-one respond back ;(  is there any active thai translator?

There is, It's that we can't approved of your edit as we don't have the power/permission to do so. So there's no point of us active translators to reply. You also said you're a native Thai (so am I) so there's not really any grammar correct or something like that needed for the bundle as we expect you to do that already

**Comment by JrTRinny** [comment]
Thank you!

**Comment by JrTRinny** [comment]
Github is drunk, for some reason. _why is there a hotfix duplicate?_

**Comment by JrTRinny** [comment]
never knew this day would come...

**Pull request merged**
