### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Bambuko-tech**
Add a G-Mod Poland server

### CODE REVIEW

**Comment by Bambuko-tech** [comment]
Add a G-Mod Polska server

**Comment by DeltaNedas** [comment]
what does gmod have to do with mindustry

**Comment by DeltaNedas** [comment]
@Somka000 competition

**Comment by Somka000** [comment]
> @Somka000 competition

Bruh, .pl will die soon

**Comment by Anuken** [comment]
Server is down.

**Pull request closed without merging**
