### PR TITLE
Cryo tiles

### PR DESCRIPTION
**Pull request by TranquillyUnpleasant**
Since all the other liquids have tile versions that can be used in maps, i figured cryofluid should also have said tile variant. It provides an interesting new liquid tile to work with that goes very nicely with cold themed maps. Notable properties and related potential reasoning:

The cryofluid pools could have been formed over a long time as titanium slowly dissolved into water, or could be remnants of the accidents from previous unknown civilizations.

The pools are shallow, and such cold temperatures reduces pump efficiency, making extraction slower.
(50% pump efficiency because everyone was crying about this being op)

The pools glow faintly with a slightly blue tint. 
(Is cryo radioactive? Why does it emit light as a liquid? Idk but if the liquid does then the tile should too i guess)

Since cryofluid is much less viscous than tar or slag, drowning units only have a 50% debuff to speed when going through it, as opposed to an 80% for the other two. They are of course affected with the freezing status effect.

Also made a shader for the fluid that sort of mimicks a 'freezing' effect, the effect is a bit subtle and the shader looks similar to tar and slag when zoomed out:

https://user-images.githubusercontent.com/62061444/134824709-976870f7-5844-4965-a1fc-9511ad18983f.mp4

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by TranquillyUnpleasant** [comment]
Pool lighting, forgot to add a screenshot in the first message:
image

**Comment by LordOfCheddar96** [comment]
I approve wholeheartedly. This is an absolute win for laziness, which I am a big supporter of. No longer will I have to send other people to make cryo for me because I can't be bothered.

**Comment by sk7725** [comment]
i l o v e i ttttttttttttt

**Comment by oinkymoo** [comment]
finally someone implemented this

**Comment by the-red-soul** [comment]
Im not a fan of this. Cryo should be made by a machine for a reason, it is a massive booster in performance for your front lines and being able to just put a thermal pump and get 118/sec is ridiculously overpowered. Next you will want surge ore. These things are meant to be made and not exist naturally because well, they dont.

**Comment by TranquillyUnpleasant** [comment]
> Im not a fan of this. Cryo should be made by a machine for a reason, it is a massive booster in performance for your front lines and being able to just put a thermal pump and get 118/sec is ridiculously overpowered. Next you will want surge ore. These things are meant to be made and not exist naturally because well, they dont.

Did you uh... not read the pr? it says 50% efficiency for pumps.

**Comment by sk7725** [comment]
> Im not a fan of this. Cryo should be made by a machine for a reason, it is a massive booster in performance for your front lines and being able to just put a thermal pump and get 118/sec is ridiculously overpowered. Next you will want surge ore. These things are meant to be made and not exist naturally because well, they dont.

its not saying every other sector in serpulo will suddenly be full of this stuff. Most, if not all, maps and sectors will still force you to use machines to make cryo.

**Comment by SoMall-dumpling** [comment]
So some titanium ores dropped into a pond, and, after some dramatic geological changes, the whole pond turned into cryopond.
Another way to throw a pool party: fill your pond with cryofluid.

**Comment by TranquillyUnpleasant** [comment]
> Another way to throw a pool party: fill your pond with cryofluid.

Dang, must be a cool party.

**Comment by MEEPofFaith** [comment]
I feel like the shader could move a little slower. Still feels a little too liquidy for something that's really cold.
Though then again what's the freezing point of cryofluid? Would liquid methane move like water or would it be slow because of the temperature? Though then again the properties of methane can't really be applied to cryofluid.

**Comment by MEEPofFaith** [comment]
> Im not a fan of this. Cryo should be made by a machine for a reason, it is a massive booster in performance for your front lines and being able to just put a thermal pump and get 118/sec is ridiculously overpowered. Next you will want surge ore. These things are meant to be made and not exist naturally because well, they dont.

Have you ever pulled 118/sec slag out of a slag pond in ***campaign*** before? No. Why? Because it doesn't generate. Cryofluid ponds won't generate eithor.

**Comment by NeonSupernova** [comment]
> Im not a fan of this. Cryo should be made by a machine for a reason, it is a massive booster in performance for your front lines and being able to just put a thermal pump and get 118/sec is ridiculously overpowered. Next you will want surge ore. These things are meant to be made and not exist naturally because well, they dont.

Regardless of whether or not it generates in campaign or not, having it available in editor when making custom maps is absolutely great, something we should've had a while ago. It may be OP, depending on how fast it can be extracted, but it doesn't really matter because the map creator would be the one to decide.

**Comment by TranquillyUnpleasant** [comment]
> I feel like the shader could move a little slower. Still feels a little too liquidy for something that's really cold.
> Though then again what's the freezing point of cryofluid? Would liquid methane move like water or would it be slow because of the temperature? Though then again the properties of methane can't really be applied to cryofluid.

Liquid nitrogen is uh... more fluid than water pretty sure, or pretty close to it anyway.

**Comment by MEEPofFaith** [comment]
¯\_(ツ)_/¯

**Pull request merged**
