### PR TITLE
edit bundle_ru overgrowth desc

### PR DESCRIPTION
**Pull request by cosMICrus**

### CODE REVIEW

**Comment by cosMICrus** [comment]
now the mace unit name in it is `Булава` and not `Титан`

**Review by summetdev — APPROVED** [review]

**Review by Remint32 — APPROVED** [review]

**Comment by Prosta4okua** [comment]
Why didn't you change that string in bundle.properties?

**Comment by Anuken** [comment]
closing due to conflicts

**Comment by Remint32** [comment]
Was merged in https://github.com/Prosta4okua/Mindustry/commit/df7d856aaeb8ffdbfc72d6134a093f4eeb5a3805 (https://github.com/Anuken/Mindustry/pull/3462)

**Pull request closed without merging**
