### PR TITLE
Thai translation

### PR DESCRIPTION
**Pull request by ballgamer56**
Took me a week to finish :3

### CODE REVIEW

**Comment by Arkanic** [comment]
well done, that's a lot of strings you have translated

**Comment by Anuken** [comment]
I'll need to add Thai characters to the font before this works properly.

**Comment by ballgamer56** [comment]
> I'll need to add Thai characters to the font before this works properly.

If you need my help. here are recommended fonts that I think it goes along with the overall style of your game :3 (totally free for commercial use)
https://www.f0nt.com/release/kulachat-slab/
https://www.f0nt.com/release/ekkamai-new/

**Comment by Anuken** [comment]
Added the font.

**Comment by SpiffyBadGaster** [comment]
U is thai?

**Pull request merged**
