### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://github.com/MindustryGame/wiki/issues/89

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Catchears** [comment]
Wouldn't nonflammable sound better?

**Comment by Anuken** [comment]
"uninflammable" may be a real word, but it's about the most confusing one I've ever seen

**Comment by BalaM314** [comment]
haha, thanks @MEEPofFaith for making the pr, but it should be "not flammable". Uninflammable and nonflammable are both, well, confusing.

**Comment by BalaM314** [comment]
> "uninflammable" may be a real word, but it's about the most confusing one I've ever seen

Well it's only in the merriam-webster dictionary and wikitionary, so it's probably only sort of a word lol

**Pull request merged**
