### PR TITLE
Darkdustry reborn

### PR DESCRIPTION
**Pull request by osp54**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Review by Darkness6030 — APPROVED** [review]

**Review by Def-Try — APPROVED** [review]

**Comment by Darkness6030** [comment]
Note that I'm no longer associated with it 👀

**Comment by Dofaminus** [comment]
Finally
(Just funny image because why not):
image-16

**Comment by phinner** [comment]
🥳

**Comment by Kowkodivka** [comment]
🥳

**Comment by OmniCorpTechAdmin** [comment]
a little more fun images, why not
ddos

**Comment by Def-Try** [comment]
can you not initiate another drama in another pull that is literally not about any of you? thank you for your cooperation

**Comment by OmniCorpTechAdmin** [comment]
> - и там **мы** ток омни дудосили
> - and there **we** only omni ddosing

**Comment by Def-Try** [comment]
🤓

**Comment by OmniCorpTechAdmin** [comment]
we don’t care, we are not satisfied that the creator of darkustry will evade responsibility, just like darkdustry itself for illegal DDoS attacks, your creator is DDoS and the fact remains that Darkness, according to my information, is still communicating and is part of Darkdustry, we demand fair decisions for the damage caused and the removal of this part of the community as harmful to both other servers and the entire community

**Comment by Darkness6030** [comment]
Bro.
I did it myself. Nobody of current Darkdustry admins has ever DDoSed anyone. I did.
And I left Darkdustry forever. I'm no longer even an admin there. I don't have any console access and I don't develop anything for them. Darkdustry without me isn't even Darkdustry.

Sooooo maybe you should stop your attempts tk cause another drama? You can blame me, lol, but shouldn't blame the guys who just want to continue this server.

**Comment by 5GameMaker** [comment]
Forts are back, baby

**Comment by OmniCorpTechAdmin** [comment]
No, I think that Darkdustry should be punished after this, since this happened with the support of, among other things, your administrators, according to them, almost everyone from your administration knew about it, and the fact that you left your role as creator does not mean that Darkdustry as a project was not guilty, this happened with the approval of your own administrators

ddos

**Comment by osp54** [comment]
> according to them, almost everyone from your administration knew about it
Is it okay that he wrote the screenshot post still a few days after leaving darkdustry and transferring ownership? No one knew about it before that, and obviously our reaction was against his actions, especially the way you got the screenshot of this message proves it.

**Comment by Def-Try** [comment]
just fuck off you both already. stop making drama in this pr, please. continue in *literally any other* pr for removal of darkdustry/omnidustry, and, if you find *real reason* with *real, irrefutable, not taken out of context, not fabricated proof that cannot be broken with a single image or contradiction* - go to anuke in dms. stop acting like a bunch of children throwing shit at each other until adult stops and punishes you.

**Comment by OmniCorpTechAdmin** [comment]
ddos

By your console admin

**Comment by OmniCorpTechAdmin** [comment]
ddos

By *unknown* user

**Review by 5GameMaker — APPROVED** [review]

**Comment by OmniCorpTechAdmin** [comment]
Anuken, understanding the number of hours spent protecting our servers because of such people and such servers - to see them in the list of servers is insulting, especially when it is confirmed that they were doing this

**Comment by 5GameMaker** [comment]
What I'm getting from this is that Darkness isn't a very good person, not that Darkdustry itself is involved in this

**Comment by Def-Try** [comment]
anyways, darkness is no longer in command of darkdustry. we are going to rename later, but currently - we are darkdustry, just so we have players before "rebranding".

**Comment by OmniCorpTechAdmin** [comment]
ddos

invalid - admin of Darkdustry

**Comment by KotMilkMeoWtwo** [comment]
Nya

**Comment by BasedUser** [comment]
i can confirm darkness has moved ownership

> a little more fun images
you're walking on thin ice, and i'll be under it when you get repobanned
speaking of, *get repobanned* for stirring shit

**Comment by OmniCorpTechAdmin** [comment]
> i can confirm darkness has moved ownership
> 
> > a little more fun images
> 
> you're walking on thin ice, and i'll be under it when you get repobanned (why now? why not many months ago when it happened? what's the point of that LARP?) speaking of, _get repobanned_ for stirring shit

This became known not long ago

**Comment by OmniCorpTechAdmin** [comment]
You can make empty threats, but the fact that darkdustry was doing DDoS is there, we want them to be excluded from the list of servers, for such an attitude, there were facts where their entire administration knew about what they were doing, so the excuse “we did a rebranding” is very doubtful

**Comment by JojoFR1** [comment]
Why complaining here? If it's, according to you, illegal DDoS then go to court or private?

**Comment by phinner** [comment]
> Why complaining here? If it's, according to you, illegal DDoS then go to court or private?

This guy is trolling. The account was literally made yesterday, and the name, why it isn't SSTentacleSS directly ?

**Comment by OmniCorpTechAdmin** [comment]
> > Why complaining here? If it's, according to you, illegal DDoS then go to court or private?
> 
> This guy is trolling. The account was literally made yesterday, and the name, why it isn't SSTentacleSS directly ? The man has enough self-respect to not use some burner account.

For technical reasons I can’t write from the main account (difficulties in switching to Sway), and I lost my TOTP from the main account, this is not a one-day account, until at least one account is restored - alas, I’ll write like this, or maybe I’ll go find the password, it’s just too much it takes time and I have been using self-hosted, federated git hosting for a long time

**Pull request merged**
