### PR TITLE
rewrite mindustry in 🚀 Rust 🚀

### PR DESCRIPTION
**Pull request by markozajc**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [🚀] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [🚀] I have ensured that my code compiles, if applicable.
- [🚀] I have ensured that any new features in this PR function correctly in-game, if applicable.
- [🚀] Fearless Concurrency

(mostly) safe
mindustry has been completely rewritten from jva (vo🤮mit) into [Rust](https://www.rust-lang.org/) 🚀. this ensures Fearless Concurrency, as well as Blazing Fast. It also takes advantage of Rich Type System and Ownership Model Guarantee Memory-Safety (never crashes).
compile with `rustc mindustry.rs` (much easier than using gr*dle and other nonsense)
required dependencies:
- Mindustry.jar (put it into the working directory, idk why this is still required, must be a bug (I used unsafe{}))
-
image

### CODE REVIEW

**Comment by Arkanic** [comment]
Because the code is in rust( :rocket: ) it automatically makes any code it executes memory-safe, fear-free, and blazing fast (only 2 hour compile time)!!!!
however you have forgotten to include more libraries. There are not enough, which means that this project is likely made by a rust noob (or an impostor who is writing c)

**Comment by markozajc** [comment]
maybe the real libraries was the friends we made along the way 😔

**Comment by Arkanic** [comment]
Also remember to remove mindustry.jar before the final commit (as it is written in j*va, which automatically makes it a bug)

**Comment by markozajc** [comment]
done !!🚀🚀🚀🚀

**Comment by IxGamerXL** [comment]
Mod developers and users will not appreciate the lack of JS and Java typed mod support. Does this pull request address and implement JS and Java runtime support for mods?

**Comment by Arkanic** [comment]
> Mod developers and users will not appreciate the lack of JS and Java typed mod support. Does this pull request address and implement JS and Java runtime support for mods?
@IxGamerXL 
see https://github.com/Anuken/Mindustry-Suggestions/issues/3664#issuecomment-1163746667

**Comment by markozajc** [comment]
> Mod developers and users will not appreciate the lack of JS and Java typed mod support. Does this pull request address and implement JS and Java runtime support for mods?

your issue has been 🚀resolved🚀. rust has no bugs.

**Comment by Arkanic** [comment]
ok but you forgot support for peepee poopoo lang v1234857.6
if a user is falling at a rate of 4.6m/s while using a 2005 thinkpad while running notepad, calculating 4.6+5.5 returns an answer off by 4dp
this is incredibly unsafe and needs to be fixed by installing 300 more packages

**Comment by markozajc** [comment]
wrong,
j*vaav🤮🤮 and j🤮ara*scritp🤮 support is written entirely in 🚀Rust🚀, which is 🚀Memory safe, blazing fast🚀

**Comment by Arkanic** [comment]
@IxGamerXL successfully added javascript emulation
your problem has been solved

**Comment by IxGamerXL** [comment]
> > Mod developers and users will not appreciate the lack of JS and Java typed mod support. Does this pull request address and implement JS and Java runtime support for mods?
> 
> your issue has been rocketresolvedrocket. rust has no bugs.

Ight. We'll see if JS will work like before in due time I guess.

**Comment by IxGamerXL** [comment]
> > > > Mod developers and users will not appreciate the lack of JS and Java typed mod support. Does this pull request address and implement JS and Java runtime support for mods?
> > > 
> > > 
> > > your issue has been rocketresolvedrocket. rust has no bugs.
> > 
> > 
> > Ight. We'll see if JS will work like before in due time I guess.
> 
> @IxGamerXL it will. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has Fearless Concurrency. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs. rocketRustrocket has no bugs.

oh no he's stuck in an infinite loop oh god he can't alt+f4 / ctrl+alt+delete

**Comment by markozajc** [comment]
wrong,
there are no infinite loops in 🚀Rust🚀 as they would be considered bugs

**Comment by Arkanic** [comment]
he was written in java

**Comment by Mnemotechnician** [comment]
this is a great plan to discourage everyone from ever using rust by showing how dipshit it's userbase is.

**Comment by Arkanic** [comment]
> this is a great plan to discourage everyone from ever using rust by showing how dipshit it's userbase is.

rust 🚨 hater 🚨  detected

**Comment by IxGamerXL** [comment]
> this is a great plan to discourage everyone from ever using rust by showing how dipshit it's userbase is.

I usually don't even focus on the Rust community or it's language because of how odd and obscure it is to me. It sounds like a form of C, but I obviously didn't see enough of Rust programming to confirm.

**Comment by Arkanic** [comment]
Rust 🚀 is nothing like c 🤮

**Comment by markozajc** [comment]
c 🤮 when you forget to free() 🤮 the malloc() 🤮

**Comment by Mnemotechnician** [comment]
> sounds a little **sus**, maybe you should get **ejected**?

I'd be thankful if i was.

**Comment by markozajc** [comment]
!

**Comment by Arkanic** [comment]
suicidal impotor

**Comment by Nikostormkilla** [comment]
This would ruin modding support and make mods that were written with the java version of Mindustry be wholly incompatible with the rust version of Mindustry

also yes i know this pull request is a joke

**Comment by RealToppLe** [comment]
what in the world

**Comment by code-explorer786** [comment]
> > this is a great plan to discourage everyone from ever using rust by showing how dipshit it's userbase is.
> 
> I usually don't even focus on the Rust community or it's language because of how odd and obscure it is to me. It sounds like a form of C, but I obviously didn't see enough of Rust programming to confirm.

everything looks like C
C-like syntax is popular

**Comment by deltanedas** [comment]
marko zajc

**Comment by EclipseTheOldOne** [comment]
marko zajc

**Comment by itcannotbe** [comment]
marko zajc

**Comment by yesC48** [comment]
marko zajc

**Comment by code-explorer786** [comment]
merge conflict

**Comment by Arkanic** [comment]
this is a bug. Github is not written in rust (:rocket:) so it does not always work.

**Comment by Volas171** [comment]
amazing

**Comment by Volas171** [comment]
you might want to turn this into a draft

**Comment by yesC48** [comment]
pls add java compatibility, thank you

**Comment by markozajc** [comment]
> merge conflict

@code-explorer786 fxied !! 🚀🚀🚀🚀🚀

**Comment by markozajc** [comment]
anuke pls press merge before its too large and I have to dedicate more of my precious time to diligently and carefully fixing all conflicts while also taking utmost care to reimplement all of the newly added features in rust

**Comment by code-explorer786** [comment]
> @code-explorer786 fxied !! 🚀🚀🚀🚀🚀

:rocket:

**Comment by Hexrotor** [comment]
💈
🐢

**Comment by EclipseTheOldOne** [comment]
🚀

**Comment by Sh1penfire** [comment]
A language empowering everyone :rocket: rust :rocket: is great

**Comment by Arkanic** [comment]
it was simply too beautiful of an idea

**Comment by Mnemotechnician** [comment]
unrusted

**Comment by end-me-please** [comment]
noo marko zajc why delete it 
all the funny meme links will 404 now

**Comment by Eclipse-04** [comment]
:(

**Review by chairclr — COMMENTED** [review]
lgtm

**Review by NathanSnail — COMMENTED** [review]
lgtm

**Review by Ramiels — COMMENTED** [review]
lgtm

**Comment by markozajc** [comment]
ministry rutst

**Comment by Arkanic** [comment]
end of an era

**Comment by Ramiels** [comment]
thanks for 2 years of 🚀humor🚀

**Comment by Tuwuppy** [comment]
🚀 rust 🚀

**Pull request closed without merging**
