### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by KhanhLamVirual**
I want to add a new vndustry server

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by KhanhLamVirual** [comment]
@Epowerj Can you merge this server and sorry to ping you:(

**Comment by Epowerj** [comment]
You're not in the git blame for vndustry, so it's unclear to me if you should be editing this server group. You'll need to wait for Anuken to take a look.

**Comment by Anuken** [comment]
@KhanhLamVirual Please provide some sort of evidence or confirmation that you are allowed to add to this server group.

**Comment by KhanhLamVirual** [comment]
> @KhanhLamVirual Please provide some sort of evidence or confirmation that you are allowed to add to this server group.

Yeah The domain name vndustry.ddns.net belongs to me completely and I am the owner in 2 servers port 6567 and 6568 you can ask me to send the following proof photo

**Pull request merged**
