### PR TITLE
Cleaner Sprites

### PR DESCRIPTION
**Pull request by Voz-Duh**
image
*I hope I wrote the title correctly*

### CODE REVIEW

**Comment by Quezler** [comment]
imo only looks good on the first 3, i'd recommend keeping the plastanium conveyor and phase weaver sprite alone 🤔

**Comment by Voz-Duh** [comment]
I don't like it 
image

**Comment by Anuken** [comment]
More angled conveyor turns would *probably* be better, but the ones you're showing have edges that are too thick on the turns by about 1 pixel, perhaps 2.

Compare:

image

image

**Comment by DeltaNedas** [comment]
love the phase weaver

**Comment by Voz-Duh** [comment]
Okay

**Comment by Voz-Duh** [comment]
image

**Pull request merged**
