### PR TITLE
add descriptions for erekir content 

### PR DESCRIPTION
**Pull request by yesC48**
please merge my google chrome became a literal impostor while i was importing the changes and i fucking hate it.
thanks for understanding, Anuke.

### CODE REVIEW

**Comment by Xontol69** [comment]
Can i tell you something?

**Comment by Xontol69** [comment]
J

**Comment by yesC48** [comment]
yeah sure

**Comment by yesC48** [comment]
pls merge

**Comment by MEEPofFaith** [comment]
https://github.com/Anuken/Mindustry/pull/7066

**Comment by yesC48** [comment]
bruh

**Comment by yesC48** [comment]
closing because outdated haha look how funny i am

**Comment by yesC48** [comment]
check #7247 instead

**Pull request closed without merging**
