### PR TITLE
Make the core top glow like the Discord server logo.

### PR DESCRIPTION
**Pull request by MEEPofFaith**

### CODE REVIEW

**Comment by Quezler** [comment]
would probably draw to much visual attention to itself

**Comment by Spfwniw** [comment]
its not a glow effect or something its the sprite, the colors are just brighter.

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md#always-test-your-changes

**Comment by MEEPofFaith** [comment]
It's a draft

**Comment by MEEPofFaith** [comment]
I haven't had the chance to test it yet, so I kept it a draft

**Comment by MEEPofFaith** [comment]
Actually, should I make this apply to all team color things?

**Comment by MEEPofFaith** [comment]
Idk, what Anuke did before I forked, but whatever it was broke every `@Nullable` in the code. I'm just gonna merge in master to fix this...

**Comment by MEEPofFaith** [comment]
This did not help.

**Comment by Anuken** [comment]
> It's a draft

Sure, but why submit a PR at all if it can't even be compiled to test it?

**Comment by MEEPofFaith** [comment]
I just liked having it here

**Comment by MEEPofFaith** [comment]
In the meantime, I'm always getting the same error every time, even if I comment out my changes.

**Comment by MEEPofFaith** [comment]
where every `@Nullable` in the entire code is getting a `cannot find symbol` error, which is weird because it shouldn't have anything to do with what I've done, right?

**Comment by MEEPofFaith** [comment]
What the it even fails if I delete my changes.

**Comment by MEEPofFaith** [comment]
Now I'm not sure if the issue is with my pr or the game itself.

**Comment by MEEPofFaith** [comment]
I'm gonna try redoing this.

**Pull request closed without merging**
