### PR TITLE
Weather with World Logic

### PR DESCRIPTION
**Pull request by MEEPofFaith**
- Weather Sense instruction checks whether or not a weather is currently active
- Weather Set instruction sets a weather to be active or inactive.

https://github.com/Anuken/Mindustry/assets/54301439/67f47617-3e2d-44e3-bc5b-c4b87039db96

Things to note:
- Weather Sense is pretty tame. Probably could remove the privileged restriction, though it would be kinda weird as the only thing visible in the world category.
- I changed the name of `snow` to `snowing` since it conflicted with the `snow` floor tile. I don't know what repercussions this will have on saves.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by JasonP01** [comment]
@MEEPofFaith may i ask, since you've already made this pr :) could you also add a toggle to the effects if possible, so that weather can be had without the status effects?? (likely would need to add a button to the map rules dialogue for weather effects)
> You can say no, its fine, asking doesnt hurt no one :)

**Comment by Catana791** [comment]
Yes. I need this.

**Comment by overdramaticpanromantic** [comment]
image

**Comment by MEEPofFaith** [comment]
oh ok

**Pull request merged**
