### PR TITLE
Filipino (Tagalog) Translation -- patch 1

### PR DESCRIPTION
**Pull request by HAJDog247**
[UNDER DEVELOPMENT]
This project may take a week or so.

### CODE REVIEW

**Comment by itcannotbe** [comment]
Under development but you made the pull?

**Comment by HAJDog247** [comment]
*Shouldn't I do that?*

*I'm just following what did the instruction said—if I ain't mistaken or
misinterpreted.*

**Comment by ritzip** [comment]
~~https://github.blog/2019-02-14-introducing-draft-pull-requests/~~

**Comment by HAJDog247** [comment]
### I apologize for not using the _“draft”_ feature.
For I'm new to this interface and not really used to these tools offered by this platform. I don't usually use these kinds of software when fulfilling my job—as a volunteer translator.

Nonetheless, I'd like to thank you (@ritzip) for the knowledge you've sent! 😄

**Pull request merged**
