### PR TITLE
[Plugins] Added MessageHandler for handling messages & commands.

### PR DESCRIPTION
**Pull request by Darkness6030**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable. [Compiles]
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable. [Tested]

I need this for my plugin to work correctly so why shouldn't i add it ;-;

### CODE REVIEW

**Comment by Darkness6030** [comment]
Wait why didn't you compile

**Comment by Phinner** [comment]
I don't think this is a good idea.

I mean, when a message is sent, a regular user or a plugin developer expect several things :
- `PlayerChatEvent` to be triggered.
- The player messages to be logged.
- The chat filters to be applied.
- etc...

But your PR delegates all these things into this `MessageHandler`, meaning this class has multiple responsibilities towards the game code.

This is a problem because a bad implementation or a simple mistake can lead to unpredictable behavior not so easy to debug.

> Example: Let's say you make a plugin that just changes the default `MessageHandler` but you forget to trigger the `PlayerChatEvent` in it. After that, you add an anti-afk plugin that record player movements and player messages to detect whether they are active or not. So now, because `PlayerChatEvent` is never fired, the anti-afk will start to kick players that are just talking. And when this will occur, the player will think he has been kicked because he was not moving. He has a very low chance of reporting this unwanted behavior.

That's why we split different responsibilities into different units of code like `TeamAssigner` assign teams, `ChatFormatter` formats chat messages, etc...

**Comment by way-zer** [comment]
In fact, there are many way to handle message.
Like some in my [plugin](https://github.com/way-zer/ScriptAgent4MindustryExt/blob/v3.0.0/scripts/coreMindustry/utilNext.kts) :
Snipaste_2022-09-11_00-21-40

**Comment by Anuken** [comment]
This also breaks the API... so, no.

**Comment by Darkness6030** [comment]
Ok, btw thanks @way-zer for showing an example, will use this

**Pull request closed without merging**
