### PR TITLE
Fixed DNS pollution as China

### PR DESCRIPTION
**Pull request by Mr-Ao-Dragon**
Fixed DNS pollution as ChinaFixed DNS pollution as China.
- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by BasedUser** [comment]
Ideally, this mirror should be used as a fallback, instead of replacing the primary github link.

**Comment by Anuken** [comment]
Indeed. I don't want to use a service like that as default for everyone.

image

**Comment by Mr-Ao-Dragon** [comment]
> Indeed. I don't want to use a service like that as default for everyone.
> 
> image
> 

I prefer to use geoip judgment, but unfortunately I do not know how to use him

**Comment by Mr-Ao-Dragon** [comment]
> Indeed. I don't want to use a service like that as default for everyone.
> 
> image
> 

Can you help me to modify the pr followed by geoip? Thanks.

**Comment by BasedUser** [comment]
You probably don't need something as complex as GeoIP, however; you could modify the error handler to try and get from `raw.githubusercontents.com` if an error is encountered.

**Comment by Mr-Ao-Dragon** [comment]
> You probably don't need something as complex as GeoIP, however; you could modify the error handler to try and get from `raw.githubusercontents.com` if an error is encountered.

好的，感谢您

**Comment by Cong0707** [comment]
add an "if" to use mirror when get is failed
don't change it directly

**Comment by BasedUser** [comment]
try catch 😨

**Pull request closed without merging**
