### PR TITLE
Correct Lighting™ for Drills

### PR DESCRIPTION
**Pull request by sk7725**
Accidentally closed #5614 by renaming the branch, sorry!
image

- [x] Drills
- [ ] New drawer
- [ ] Any other blocks I may have missed

### CODE REVIEW

**Comment by sk7725** [comment]
also forgot to open this as draft because I'm dumb.

**Comment by GlennFolker** [comment]
> image

Nice formatting

**Comment by sk7725** [comment]
> > image
> 
> Nice formatting

the formatting guidelines did say one-liner ifs are not like *forbidden*, and I do not see a reason to turn 2 lines into 6.

**Comment by sk7725** [comment]
image
rotator region set to region so you can see what is happening more clearly.

**Pull request merged**
