### PR TITLE
click player icon to respawn

### PR DESCRIPTION
**Pull request by DeltaNedas**
Equivalent of V key on mobile, for when you dont want to swipe over to core and double tap.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
@Anuken another commit called h for master please

**Comment by Quezler** [comment]
and in case of an accidental swipe/press?

**Comment by DeltaNedas** [comment]
then you have to go back to your unit.
i would make it respawn on double click but i don't know how to, cleanly

**Comment by Anuken** [comment]
Will implement myself.

**Pull request closed without merging**
