### PR TITLE
json moment

### PR DESCRIPTION
**Pull request by BlueWolf3682**
I'm not sure why you used json5 in json - though it *does* parse, it looks horrible.

### CODE REVIEW

**Comment by Quezler** [comment]
here is the rest of your nightmare: https://github.com/Anuken/Mindustry/tree/master/annotations/src/main/resources/revisions

**Comment by BlueWolf3682** [comment]
oh come on seriously

**Comment by Anuken** [comment]
That is not JSON5, it is libGDX's standard "minimal JSON" format, which is used throughout the game. The official libGDX wiki [uses this format](https://github.com/libgdx/libgdx/wiki/Texture-packer#configuration) for examples. 

I don't see any good reason to change it.

**Comment by BlueWolf3682** [comment]
It just looks terrible on GitHub due to all of it erroring. On top of that, modders do this a lot and I really don't like the way it looks. But if you don't want to change it I guess I'll have to leave it be.

**Pull request closed without merging**
