### PR TITLE
Update server's

### PR DESCRIPTION
**Pull request by MINDUSTRYRU**
Add
mindustry.ru (Survival)
mindustry.ru:9990 (Survival 2)
mindustry.ru:9991 (PvP)
mindustry.ru:9992 (Attack)
mindustry.ru:9993 (HardEarth)

### CODE REVIEW

**Comment by DeltaNedas** [comment]
why not leave it as is with the hub and not 5 servers

**Comment by MINDUSTRYRU** [comment]
To maintain the lobby, system resources are required, as well as if the lobby of the server is turned off, access to other servers is limited

**Comment by KeviTV** [comment]
I still don't see the point in adding all 5 servers ^

**Comment by Kieaer** [comment]
Use a Lobby server

**Pull request closed without merging**
