### PR TITLE
Update servers_v6.json

### PR DESCRIPTION
**Pull request by SachaTending**
Add RCR

### CODE REVIEW

**Comment by Quezler** [comment]
usually new entries go at the bottom, even though its ordered by ping anyways

**Comment by Anuken** [comment]
Server looks alright, but please update it to 124. I can't connect until then.

**Comment by SachaTending** [comment]
Updatet to 124.1

**Comment by SachaTending** [comment]
> Server looks alright, but please update it to 124. I can't connect until then.

I will be updatet to 124.1

**Pull request merged**
