### PR TITLE
New feature request: bullet homing delay

### PR DESCRIPTION
**Pull request by abomb4**
I'm a mod creator, I want a feature that adds a delay for bullet homing, to get some funny effects.
The image below shows the difference between homing delay or not, the left turret has a delay, the right one has no delay.
图片

### CODE REVIEW

**Comment by Quezler** [comment]
wouldn't `0` instead of `-1` have the same effect?

**Comment by sk7725** [comment]
not bad tbh

**Comment by summetdev** [comment]
cool

**Comment by abomb4** [comment]
> 
> 
> wouldn't `0` instead of `-1` have the same effect?

Hmm, I saw `splashDamageRadius` default value is `-1`, so I used `-1` as default value.
Now `0` has the same effect as `-1`.

**Comment by SirMachinegun** [comment]
> > wouldn't `0` instead of `-1` have the same effect?
> 
> Hmm, I saw `splashDamageRadius` default value is `-1`, so I used `-1` as default value.

I think the reason 'splashDamageRadius' has '-1' as default value is because '-1' isn't a valid value therefore disabling splash damage. So I think by default, splash damage is disabled on a bullet, but if it is higher than 0 it will enable splash damage and define it's radius.

By setting homing delay to '-1' I think same things will happen.

**Comment by DeltaNedas** [comment]
you had me at
> feature **request**

h

**Pull request merged**
