### PR TITLE
Update of Pt-Br bundle

### PR DESCRIPTION
**Pull request by MMT007**
**Esquema** = Schematic or scam
**Planilha** = Schematic

.. dont use **Esquema** use **Planilha**

### CODE REVIEW

**Comment by Pietro303HD** [comment]
bad. changing something simple to something most people won't understand

**Comment by Pietro303HD** [comment]
Note to Anuke: Do not merge.

**Comment by MMT007** [comment]
bruh. if u continue with Esquema the people will think that the game have a stealing option.. do u have any better words for it?

**Comment by Pietro303HD** [comment]
Stealing? STEALING? When you first hear about schematics you already know
what they are for.

>

**Comment by MMT007** [comment]
so u even know Portuguese?

**Comment by Pietro303HD** [comment]
Just go ahead and change it to blueprint

**Comment by MMT007** [comment]
thats actually better

**Comment by MMT007** [comment]
thinking better.. blueprint is actually more confusing

**Comment by Pietro303HD** [comment]
And "planilha" is even more confusing. It translates to spreadsheet.

**Comment by Pietro303HD** [comment]
> so u even know Portuguese? 

i know how to use a translator

**Comment by Pietro303HD** [comment]
You should ask for opinions on the PT-BR server.

**Comment by MMT007** [comment]
i will

**Comment by King-BR** [comment]
1. First thing i thougth after reading "planilha" was excel spreadsheets and not schematics.
2. The translation for scam is "golpe" and not "esquema".
3. Who would think that "esquema" _~~that literally translate to schematic~~_ is about stealing in a 2D base building game where most of the time YOU are the one being attacked?

**Comment by King-BR** [comment]
If you are not convinced, i just made a poll on the PT-BR server to get the opinion of the others members of the brazillian community

**Comment by Pietro303HD** [comment]
Spoiler alert: everybody said schematic.

**Comment by King-BR** [comment]
Result for the vote:

"Esquema": 8 votes
"Planilha": 0 votes

**Pull request closed without merging**
