### PR TITLE
Add 3.5 .pl server to 7.0 serverlist

### PR DESCRIPTION
**Pull request by Ilya246**

### CODE REVIEW

**Review by Somka000 — APPROVED** [review]

**Comment by Anuken** [comment]
what's the joke here

**Comment by Somka000** [comment]
No, being on public 7.0 server list is a good advertisement for a 3.5 server, most players know about this server thanks to public list.

**Comment by LeoSko** [comment]
> what's the joke here

@Anuken, I don't know if you opened v6 version recently, but 1/3rd of the community servers are not relevant in the list as well and don't match v6 version. It looks messy, *including 3.5 version .pl server* there.

**Comment by Ilya246** [comment]
being on a public list is pretty much the only way any people at all can know about the 3.5 server

**Comment by Anuken** [comment]
> good advertisement

The server list is not a place to advertise.

> 1/3rd of the community servers are not relevant in the list as well and don't match v6 version

I'll deal with this.

**Pull request closed without merging**
