### PR TITLE
Make custom Env flag reliably possible

### PR DESCRIPTION
**Pull request by GlennFolker**
- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by sk7725** [comment]
Is this really needed? It is already possible to add custom Env flags in mods (check betamindy).
This change *will* break all mods that already implemented custom Env flags, and idk if it is worth it for new mods that *may or may not* use this niche functionality.

**Comment by sk7725** [comment]
(btw the betamindy versionbused in the github actions really needs to be updated)

**Comment by MEEPofFaith** [comment]
> Is this really needed? It is already possible to add custom Env flags in mods (check betamindy). This change _will_ break all mods that already implemented custom Env flags, and idk if it is worth it for new mods that _may or may not_ use this niche functionality.

What, you expect people to go through every mod that uses custom env flags to make sure yours don't conflict with theirs?

**Comment by rocknruzz12** [comment]
Hi im trying to figure out how to code im looking for help if you want to help please email finnr@morrisjeffschool.org😃

**Pull request merged**
