### PR TITLE
Update version name from 5->6 in .travis.yml

### PR DESCRIPTION
**Pull request by rnauber**
This should fix this fdroid build error:
`ERROR: Could not build app io.anuke.mindustry: Unexpected version/version code in output; APK: '6-fdroid-107' / '107',  Expected: '5-fdroid-107' / '107'`

### CODE REVIEW

**Comment by DeltaNedas** [comment]
merge when v6 is beta

**Comment by rnauber** [comment]
> merge when v6 is beta

But the [F-Droid build is broken](
https://f-droid.org/wiki/index.php?title=io.anuke.mindustry/lastbuild_107&redirect=no) right now, as the version name is **6** in:
https://github.com/Anuken/Mindustry/blob/9f2875006354e7ca35a7edb60394537b119b1c46/build.gradle#L34
but **5** in:
https://github.com/Anuken/Mindustry/blob/9f2875006354e7ca35a7edb60394537b119b1c46/.travis.yml#L12

Ideally the latter should get the version name from the former. Maybe @Anuken can build a mechanism to keep both in sync?

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/issues/2853#issuecomment-704978047

**Comment by rnauber** [comment]
Oh, this leaves me a little embarrassed that I did not find #2853  before. Sorry!

**Pull request closed without merging**
