### PR TITLE
coloured item bubble

### PR DESCRIPTION
**Pull request by Slava0135**
Peek 2020-11-30 20-24

### CODE REVIEW

**Comment by Legomonster33** [comment]
yis uwu

**Comment by summetdev** [comment]
actually it's a part of UI, that shouldn't be colored

**Comment by Legomonster33** [comment]
> it's a part of UI, that shouldn't be colored

its part of the ui yes, but it isnt like the rest of the ui and its more of an actual gameplay thing rather than a  proper ui element

**Comment by Slava0135** [comment]
> > it's a part of UI, that shouldn't be colored
> 
> its part of the ui yes, but it isnt like the rest of the ui and its more of an actual gameplay thing rather than a proper ui element

facts

**Comment by Slava0135** [comment]
The reason I want it to be changed is because there is colored engine below the bubble. Other UI elements don't have this.

**Comment by Remint32** [comment]
> its part of the ui yes, but it isnt like the rest of the ui and its more of an actual gameplay thing rather than a proper ui element

I agree with this, but then this element itself should be visually redesigned if it is going to be colored in the team color. Because the colors of the teams are not always bright and the bubble merges with the engine fire and even the ship's hull.

**Comment by Anuken** [comment]
I'd rather not.

**Comment by Legomonster33** [comment]
> I'd rather not.

Sad

**Comment by Voz-Duh** [comment]
@Slava0135 don't copy paste my code, stop it

**Pull request closed without merging**
