### PR TITLE
Effect added/removed

### PR DESCRIPTION
**Pull request by MEEPofFaith**
idk why you want this @GlennFolker but ok.

image

https://user-images.githubusercontent.com/54301439/153696950-246365b0-ecb9-4a64-85f3-1ea369ca9d46.mp4

(Made it spawn `blockBreak` at start then spawn `blockBuild` at the end)

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
What is the purpose of this?

**Comment by MEEPofFaith** [comment]
> What is the purpose of this?

Ask @GlennFolker

**Comment by Anuken** [comment]
Closing for reasons above, see `#workspace` discussion.

**Comment by MEEPofFaith** [comment]
Discord was recently blocked on school wifi, will check later.

**Comment by SMOLKEYS** [comment]
> Discord was recently blocked on school wifi, will check later.

oh no

skool

al cringe

**Pull request closed without merging**
