### PR TITLE
Update MinDurka IP

### PR DESCRIPTION
**Pull request by Darkness6030**
The biggest update of mindustry server ever! We've added SO many useful features, commands, new servers and more!

### CODE REVIEW

**Comment by Prosta4okua** [comment]
why first

**Comment by Darkness6030** [comment]
Why not

**Comment by thedimas3007** [comment]
Используй домен для того чтобы не делать подобную ерунду при смене хоста. Я на изи сделал это

**Comment by Darkness6030** [comment]
@Anuken, can you merge it now? All my server community is waiting for update

**Comment by Darkness6030** [comment]
I'll make domain name later, so this is the last ip changing

**Pull request merged**
