### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by abcxyzDustry**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by TheRadioactiveBanana** [comment]
Remove 140.238.246.78:7000 from this, I was hosting ziger from my server but no longer will be. 
@abcxyzDustry

**Comment by abcxyzDustry** [comment]
Ziger collab with you? @TheRadioactiveBanana

**Comment by TheRadioactiveBanana** [comment]
Elaborate
@abcxyzDustry

**Comment by abcxyzDustry** [comment]
ziger is dead and I will remove it from the server lisí @TheRadioactiveBanana

**Comment by TheRadioactiveBanana** [comment]
@abcxyzDustry ok

**Pull request closed without merging**
