### PR TITLE
pls delete it

### PR DESCRIPTION
**Pull request by AmateurPotion**
Because of this, co-op game mode(use 2+teams map) is not implemented. Please remove it.

### CODE REVIEW

**Comment by AmateurPotion** [comment]
If the size of the map is 200 × 200 or less, and there are multiple cores in a map, there is a problem with the play because the overlapping range is impossible.

**Comment by Prosta4okua** [comment]
You can customize this rule when you are creating map.

**Comment by Anuken** [comment]
You can just change it in the map-specific rules, as said above. No need to change it for everyone.

**Comment by AmateurPotion** [comment]
I tried to modify and run the map's custom rules for this, but there was a bug where the game rules-never install core zones apply on the client but not on the server.

**Comment by Anuken** [comment]
Then you should specify what the bug is, which map it happened on, and how to reproduce it
.

**Comment by AmateurPotion** [comment]
The gamerule- enemy no build zone was applied correctly when the server was opened as a game client, but this rule was not applied properly when opened as a server (like server-release.jar).

**Pull request closed without merging**
