### PR TITLE
Team Colors For Payload Conveyor and Router

### PR DESCRIPTION
**Pull request by Voz-Duh**
I created team colors for payload conveyors and router
Because Anuke say me:

> I think team colors make sense for blocks, e.g. payload conveyors, but not most effects

screenshot-1
screenshot-2

### CODE REVIEW

**Comment by Voz-Duh** [comment]
Anuke say me:
> I think team colors make sense for blocks, e.g. payload conveyors, but not most effects
I created team colors for payload conveyors and router

**Comment by TheMrAlbert** [comment]
Nice!

**Comment by Ubuntu8406** [comment]
Again... -_-

**Comment by Voz-Duh** [comment]
> Again... -_-
*Ignoring*

**Comment by Voz-Duh** [comment]
@Anuken please check this pull

**Comment by Quezler** [comment]
sweet

**Pull request merged**
