### PR TITLE
Sussy item sprites

### PR DESCRIPTION
**Pull request by MEEPofFaith**
#6657 but doesn't affect item ids.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
image

**Comment by MEEPofFaith** [comment]
do do **do do** do do *do* dododo

image

**Review by DeltaNedas — APPROVED** [review]

**Comment by DeltaNedas** [comment]
worthy of april 1th

**Comment by Anuken** [comment]
perhaps it would make sense for flarogus to be a retexture as well...

**Comment by SMOLKEYS** [comment]
oh no

**Comment by SMOLKEYS** [comment]
also, delta

> april 1**th**

again

**Comment by DeltaNedas** [comment]
> also, delta
> 
> > april 1**th**
> 
> again

do you think i dont know how to spekl firth

**Review by SMOLKEYS — APPROVED** [review]
certified Teo moment

**Comment by Anuken** [comment]
merged in, somewhere (kind of)

**Comment by EclipseTheOldOne** [comment]
oh hell naw

**Comment by MEEPofFaith** [comment]
ASB

**Comment by MEEPofFaith** [comment]
If all of them were "<color> sus", what would some be?
Blast is obviously "red sus", but there is some color overlap like lead and spore both being purple

**Comment by MEEPofFaith** [comment]
(will have to check in a few hours, discord was blocked on school wifi like a month ago :pensive:)

**Pull request closed without merging**
