### PR TITLE
Adds mindustry.tk

### PR DESCRIPTION
**Pull request by ZacBytes**

### CODE REVIEW

**Comment by DeltaNedas** [comment]
i disapprove

**Comment by ZacBytes** [comment]
Ok no one asked

**Comment by Kieaer** [comment]
disapprove 2

**Comment by ZkyLB** [comment]
***oh no***

**Comment by ado1928** [comment]
In my opinion, if you want to build a respectful playerbase, your server shoudlnt be on the global list. IMO, no unofficial servers should be on the global server list, only exception is .kr because of how many anti-grief and verification measures it has

**Comment by DeltaNedas** [comment]
conflict lol

**Comment by pyronie** [comment]
Mindustry.tk is always laggy and has connection problems, and that is while I am the only one on. A raspberry pi is simply not enough for hosting a decent server.

**Comment by pyronie** [comment]
Also, Zacbytes has (from what I have heard, so take this with a grain of salt) griefed his own server repeatedly and I know for a fact that he joins other servers and griefs them while spamming his servers ip in chat for advertisement.

**Comment by ZacBytes** [comment]
Stfu i have never griefed my own servers or advertised my own server in another server

**Comment by Kieaer** [comment]
You already griefed my server lol

**Comment by ZacBytes** [comment]
No i only built draugs

**Comment by ZkyLB** [comment]
> No i only built draugs

hm, sounds like you're griefing player's performance

**Comment by Arkanic** [comment]
i think we need a benchmark limit for servers
i don't think a rpi should be a global server by any means

**Comment by DeltaNedas** [comment]
>Stfu i have never griefed my own servers or advertised my own server in another server
so zac didnt deny the accusation of griefing other servers, only advertising his own
interesting
no :rocket: 10

**Pull request closed without merging**
