### PR TITLE
Remove omnidustry from serverlist

### PR DESCRIPTION
**Pull request by TimaHappy**
**Im tired of this**

Omnidustry was being hated by most mindustry community. I wont send here useless "proofs" that could do nothing, im doing pr with actual reason.
Here's the thing, Omnidustry console that almost owns the server and do all things in it managed to build NSFW on sandbox, meaning that omnidustry allows such content
proof:

**WARNING! NSFW CONTENT INSIDE!**
image (4)
image (1)
image
image (5)
image (2)
image (3)

### CODE REVIEW

**Comment by Def-Try** [comment]
SSTentacleSS: it is not mfkhs!!! it is drukdustr or megaohub!!

**Comment by Phinner** [comment]
I don't quite understand why you guys have the **irrepressible need** to bring drama on GitHub. Like do you need to involve absolutely **everyone** in the community ?
Because when I see #8206. it's not about pointing out problems in their servers anymore, its just throwing complaints and non-constructive criticism.
Please, just create a temporary Discord server and solve this issue once and for all with the concerned server owners.
Solving this problem is so simple and yet you want to make such a big deal about that.

**Comment by TimaHappy** [comment]
> Please, just create a temporary Discord server and solve this issue once and for all with the concerned server owners.
> Solving this problem is so simple and yet you want to make such a big deal about that.
I mean, we tried, but they couldn't listen us.

**Comment by UltraBlackLinux** [comment]
I'm all for just keeping servers. It's cool to have a broad community for mindustry. Why require strict rules? Every server is it's own bubble. The players should be able to freely choose which server to play on. Don't remove servers from the server list. Just mark them as "unverified" or something, so newcomers have a better way to distinguish between total anarchy and normal multiplayer.

**Comment by Dofaminus** [comment]
> I don't quite understand why you guys have the **irrepressible need** to bring drama on GitHub. Like do you need to involve absolutely **everyone** in the community ? Because when I see #8206. it's not about pointing out problems in their servers anymore, its just throwing complaints and non-constructive criticism. Please, just create a temporary Discord server and solve this issue once and for all with the concerned server owners. Solving this problem is so simple and yet you want to make such a big deal about that.

I already tried to do that.
And omnidustry owner, OGalaxy, just leaved it in the middle of the conversation about moderation problems and owner's responsibilities.
But yeah, that PR is nothing but fart, bruh.
I'm disappointed

**Pull request closed without merging**
