### PR TITLE
Make payload blocks run `onDestroyed()` of the block payload it carries when destroyed.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Before: 

https://user-images.githubusercontent.com/54301439/216706630-0b8fe7e3-137a-45b9-b006-535831b291fc.mp4

After:

https://user-images.githubusercontent.com/54301439/216706638-da9354fd-36bd-4349-9657-792634ec89b8.mp4

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by stacktrace-error** [comment]
YES

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/216709270-d91cdf20-b2b4-4435-93af-f3d718527ee9.mp4

**Comment by Larofeticus** [comment]
This is the most unbalanced thing I've ever seen. Mindustry becomes ozone bombing simulator; no other content relevant.

**Comment by Anuken** [comment]
makes sense on blocks, has balance implications for units so I'd rather not do that.

**Comment by MEEPofFaith** [comment]
Added a rule to enable it.

https://user-images.githubusercontent.com/54301439/217913317-4ae1e614-b41e-4eb7-96c4-b296b6b76f14.mp4

**Comment by MEEPofFaith** [comment]
ooo

**Pull request merged**
