### PR TITLE
Removed redundant (and probably also broken) vars

### PR DESCRIPTION
**Pull request by buthed010203**
These shouldn't have existed in the first place.

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by buthed010203** [comment]
The real question is why the textField has an update() and why changed() is used instead of typed() but oh well

**Comment by Anuken** [comment]
Now that I look at it, both of those classes are rather cursed.

**Comment by buthed010203** [comment]
> Now that I look at it, both of those classes are rather cursed. The default value isn't even used.

Amazing

**Comment by buthed010203** [comment]
FWIW, the default value isnt used in things such as checkpref either lmao

**Pull request merged**
