### PR TITLE
Tech Tree is no longer excessively wide

### PR DESCRIPTION
**Pull request by MEEPofFaith**
image
image

Should fix the mess I made in #7641 

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
image

\*notices\*
REEEEEEEE

**Comment by Anuken** [comment]
Maybe it's better reordered or something then. Nothing else is super wide. Might need to see how *wide* mod trees get.

**Comment by MEEPofFaith** [comment]
> Maybe it's better reordered or something then. Nothing else is super wide. Might need to see how _wide_ mod trees get.

\*Installs Exotic\*
\*Screams\*

image
image

**Comment by Anuken** [comment]
Is that tree with additional changes from this PR applied?

**Comment by MEEPofFaith** [comment]
Yes

**Comment by Anuken** [comment]
Keep it as-is then.

**Pull request closed without merging**
