### PR TITLE
Team Indicator For Unit Factory And Reconstructor

### PR DESCRIPTION
**Pull request by Voz-Duh**
In this pull i created team indicator for "Unit Factory" and "Reconstructor"
indicators-1
*Only now, instead of yellow color, there will be red*

### CODE REVIEW

**Comment by Zenith-LY** [comment]
seeing this red feels weird though the reconstructors are yellow themed, having a big red dispkay inside them doesnt fell good. Either reconstructors should also be red themed or this PR should fail.

**Comment by Voz-Duh** [comment]
@Zenith-LY in the game, the sprites are also changed to red, I just could not take a screenshot

**Comment by YellOw139** [comment]
How about unloaders next? Now that vaults and containers are colored... But go at your pace, don't mind me...

**Comment by Voz-Duh** [comment]
> How about unloaders next? Now that vaults and containers are colored... But go at your pace, don't mind me...

I created colored vaults and containers, i can create colored unloader but this looks bad

**Pull request closed without merging**
