### PR TITLE
3x3 Router: Splitter

### PR DESCRIPTION
**Pull request by z0mbiesrock**
A larger (and faster) router. Useful for late-game distribution.

Knowing my luck with PRs, I'm certain you're going to reject it...

### CODE REVIEW

**Comment by Anuken** [comment]
> Knowing my luck with PRs, I'm certain you're going to reject it...

Yep. This is unnecessary. We do not need even more transportation blocks that don't do anything new.

**Comment by Spfwniw** [comment]
> Yep. This is unnecessary. We do not need even more transportation blocks that don't do anything new.

merging a PR shouldn't be hard, therefore, extra things would harm the game.

**Comment by Anuken** [comment]
merging a PR that deletes everything in the repo would not be hard, therefore it would not harm the game

flawless logic

**Comment by DeltaNedas** [comment]
this belongs in a bad version of routorio where there are 3x3 to 16x16 routers

**Comment by z0mbiesrock** [comment]
> this belongs in a bad version of routorio where there are 3x3 to 16x16 routers

no

**Comment by sk7725** [comment]
> > this belongs in a bad version of routorio where there are 3x3 to 16x16 routers
> 
> no

yes, mods exist for a reason

**Comment by Spfwniw** [comment]
> merging a PR that deletes everything in the repo would not be hard, therefore it would not harm the game
> 
> flawless logic

What do you mean? It would harm but this doesn't.

**Comment by Esnardo** [comment]
I don't think we need this. it would be better in most cases to just use several distributors. What i would like to see is some capacity (like 5 items) in distributors

**Comment by MEEPofFaith** [comment]
Distributors already split into 7, we don't need something to split to 11.

**Pull request closed without merging**
