### PR TITLE
Update servers_v6.json

### PR DESCRIPTION
**Pull request by Volas171**

### CODE REVIEW

**Comment by Volas171** [comment]
im sorry but the ip changed just after #4091 got merged

**Comment by alexpvpmindustry** [comment]
is it ok to add 3 other addresses? we have pvp and attack and surv to add to the mix.
- alexmindustryhub.ddns.net:6568 (hub)
- alexmindustry.ddns.net:6568 (pvp)
- alexmindustry.ddns.net:6569 (survival)
- alexmindustryattac.ddns.net:2293 (attack)

**Comment by Volas171** [comment]
> is it ok to add 3 other addresses? we have pvp and attack and surv to add to the mix.
> 
> * alexmindustryhub.ddns.net:6568 (hub)
> * alexmindustry.ddns.net:6568 (pvp)
> * alexmindustry.ddns.net:6569 (survival)
> * alexmindustryattac.ddns.net:2293 (attack)

done

**Comment by alexpvpmindustry** [comment]
thank you!!

**Comment by unjown** [comment]
hello love this server pls add

**Pull request merged**
