### PR TITLE
[Mod] Deep Water Placeable Implementation

### PR DESCRIPTION
**Pull request by zethnest**
Peek 2020-05-24 18-49

Implements https://github.com/Anuken/Mindustry-Suggestions/issues/196

GIF above shows a mod that contains a block that uses the variable `requiresDeepWater` and is only placeable on deep water

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
What about being able to place in normal and deep water?
Land and water?

**Comment by zethnest** [comment]
Denied

**Comment by MEEPofFaith** [comment]
oh no

**Comment by garyType1** [comment]
If the block could be placed on deep water though, they should have a "sink" look

**Comment by zethnest** [comment]
@garyType1 That would mean the blocks are underwater

**Comment by Anuken** [comment]
I don't see much use for requirements of *deep* water specifically. This can be implemented by making `requiresWater` allow deep water placement instead.

**Pull request closed without merging**
