### PR TITLE
New team indication

### PR DESCRIPTION
**Pull request by Slava0135**
image
image

### CODE REVIEW

**Comment by Slava0135** [comment]
*not sure about turret bases

**Comment by BlueWolf3682** [comment]
green has no lower area and i see z fighting

**Comment by joshuaptfan** [comment]
The concept has problems on various terrain types of varying color, such as spore moss, grass, etc.

**Comment by Slava0135** [comment]
image

**Comment by unjown** [comment]
this is actually a good idea but i think its too bright?? maybe make it more transparent

**Comment by Slava0135** [comment]
ok, I am having problems with parallax base coloring. Probably should revert the effect,,,

**Comment by Slava0135** [comment]
image

**Comment by Slava0135** [comment]
image
*alpha 75%

**Comment by Slava0135** [comment]
> green has no lower area and i see z fighting

It's because I am green lol

**Comment by Slava0135** [comment]
> The concept has fundamental problems on various terrain types of varying color, such as sand, spore moss, grass, etc.

But it's better than nothing. Without it it's even harder to see...

**Comment by Slava0135** [comment]
If you don't like it - tell me why. Everything can be changed.

**Comment by Slava0135** [comment]
ok, I removed the turret base coloring. Also I added a setting to configure the outline opacity.

**Comment by Slava0135** [comment]
https://user-images.githubusercontent.com/40753025/105174902-45a80b80-5b34-11eb-9621-b15654a86dcd.mp4

**Comment by Slava0135** [comment]
image

**Comment by Slava0135** [comment]
image

**Comment by Slava0135** [comment]
*removed opacity option until intersections will be solved

**Comment by Slava0135** [comment]
image

**Comment by Anuken** [comment]
Tested this out a bit on some servers, and while it doesn't look *awful* for most blocks, it's not really an improvement either.

**Pull request closed without merging**
