### PR TITLE
show liquids in "resources detected" section

### PR DESCRIPTION
**Pull request by ThatOneBepis**
Just a little QoL. It is draft because i don't really have memorized liquid localisation in zones that well...

### CODE REVIEW

**Comment by ThatOneBepis** [comment]
apparently it cannot be done

**Comment by Anuken** [comment]
Please use an IntelliJ for development. If you try to edit code without seeing exactly what's going on, everything will result in errors. At the very least, try running it first.

**Comment by ThatOneBepis** [comment]
Well, the issue of "running it first"... i cannot even compile working master branch, by any means

**Comment by Anuken** [comment]
Import it in IntelliJ and find out why that is.

**Comment by ThatOneBepis** [comment]
Perhaps gradlew in general
actually lets continue this in DMs (#nope.avi#4037 is my discord tag incase you wonder)

**Pull request closed without merging**
