### PR TITLE
Add PlayerChatEvent on clients

### PR DESCRIPTION
**Pull request by code-explorer786**
based on [this](https://github.com/mindustry-antigrief/mindustry-client/commit/d32dd01097ef62fb0a1bd5aade2a738c04652854) and a conversation with @buthed010203 on Discord :)

untested because rushed

- [X] I am still deciding.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by code-explorer786** [comment]
i have an unhealthy `git commit --amend; git push -f` addiction

**Comment by Weathercold** [comment]
This will be very useful

> i have an unhealthy `git commit --amend; git push -f` addiction

Force pushing on a pr is pretty healthy

**Comment by buthed010203** [comment]
Copium overload

**Comment by Anuken** [comment]
testing is required

**Comment by code-explorer786** [comment]
it breaks :+1:
by the way should we also have another EventType whenever `playersender` or `unformatted` is invalid (so when the server `Call.sendMessage`'s us, we fire something like `ChatEvent`)
i'm currently testing this right now

**Comment by code-explorer786** [comment]
image
will push later, currently deciding what to do

**Comment by code-explorer786** [comment]
ah welp there it goes
i hope nothing goes wrong

**Pull request merged**
