### PR TITLE
Improved Bullet Velocity Inheritance

### PR DESCRIPTION
**Pull request by MEEPofFaith**
- Frag bullets now use the velocity of the parent bullet instead of the velocity of the unit that fired the original bullet
- The amount inherited is now scalable

https://cdn.discordapp.com/attachments/653293028869537843/949927139799609354/Improved_Bullet_Velocity_Inheritance.mp4

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
> Frag bullets now use the velocity of the parent bullet instead of the velocity of the unit that fired the original bullet

But this is very much undesirable. It completely changes the way fragmentation works; for every bullet I've made, I want the child bullets to explode *around* the source bullet, *not* keep flying forward. This breaks bullet patterns without good reason.

**Comment by MEEPofFaith** [comment]
> > Frag bullets now use the velocity of the parent bullet instead of the velocity of the unit that fired the original bullet
> 
> But this is very much undesirable. It completely changes the way fragmentation works; for every bullet I've made, I want the child bullets to explode _around_ the source bullet, _not_ keep flying forward. This breaks bullet patterns without good reason.

~~Just set `velocityInheritance = 0f;`~~
~~That fact the frag bullets inherit the velocity of the unit that fired it makes no sense anyways, like how Toxopid currently is.~~

**Comment by Anuken** [comment]
> Just set velocityInheritance = 0f;

That's still broken behavior by default - terrible design.

**Comment by MEEPofFaith** [comment]
~~Since v7 is already breaking everything why not add something else to the list of smashed items :)))~~

**Pull request closed without merging**
