### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by MichaAI**
Add my server

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MichaAI** [comment]
@Anuken review pls

**Comment by StalkerBaran** [comment]
I guess, its bad idea to allow him to be added in global list. I dont want a drama, but there are many complaints about him, both from me and other people. There's only some of them, it could be much more

1. He raided old Darkdustry (Mindurka) server (probably year-two ago) (using discord webhooks for ping @everyone)
image

2. He raided MeowIsland (my own server. He was a coder and had access for bots and used them to do a lot ugly things on screenshots:) 
image
image
2.1 Tried to ping everyone, using a bot with my and my head-admin pfp
image
image
2.2 Proofs about raiding 
image
image
image

3. Stole MeowIsland plugin and used on his own server without permission (before adding to global list)
image

4. Threats about raiding a server 
image
image
image

Sorry for russian text, but anyway compare his behavior (the raid two years ago and the raid of my server "for a joke" a month ago)

**Comment by MichaAI** [comment]
> I guess, its bad idea to allow him to be added in global list. I dont want a drama, but there are many complaints about him, both from me and other people. There's only some of them, it could be much more
> 
> 1. He raided old Darkdustry (Mindurka) server (probably year-two ago) (using discord webhooks for ping @everyone)
>    image
> 2. He raided MeowIsland (my own server. He was a coder and had access for bots and used them to do a lot ugly things on screenshots:)
>    image
>    image
>    2.1 Tried to ping everyone, using a bot with my and my head-admin pfp
>    image
>    image
>    2.2 Proofs about raiding
>    image
>    image
>    image
> 3. Stole MeowIsland plugin and used on his own server without permission (before adding to global list)
>    image
> 4. Threats about raiding a server
>    image
>    image
>    image
> 
> Sorry for russian text, but anyway compare his behavior (the raid two years ago and the raid of my server "for a joke" a month ago)

- 1 It was a vulnerability in the @Def-Try Discord bot, anyone else could have done it, but I found it first. 
- 2 I do not deny that there was a case, but I have already received my punishment on this server, so this does not affect the addition of the server to the globalist in any way 
- 3 You have been using my plugin for integration with Discord for the last 2 months without my permission
image-7
image-6
, and I, in turn, deleted the plugin before creating this pull request 
Screenshot_20240916_172958
- 4 The fact that I say that I have the opportunity for ddos does not mean that I am going to commit them. 

I also want to add that this person does not want me to get into the globalist because he is going to do the same mode on his server that I am currently creating, thus eliminating a competitor

**Comment by StalkerBaran** [comment]
1. I guess... you found... vulnerability... in your OWN bot and used it AGAINST darkdustry multiples time. If you found a bug, you CANT use against a server to ping everyone or do something worse
2. Its not first raid server. You were a coder on AT LEAST two servers, which you then crashed. It can say a lot about you and your behavior
3. We already deleted your plugin after some days you got banned. You was a CODER on my server and you made this plugin FOR SERVER, not for yourself. And Afflict (head-admin) bought 2 games for you in steam to pay with you (7-8+ dollars)
4. -_-
Nope, we are not gonna make a ranked (right now, but maybe in future). There's already thedimas and Eradication making Ranked

**Comment by MichaAI** [comment]
> 1. I guess... you found... vulnerability... in your OWN bot and used it AGAINST darkdustry multiples time. If you found a bug, you CANT use against a server to ping everyone or do something worse
> 2. Its not first raid server. You were a coder on AT LEAST two servers, which you then crashed. It can say a lot about you and your behavior
> 3. We already deleted your plugin after some days you got banned. You was a CODER on my server and you made this plugin FOR SERVER, not for yourself. And Afflict (head-admin) bought 2 games for you in steam to pay with you (7-8+ dollars)
> 4. -_-
>    Nope, we are not gonna make a ranked (right now, but maybe in future). There's already thedimas and Eradication making Ranked

- 1 It was a vulnerability in the ***@Def-Try*** Discord bot, not in my discord bot, my discord bots have never even been on mindura 
- 2 I have NEVER been a coder on mindura. And I wouldn't call one ping an evivan raid. 
- 3 Please look at the date of the second screenshot before you approve it. In any case, I am the author of the plugin, so I can quite claim that this is MY plugin, even though it was written for your server. 
- 5 Okay, then why do you tell the programmer to come to you after he says that he is going to make his Prototype of a ranked one?
Screenshot_2024_0916_181930

**Comment by vir214** [comment]
github drama

**Comment by Minemaster656** [comment]
~~help, MichaAI stole me to code a plugin for this server. I don't know where i am.~~

**Comment by Def-Try** [comment]
i don't know what to say. micha, i'm sorry, but all this stuff reminded of *why* i blocked and ceised all communication with you that one time

**Comment by HazarderCrypt** [comment]
> * 1 It was a vulnerability in the _**@Def-Try**_ Discord bot, not in my discord bot, my discord bots have never even been on mindurka
> * 2 I have NEVER been a coder on mindurka. And I wouldn't call one ping an everyone raid.
> * 3 Please look at the date of the second screenshot before you approve it. In any case, I am the author of the plugin, so I can quite claim that this is MY plugin, even though it was written for your server.
> * 5 Okay, then why do you tell the programmer to come to you after he says that he is going to make his Prototype of a ranked one?

(Im hazarder, meowisland head-admin)
I want to make some amendments.
1. you still haven't answered why you can just harm servers for no reason using the Def-Try vulnerability and use nicknames and pfps of head-admins.
2. I would like to correct blackberry (stalkerBaran). As far as I was told (screenshot(<meo> ня is Googer)), you used someone else's bot for ping. and even if it’s not a raid, it’s serious harm to the server anyway.
3. It is YOUR plugin, but if you made it for Meowisland and don't forbid us to use it for 2 months, there are no reason to delete it. We deleted your plugin only when you said to do that.

We want to make ranked pvp, but it's not the reason why you shouldn't be it global list. Even if you are correct and your crimes against 2 servers is not a reason for not to add you to global list, I think Anuke should know what you are doing in other servers. But I think it is reason not to add you: You are harming other servers.
Screenshot_2024-09-16-19-33-21-868-edit_com bluecord
Screenshot_2024-09-16-19-33-54-541-edit_com bluecord

**Comment by MichaAI** [comment]
> > * 1 It was a vulnerability in the _**@Def-Try**_ Discord bot, not in my discord bot, my discord bots have never even been on mindurka
> > * 2 I have NEVER been a coder on mindurka. And I wouldn't call one ping an everyone raid.
> > * 3 Please look at the date of the second screenshot before you approve it. In any case, I am the author of the plugin, so I can quite claim that this is MY plugin, even though it was written for your server.
> > * 5 Okay, then why do you tell the programmer to come to you after he says that he is going to make his Prototype of a ranked one?
> 
> (Im hazarder, meowisland head-admin) I want to make some amendments.
> 
> 1. you still haven't answered why you can just harm servers for no reason using the Def-Try vulnerability and use nicknames and pfps of head-admins.
> 2. I would like to correct blackberry (stalkerBaran). As far as I was told (screenshot(meo ня is Googer)), you used Googer's bot for ping. and even if it’s not a raid, it’s serious harm to the server anyway.
> 3. It is YOUR plugin, but if you made it for Meowisland and don't forbid us to use it for 2 months, there are no reason to delete it. We deleted your plugin only when you said to do it.
> 
> We want to make ranked pvp, but it's not the reason why you shouldn't be it global list. Even if you are correct and your crimes against 2 servers is not a reason for not to add you to global list, I think Anuke should know what you are doing in other servers. But I think it is reason not to add you: You are harming other servers. Screenshot_2024-09-16-19-33-21-868-edit_com bluecord Screenshot_2024-09-16-19-33-54-541-edit_com bluecord

- 1 I had reasons to cause harm, and I have already received punishment for this on both servers
- 3 I can just as well say that you didn’t ask me for permission to use it, and I didn’t ask to remove the plugin because I was busy.

> But I think it is reason not to add you: You are harming other servers.

Does it make sense for me to harm other servers when I make my own?

**Comment by Def-Try** [comment]
TL;DR: you have very bad reputation and there is no guarantees that your server won't get removal pr in first week of it's existence considering how you handle your boredom

**Comment by HazarderCrypt** [comment]
> * 1 I had reasons to cause harm, and I have already received punishment for this on both servers
> * 3 I can just as well say that you didn’t ask me for permission to use it, and I didn’t ask to remove the plugin because I was busy.
> 
> > But I think it is reason not to add you: You are harming other servers.
> 
> Does it make sense for me to harm other servers when I make my own?

1. Ah! OF COURCE!!! You had a reason!!!!! (Screenshot)
3. You are so busy that you couldn't write 1 message with 3 words: "remove my plugin"? And I think we had permissions to use it, because you made it for Meowisland. In that case I think we will not be able to use it only when you will tell us not to use it. But you can't write 1 message and now you are trying to blame us for your "ultimate busyness".

You are contradicting yourself. In 1. You said that you had reasons (yeah, "For fun" Is the best reason) And now you say, that you don't have sense to harm because you are making your own server.
Screenshot_2024-09-16-20-41-48-337-edit_com bluecord

**Comment by HazarderCrypt** [comment]
Forgot about screen
Screenshot_2024-09-16-20-41-48-337-edit_com bluecord

**Comment by MichaAI** [comment]
> > * 1 I had reasons to cause harm, and I have already received punishment for this on both servers
> > * 3 I can just as well say that you didn’t ask me for permission to use it, and I didn’t ask to remove the plugin because I was busy.
> > 
> > > But I think it is reason not to add you: You are harming other servers.
> > 
> > 
> > Does it make sense for me to harm other servers when I make my own?
> 
> 1. Ah! OF COURCE!!! You had a reason!!!!! (Screenshot)
> 2. You are so busy that you couldn't write 1 message with 3 words: "remove my plugin"? And I think we had permissions to use it, because you made it for Meowisland. In that case I think we will not be able to use it only when you will tell us not to use it. But you can't write 1 message and now you are trying to blame us for your "ultimate busyness".
> 
> You are contradicting yourself. In 1. You said that you had reasons (yeah, "For fun" Is the best reason) And now you say, that you don't have sense to harm because you are making your own server. Screenshot_2024-09-16-20-41-48-337-edit_com bluecord



> > * 1 I had reasons to cause harm, and I have already received punishment for this on both servers
> > * 3 I can just as well say that you didn’t ask me for permission to use it, and I didn’t ask to remove the plugin because I was busy.
> > 
> > > But I think it is reason not to add you: You are harming other servers.
> > 
> > 
> > Does it make sense for me to harm other servers when I make my own?
> 
> 1. Ah! OF COURCE!!! You had a reason!!!!! (Screenshot)
> 2. You are so busy that you couldn't write 1 message with 3 words: "remove my plugin"? And I think we had permissions to use it, because you made it for Meowisland. In that case I think we will not be able to use it only when you will tell us not to use it. But you can't write 1 message and now you are trying to blame us for your "ultimate busyness".
> 
> You are contradicting yourself. In 1. You said that you had reasons (yeah, "For fun" Is the best reason) And now you say, that you don't have sense to harm because you are making your own server. Screenshot_2024-09-16-20-41-48-337-edit_com bluecord

1 There were reasons in the past, but now I won’t have them because I’ll be busy with my server
2 How do you know if I had time to write these three words
And yes, I want to note that the discussion is about what I did in the past, but there is nothing against the server that I open.

**Comment by Minemaster656** [comment]
Wow, now I can read MichaAI's drammas also on GitHub.

**Comment by Minemaster656** [comment]
If the server plugin will be really good and MichaAI doesn't do Average-MichaAIs-destructive-things, then adding this server to the global list will make sense. (But as I know - MichaAI is unfixable clown)

**Comment by Pulsar6** [comment]
I don't see any reason not to add the server to the global list. Conflicts are a personal matter as long as they do not affect the servers in the game(e.g. DDoS attacks) and Micha did not interfere with the servers in the game in any way and you can always remove the server from the global l+ You can always remove a server from the global list if Micha interferes with other servers

**Comment by HazarderCrypt** [comment]
> 1 There were reasons in the past, but now I won’t have them because I’ll be busy with my server 2 How do you know if I had time to write these three words And yes, I want to note that the discussion is about what I did in the past, but there is nothing against the server that I open.
> 
> Edit: double reply

1. Yes, you are right, you have reasons: "for fun". And why did this reason disappear? It becomes unfunny when the question is about your server? I see only this way of disappearing the reason "for fun".
2. Bruh, if you answered me so geniously, I will follow your example: there are approximately  5184000 seconds in 2 months, writing 3 words takes 4.5 seconds. It is physically impossible for a human to be so busy for 2 months without stopping that there is no time to spend 4.5 seconds on the phone. at least you could spend 4.5 seconds of your 30600 seconds of sleeping time. But it looks like you just have nothing to answer and you are writing something like this.

The past was 2 months ago. It isn't enough for forgetting your server crimes. You aren't even learned anything from your first punishment in darkdustry.

You aren't properly explain any of the claims. Reason of raid: for fun. Reason for blaming Meowisland: I don't have 4.5 seconds.

If you want, we can end this drama now, and give Anuke to choose:
-------Is 1.5 raids with pings Everyone for fun, identity faking in raid, unjustified accusation of using your plugin and other small or not small things A reason not to add the server. Or No-------. Let's just see?

**Comment by MichaAI** [comment]
> > 1 There were reasons in the past, but now I won’t have them because I’ll be busy with my server 2 How do you know if I had time to write these three words And yes, I want to note that the discussion is about what I did in the past, but there is nothing against the server that I open.
> > Edit: double reply
> 
> 1. Yes, you are right, you have reasons: "for fun". And why did this reason disappear? It becomes unfunny when the question is about your server? I see only this way of disappearing the reason "for fun".
> 2. Bruh, if you answered me so geniously, I will follow your example: there are approximately  5184000 seconds in 2 months, writing 3 words takes 4.5 seconds. It is physically impossible for a human to be so busy for 2 months without stopping that there is no time to spend 4.5 seconds on the phone. at least you could spend 4.5 seconds of your 30600 seconds of sleeping time. But it looks like you just have nothing to answer and you are writing something like this.
> 
> The past was 2 months ago. It isn't enough for forgetting your server crimes. You aren't even learned anything from your first punishment in darkdustry.
> 
> You aren't properly explain any of the claims. Reason of raid: for fun. Reason for blaming Meowisland: I don't have 4.5 seconds.
> 
> If you want, we can end this drama now, and give Anuke to choose: -------Is 1.5 raids with pings Everyone for fun, identity faking in raid, unjustified accusation of using your plugin and other small or not small things A reason not to add the server. Or No-------. Let's just see?

Its not 1,5 raids, its only one raid to meow island 

In turn, I want to note that you still used my plugin without permission for 2 months, although I did not say that I was against it. The fact that I didn't say that I was against these two months doesn't mean that I was for it.

**Comment by Def-Try** [comment]
this is going nowhere. we all know what anuke will either
a) ignore all that drama and just merge the pr
b) whip out the "monkeys throwing shit at each other" card and make us shut up, then proceed with a or c
or c) ignore that pr whatsoever

**Comment by neprobit** [comment]
I think that a new ranked server is needed in the global list. Despite the conflicts, I am sure that Micha will take a responsible approach to the server's maintenance. Now in the global list there is no really normal ranked server that would be pleasant to play

**Comment by 5GameMaker** [comment]
Personally I see no issue with this server being added on server list for as long as it doesn't use Meowland plugin

**Comment by MichaAI** [comment]
@Anuken please watch this

**Comment by nicknamewhat801** [comment]
> github drama

ya-ya.Github drama.

**Comment by StalkerBaran** [comment]
~~MichaAI really dont asked in DM everyone to place like reactions~~

**Comment by Pulsar6** [comment]
If people want a normal ranked, then what's the problem with asking them to say that they need a ranked?

**Review by Darkness6030 — APPROVED** [review]

**Comment by StalkerBaran** [comment]
image
image

Uhhh... I guess, Micha really asked everyone on his server to get likes under his pull -_-

**Comment by Def-Try** [comment]
he's so desperate lol

**Comment by Pulsar6** [comment]
Bro asked not Micha but I because I know that no one will do a normal rank PvP server in the near future except Micha

**Comment by Pulsar6** [comment]
+ many players want a ranked pvp server, but know what to do for it

**Comment by BnDLett** [comment]
"I don't want a drama"
*causes drama*

Peak Mindustry Github experience.

**Comment by StalkerBaran** [comment]
:clueless:

**Comment by BnDLett** [comment]
Also, while I'm at it, I'm going to throw in my two cents. There's really no guideline in the [serverlist guidelines](https://github.com/Anuken/Mindustry/blob/master/SERVERLIST.md) against these actions. Sure, they're distasteful if they are true, but there is no guideline that is stopping Anuke from adding this server into the server list. 

Of course, that said, it really is up to Anuke's own discretion -- this is just my two cents.

**Comment by Gwapowo** [comment]
take a shot everytime a server is involved in drama

**Comment by Def-Try** [comment]
Just so you know, more messages leads to the less chance of server being actually accepted, so i wouldn't recommend micha's supporters just repeating arguments already told in there (of which there are like 2, and they both are extrapolated from what pulsar wants, who recently raided mindurka via asking 2 other people to spam stuff in there)

**Review by osp54 — APPROVED** [review]

**Review by Darkness6030 — APPROVED** [review]

**Comment by Dofaminus** [comment]
As long as he doesn't do anything sketchy(again) i don't mind personally. Anyway we can(i hope) take down this server at anytime if Micha does something against the rules.

**Comment by Def-Try** [comment]
anuke pretty much never deletes servers from global from my experience, so... that's really mostly a one-way pr. once he gets inz there is a very little chance of us getting him back out, even if he does terrible stuff. remember the omny incident.

**Comment by Dofaminus** [comment]
> anuke pretty much never deletes servers from global from my experience, so... that's really mostly a one-way pr. once he gets inz there is a very little chance of us getting him back out, even if he does terrible stuff. remember the omny incident.

fair

**Comment by StalkerBaran** [comment]
image

Lol

**Comment by Anuken** [comment]
I'm not reading all that.

**Pull request closed without merging**
