### PR TITLE
Change to overdrive sprite to help color blind people

### PR DESCRIPTION
**Pull request by bloool**
This includes changes both to the overdrive projector and overdrive dome, overdrive main sprite change is due to it being just a recolor of mender, and many people have red to green colorblindness which can make differentiate from both very hard. Overdrive dome also gets a sprite change to match the new small one.

Even if these don't make it into the game, getting anything similar would still be nice, even if OD has a little animation can still be hard to distinguish them quickly.

There is also another alternative made by Newguy#7763 on discord, that covers more of the middle part.
image

### CODE REVIEW

**Comment by liuxilu** [comment]
Better a layer on the final image for everything, or just OS build-in color-blind filter.

**Comment by sk7725** [comment]
I would do a different approach, mainly tweak the square effect drawn on top. There are striking UI differences when hovered over(the overdrive has an extra bar), and both projectors are normally almost always in a powered state constantly.
Also the 3x3 looks bad, and you don't need to change the 3x3 anyways

**Comment by bloool** [comment]
> I would do a different approach, mainly tweak the square effect drawn on top. There are striking UI differences when hovered over(the overdrive has an extra bar), and both projectors are normally almost always in a powered state constantly.
> Also the 3x3 looks bad, and you don't need to change the 3x3 anyways



> I would do a different approach, mainly tweak the square effect drawn on top. There are striking UI differences when hovered over(the overdrive has an extra bar), and both projectors are normally almost always in a powered state constantly.
> Also the 3x3 looks bad, and you don't need to change the 3x3 anyways

Yeah but think about it in a image or scheme, you wouldn't be able to see a difference if you are colorblind, and I just changed the 3x3 just so it doesn't look way too different from the 2x2, but anyway, even if those exact sprites doesn't get in the game, anything would be better than a recolor

**Comment by sk7725** [comment]
> image or schem

Why didn't I even think of them, you're right.
But still I don't think sprite change is the best approach here...hmm...

**Comment by bloool** [comment]
The only thing I can think about atm is a sprite change, because effects are out of the equation in schems or just some quick look at a defense

**Comment by MEEPofFaith** [comment]
Why not sprite and effect changes?

**Comment by bloool** [comment]
> Why not sprite and effect changes?

That would work wonders, but idk if anuke would want to change the sprites completely, since its very iconic by now, but who knows, if plastanium can get a change after so much time

**Comment by Quezler** [comment]
@bloool is this still needed, or was #4807 enough?

**Comment by bloool** [comment]
> @bloool is this still needed, or was #4807 enough?

That would still not solve the problem when using schems, but it's really good already

**Pull request closed without merging**
