### PR TITLE
Update thedimas' hub ip

### PR DESCRIPTION
**Pull request by thedimas3007**
The new hub has smaller ping then the one that's now

### CODE REVIEW

**Comment by L0615T1C5-216AC-9437** [comment]
bruh use a dns/ddns

**Comment by WilloIzCitron** [comment]
ddns its pay host, use noip but limited host for free user

**Comment by WilloIzCitron** [comment]
thedimas could not afford to pay for DDNS

**Comment by thedimas3007** [comment]
I'll close this PR due to instability of gefr node

**Pull request closed without merging**
