### PR TITLE
Heat for accelerator

### PR DESCRIPTION
**Pull request by sk7725**
The lights glow when powered, the effects on bullet layer glow when items are sufficient.
녹화_2020_12_22_09_54_04_275
*Left: items & power are sufficient(aka consValid), right: only power is sufficient*

### CODE REVIEW

**Comment by Quezler** [comment]
maybe a small gif/video preview?

**Comment by sk7725** [comment]
> maybe a small gif/video preview?

Sure, as soon as Im freed(aka 6 hours later)

**Comment by sk7725** [comment]
> maybe a small gif/video preview?

@quezler done

**Comment by catatagun** [comment]
What is this. This is bad

**Comment by Erisfiregamer1** [comment]
no its good

**Pull request merged**
