### PR TITLE
Allow for modifying build turret units?

### PR DESCRIPTION
**Pull request by MEEPofFaith**
image
image
image

hahaha I have no idea what im doing and should definitely test

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
What exactly would you even do with this unit?

**Comment by BlueWolf3682** [comment]
basically stick a unit onto a block, allowing for stuff like some limited multiweapon turrets and build/defense hybrids
not sure if you can fire weapons as a build turret, but at least being able to stick autoweapons or multiple build weapons would be cool

**Comment by Anuken** [comment]
None of those are possible with builder turrets. The "unit" they have is fake, it's not supposed to be a *real* unit on top of a turret. The things that draw and update on it are strictly limited to the base build beam and building logic, anything else (like weapons) won't show up or function at all.

**Comment by BlueWolf3682** [comment]
well it was worth a shot

**Pull request closed without merging**
