### PR TITLE
Huge translate and fix, bundle_fr.properties I respect the etymology and the context (not finished)

### PR DESCRIPTION
**Pull request by Bryggel**
All this work is done with others translators :+1:

### CODE REVIEW

**Comment by itskatt** [comment]
I am sorry, but there's is already a pull request about updating the game's French translation (see #594). If you want to help me, please submit a pull request on my fork instead ([link](https://github.com/itskatt/Mindustry/blob/french-translation/core/assets/bundles/bundle_fr.properties))

**Comment by Bryggel** [comment]
> I am sorry, but there's is already a pull request about updating the game's French translation (see #594). If you want to help me, please submit a pull request on my fork instead ([link](https://github.com/itskatt/Mindustry/blob/french-translation/core/assets/bundles/bundle_fr.properties))

Non je vais pas t'aider, trop tard flemme de tout recommencer j'ai fait un gros travail

**Comment by Bryggel** [comment]
wait :)

**Comment by Bryggel** [comment]
i will help you after they confirm and apply my work

**Comment by Bryggel** [comment]
Several serious errors,  an example.
For the mender and projector
Silicone can be used for the mender and phased fabric for the projector to improve the range and efficiency
I did not know because of monkeys, who are blind and  can not compare two files
 what has been untranslated and erased.
Faults of context,  the slag is not "scories" because slag is liquid, not solid so the correct term is "lave".
Take the file in English and translate since otherwise there will still be errors that will cause gaps

**Comment by Bryggel** [comment]
Thx to @itskatt and his work #594, i merge  faede99  and his file 31cd98b

**Comment by Bryggel** [comment]
Thx to @itskatt and his work #594, i merge  faede99  and his file 31cd98b :+1:

**Comment by Bryggel** [comment]
Just above, thank in advance: )

**Comment by Anuken** [comment]
>  i merge faede99 and his file 31cd98b

Please *don't* copy-paste other people's pull requests into yours, especially without their permission. Not only is it rude, but it is also completely unnecessary; if you have new changes that need to be made, both file contents can be merged automatically, as long you're editing different parts of the file.

In fact, by copy-pasting that file, you've caused a *massive* merge conflict, which would take a very long time to resolve manually. I just can't merge this.

**Pull request closed without merging**
