### PR TITLE
spawnUnit, spawnUnitTeam and spawnUnitCount

### PR DESCRIPTION
**Pull request by SMOLKEYS**
Essentially allows for the creation of "egg" blocks.

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by code-explorer786** [comment]
I like the idea!
Though, I don't think this will function correctly because there's no modification to `Buildingc` so that it'll actually spawn units when killed...

**Comment by SMOLKEYS** [comment]
wait

**Comment by SMOLKEYS** [comment]
ohfuck i forgot to add the code for handling it 💀

**Comment by GlennFolker** [comment]
sigh

**Pull request closed without merging**
