### PR TITLE
Add servers v6.0 from Mindustry.ru

### PR DESCRIPTION
**Pull request by MindustryRu**
Add server v6.0

**v6.mindustry.ru** - Survival
**v6.mindustry.ru:6577** - PvP
**v6.mindustry.ru:6587** - SandBox
**v6.mindustry.ru:6597** - Hexed server

P.s We strongly recommend not to make a srach through reactions / emoticons / messages. The game developer will make the decision himself.
logo

### CODE REVIEW

**Comment by Makc-Carbon** [comment]
Зачееем? У вас есть хаб, прошу пихать все туда. Нам вас хватает лишь с 1 хабом. Я уже тогда описал все.

**Comment by TheSlaylord** [comment]
@MINDUSTRYRU у вас уже есть PR, ёпрст

**Comment by MINDUSTRYRU** [comment]
> Зачееем? У вас есть хаб, прошу пихать все туда. Нам вас хватает лишь с 1 хабом. Я уже тогда описал все.

To create a "hub" additional equipment is required, which is not available, since a hub is a separate server.
Having Eng servers have all their servers on the list + the same hub, doesn't it contradict? Do not make me laugh. As previously stated, the decision will be made by the developer, starting from common sense and reason.

**Comment by Remint32** [comment]
I strongly recommend that you do not make duplicates of not accepted PRs

**Comment by BasedUser** [comment]
Duplicate of #3039. No comment.

**Comment by Vandomas** [comment]
> > Зачееем? У вас есть хаб, прошу пихать все туда. Нам вас хватает лишь с 1 хабом. Я уже тогда описал все.
> 
> To create a "hub" additional equipment is required, which is not available, since a hub is a separate server.
> Having Eng servers have all their servers on the list + the same hub, doesn't it contradict? Do not make me laugh. As previously stated, the decision will be made by the developer, starting from common sense and reason.

its _your_ problem, not our

**Comment by DeltaNedas** [comment]
no

**Comment by shebandr** [comment]
мало вам было наличия дурки в глобале, теперь у нас есть аж 4 дурки в глобале, с донатом и отбитыми админами, вообще отличная идея, я вас поздравляю

**Comment by macdowntwo** [comment]
bruh y u duplicate

> P.s We strongly recommend not to make a srach through reactions / emoticons / messages.

ah yes, _**scrah**_

> The game developer will make the decision himself.

the game developer **AND** the community will decide the fate of this spoiled egg

**Comment by ThePythonGuy3** [comment]
Thats how Open Source works

**Comment by Xusk947** [comment]
if your admins dont know java code to write plugins that not our problem to spam with 4 not need servers

**Comment by Voz-Duh** [comment]
@MINDUSTRYRU перестаньте пихать всем своё (извеняюсь за выражение) дерьмо, если хотите чтобы это было в игре, для начала исправтесь
А так, сами сидите в своих недосерверах

**Comment by Voz-Duh** [comment]
> We strongly recommend not to make a srach through reactions / emoticons / messages. The game developer will make the decision himself.

И с этим я не согласен, разработчику игры нужны отзывы людей, ибо если он добавит в игру то что не-кому не нужно и не нравится то скорее всего на него пойдут жалобы так что я не предлагаю писать такие "Ps" ибо потом проблемы будут у тебя (вас)

**Comment by Somka000** [comment]
Nobody wants this server in the public 6.0 server list, why?

P2W (https://www.cyberdefinitions.com/definitions/P2W) - all mindustry players hate it. Mindustry.ru is first server where it was P2W. I thought the owner was creating a server for fun, for players, not for money. For me owner .ru is really a greedy man and broken. 
Now there is no p2w, but we see that the administration is trying to punish or ban players for very low harmful deeds, and if e.g muted player on dc wants to get unmute, they cant write application for unmute, he can only buy(XD) unmute. https://i.imgur.com/e3BTdhn.png
Another issue is administration, which looks at how players build shame design factories/schematics and they don't do anything about it. As a result, every player who plays longer on mindustry.ru are worse, then I see such players on other servers and on my. There are many more reasons why gamers hate mindustry.ru. Now mindustry has many servers, everyone is better than mindustry.ru and everyone will fit for .ru place on the public 6.0 server list, there are also servers for Russians: pandorum and routerchain that have experienced admins.

**Comment by YellOw139** [comment]
> Duplicate of #3039. No comment.

You also closed #3039 too, which speaks for yourself. Either you are trying to run from the backlash of that PR's thread, or you are trying to get attention.
If Anuke didn't want to merge it @MINDUSTRYRU, Anuke would have closed it himself. So any worries about not being in 6.0 are  unjustified, and any attempt ro run from the backlash is just futile, you are attracting more attention this way, hence I, who didn't care about the scandal and who's right or wrong started to.

**Comment by ritzip** [comment]
Point was the first pull was closed to get rid of the dislikes, this pull does the same thing.

**Comment by ifritdiezel** [comment]
You ain't getting rid of all the dislikes _that_ easily; they aren't coming from nowhere. Your whole history of wrongdoings and offense will ultimately _not_ be forgotten. Accept what you deserve.

**Comment by sk7725** [comment]
> You ain't getting rid of all the dislikes _that_ easily; they aren't coming from nowhere. Your whole history of wrongdoings and offense will ultimately _not_ be forgotten. Accept what you deserve.

r

**Comment by ifritdiezel** [comment]
> r

m

**Comment by Anuken** [comment]
Locking conversation here, as there's nothing new to be said. I'll decide what to do with this PR after discussing it with the members involved, personally.

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/pull/3793#issuecomment-739560478

**Pull request closed without merging**
