### PR TITLE
made comment statement

### PR DESCRIPTION
**Pull request by Jenya705**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Darkness6030** [comment]
Did you test it?
If yes, please show some screenshots

**Comment by Jenya705** [comment]
изображение
Comments are saving on rejoin

**Comment by Darkness6030** [comment]
Oh

**Comment by Darkness6030** [comment]
@Anuken review please :eyes:

**Comment by Anuken** [comment]
This doesn't work properly:

1. Comments don't have an inherent length limit, which means logic block info can get arbitrarily large with comment spam. This has severe implications for both memory usage and network sync. I don't see a way around this.
2. Comments act as statements, meaning *having comments in your logic program will slow it down*. You can't just strip them out, because 1) you won't be able to view the comments afterwards then, and 2) jump offsets will be broken. Not an easy problem to fix.

**Comment by Jenya705** [comment]
It will slow down only on code update, because it throw away all null instructions
```java
asm.instructions = st.map(l -> l.build(asm)).filter(l -> l != null).toArray(LInstruction.class);
```

**Pull request closed without merging**
