### PR TITLE
Chaos Array and Eradicator, Lich and Reaper weapons, and Other Small Unit Changes

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Also made a small change to WeaponComp to make the shootSound play with every shot instead of every volley.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Travis: Build failed.
Info at the bottom of the gradle bit: Build Successful

**Comment by Syncinus** [comment]
Lich and Reaper are probably going to be reworked (which is why they currently don't have weapons), and Chaos Array and Eradicator are probably going to also be highly changed. This PR will probably never be accepted.

**Comment by MEEPofFaith** [comment]
Well, it's a start. Plus, I did do some changes to weapons.

**Comment by MEEPofFaith** [comment]
Current changes:

- Chaos Array and Eradicator
- Weapons for Lich and Reaper, changed Revenant to alternate. (I'll just let Anuke figure out how to make Mirror + Rotate work)
- Weapons with shotDelay can shoot from out to in or from in to out with `spreadIn = true/false`
- Sound plays when trying to shoot with no ammo (Currently uses the door sound, didn't bother making a new sound)

**Pull request closed without merging**
