### PR TITLE
🐝 Flight of the pootisbird 🐦

### PR DESCRIPTION
**Pull request by Quezler**
Just something silly ima leave here, movable cores (っ◕‿◕)っ

Nov-30-2019 15-39-44

### CODE REVIEW

**Comment by DeltaNedas** [comment]
stop

**Comment by Dexapnow** [comment]
It's really good idea, but core shouldn't rotate.

**Comment by Quezler** [comment]
@Dexapnow well my logic was that anything in the game faces the direction it flies in, it is in fact less work to have it not rotate at all, it would make the animation helluvalot smoother though 👍

**Comment by Violet-Scarelli** [comment]
Shades of the Terrans. To top this off, all ya need to do is add different core behavior for each team color. Blue would do this. Red would have "creep" that transfers items and power. Green would have item/power pylons. Bwahahahaha!

**Comment by Quezler** [comment]
latest

**Comment by Violet-Scarelli** [comment]
Honestly the cutest depiction of a Zergling I have ever seen. Starcrafts is the best.

**Comment by Arkanic** [comment]
why does this give me the same ironic feeling as hitchhiker's guide to the galaxy

**Comment by Arkanic** [comment]
may i also ask why that core's shading is inverted

**Comment by Quezler** [comment]
Ah, that's because textures are sprited facing the left and thus the rotation needs to be `+90`'d, didn't notice it, thx for pointing out out

**Comment by sk7725** [comment]
This should return for 6.0

**Comment by Anuken** [comment]
No.

**Comment by Meltdown-Altair** [comment]
it's honestly *not* that bad of a choice for cores to be movable , but cant you just , set them to be pickable by paload units?
cores moving would cause all kinds of lag & stuff

**Comment by USMP-lancer** [comment]
> it's honestly _not_ that bad of a choice for cores to be movable , but cant you just , set them to be pickable by payload units?
> cores moving would cause all kinds of lag & stuff

because of how gameover works, this would cause easy gameover on single core maps

**Pull request closed without merging**
