### PR TITLE
Domain name change

### PR DESCRIPTION
**Pull request by EasyPlaySu**

### CODE REVIEW

**Comment by Quezler** [comment]
duplicate of #5074

**Comment by USMP-Mandarin** [comment]
поменяйте домен на "DungeonMaster'sGayParty.cum"

**Review by osp54 — CHANGES_REQUESTED** [review]
Bruh

**Comment by Darkness6030** [comment]
Oh no

**Comment by Darkness6030** [comment]
EasyPlay.sus

**Comment by osp54** [comment]
Changing your domain will not change the opinion of the community about you.

**Comment by Ademun** [comment]
> EasyPlay.sus

.suck*

**Comment by RoomServers** [comment]
меняйте на MasterGayParty

**Comment by osp54** [comment]
Anuken, think!

**Pull request closed without merging**
