### PR TITLE
Don't attempt to remove `itemCapacity` if there never was `itemCapacity` in the first place.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Might be related to [this](https://github.com/MEEPofFaith/prog-mats-java/issues/16).

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by buthed010203** [comment]
~~why does this even throw an exception in the first place smh~~

**Comment by Anuken** [comment]
Probably easier to remove the exception instead.

**Comment by buthed010203** [comment]
Agreed, logging is probably a better option

**Comment by Anuken** [comment]
Or just ignore it, I don't think anyone really cares. It never caught any real problems.

**Comment by buthed010203** [comment]
Sure, you could do that but I think at least keeping logging might make it easier to debug stuff for modders? Especially considering that up until now it would just crash lol

**Comment by Anuken** [comment]
> might make it easier to debug stuff for modders?

I don't really think removing a non-existent stat is something that modders need to care about in the first place.

**Comment by Anuken** [comment]
Fixed in private branch by removing the check.

**Pull request closed without merging**
