### PR TITLE
[Following] Update bundle_ko.properties

### PR DESCRIPTION
**Pull request by Kieaer**
### This PR follows the latest commit!
If you don't accpet this PR, it will continue to be updated.

Success 691 items, Total 1217 items

### CODE REVIEW

**Comment by Kieaer** [comment]
1093 / 1217

**Comment by zethnest** [comment]
Why do you change from `[:space:]=[:space:]` to `=`. Does it provide complications somewhere else?

**Comment by Kieaer** [comment]
@zethnest Intellij IDEA Resource bundle auto change

**Comment by Anuken** [comment]
Bundles won't be getting additions for some time, so I'll merge this.

**Pull request merged**
