### PR TITLE
Filipino (Pilipinas) Language for Mindustry

### PR DESCRIPTION
**Pull request by Raisen1920**
Filipino Translation
-------------------------------------------------------------------------------------------
 _Calling all attention of Filipino Mindustry players! Magandang araw or nice day! The Filipino translation is getting complete with the help of few people, it is finally getting complete! However, I am still calling for help for extra languages leftover. Dont worry, though, translation that I need is not many, not small, but is for you to decide!_

 _Within 5 days, if anyone who could translate the file below will also get their names onto the contribution list. If none could translate then I have no choice but to pass my own translated version instead._

> I am at Discord - rAiSen192O#3832 - DM me if needed. 

------------------------------------------------------------------------------------------------
### Bundle Properties:
bit.ly/mindustryFil
 ^ `Other Contributors: @MageQanny`

### CODE REVIEW

**Comment by Raisen1920** [comment]
Notice that since its unfinished, I will still try to continue working on this language as possible! Thanks 👍

**Comment by Prosta4okua** [comment]
https://discord.gg/mindustry - official server mindustry

**Comment by itcannotbe** [comment]
Should it be bundle_tl.properties or bundle_fil.properties?

**Comment by Raisen1920** [comment]
> Should it be bundle_tl.properties or bundle_fil.properties?

 Its TL for tagalog and FIL for Pilipinas..

**Comment by Luxray5474** [comment]
I speak Tagalog, though not 100% fluent as school is English, and I would be happy to contribute! Your discord tag does not work, though.

**Comment by Raisen1920** [comment]
Please contact me on Discord. Thanks for your time here!

**Comment by Raisen1920** [comment]
Updated translation! Please check in for more details

**Comment by Raisen1920** [comment]
Translation is now complete. Please translate the updated file above!

> **"No one is useless in this world who lightens the burdens of another."**

**Pull request closed without merging**
