### PR TITLE
Universium Server

### PR DESCRIPTION
**Pull request by RebornTrack970**
Added the server of Universium.
Owner: shminkie#1485

### CODE REVIEW

**Comment by RebornTrack970** [comment]
Their dc:
https://discord.gg/GjSzmmdcd5

**Comment by Anuken** [comment]
> Their dc:
> Added the server of Universium.
> Owner: shminkie#1485

This should be added to the server desc or connection message somewhere. Currently, there's no information on who hosts the server.

**Comment by DeltaNedas** [comment]
rtomega why are you a proxy for every server owner lately
is making a github acc that hard, you can use cock.li

**Comment by RebornTrack970** [comment]
> rtomega why are you a proxy for every server owner lately
> is making a github acc that hard, you can use cock.li

I dont know...

**Comment by Anuken** [comment]
The information I asked for doesn't seem to have been added, and the server is down now.

**Pull request closed without merging**
