### PR TITLE
Team colors for more blocks

### PR DESCRIPTION
**Pull request by Voz-Duh**
This pull was made with the hope of improving Mindustry, I changed a lot and I want the creator to accept it because I tried very hard and in some places I chooser colors for sprites

new-team-colors-1
new-team-colors-2

> Deleted all powers moment

### CODE REVIEW

**Comment by Zenith-LY** [comment]
Basically, every (or most) block that has a black or yellow color theme should have their team's respective color.

**Comment by Voz-Duh** [comment]
Yes, in the local I changed this 6 times

**Comment by Voz-Duh** [comment]
> Basically, every (or most) block that has a black or yellow color theme should have their team's respective color.

Yes

**Comment by Zenith-LY** [comment]
i updated my comment

**Comment by Voz-Duh** [comment]
Oops
*Shocked*

**Comment by Voz-Duh** [comment]
Hm...
If Anuke don't like my large solar panel Anuke can say me delete solar panel team colors

**Comment by Voz-Duh** [comment]
@Zenith-LY thx

**Comment by Anuken** [comment]
Only vaults and containers should be team colored here. The power blocks are yellow because they're power related, not because of team. Their palette is different from that of cores.

**Comment by Voz-Duh** [comment]
Ok

**Comment by Voz-Duh** [comment]
I close this for cleaner changes

**Pull request closed without merging**
