### PR TITLE
Desktop: Boost toggle setting

### PR DESCRIPTION
**Pull request by joshuaptfan**
This PR resolves [suggestion #2127](https://github.com/Anuken/Mindustry-Suggestions/issues/2127).

It adds a game setting (default: off) to change the desktop boost key from a hold to a toggle, to lessen strain on players' pinkie fingers.

Mechanically, boost behavior is unchanged; the player unit will continue to only boost while moving, and will remain boosted if boost is turned off while the player unit is over an obstruction.

## Needs localization
* "Boost Toggle" game setting

### CODE REVIEW

**Comment by Quezler** [comment]
boost while capslock is on 😄

**Comment by joshuaptfan** [comment]
Players are free to modify their keybinds as such. However, the boost key will only toggle boost while you are controlling a boostable unit, so Caps Lock may get out of sync with the state of boost.

**Review by Bohaska — APPROVED** [review]

**Comment by sk7725** [comment]
Should be left as a control option setting, I myself want the boost to be held and not toggle, and I know that some others would too.

**Comment by joshuaptfan** [comment]
I have been fishing for specific situations when boost hold is better, and I'm sure this PR would be more palatable to Anuke if it were optional. Can you explain yours?

**Comment by sk7725** [comment]
> I have been fishing for **specific situations** where boost hold is better, and I'm sure this PR would be more palatable to Anuke if it were optional. However, I feel game settings are getting a bit bloated, and an option isn't worth adding if one of the choices is worse in every way.
> 
> Can you explain yours? "I want" is not enough; _why_ do you want?

Because 99% of the time, you *don't* want to be boosting; boosting makes the mech unable to react and use weapons. Most of the time, if you are boosting to jump over solid blocks, you dont need to hold it down anyways, so it isnt too much of a strain on the pinky (wait, you press shift with your pinky?)

**Comment by sk7725** [comment]
In PvP/PvE/PvT situations, you need to react quickly, and forgetting to press shift again, or failing to do so quickly, will cost you an unit. Not to mention that the increased urgent presses will actually stress your pinky more, thus negating the pros of this change, if any.

**Comment by sk7725** [comment]
uh, hello? Why are you not addressing my points at all? I addressed yours.

**Review by sk7725 — CHANGES_REQUESTED** [review]
for above reasons, this must be an option if implemented at all.

**Comment by joshuaptfan** [comment]
Let's refactor your points to make them impartial.

* Not boosting is the ideal state to be in, because you can't shoot while boosting.

Moving while boosting is significantly faster than not boosting, so when traveling long distances in boostable units, you will be holding down the boost key for a long time. This is where pinkie strain comes into play.

* Forgetting to toggle off boost can be dangerous.

Any movement while boost is toggled on will cause your unit to visibly rise. It's practically impossible to forget that boost is toggled on.

Thus, considering the hypothetical situation where you are commanding a group of novas in an attack map, against a mix of anti-air and anti-ground defenses, and accidentally boosting within range of anti-air can cause your units to be destroyed: Even with boost as a toggle, it would be impossible to accidentally boost without you manually pressing the boost key. It is impossible to "leave it toggled on by accident" because you can't move without your movement reflecting your current boost state.

**Comment by sk7725** [comment]
+ Moving while boosting is significantly faster than not boosting

Nope! Units have a *different*, not *faster* speed while boosting. Modded units, as well as (maybe) future planned units may have boosting speed slower than normal speed.

+ Any movement while boost is toggled on will cause your unit to visibly rise. It's practically impossible to forget that boost is toggled

You are vastly overestimating the capacity of the human brain, or underestimating its stupidity. Static (the engine does grow and shrink but only too subtley) visory cues are commonly disregarded in the human brain, and its a gleden rule that for one "A cannot be forgotten" presumption, there are 10 instances of A forgotten. (don't trust me? go to any irl-topic website/media/subreddit etc.)

**Comment by joshuaptfan** [comment]
I'm not persuaded by your memory arguments, as they are getting rather contrived. However, I'm adding the setting anyway, because Anuke would otherwise be uncomfortable with a PR that irreversibly alters the current behavior of controls.

**Review by Bohaska — APPROVED** [review]
hmm looks good ok i approve this

**Comment by Anuken** [comment]
This is a year late, but with the Erekir update, boosting becomes even less relevant, and regardless of usefulness, I just don't want to maintain another keybind or add another setting for something that very few people will use.

**Comment by joshuaptfan** [comment]
Ok, as long as it's not an issue.

**Pull request closed without merging**
