### PR TITLE
Server crashes when a RuntimeException is unhandled in a server-side command

### PR DESCRIPTION
**Pull request by Phinner**
If a RuntimeException is thrown in a server-side command, the whole server crashes.
It doesn't occur in a client-side one.

When using this code for example:
```java
handler.register("crash", "crashes the server", (args, player) -> {
        throw new ArcRuntimeException("Oh no !");
});
```

Client-side:
```
[07-06-2021 13:45:03] [I] <[cyan]{MXP}[gray]Phinner: /crash>
java.lang.RuntimeException: Failed to read remote method 'sendChatMessage'!
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:85)
        at mindustry.core.NetServer.lambda$new$7(NetServer.java:261)
        at mindustry.net.Net.handleServerReceived(Net.java:277)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:118)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: arc.util.ArcRuntimeException: Oh no !
        at fr.xpdustry.distributor.DistributorPlugin.lambda$registerClientCommands$3(DistributorPlugin.java:51)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:85)
        at mindustry.core.NetClient.sendChatMessage(NetClient.java:208)
        at mindustry.gen.RemoteReadServer.readPacket(RemoteReadServer.java:83)
        ... 6 more
```
And continues to run normally...

Server-side:
```
[07-06-2021 13:40:35] [E] arc.util.ArcRuntimeException: Oh no !
	at fr.xpdustry.distributor.DistributorPlugin.lambda$registerServerCommands$0(DistributorPlugin.java:28)
	at arc.util.CommandHandler.handleMessage(CommandHandler.java:85)
	at arc.util.CommandHandler.handleMessage(CommandHandler.java:29)
	at mindustry.server.ServerControl.handleCommandString(ServerControl.java:939)
	at mindustry.server.ServerControl.lambda$readCommands$65(ServerControl.java:934)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
```
Then crashes...

Patch:
```
crash
[07-06-2021 13:41:40] [E] An exception occurred while running the command: arc.util.ArcRuntimeException: Oh no !
        at fr.xpdustry.distributor.DistributorPlugin.lambda$registerServerCommands$0(DistributorPlugin.java:28)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:85)
        at arc.util.CommandHandler.handleMessage(CommandHandler.java:29)
        at mindustry.server.ServerControl.handleCommandString(ServerControl.java:970)
        at mindustry.server.ServerControl.lambda$readCommands$64(ServerControl.java:964)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
```
And continues to run normally...

### CODE REVIEW

**Comment by Phinner** [comment]
oops, didn't finish the text

**Comment by Kieaer** [comment]
Not a bug. It's correct code working

**Comment by Anuken** [comment]
> If a RuntimeException is thrown in a server-side command, the whole server crashes.

This is as it should be. There's no reason to suppress crashes from flawed commands that are only available to the host.

Client-side commands don't crash because they are *sent in as packets from remote clients*. Ideally, they shouldn't have their exceptions handled either, but all received packets have an additional "safety net" to prevent server crashes in case of invalid data.

**Comment by Phinner** [comment]
ok

**Pull request closed without merging**
