### PR TITLE
Fix turret shooting priority when there are multiple teams

### PR DESCRIPTION
**Pull request by notrealn**
before:
image

after:
image

### CODE REVIEW

**Comment by LeoSko** [comment]
Wouldn't it make more sense to target team which is active (aka has core)?

**Comment by notrealn** [comment]
im *pretty sure* im already doing that
image
this just loops over all active teams, right?

**Comment by LeoSko** [comment]
@notrealn, no - activeTeams here contains all teams which have some *tile*, not some *core*.

**Comment by notrealn** [comment]
this is just the logic thats already there
haha i have no idea how to do that

is there some sort of team.hascore()

**Comment by notrealn** [comment]
ok i think it shouldnt matter whether or not a team has a core.
would you rather shoot a random copper wall or a neutral ripple shooting at you?

**Comment by Anuken** [comment]
If you're going to check all teams, might as well check the distance too. With the current implementation, a turret further away that happens to have a lower team index will be targeted first.

**Comment by notrealn** [comment]
image
woohoo it works (i think)

**Pull request merged**
