### PR TITLE
Update bundle_zh_CN.properties for scathe

### PR DESCRIPTION
**Pull request by xem8k5**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by xem8k5** [comment]
okay

**Review by Cong0707 — CHANGES_REQUESTED** [review]
unit.stell.name = 围护
unit.locus.name = 循迹
unit.precept.name = 准绳
unit.vanquish.name = 征服
unit.conquer.name = 领主
unit.merui.name = 天守
unit.cleroi.name = 天赐
unit.anthicus.name = 天灾
unit.tecta.name = 天理
unit.collaris.name = 天帝
unit.elude.name = 挣脱
unit.avert.name = 遮蔽
unit.obviate.name = 消散
unit.quell.name = 遏止
unit.disrupt.name = 悲怆
unit.evoke.name = 苏醒
unit.incite.name = 策动
unit.emanate.name = 发散

**Comment by xem8k5** [comment]
got it!

**Review by Cry0flu1d — COMMENTED** [review]
sorry for my bad chinese :(

**Pull request merged**
