### PR TITLE
Allow for dynamic laser absorption and insulation

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Creates `absorbLasers()` in `BuildingComp`, so that scripts can make a block sometimes absorb lasers and sometimes don't.
Same with `isInsulated()`.

### CODE REVIEW

**Comment by Phinner** [comment]
Nice idea

**Comment by MEEPofFaith** [comment]
I am the random "this should be made dynamic" person.

**Comment by MEEPofFaith** [comment]
~~wait that worked?~~

**Comment by sk7725** [comment]
one issue: `boolean isInsulated` (for Lightning) and `canConduct` (for adjacent PowerGraphs) may be confusing.

**Comment by MEEPofFaith** [comment]
no idea what else to call them you can handle changing them

**Pull request merged**
