### PR TITLE
Some traduction about the new components add

### PR DESCRIPTION
**Pull request by Mihawka**

### CODE REVIEW

**Comment by itskatt** [comment]
I am sorry, but there's is already a pull request about updating the game's French translation (see #594). If you want to help me, please [
submit a pull request on my fork instead ([link](https://github.com/itskatt/Mindustry/blob/french-translation/core/assets/bundles/bundle_fr.properties))

**Comment by JustYanns** [comment]
You should close this pr 😉

**Comment by Mihawka** [comment]
Yes x)

**Comment by Mihawka** [comment]
Yes x)

**Pull request closed without merging**
