### PR TITLE
Add game server's

### PR DESCRIPTION
**Pull request by MINDUSTRYRU**
mindustry.ru - Survival
mindustry.ru:9991 - PvP
mindustry.ru:9992 - Attack
mindustry.ru:9993 - King of the hill(Hex)
mindustry.ru:9994 - HardEarth(survival)

### CODE REVIEW

**Comment by Summet-V** [comment]
Use hub.

**Comment by Volas171** [comment]
you guys have the hub online , why other servers.....

**Comment by DeltaNedas** [comment]
hub

**Comment by TheSlaylord** [comment]
Agreed with all comments above.

**Pull request closed without merging**
