### PR TITLE
remove stray newline

### PR DESCRIPTION
**Pull request by buthed010203**

### CODE REVIEW

**Comment by Voz-Duh** [comment]
@buthed010203 if you can't make good PR don't doing PR spam

**Review by Quezler — APPROVED** [review]

**Comment by buthed010203** [comment]
> @buthed010203 if you can't make good PR don't doing PR spam

???? What is that supposed to mean, they are two different PRs that fix two different problems it's not "pr spam"

**Comment by Quezler** [comment]
anuke would prefer if you combine cleanups in the same pr if one is still unmerged ^

**Comment by buthed010203** [comment]
> anuke would prefer if you combine cleanups in the same pr if one is still unmerged ^

Fair enough, will do next time

**Pull request merged**
