### PR TITLE
Team Colors For Effects

### PR DESCRIPTION
**Pull request by Voz-Duh**
After 3 days of work did this, I changed almost all the effects, I also changed the color of the mass conveyors as a bonus :)
screenshoot-1
screenshoot-2
screenshoot-5
screenshoot-6
screenshoot-3
screenshoot-4

### CODE REVIEW

**Comment by Quezler** [comment]
the colored mass conveyors look neat 👍

**Comment by Voz-Duh** [comment]
> the colored mass conveyors look neat 👍

**Comment by Xusk947** [comment]
maybe make for storages?

**Comment by Quezler** [comment]
pull requests have a higher chance of being accepted if they add just one feature each ^

**Comment by ThePythonGuy3** [comment]
I dislike the unit control fx color. It just doesnt feel right. But the conveyors and blocks placement looks great imo.

**Comment by sk7725** [comment]
~~Maybe just set Pal.accent to the team color~~

**Comment by ILiekMelons** [comment]
Screenshot from 2020-08-31 01-12-43
ooh pretty

**Comment by ILiekMelons** [comment]
Screenshot from 2020-08-31 01-17-09
I would like the colors to fade out into grey instead of this, but I'm just nitpicking.

**Comment by Esnardo** [comment]
I love the recent trend of everything getting team colored in 6.0. Hopefully next you do storage, unloaders, command centers, etc.

**Comment by Esnardo** [comment]
Catch me nodding the game so I can play as red or blue in campaigns. These sprites look beautiful

**Comment by SupremeTurtle** [comment]
Remove that single stripe that represents the team color so it looks better. Since the arrows are colored, I think it should be removed.

**Comment by Voz-Duh** [comment]
> I love the recent trend of everything getting team colored in 6.0. Hopefully next you do storage, unloaders, command centers, etc.

In next I create: Storage, Power Nodes and Unit Factory.

**Comment by Voz-Duh** [comment]
> Remove that single stripe that represents the team color so it looks better. Since the arrows are colored, I think it should be removed.

i don't can delete it, i don't know in what moment in the code Anuke created it

**Comment by Voz-Duh** [comment]
> I dislike the unit control fx color. It just doesnt feel right. But the conveyors and blocks placement looks great imo.

Me too don't like it, but I can make it a little more transparent

**Comment by Ubuntu8406** [comment]
> > I dislike the unit control fx color. It just doesnt feel right. But the conveyors and blocks placement looks great imo.
> 
> Me too don't like it, but I can make it a little more transparent

yes, do it.

**Comment by Voz-Duh** [comment]
> > > I dislike the unit control fx color. It just doesnt feel right. But the conveyors and blocks placement looks great imo.
> > 
> > 
> > Me too don't like it, but I can make it a little more transparent
> 
> yes, do it.

Ok

**Review by RandomTNT — APPROVED** [review]
Well, i can think, it will fit into team colour update (or its name)

**Comment by Voz-Duh** [comment]
> Well, i can think, it will fit into team colour update (or its name)

Thank
But I think that it would be necessary for it to be confirmed Anuken XD

**Comment by ThePythonGuy3** [comment]
Why are you closing all of your PRs

**Comment by Ubuntu8406** [comment]
oh yes

**Comment by Voz-Duh** [comment]
> Why are you closing all of your PRs

This happened during the time that I had a creative crisis + stress + eternal name-calling

**Comment by Voz-Duh** [comment]
In this moment i create new PR, new version has very better

**Pull request closed without merging**
