### PR TITLE
New overdrive visuals for colorblind users

### PR DESCRIPTION
**Pull request by sk7725**
#4804, my take.
overBrrr

### CODE REVIEW

**Comment by Quezler** [comment]
ingame preview video/gif?

**Comment by sk7725** [comment]
> ingame preview video/gif?

Sorry, I'm not home right now...will post preview when I get home and meet my beloved computer.

**Comment by sk7725** [comment]
> ingame preview video/gif?

done

**Review by RebornTrack970 — APPROVED** [review]

**Comment by Jammo2000** [comment]
The animation is too big, it shouldn't extend over the boundaries of the block.

**Comment by sk7725** [comment]
> The animation is too big, it shouldn't extend over the boundaries of the block.

yup! working on that rn

**Pull request merged**
