### PR TITLE
(attempt 2 because merge conflict) add descriptions and stuff for Erekir content

### PR DESCRIPTION
**Pull request by yesC48**
…and this time, no more procrastination.
no seriously

### CODE REVIEW

**Comment by SoMall-dumpling** [comment]
wow

**Comment by hello-hello-there** [comment]
Some minor fixes:
Screen Shot 2022-08-03 at 5 20 46 PM

**Comment by Catchears** [comment]
There was a PR on https://github.com/yesC48/Mindustry fixing most of these issues, but it targeted master instead of patch-3. I was going to open a PR simply merging the two, but it seems that the new entries are both in different orders and different lines (and partially incomplete / reordered).

**Comment by yesC48** [comment]
ps: edit made out of pure laziness, yesC48/ErekirBundles for context

**Comment by Anuken** [comment]
This has been "more or less" merged; I used it as a base and rewrote many of the entries.

**Comment by yesC48** [comment]
oh ok

**Pull request closed without merging**
