### PR TITLE
Added gameData folder detection.

### PR DESCRIPTION
**Pull request by clivinghouse**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable (Windows 10/Ubuntu Desktop20.04).

## Scenario 

I just started playing this game, I absolutely love it. However, I am a very busy college student who goes from computer to computer. I wanted to save my game data without exporting and importing it. I carry the game around on a USB. in my Pull request I added the ability for the game to scan for a folder called `gameData` and use that instead of the default %appdata% in windows. I also did not want to keep settings the env variable. I have only been coding in java off and on as the semesters have required me, so my code may be a bit noobish. I hope this is a useful addition or at least the gateway to future development on this functionality.

### CODE REVIEW

**Comment by Anuken** [comment]
Why not use the env variable?

**Comment by clivinghouse** [comment]
Hello @Anuken, for those who decide to carry the game around on a usb stick to go computer to computer. I feel that it is easier if the game searches for a folder instead. That way, in this very specific use case, you wouldn't have to keep setting the env variable on each computer every time you switch computers.

**Comment by Anuken** [comment]
Why not just import the data then...?

**Comment by clivinghouse** [comment]
To import the data and export it every time? I believe that this extra added functionality can increase the games portability aspect. I also believe that this can make it easier for the non technical users to save the data.

**Comment by Anuken** [comment]
I don't understand how this increases portability when you can simply copy paste into the game data folder or import/export it from the game.

**Comment by clivinghouse** [comment]
That still would mean you would have to do it every time. Adding the folder is a one and done deal. I guess increasing the portability is the wrong way if putting it. It decreases the hassle of carrying the game around on a USB stick.

**Comment by SachaTending** [comment]
bruh, just use scripts to set env and start mindustry

example for windows:


```
::Setting var
set MINDUSTRY_DATA_DIR=your data dir

::Start mindustry
java -jar mindustry.jar
```

**Comment by clivinghouse** [comment]
@SachaTending, thank you for the recommendation! Thank you @Anuken for the time.

**Pull request closed without merging**
