### PR TITLE
bundle updates for new functionality

### PR DESCRIPTION
**Pull request by Remint32**
any changes are welcome

### CODE REVIEW

**Comment by Remint32** [comment]
If I forgot something, tell me about it

**Comment by YellOw139** [comment]
Last I checked, unit ammo isn't enabled on campaign by default. That proves that it's probably still experimental and not finished. Are you sure you want to to confuse new players by including info about something not enabled by default (aka probably enabled in too few games for some players to notice unit ammo recharging and to know what the description is talking about)?

**Review by XEN0PHIL — CHANGES_REQUESTED** [review]
the со множественным числом не используется
charges energy weapons

**Comment by Remint32** [comment]
@YellOw139 I suggest that you remove from the description of the thorium reactor the mention that it explodes, because this can be disabled in the configs. Stupid remark. The description should reflect the full functionality.

**Review by summetdev — APPROVED** [review]

**Comment by Catchears** [comment]
I wouldn't bother changing the descriptions because they are all going to be rewritten anyway.

**Comment by Anuken** [comment]
I agree with the "surface" change, but the rest isn't necessary, I think.
> Charges energy weapons of units.

This will confuse people who aren't playing with ammo on. I'll hold back on adding it.

**Comment by Remint32** [comment]
@Anuken 

изображение

изображение

изображение

**Comment by Anuken** [comment]
I'll rename that category to "Function".

**Pull request closed without merging**
