### PR TITLE
Attempt to rewrite Mindustry in Rust

### PR DESCRIPTION
**Pull request by code-explorer786**
...while learning Rust on the fly
_This PR is unfinished. [3664](https://github.com/Anuken/Mindustry-Suggestions/issues/3664)_
***Unlike [that PR](https://github.com/Anuken/Mindustry/pull/7062), this PR is actually serious.***

~~If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:~~
no, i am rewriting to rust

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
> this PR is actually serious

no, no it is not.

**Comment by code-explorer786** [comment]
funny fail

**Comment by code-explorer786** [comment]
ok so i'll leave this as an activity instead (learning rust by rewriting game)

**Comment by Anuken** [comment]
If you *actually* want to learn rust or rewrite something, you are approaching it from the completely wrong direction - the code you have here makes absolutely no sense, you shouldn't be using global variables, or structs, or separate files, or `IntMap` (rust has proper generic), or-

You can't just "port" Java code to Rust, the are fundamentally different languages and any real rewrite should be done from the ground up with no shared structure.

**Pull request closed without merging**
