### PR TITLE
Consistent effect time with liquid-only generators

### PR DESCRIPTION
**Pull request by MEEPofFaith**
I have been enslaved once again.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by BlueWolf3682** [comment]
you missed a closing )

**Comment by summetdev** [comment]
there's no need for second `(`

**Comment by MEEPofFaith** [comment]
aaaaaa

**Comment by Anuken** [comment]
Test this first. I don't see any code in liquid-only generators inc/decrementing `generateTime`.

**Comment by MEEPofFaith** [comment]
nice

**Pull request closed without merging**
