### PR TITLE
Slag Incinerator Rework: No Slag Consumption Rate

### PR DESCRIPTION
**Pull request by SomeonesShade**
Implements https://github.com/Anuken/Mindustry-Suggestions/issues/5210
Specifically A1, "Input Slag Once/No Slag Consumption Rate"

Details:
Set Slag Incinerator Consumption rate to: ```0f```
Removed ```/sec``` in Liquid Display if amount is ```0f```

Slag Incinerator in Action:
Screenshot 2024-09-10 131751
Video:

https://github.com/user-attachments/assets/a3ab3925-ae33-4d9b-b031-5a944734155e

Liquid Display Fix:
image
Before:
Screenshot 2024-09-10 130848

Seems to be well supported by the discord: https://discord.com/channels/391020510269669376/766777428097105920/127977327314351317
and has already been reviewed at #balancing

Suggestion Alternative B: "Slag Producing Slag Incinerator" might be chosen instead if implementation is possible, if I'm in a position to do it myself, although priority is getting something working/non-controversial first, then follow up if it has support.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Have you, uh, run this by the balancing channel in the discord?

**Comment by SomeonesShade** [comment]
wait I can probably remove the /sec slag and call it a day

**Comment by JasonP01** [comment]
> how did the check fail for a one line change….

Cause its a workflow issue, anuke needs to update dependacies

**Comment by SomeonesShade** [comment]
Fixed the liquid Display thing, seems complete now

**Comment by SomeonesShade** [comment]
my first merge conflict and it somehow caused the pr to close ...
yay

**Comment by JasonP01** [comment]
Omg!?

**Pull request merged**
