### PR TITLE
[votekick] neutral ballot 

### PR DESCRIPTION
**Pull request by Quezler**
just something i had in my own custom server jar for a while in case someone votes against 🤔

### CODE REVIEW

**Comment by mRebornM** [comment]
Can i ask why?

**Comment by Quezler** [comment]
> Can i ask why?

`foo has voted to kick bar` makes sense if you vote yes,
but when you vote no, the `kick` word still points to kicking said person,
so `kicking` just means the player has voted either yes or no.

**Comment by mRebornM** [comment]
So its normally the same message for both yes and no, you fixed it?

**Comment by Quezler** [comment]
yes, now the same message applies to both positive and negative votes

**Pull request merged**
