### PR TITLE
Unhorrible Turret Recoil Design

### PR DESCRIPTION
**Pull request by MEEPofFaith**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
Changed code does not break turret animations.

https://user-images.githubusercontent.com/54301439/190078603-9291b0c0-af4f-4097-af9d-700c83b94b6f.mp4

**Comment by Anuken** [comment]
How is this less horrible?

**Comment by stacktrace-error** [comment]
meep, slightly changing the order these are in doesn't change how bad it is

**Comment by Anuken** [comment]
Arguably make it static makes it *significantly more* horrible, since it 1) breaks turrets from existing mods, 2) leads to uglier code and 3) gives more opportunities for turrets using the wrong recoil from a previous call.

**Pull request closed without merging**
