### PR TITLE
Bullets shouldn't home on what they've already collided with.

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Why home in on something when you can't damage them anyways.

### CODE REVIEW

**Comment by TheRealIvyX** [comment]
this should only apply to non-piercing homing bullets imo since piercing bullets can hit the same thing several times

**Comment by MEEPofFaith** [comment]
They can, but they cannot damage the same thing twice.

**Comment by MEEPofFaith** [comment]
`collision` will not be called on the same target twice

**Comment by bvcbvc** [comment]
yea, the only reason this was done was because v5 scorch

**Pull request closed without merging**
