### PR TITLE
Update Block.java

### PR DESCRIPTION
**Pull request by Raotor123**
Changed for loop in 151 and 181. Now checks for the length of the tiles array.

### CODE REVIEW

**Comment by Raotor123** [comment]
Error was not in this file.

**Comment by Kappandrew** [comment]
4 years later, i thank you so damn much as i was looking for a mindy build before 2018, and i finally found one, thanks to you :D

**Comment by Raotor123** [comment]
> 4 years later, i thank you so damn much as i was looking for a mindy build before 2018, and i finally found one, thanks to you :D

Glad I could help :p

**Comment by Kappandrew** [comment]
> > 4 years later, i thank you so damn much as i was looking for a mindy build before 2018, and i finally found one, thanks to you :D
> 
> Glad I could help :p

Lol, ive found https://github.com/kylelt/Mindustry now, witch is a build from nov. 9th, but you were still instrumental in helping. Thanks for not deleting your fork for 3.5 years

**Comment by Anuken** [comment]
You can find every single Mindustry version ever released by looking through this repo's commit history - a fork isn't necessary.

**Comment by Kappandrew** [comment]
> You can find every single Mindustry version ever released by looking through this repo's commit history - a fork isn't necessary.

Yeah buddy uh 121 releases < 127.2

**Comment by Kappandrew** [comment]
oh....... nvm
i forgot commits and releases were different, release 33 is useless now
also thanks for responding in the first place and letting me bug you @Anuken . ima go look for early compiled builds now becuase the old source code instructions are broken

**Pull request closed without merging**
