### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by rodrigolitzius**
H

### CODE REVIEW

**Comment by Bohaska** [comment]
Why do you add typos...

**Comment by firstcreator48** [comment]
how

**Comment by rodrigolitzius** [comment]
> Why do you add typos...

some problem? I only fixed some Portuguese errors. nothing wrong.

**Comment by rodrigolitzius** [comment]
> how

How what?

**Comment by Anuken** [comment]
Google Translate seems to think that this is correct.

**Pull request merged**
