### PR TITLE
Update bundle_it.properties

### PR DESCRIPTION
**Pull request by DeltaRays**

### CODE REVIEW

**Comment by Tazshelby2016** [comment]
Could you please add a description to give people an idea of what you did?

**Comment by Anuken** [comment]
Google translate gives me "elevated conveyor belt" being changed to "ramp for objects". I'm not sure if this is a good change, could you explain the reasoning?

**Comment by PotassioK** [comment]
rampa per oggetti non ha senso

**Comment by Tazshelby2016** [comment]
> Google translate gives me "elevated conveyor belt" being changed to "ramp for objects". I'm not sure if this is a good change, could you explain the reasoning?

 Google Translate is only good for pronunciation. You need to go dictionary diving for more correct translations.

**Comment by Anuken** [comment]
> Google Translate is only good for pronunciation. You need to go dictionary diving for more correct translations.

I am aware of this, which is why I asked.

**Pull request closed without merging**
