### PR TITLE
Update servers_v6.json

### PR DESCRIPTION
**Pull request by Somka000**
Move .pl to 6.0 server list

### CODE REVIEW

**Review by Quezler — CHANGES_REQUESTED** [review]
maybe remove them from https://github.com/Anuken/Mindustry/blob/master/servers_be.json in the same pull request?

**Comment by Somka000** [comment]
I wanted to do that, but I don't know how add second commit to one PR.

**Comment by Quezler** [comment]
by going to the branch of this pull request and editing the file, then it gets added automatically: 
https://github.com/Somka000/Mindustry/tree/patch-5

**Comment by Somka000** [comment]
Unfortunately, I made second PR before :/

**Comment by Quezler** [comment]
well due to impending merge conflicts in the v6 list this might even be the better option, so i suggest to keep both 🤔

**Pull request merged**
