### PR TITLE
More Dark UI in stats display

### PR DESCRIPTION
**Pull request by JniTrRny**
This is only the beginning.

The most painful Pull Request I've ever made.
With a few hundreds debugging and headaches later, I've finished it.

Replace boring and uninformative old UI with the new, still uninformative, DARK UI.

image

Oh wow this looks so cool, I wonder what's the code behind it... (don't)

image

Hey this looks cool too huh, but it's kinda look crowded... (if only there is no mobile platform to consider)

image

Damn these looks nice, but where's the item rate?!?! (I couldn't figure out how to really convert mine speed to item/sec, so I, well, just removed it, simple solution)

image

OMG 🤯 😱 👍 THEY GOT THE PHASE BOOST (The force projector's coolant speed boost is kinda misleading, maybe I should remove it... like the units mine tier)

image

OH MY LORD THIS IS THE BEST FEATURE 😱 (still in beta... really)

And onto the main feature of this Pull Request...

image

WHATTT, liquid unit got the PIPE now?!?!? (seriously, please suggest a better icon than pipe, I kinda... don't like it)

Okay maybe we should end this here before the Dark UI takes over this Pull Request.
Still, this is only the beginning, The Attack Of the Dark UI is coming soon... or maybe when I have the free time.

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [X] I have ensured that my code compiles, if applicable.
- [X] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by BlueWolf3682** [comment]
ok drill rate per ore hardness is actually really useful

**Comment by MEEPofFaith** [comment]
Maybe the `0.17/sec` should go under the "Phase Fabric" like with liquid rates

image

**Comment by MEEPofFaith** [comment]
Is this per tile or if all the drill's tiles have the ore?

image

**Comment by JniTrRny** [comment]
> Are these rates in items/sec/tile covered or item/sec if all tiles are covered?

item/sec in all tile, to match the old base drill speed stats

**Comment by Anuken** [comment]
> should go under the "Phase Fabric" like with liquid rates

(I did this after merging)

**Pull request merged**
