### PR TITLE
🗺 Locate existing mechpads

### PR DESCRIPTION
**Pull request by Quezler**
When playing on a server its pretty common for multiple mechpads to be scattered all over the place since players aren't aware where others might have placed theirs, if any at all 😵  

This change causes all mechpads on the map to be highlighted by (currently, subject to change*) its engine color as long as the build tab has that category selected, which should make it easier for other players (and yourself) to be aware of where they are 📌 
Oct-27-2019 21-20-48
(note that the low fps of the gif is due to filesize limitions, and not the constant checking of the entire grid 😗)

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
Checking the entire map like that is a horrible idea, it should just have a static list for mech pads where they get added when created and removed when destroyed.

**Comment by Quezler** [comment]
Any suggestion(s) as to where in the code to put said list? 😗

**Comment by Anuken** [comment]
Create a new `BlockFlag` (call it, say, `MechPad`), set that flag in the mech pad's constructor and call `indexer.getAllied(team, BlockFlag.mechPad)` to get a list of all pads in the map.

**Comment by Quezler** [comment]
Thx, I'll try it tomorrow 😇

**Comment by Anuken** [comment]
May need some graphical indicator changes later, but for now I don't have any issues with it. Thanks.

**Comment by Quezler** [comment]
True, one of the colors looks to much like the allied player one, and another barely looks blue, but at least they are squares 🎛️

**Pull request merged**
