### PR TITLE
Support for continuous laser weapons with more than 1 beam

### PR DESCRIPTION
**Pull request by MEEPofFaith**
`shots` and `inaccuracy`:

https://user-images.githubusercontent.com/54301439/110986710-dc1dcf80-8322-11eb-84c4-6f0616adcd2a.mp4

---

`burstSpacing`

https://user-images.githubusercontent.com/54301439/110986769-ed66dc00-8322-11eb-8b73-4b9d049d150a.mp4

### CODE REVIEW

**Comment by BlueThecno** [comment]
This seems crazy.



*I like It*

**Comment by sk7725** [comment]
I second that

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/111258573-7e1b1180-85da-11eb-9cc7-b82a6e4eac92.mp4

needs fixing, but I do not have time now.

**Comment by MEEPofFaith** [comment]
https://user-images.githubusercontent.com/54301439/111259175-a6efd680-85db-11eb-987d-d2cdaa08272e.mp4

and its fixed now

**Comment by liuxilu** [comment]
"more than one laser"

**Comment by Anuken** [comment]
This is a niche use case and will break any mods that extend/access these classes, so I can't merge this.

**Comment by MEEPofFaith** [comment]
~~amazing~~

**Comment by Anuken** [comment]
> does you looking at really old prs means you're merging soon

no, but the growing number of stagnant PRs is concerning

**Pull request closed without merging**
