### PR TITLE
Smelter flame size multiplier

### PR DESCRIPTION
**Pull request by MEEPofFaith**
https://github.com/Anuken/Mindustry-Suggestions/issues/2432
> 4. Ability to change the flame circle effect on GenericSmelters, or at least the size of the flame circles.

### CODE REVIEW

**Comment by Anuken** [comment]
s e e  o t h e r  c o m m e n t

**Comment by MEEPofFaith** [comment]
w h e r e

**Comment by BlueWolf3682** [comment]
~~i am laughing so hard right now lmfao~~

**Comment by MEEPofFaith** [comment]
~~p a i n~~

**Comment by sk7725** [comment]
> w h e r e

> already in 7.0

**Pull request closed without merging**
