### PR TITLE
tung cost for merui fac removed

### PR DESCRIPTION
**Pull request by Zerenta**
why is it even there
its overshadowed by everything else in tung tier 

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
https://discord.com/channels/391020510269669376/396416151032299521/973598654134886400

**Comment by Zerenta** [comment]
> https://discord.com/channels/391020510269669376/396416151032299521/973598654134886400

why should any of it cost tungsten in the first place
it just makes the unit barely ever get used because theres always an option thats 2 trillion times better the moment you get said unit

**Comment by Anuken** [comment]
Argue with people in `#balancing`, not me.

**Comment by YSMQTHLQYH** [comment]
Guess someone (me perhaps) is going to have to write a justification for this in the suggestions github
I just find it dumb that the t1 mech factory is more expensive than the t2 ones

**Pull request closed without merging**
