### PR TITLE
correction of spelling mistakes

### PR DESCRIPTION
**Pull request by Lrakotobe**

### CODE REVIEW

**Comment by darnuria** [comment]
Hi, just a little bump this was a first contributions of students of mine. If there is any problem please get in touch with @Lrakotobe or I.

Thanks a lot for the game and also your review time! :)
(Students from Paris 8 university in bachelor computer-science)

**Comment by darnuria** [comment]
@Lrakotobe maybe cherry-picking 10533b3c9b64ae683a047070d25b43744b64969f ontop of maser without the merge commit is needed and a little explanation of your work! ;)

**Comment by darnuria** [comment]
Afterthough or just removing aa7b83ce0cfb28453ac8445aaa5246cd76e681d1

**Comment by Lrakotobe** [comment]
@darnuria so I need to do an another pull request and delete this one? I don't know how to remove just one commit in a pull request :3

**Comment by Anuken** [comment]
There currently aren't any other open pull requests to this bundle, so this can be merged as-is, thanks.

**Pull request merged**
