### PR TITLE
switch to GFM markdown renderer for github pages

### PR DESCRIPTION
**Pull request by Arkanic**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

Table at the bottom of README.md does not render properly in github pages, as the markdown renderer (kramdown) has some weird behaviour around tables.
image

Config file switches the renderer to GFM, which renders the table properly
image
GFM is the renderer natively used on github (e.g. rendering the README on the repository site.)

### CODE REVIEW

**Comment by Anuken** [comment]
> Table at the bottom of README.md does not render properly in github pages

Seems kinda weird to view this on github pages.

**Comment by Arkanic** [comment]
> Seems kinda weird to view this on github pages.

@Anuken 
yet there is a github pages deployment for some reason?
https://anuken.github.io/Mindustry/

**Comment by Anuken** [comment]
I don't know how that came about; I've never needed a page for Mindustry. Maybe I accidentally turned it on while messing around in the settings, or mistook Mindustry for another repo while setting up pages? Either way, it's disabled now.

**Comment by Arkanic** [comment]
Cool, I just thought it was intended as some sort of mirror

**Pull request closed without merging**
