### PR TITLE
Make coreblocks have their team represented on sprite

### PR DESCRIPTION
**Pull request by ThePythonGuy3**
I made this on my custom build, and it turned out very well. As I can't upload files, I can't upload the sprites required, but look in my build's sprites: [block sprites](https://github.com/ThePythonGuy3/Mindblowstry/tree/master/core/assets-raw/sprites/blocks/storage)

If you don't like mine, you'll need: name (sharded team block), name-top (The part that changes depending on team) and name-base (The base of the core).

Here's how it turns out:
image

### CODE REVIEW

**Comment by Quezler** [comment]
they look great imo, ima just link this as well #805 ❤️

**Comment by Anuken** [comment]
While the other cores look... fine, I'm not a fan of having a special core top sprite for the sharded team. Having correctly shaded top sprites for everything (with a red/blue tint on darker colors) would be optimal, but that's currently very difficult to pull off, since the tint multiplies colors only.

This code doesn't compile. Test your PRs before submitting them, please.

**Comment by ThePythonGuy3** [comment]
I actually tested it. Unless you changed sth in the code after I made the PR, it should work, because that picture was taken on v6

**Comment by Anuken** [comment]
> that picture was taken on v6

Unless you tested it months ago, that's not possible. Tile entities have not had a `draw(Tile tile){` method for a long time now, and if you check the [Travis logs](https://travis-ci.org/github/Anuken/Mindustry/builds/698624820#L268), you can see that it didn't compile even when you submitted the request.

**Comment by ThePythonGuy3** [comment]
Then I was using a very old v6. Well, since Quezler made a better version, and compiles, I will close this one.

**Pull request closed without merging**
