### PR TITLE
type.speed -> speed()

### PR DESCRIPTION
**Pull request by DeltaNedas**
1. Have everything using it automatically account for commanding units
2. Modded units having variable speed is possible

### CODE REVIEW

**Comment by summetdev** [comment]
It doesn't compile.
```
/home/travis/build/Anuken/Mindustry/core/src/mindustry/entities/comp/UnitComp.java:72: error: cannot find symbol
        return isCommanding() ? minFormationSpeed * 0.98f : type.speed;
                                ^
  symbol:   variable minFormationSpeed
  location: class UnitComp
```

**Comment by DeltaNedas** [comment]
r

**Comment by DeltaNedas** [comment]
god i should sleep more that was a no brainer

**Comment by summetdev** [comment]
Finally.

**Comment by DeltaNedas** [comment]
forgot how anukes multiple inheritance thing worked lol

**Pull request merged**
