### PR TITLE
Allow for modded water extractors to use no power

### PR DESCRIPTION
**Pull request by Quezler**
[`discord w/@Slava0135`](https://discordapp.com/channels/391020510269669376/396416151032299521/644176447606620161)

### CODE REVIEW

**Comment by ThatOneBepis** [comment]
yes, LONG LIVE WELL

**Comment by Quezler** [comment]
Screen Shot 2019-11-14 at 13 42 58

**Comment by Anuken** [comment]
I'm not sure about solving the problem this way, as many blocks may potentially have this problem and checking for presence of power on each one seems messy.

**Comment by Quezler** [comment]
Hmm, well do let me know (please) when you know more, freezing/closing this pr for the time being 😇

**Comment by Anuken** [comment]
Implemented a special efficiency method in 30ea285ca025766f2455cc53e026da158cf706a6, may be useful for other types of efficiency boosts in the future.

**Pull request closed without merging**
