### PR TITLE
show public ip when hosting in-game

### PR DESCRIPTION
**Pull request by DeltaNedas**
uses icanhazip.com, nice plaintext ip thing

### CODE REVIEW

**Comment by summetdev** [comment]
So technically if you change your IP, it doesn't update in game.

**Comment by DeltaNedas** [comment]
yes

**Comment by Anuken** [comment]
This breaks UI layout.

*now that it comes with artifacts, you have no excuse not to...*

image

**Comment by DeltaNedas** [comment]
yes but i dont know why
i added row and all

**Comment by Anuken** [comment]
1. This is still broken, you haven't used colspan() or any nested tables.
2. Seems like a bad idea. What happens if you're on a cellular network, or it's IPv6?
3. Not a big fan of making HTTP requests to another site, even if it fails gracefully.

**Pull request closed without merging**
