### PR TITLE
Unit.type is nullable

### PR DESCRIPTION
**Pull request by buthed010203**
I don't know why its not marked as such when it clearly is: https://discord.com/channels/391020510269669376/807692120160337981/898588334023139348

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by buthed010203** [comment]
Oh that check was bound to fail anyways since i didnt do anything if it was null lol, checking if its dead is probably a better solution yeah

**Comment by Anuken** [comment]
were you checking for `player.dead()`? if so, was the unit type still null?

**Comment by buthed010203** [comment]
Yeah, it was still null somehow

**Comment by Anuken** [comment]
The `!= false` comparison still pains me (although I know it's necessary)

**Pull request closed without merging**
