### PR TITLE
v6, new turret: Brazier

### PR DESCRIPTION
**Pull request by SnakkiZXZ**
Why not add a stronger rocket turret or a stronger flamethrower? I decided to `combine` both in the `"Brazier"` turret.
Screenshot_20201001_124438
maybe I'll change the color of the bullet path (most likely it will). A `3x3` block turret with a medium range (slightly less ripple), suitable for later defense as an alternative to the `Scorchers.`

if it is too weak or strong it is easily solved. I look forward to your feedback.

P.s. Anuke, maybe this turret is suitable for build 108?

### CODE REVIEW

**Comment by SteelBlue8** [comment]
Why does it use phase colours

**Comment by sk7725** [comment]
"flame" is kind of a widely used common noun, can you change it to "firelite", "combust" or something else?

**Comment by SnakkiZXZ** [comment]
@sk7725 hmm, that's interesting. I'll think about the name

**Comment by Vinzgamer** [comment]
Try blitz,flare,flamestorm,vortex?

**Comment by SnakkiZXZ** [comment]
@Vinzgamer here are some more ideas: `brazier, igniter`

**Comment by SnakkiZXZ** [comment]
@SteelBlue8 which one do you suggest? blue is busy, yellow too, and red too. I can make green, but it will look strange

**Comment by Gdeft** [comment]
> https://discord.com/channels/391020510269669376/396416151032299521/761000596064436247

He won't be accepting turret PRs for 6.0 anymore.

**Comment by SnakkiZXZ** [comment]
Oh no

**Comment by SnakkiZXZ** [comment]
okay, let's see what he says and we won't make turrets anymore

**Comment by Colonizor48** [comment]
Lets start a petition to put this into mindustry.

**Comment by Anuken** [comment]
(no)

**Pull request closed without merging**
