### PR TITLE
Update servers_v7.json

### PR DESCRIPTION
**Pull request by TheTrueInfinity**
Hello Anuken. Sorry to bother you, but only me and my deputy can delete my servers, and these servers are also backup servers in case of a DDoS attack. They will soon be used for new game modes. Thank you.

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
Why do they appear twice on the same server list?

**Comment by Darkness6030** [comment]
> Also because of DDoS

If you're getting ddosed (about it I highly doubt), you don't need to use two different hosts, because both of them can be ddosed at the same time 💀

**Comment by osp54** [comment]
> > Also because of DDoS
> 
> If you're getting ddosed (about it I highly doubt), you don't need to use two different hosts, because both of them can be ddosed at the same time 💀

At the same time, the IP to which the domain redirects can be changed at any time.

**Comment by SSTentacleSS** [comment]
> Why do they appear twice on the same server list?

We have been subjected to DDoS attacks on our main server for a long time, so the second server is used only as a server if the first one does not work (Anuken, what’s wrong with the community?)

**Comment by Anuken** [comment]
> Anuken, what’s wrong with your community?

Don't act like I have anything to do with it. I'm not the one who opened an issue opened demanding removal of this server.

> If you really do not allow it, then you can delete the server with the address omnidustry.ddns.net. But, omnidustry.ru is our main server

I don't allow the same server group to be in the list twice; it wastes space. If you wish to replace the existing one, make a different PR.

**Pull request closed without merging**
