### PR TITLE
Update bundle_hu.properties

### PR DESCRIPTION
**Pull request by summoner001**
Correcting minor spelling mistakes. Thanks for the feedback to the Hungarian mindustry community! Nice catch! :)

@Anuken - Ready to merge ... again. ☹️🙂

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [ ] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by JasonP01** [comment]
Bozo mentions anuke in every pr like it does something

**Comment by Anuken** [comment]
@JasonP01 Yes, I may get a notification for the PR regardless, but this is not a place to insult people, especially contributors. Don't do that.

**Comment by summoner001** [comment]
I'm sorry I didn't mean to offend anyone. Anuken asked me at the very first PR to tell him when I was ready. I didn't want any trouble. I'm so Sorry!

I can't do it anymore.

Best regards!

**Comment by summoner001** [comment]
Here it is the old conversation:
https://github.com/Anuken/Mindustry/pull/9207

I thought I was supposed to tell you whenever I was ready.

I don't do this anymore.

Unfortunately, the Hungarian language is much more complicated than English. At first glance, of course, the written text is fine, but if you want to comply with Hungarian spelling, you have to follow a lot of rules, while in your spoken words these mistakes don't show up. Many spelling mistakes only become apparent when one examines the text very closely. The Mindustry text is ready and understandable for beginners. But there are also mistakes like this PR that don't stand out because otherwise what is there is understandable, but the Hungarian spelling rules require it.

So we had to make a lot of corrections to the text so that we didn't come up with a ridiculous translation, but I don't know all the spelling rules, even though it's my mother language.

**Pull request merged**
