### PR TITLE
Change MinDurka's ip address

### PR DESCRIPTION
**Pull request by Darkness6030**
FINALLY WE HAVE EATEN DDOSERS, IT NOW WORKS!

### CODE REVIEW

**Comment by Darkness6030** [comment]
@Anuken, merge it as fast as you can, pls

**Comment by osp54** [comment]
At last!!

**Comment by summetdev** [comment]
~~when you want to be a contributor but don't know java:~~

**Comment by Humanoid-X** [comment]
@Darkness6030 , please dont ping the cat

**Comment by Darkness6030** [comment]
My java skills are lower than IQ of DDoS'ers

**Comment by Darkness6030** [comment]
Thanks

**Pull request merged**
