### PR TITLE
Fix a single pixel in Fuse's sprite

### PR DESCRIPTION
**Pull request by SMOLKEYS**
Gyrator really panicked over this.

---

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [ ] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by Anuken** [comment]
~~surely there are better things to worry about~~

**Comment by SMOLKEYS** [comment]
> ~~surely there are better things to worry about~~

~~gyrator decided to get a panic attack so i just fixed it~~

**Comment by MEEPofFaith** [comment]
~~what single pixel~~

**Comment by SMOLKEYS** [comment]
> ~~what single pixel~~



this

**Pull request merged**
