### PR TITLE
Remove the slight delay in `wind3.ogg`

### PR DESCRIPTION
**Pull request by MEEPofFaith**
If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [X] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [ ] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by JrTRinny** [comment]
ah yes

**Comment by USMP-lancer** [comment]
Sounds.wind3.play(1)

**Comment by MEEPofFaith** [comment]
Sounds.wind3.play(31415926535)

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by USMP-lancer** [comment]
> Sounds.wind3.play(31415926535)
> 
> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Sounds.wind3.play(999999999999999999999999999)
what?

**Comment by buthed010203** [comment]
> Sounds.wind3.play([31415926535](tel:31415926535))
> 
> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Why pi volume tho

**Comment by USMP-lancer** [comment]
> > Sounds.wind3.play(31415926535)
> > AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
> 
> Why pi volume tho

maph

**Pull request merged**
