### PR TITLE
Added affinity for solar panels

### PR DESCRIPTION
**Pull request by Bohaska**
I'm not sure if this works though... I haven't tested it yet. Can anyone give me feedback about this?

### CODE REVIEW

**Comment by Anuken** [comment]
This doesn't make any sense, and doesn't compile. Why would *solar* panels generate power more on sand?

**Comment by MEEPofFaith** [comment]
If this were October, this would have the Hacktoberfest of Shame slapped onto it.

**Comment by Legomonster33** [comment]
> This doesn't make any sense, and doesn't compile. Why would _solar_ panels generate power more on sand?

thermal generators working on sand might make sense (at like 25% speed) but solar panels makes 0 sense.

**Comment by Anuken** [comment]
> at like 25% speed

Even that doesn't make sense. Sand isn't hot by itself, and it's definitely not going to be once you put a large generator on top that blocks out the sun.

**Pull request closed without merging**
